### ISSUE TITLE
Confusing warning for incorrect `--ignore-path` usage

### ISSUE THREAD

**Issue by brianmacdonald** [eslint/eslint#10076]
**Tell us about your environment**

* **ESLint Version:**
v4.18.2
* **Node Version:**
v9.7.1
* **npm Version:**
v5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
Default

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
I ran `--ignore-path` like I should have run `--ignore-pattern`

```bash
./node_modules/.bin/eslint  -c .eslint_check/.eslintrc . --ignore-path node_modules
```

**What did you expect to happen?**
Have a meaningful message with similar when a config file is missing for `-c` displays a `Cannot read config file:` message

**What actually happened? Please include the actual, raw output from ESLint.**
Displays a confusing Node `fs` error.
```js
root:/usr/src/app# ./node_modules/.bin/eslint  -c .eslint_check/.eslintrc . --ignore-path node_modules
EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:697:18)
    at tryReadSync (fs.js:561:20)
    at Object.fs.readFileSync (fs.js:604:19)
    at IgnoredPaths.readIgnoreFile (/usr/src/app/node_modules/eslint/lib/ignored-paths.js:215:39)
    at IgnoredPaths.addIgnoreFile (/usr/src/app/node_modules/eslint/lib/ignored-paths.js:228:28)
    at new IgnoredPaths (/usr/src/app/node_modules/eslint/lib/ignored-paths.js:164:22)
    at lodash.memoize.optionsObj (/usr/src/app/node_modules/eslint/lib/util/glob-util.js:115:13)
    at memoized (/usr/src/app/node_modules/lodash/lodash.js:10543:27)
    at globPatterns.forEach.pattern (/usr/src/app/node_modules/eslint/lib/util/glob-util.js:175:34)
    at Array.forEach (<anonymous>)
```

**Comment by platinumazure** [comment]
Hi @brianmacdonald, thanks for the issue! I think we could check that the ignore file path points to a file and display a better error message.

**Comment by platinumazure** [comment]
I think the appropriate fix for this issue is:

In CLIEngine, if `ignorePath` is specified and points to something that is not a file or symlink (e.g., a nonexistent file, or a directory), we should throw a nice error message (similar to what we do when we can't resolve a plugin).

Please comment here or stop by our [Gitter chat](https://gitter.im/eslint/eslint) if you want to take this on and have any questions about where to start.

**Comment by malcolmsgroves** [comment]
I'd like to work on this, give me a couple days
