### ISSUE TITLE
version 4.19.1's  bug

### ISSUE THREAD

**Issue by ruanzhijun** [eslint/eslint#10249]
my eslint's version is 4.19.1

my eslint's configuration is base on the newest eslint-config-airbnb version, the following is the complete content :
```json
{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "env": {
    "node": true,
    "mocha": true
  },
  "globals": {
    "share": true,
    "getController": true,
    "getValidate": true,
    "getLogger": true,
    "getService": true,
    "getModel": true,
    "ObjectId": true
  },
  "rules": {
    "max-depth": [
      "error",
      {
        "max": 3
      }
    ],
    "radix": [
      "off"
    ],
    "max-len": [
      "off"
    ],
    "object-curly-spacing": [
      "off"
    ],
    "no-underscore-dangle": [
      "off"
    ],
    "import/no-dynamic-require": [
      "off"
    ],
    "global-require": [
      "off"
    ],
    "class-methods-use-this": [
      "off"
    ],
    "no-restricted-syntax": [
      "off"
    ],
    "no-await-in-loop": [
      "off"
    ],
    "brace-style": [
      "error",
      "1tbs"
    ],
    "object-curly-newline": [
      "off",
      {
        "minProperties": 100000
      }
    ],
    "newline-per-chained-call": [
      "off"
    ],
    "object-property-newline": [
      "error",
      {
        "allowMultiplePropertiesPerLine": true
      }
    ]
  }
}
```

when I npm run eslint --fix it made a mistake like this: ↓↓↓↓↓
```sh
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenBefore (/srv/kiskis-server-app/node_modules/eslint/lib/token-store/index.js:303:18)
    at checkSpacingBefore (/srv/kiskis-server-app/node_modules/eslint/lib/rules/template-curly-spacing.js:52:42)
    at TemplateElement (/srv/kiskis-server-app/node_modules/eslint/lib/rules/template-curly-spacing.js:117:17)
    at listeners.(anonymous function).forEach.listener (/srv/kiskis-server-app/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/srv/kiskis-server-app/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/srv/kiskis-server-app/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/srv/kiskis-server-app/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/srv/kiskis-server-app/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/srv/kiskis-server-app/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
```

I expect eslint run no mistake

**Comment by ruanzhijun** [comment]
my eslint's version is 4.19.1

my eslint's configuration is base on the newest eslint-config-airbnb version, the following is the complete content :
{
"parser": "babel-eslint",
"extends": "airbnb",
"env": {
"node": true,
"mocha": true
},
"globals": {
"share": true,
"getController": true,
"getValidate": true,
"getLogger": true,
"getService": true,
"getModel": true,
"ObjectId": true
},
"rules": {
"max-depth": [
"error",
{
"max": 3
}
],
"radix": [
"off"
],
"max-len": [
"off"
],
"object-curly-spacing": [
"off"
],
"no-underscore-dangle": [
"off"
],
"import/no-dynamic-require": [
"off"
],
"global-require": [
"off"
],
"class-methods-use-this": [
"off"
],
"no-restricted-syntax": [
"off"
],
"no-await-in-loop": [
"off"
],
"brace-style": [
"error",
"1tbs"
],
"object-curly-newline": [
"off",
{
"minProperties": 100000
}
],
"newline-per-chained-call": [
"off"
],
"object-property-newline": [
"error",
{
"allowMultiplePropertiesPerLine": true
}
]
}
}

when I npm run eslint --fix it made a mistake like this: ↓↓↓↓↓
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
at SourceCode.getTokenBefore (/srv/kiskis-server-app/node_modules/eslint/lib/token-store/index.js:303:18)
at checkSpacingBefore (/srv/kiskis-server-app/node_modules/eslint/lib/rules/template-curly-spacing.js:52:42)
at TemplateElement (/srv/kiskis-server-app/node_modules/eslint/lib/rules/template-curly-spacing.js:117:17)
at listeners.(anonymous function).forEach.listener (/srv/kiskis-server-app/node_modules/eslint/lib/util/safe-emitter.js:47:58)
at Array.forEach ()
at Object.emit (/srv/kiskis-server-app/node_modules/eslint/lib/util/safe-emitter.js:47:38)
at NodeEventGenerator.applySelector (/srv/kiskis-server-app/node_modules/eslint/lib/util/node-event-generator.js:251:26)
at NodeEventGenerator.applySelectors (/srv/kiskis-server-app/node_modules/eslint/lib/util/node-event-generator.js:280:22)
at NodeEventGenerator.enterNode (/srv/kiskis-server-app/node_modules/eslint/lib/util/node-event-generator.js:294:14)
at CodePathAnalyzer.enterNode (/srv/kiskis-server-app/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)

I expect eslint run no mistake

**Comment by Aladdin-ADD** [comment]
@ruanzhijun could you please post the source code causing the issue, thanks!

**Comment by ilyavolodin** [comment]
I believe this has been reported in the past, and was determined to be an issue with `babel-eslint`. Can you reproduce the same issue without `babel-eslint`?
