### ISSUE TITLE
TypeError: Cannot read property 'type' of null at isLoneBlock

### ISSUE THREAD

**Issue by kurtextrem** [eslint/eslint#10365]
**Tell us about your environment**

* **ESLint Version:** 5.0.0-alpha.3
* **Node Version:** 10.1.0
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
	"root": true,
	"parser": "babel-eslint",
	"parserOptions": {
		"ecmaVersion": 2018,
		"sourceType": "module",
		"ecmaFeatures": {
			"impliedStrict": true,
			"jsx": true,
			"experimentalDecorators": true,
			"allowImportExportEverywhere": true,
			"sourceType": "module"
		}
	},
	"extends": [
		"eslint:recommended",
		"airbnb",
		"plugin:node/recommended",
		"plugin:react/recommended",
		"plugin:import/errors",
		"plugin:import/warnings",
		"plugin:promise/recommended",
		"plugin:unicorn/recommended",
		"plugin:inferno/recommended",
		"standard",
		"standard-react",
		"xo",
		"xo-react",
		"xo/esnext",
		"xo/browser",
		"prettier",
		"prettier/react",
		"plugin:react-perf/recommended"
	],
	"plugins": [
		"compat",
		"json",
		"security",
		"promise",
		"promise-catch",
		"node",
		"react",
		"babel",
		"unicorn",
		"jsdoc",
		"dependencies",
		"perf-standard",
		"prototype-chain",
		"inferno",
		"sort-imports-es6-autofix",
		"optimize-regex",
		"react-functional-set-state",
		"react-perf",
		"tree-shaking",
		"no-useless-assign",
		"no-unsafe-regex",
		"lean-imports",
		"dollar-sign",
		"prefer-object-spread",
		"class-prefer-methods"
	], // "sort-class-members",
	"env": {
		"browser": true,
		"jquery": true,
		"node": true,
		"webextensions": true,
		"serviceworker": true,
		"worker": true,
		"shared-node-browser": true,
		"commonjs": true,
		"es6": true
	},
	"rules": {
		// Style
		"linebreak-style": 0,
		"indent": [
			0,
			"tab",
			{
				"SwitchCase": 1
			}
		],
		"no-tabs": 0,
		"semi": 0,
		"babel/semi": [
			2,
			"never"
		],
		"brace-style": 0,
		"camelcase": 0,
		"curly": 0,
		"babel/object-curly-spacing": [
			1,
			"always"
		],
		"object-curly-spacing": 0,
		"space-before-function-paren": [
			2,
			"never"
		],
		"no-inline-comments": 0,
		"lines-around-comment": 0,
		"new-cap": 1,
		// Plugins
		"react/no-typos": 2,
		"react/no-unused-state": 1,
		"react/destructuring-assignment": 0,
		"class-methods-use-this": 0,
		"react-functional-set-state/no-this-state-props": 2,
		"dollar-sign/dollar-sign": [
			2,
			"ignoreProperties"
		],
		"no-useless-assign/no-useless-assign": 2,
		"tree-shaking/no-side-effects-in-initialization": 0, // @TODO
		"react/no-unknown-property": [
			2,
			{
				"ignore": [
					"class"
				]
			}
		], // preact
		"inferno/no-unknown-property": [
			2,
			{
				"ignore": [
					"class"
				]
			}
		], // preact
		"optimize-regex/optimize-regex": 1,
		"compat/compat": 1,
		"promise/always-return": 2,
		"promise/no-return-wrap": 2,
		"promise/param-names": 2,
		"promise/catch-or-return": 2, // needed, as v8 deopts if missing probably
		"promise/no-native": 0,
		"promise/no-nesting": 1,
		"promise/no-promise-in-callback": 2,
		"promise/no-callback-in-promise": 2,
		"promise/avoid-new": 0,
		"promise-catch/throw-or-log": [
			2,
			{
				"customLoggers": true
			}
		],
		"node/no-unsupported-features": 0,
		"node/no-unpublished-require": 0,
		"es-beautifier/jsx-separateline-literals": 0,
		"es-beautifier/multiline-import-specifiers": 0,
		/*"sort-class-members/sort-class-members": [
			2,
			{
				"order": [
					"[static-properties]",
					"[static-methods]",
					"constructor",
					"[properties]",
					"[conventional-private-properties]",
					"[methods]",
					"[conventional-private-methods]"
				],
				"accessorPairPositioning": "getThenSet"
			}
		],*/
		"dependencies/case-sensitive": 1,
		"dependencies/no-cycles": 1,
		"dependencies/no-unresolved": 1,
		"dependencies/require-json-ext": 1,
		"unicorn/filename-case": 0,
		"unicorn/explicit-length-check": 1,
		"unicorn/catch-error-name": 0,
		"sort-imports-es6-autofix/sort-imports-es6": [
			2,
			{
				"ignoreCase": false,
				"ignoreMemberSort": false,
				"memberSyntaxSortOrder": [
					"single",
					"none",
					"all",
					"multiple"
				]
			}
		],
		// Mitigate extended rules
		"func-names": [
			0,
			"as-needed"
		],
		"spaced-comment": 0,
		"capitalized-comments": 0,
		"prefer-promise-reject-errors": 1,
		"max-statements-per-line": [
			2,
			{
				"max": 2
			}
		],
		"one-var": 0,
		"no-var": 0,
		"no-unused-vars": 1,
		"no-console": 0,
		"no-return-assign": [
			2,
			"except-parens"
		],
		"no-negated-condition": 0, // maybe enable
		"no-template-curly-in-string": 1, // webpack files
		"no-use-before-define": [
			2,
			{
				"functions": false,
				"classes": true,
				"variables": false
			}
		],
		"react/sort-comp": [
			"error",
			{
				"order": [
					"static-methods",
					"lifecycle",
					"getters",
					"setters",
					"/^(get|set)(?!(InitialState$|DefaultProps$|ChildContext$)).+$/",
					"everything-else",
					"/^on.+$/",
					"callbackfns",
					"/^render.+$/",
					"render"
				],
				"groups": {
					"lifecycle": [
						"displayName",
						"propTypes",
						"contextTypes",
						"childContextTypes",
						"statics",
						"mixins",
						"defaultProps",
						"getDefaultProps",
						"constructor",
						"getInitialState",
						"state",
						"getChildContext"
					],
					"callbackfns": [
						"componentWillMount",
						"componentDidMount",
						"componentWillReceiveProps",
						"shouldComponentUpdate",
						"componentWillUpdate",
						"componentDidUpdate",
						"componentWillUnmount"
					]
				}
			}
		],
		"no-plusplus": 0,
		"react/jsx-filename-extension": 0,
		"jsx-a11y/alt-text": 1,
		"react/no-unused-prop-types": 1,
		"jsx-a11y/anchor-is-valid": 1, // #
		"import/first": 0,
		"strict": 0,
		"prefer-destructuring": 0,
		"complexity": 0,
		"jsx-a11y/media-has-caption": 1,
		"no-shadow": 1,
		"no-continue": 0, // ???
		"global-require": 0,
		// Perf
		"no-implicit-coercion": 0, // constructors worsen perf a little
		"guard-for-in": 0, // not needed anymore
		"prefer-object-spread/prefer-object-spread": 1,
		"no-unsafe-regex/no-unsafe-regex": 2,
		"class-prefer-methods/prefer-methods": 0,
		"no-new": 0,
		"no-array-constructor": 1, // new Array pre-allocates 4 elements, so it has its use
		"prefer-arrow-callback": 0,
		"perf-standard/no-instanceof-guard": 2,
		"perf-standard/no-self-in-constructor": 2,
		"perf-standard/check-function-inline": 1,
		"prototype-chain/prototype-chain": [
			2,
			3,
			1
		],
		"prefer-const": [
			1,
			{
				"ignoreReadBeforeAssign": true,
				"destructuring": "any"
			}
		],
		// React
		"jsx-quotes": [
			2,
			"prefer-double"
		],
		"react/react-in-jsx-scope": 0,
		"react/prop-types": 0,
		"react/forbid-component-props": 0,
		"react/jsx-tag-spacing": 0,
		// Possible Errors
		"comma-dangle": [
			2,
			"only-multiline"
		]
		// "handle-callback-err": 2,
		// "no-bitwise": 0,
		// "no-cond-assign": 2,
		// "no-console": 0,
		// "no-constant-condition": 2,
		// "no-control-regex": 2,
		// "no-debugger": 2,
		// "no-dupe-args": 2,
		// "no-dupe-keys": 2,
		// "no-duplicate-case": 2,
		// "no-empty": 2,
		// "no-empty-character-class": 2,
		// "no-ex-assign": 2,
		// "no-extra-boolean-cast": 2,
		// "no-extra-parens": 0,
		// "no-extra-semi": 2,
		// "no-func-assign": 2,
		// "no-inner-declarations": 2,
		// "no-invalid-regexp": 2,
		// "no-irregular-whitespace": 2,
		// "no-negated-in-lhs": 2,
		// "no-obj-calls": 2,
		// "no-regex-spaces": 2,
		// "no-sparse-arrays": 2,
		// "no-unexpected-multiline": 2,
		// "no-unreachable": 2,
		// "use-isnan": 2,
		// "valid-jsdoc": 1,
		// "valid-typeof": 2,
		// //Best Practices
		// "accessor-pairs": 2,
		// "block-scoped-var": 0,
		// "consistent-return": 2,
		// "curly": 0,
		// "default-case": 2,
		// "dot-location": 0,
		// "dot-notation": 2,
		// "eqeqeq": 2,
		// "guard-for-in": 2,
		// "no-alert": 2,
		// "no-caller": 2,
		// "no-div-regex": 2,
		// "no-else-return": 2,
		// "no-labels": 2,
		// "no-eq-null": 2,
		// "no-eval": 2,
		// "no-extend-native": 2,
		// "no-extra-bind": 2,
		// "no-fallthrough": 2,
		// "no-floating-decimal": 2,
		// "no-implicit-coercion": 1,
		// "no-implied-eval": 2,
		// "no-invalid-this": 0,
		// "no-iterator": 2,
		// "no-lone-blocks": 0,
		// "no-loop-func": 2,
		// "no-multi-spaces": 2,
		// "no-multi-str": 2,
		// "no-native-reassign": 2,
		// "no-new": 0,
		// "no-new-func": 0,
		// "no-new-wrappers": 2,
		// "no-octal": 2,
		// "no-octal-escape": 2,
		// "no-param-reassign": 0,
		// "no-process-env": 0,
		// "no-proto": 2,
		// "no-redeclare": 2,
		// "no-script-url": 2,
		// "no-self-compare": 2,
		// "no-sequences": 2,
		// "no-throw-literal": 2,
		// "no-unused-expressions": 2,
		// "no-useless-call": 2,
		// "no-useless-concat": 2,
		// "no-void": 2,
		// "no-warning-comments": 0,
		// "no-with": 2,
		// "radix": 2,
		// "vars-on-top": 0,
		// "wrap-iife": 2,
		// "yoda": 2,
		// // Variables
		// "init-declarations": 1,
		// "no-catch-shadow": 0,
		// "no-delete-var": 2,
		// "no-label-var": 2,
		// "no-shadow": 1,
		// "no-shadow-restricted-names": 2,
		// "no-undef": 2,
		// "no-undefined": 0,
		// "no-undef-init": 2,
		// "no-unused-vars": 1,
		// "no-use-before-define": 0,
		// // Stylistic
		// "array-bracket-spacing": 2,
		// "block-spacing": 2,
		// "brace-style": 0,
		// "camelcase": 1,
		// "comma-spacing": 2,
		// "comma-style": 2,
		// "computed-property-spacing": 2,
		// "consistent-this": 2,
		// "eol-last": 2,
		// "func-names": 0,
		// "func-style": [2, "declaration", { "allowArrowFunctions": true }],
		// "key-spacing": 2,
		// "linebreak-style": 0,
		// "newline-after-var": 0,
		// "new-parens": 2,
		// "no-continue": 0,
		// "no-lonely-if": 2,
		// "no-mixed-spaces-and-tabs": 2,
		// "no-multiple-empty-lines": 2,
		// "no-nested-ternary": 0,
		// "no-new-object": 2,
		// "no-spaced-func": 2,
		// "no-ternary": 0,
		// "no-trailing-spaces": 2,
		// "no-underscore-dangle": 1,
		// "no-unneeded-ternary": 2,
		// "object-curly-spacing": [1, "always"],
		// "operator-assignment": 2,
		// "operator-linebreak": 0,
		// "padded-blocks": 0,
		// "quote-props": [2, "as-needed"],
		// "quotes": [2, "single"],
		// "semi": [2, "never"],
		// "semi-spacing": 2,
		// "sort-vars": 1,
		// "keyword-spacing": 2,
		// "space-before-blocks": 2,
		// "spaced-comment": 0,
		// "space-infix-ops": 2,
		// "space-in-parens": 2,
		// "space-unary-ops": 2,
		// "func-call-spacing": [2, "never"],
		// // es6
		// "arrow-parens": 2,
		// "arrow-spacing": 2,
		// "constructor-super": 2,
		// "generator-star-spacing": 2,
		// "no-class-assign": 2,
		// "no-const-assign": 2,
		// "no-dupe-class-members": 2,
		// "no-this-before-super": 2,
		// "object-shorthand": 2,
		// "prefer-arrow-callback": 0,
		// "prefer-reflect": 0,
		// "prefer-spread": 2,
		// "prefer-template": 0,
		// "require-yield": 2
	},
	"settings": {
		"flowtype": {
			"onlyFilesWithFlowAnnotation": false
		}
	}
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

It happens no matter what file / source code I open.
I use ESLint in VS Code.

**What did you expect to happen?**
No error.

**What actually happened? Please include the actual, raw output from ESLint.**
[Error - 11:56:42] ESLint stack trace:
[Error - 11:56:42] TypeError: Cannot read property 'type' of null
    at isLoneBlock (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\rules\no-lone-blocks.js:47:31)
    at BlockStatement (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\rules\no-lone-blocks.js:84:25)
    at listeners.(anonymous function).forEach.listener (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\util\safe-emitter.js:45:58)
    at Array.forEach (native)
    at Object.emit (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\util\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:608:23)
    at nodeQueue.forEach.traversalInfo (C:\Users\admin\AppData\Roaming\npm\node_modules\eslint\lib\linter.js:861:28)

**Comment by platinumazure** [comment]
Hi @kurtextrem, thanks for the issue.

This is going to be pretty difficult for us to try to reproduce, since your config refers to a lot of plugins/sharable configs.

It would help if you could try removing some plugins/configs (and associated rules) to try to reduce the test case. By doing so, you might be able to find which module could be causing the issue-- but if not, it will at least help narrow things down for us.

Another test case worth trying is, what happens if you take one of your same files and lint it with the babel-eslint parser (same version as what you have now) and with no-lone-blocks being the only rule turned on?

**Comment by kurtextrem** [comment]
I don't really know what fixed it, but the issue seems to be gone. Thank you!
