### ISSUE TITLE
TypeError: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by FelixVicis** [eslint/eslint#10372]
**Tell us about your environment**

* **ESLint Version:** v4.15.0
* **Node Version:** v8.9.4
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
- `babel-eslint`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
	parser: "babel-eslint",
	rules   : {
		'arrow-body-style' : ['warn', 'as-needed'],
	},
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
test = () => { return }
```

```bash
./node_modules/.bin/eslint FILE
```

**What did you expect to happen?**

Eslint to lint the file

**What actually happened? Please include the actual, raw output from ESLint.**

Error received `TypeError: Cannot read property 'value' of null`

```
Cannot read property 'value' of null
TypeError: Cannot read property 'value' of null
    at Object.isOpeningBraceToken (./node_modules/eslint/lib/ast-utils.js:354:18)
    at validate (./node_modules/eslint/lib/rules/arrow-body-style.js:119:41)
    at listeners.(anonymous function).forEach.listener (./node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (./node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (./node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (./node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.leaveNode (./node_modules/eslint/lib/util/node-event-generator.js:303:14)
    at CodePathAnalyzer.leaveNode (./node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:630:23)
    at Traverser.leave [as _leave] (./node_modules/eslint/lib/linter.js:1001:32)
```

**Comment by chatcher** [comment]
occurs with default parser as well.

**Comment by chatcher** [comment]
Also occurs with default parser:
```bash
echo '() => { return }' > cannot-read-value-of-null.js
eslint --no-eslintrc --parser-options '{"sourceType":"module"}' --rule '{"arrow-body-style":1}' cannot-read-value-of-null.js
```

**Comment by not-an-aardvark** [comment]
Thanks for the report, I can reproduce this issue.

**Comment by sstern6** [comment]
@not-an-aardvark mind if i take this one?

**Comment by not-an-aardvark** [comment]
Sure!

**Comment by not-an-aardvark** [comment]
@sstern6 Actually it looks like a PR was just submitted: https://github.com/eslint/eslint/pull/10379

**Comment by sstern6** [comment]
Yup ill get another one! all good @not-an-aardvark

**Comment by josemigallas** [comment]
Getting exactly this error with following:
**.eslintrc**
```
{
    "extends": "airbnb",
    "rules": {
        "quotes": ["error", "double"],
        "comma-dangle": ["error", "never"],
        "arrow-parens": ["error", "as-needed"],
        "curly": ["error", "all"],
        "brace-style": ["error", "1tbs"],
        "padded-blocks": ["error", { "classes": "always", "blocks": "never" }],
        "object-curly-newline": [
            "error",
            {
                "ImportDeclaration": { "multiline": true, "minProperties": 3 }
            }
        ],
        "indent": ["error", 4],
        "class-methods-use-this": "off",
        "import/prefer-default-export": "off",
        "react/jsx-filename-extension": "off",
        "react/jsx-one-expression-per-line": "off",
        "react/prop-types": "warn",
        "react/jsx-indent": ["error", 4],
        "react/jsx-indent-props": ["error", "first"],
        "react/button-has-type": "off",
        "react/destructuring-assignment": "warn",
        "jsx-a11y/label-has-for": "off"
    },
    "plugins": ["mocha"],
    "env": {
        "mocha": true,
        "browser": true
    }
}
```
**.babelrc**
```
{
  "presets": ["env", "react"],
  "plugins": ["transform-object-rest-spread"]
}
```
**dependencies**
```
"eslint": "^4.19.1",
"eslint-config-airbnb": "^17.0.0"
"eslint-plugin-import": "^2.13.0"
"eslint-plugin-jsx-a11y": "^6.0.3"
"eslint-plugin-mocha": "^5.0.0"
"eslint-plugin-react": "^7.10.0"

node v8.11.2
npm 6.1.0
```

**Comment by deanwagman** [comment]
In my case, I had a React Component that had a method that was empty.  Inside I had a one comment line.

```
...
doThing = () => {
  // futureFeature
}

return <div onThing={this.doThing} />
...
```

**Comment by not-an-aardvark** [comment]
If this is still happening with the latest version of ESLint, may you please open a new issue? Thanks!
