### ISSUE TITLE
TypeError: Cannot read property 'local' of undefined

### ISSUE THREAD

**Issue by daviddelusenet** [eslint/eslint#10443]
**Tell us about your environment**

* **ESLint Version: 4.19.1**
* **Node Version: 8.9.3**
* **npm Version: 6.1.0**

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parser: 'babel-eslint',
  env: {
    browser: true,
    es6: true,
  },
  settings: {
    jsx: true,
  },
  plugins: [
    'react',
  ],
  extends: 'airbnb',
  rules: {
    'import/no-extraneous-dependencies': ['error', {
      devDependencies: true,
      optionalDependencies: false,
      peerDependencies: false,
    }],
    'jsx-a11y/anchor-is-valid': ['error', {
      components: ['Link'],
      specialLink: ['to'],
    }],
    'keyword-spacing': 0,
    'max-len': ['error', {
      code: 120,
      ignoreTemplateLiterals: true,
      tabWidth: 2,
    }],
    'react/jsx-filename-extension': 0,
    'react/jsx-max-props-per-line': ['error', {
      maximum: 3,
    }],
  },
  globals: {
    Modernizr: true,
  },
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
import 'react';
import PropTypes from 'prop-types';
import { formatMoney } from 'accounting-js';
import fx from 'money';

// Containers
import withCurrency from './../../containers/withCurrency';

// Consts
import { SUPPORTED_CURRENCIES } from './../../utils/consts';

const FormatAmount = ({ amount, baseCurrency, selectedCurrency }) => {
  const convertedAmount = selectedCurrency === baseCurrency ?
    amount :
    fx(amount).from(baseCurrency).to(selectedCurrency);

  return formatMoney(convertedAmount, {
    precision: 0,
    symbol: SUPPORTED_CURRENCIES[selectedCurrency],
  });
};

FormatAmount.propTypes = {
  amount: PropTypes.string.isRequired,
  baseCurrency: PropTypes.string.isRequired,
  selectedCurrency: PropTypes.string.isRequired,
};

export default withCurrency(FormatAmount);
```

```bash
eslint './src/**/*.js' --config config/.eslintrc.js
```

**What did you expect to happen?**
That my file got linted.

**What actually happened? Please include the actual, raw output from ESLint.**
```bash
Cannot read property 'local' of undefined
TypeError: Cannot read property 'local' of undefined
    at ImportDeclaration (/Users/lusenet/Development/shop/node_modules/eslint-plugin-react/lib/rules/no-typos.js:158:49)
    at listeners.(anonymous function).forEach.listener (/Users/lusenet/Development/shop/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/lusenet/Development/shop/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/lusenet/Development/shop/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/lusenet/Development/shop/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/lusenet/Development/shop/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/lusenet/Development/shop/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at Traverser.enter [as _enter] (/Users/lusenet/Development/shop/node_modules/eslint/lib/linter.js:865:28)
    at Traverser._traverse (/Users/lusenet/Development/shop/node_modules/eslint/lib/util/traverser.js:132:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shop@1.0.0 lint:js: `eslint './src/**/*.js' --config config/.eslintrc.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shop@1.0.0 lint:js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lusenet/.npm/_logs/2018-06-06T06_56_09_008Z-debug.log
```

**Some extra information**
So I wrote this `FormatAmount` component a few weeks ago. Linting worked fine. However, when I opened the file again yesterday it crashed my ESLint. Already restarted my computer, updated my software, updated the ESLint version but it still breaks.

**Comment by not-an-aardvark** [comment]
Thanks for the report. It looks like this error is being thrown from a custom rule in [`eslint-plugin-react`](https://github.com/yannickcr/eslint-plugin-react), which is not maintained by the ESLint team. I would recommend reporting this issue on that repository instead.

**Comment by AKFourSeven** [comment]
I have a similar issue and I disabled the no-typos rule but I still get a similar error : 

```
 ❯ npm run lint                                                                                                                                                                                                                                           [07-06-2018 09:42:39]

> selfcare@0.1.0 lint /project
> run-s lint:javascript lint:others


> selfcare@0.1.0 lint:javascript /project
> eslint .

Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenBefore (/project/node_modules/eslint/lib/token-store/index.js:303:18)
    at checkSpacingBefore (/project/node_modules/eslint/lib/rules/template-curly-spacing.js:52:42)
    at TemplateElement (/project/node_modules/eslint/lib/rules/template-curly-spacing.js:117:17)
    at listeners.(anonymous function).forEach.listener (/project/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/project/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/project/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/project/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/project/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/project/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
```
Oddly enough `npm` will encounter an error while `yarn`will keep on running smoothly.
Perhaps it isn't only an eslint-plugin-react issue...

**Comment by not-an-aardvark** [comment]
That error looks like the same as https://github.com/eslint/eslint/issues/9872.

**Comment by not-an-aardvark** [comment]
Closing because this issue is a result of an error from an external plugin.
