### ISSUE TITLE
npm run perf got error

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#10577]
**Tell us about your environment**

* **ESLint Version:** master/5.0.1
* **Node Version:** 10.6.0
* **npm Version:** 6.1.0

**What parser (default, Babel-ESLint, etc.) are you using?**

**after running `npm run perf`, got "No files matching the pattern"**

<details>
<summary>error log</summary>

```js
Oops! Something went wrong! :(

ESLint: 5.0.1.
No files matching the pattern "/var/folders/gw/2hlkmn1j5yl2mb3qdy8b1k2w0000gn/T/eslint/performance/eslint/{lib,tests/lib}/**/*.js" were found.
Please check for typing mistakes in the pattern.




/Users/weiran/repo/eslint/Makefile.js:1047
            throw new Error("Performance test failed.");
            ^

Error: Performance test failed.
    at results (/Users/weiran/repo/eslint/Makefile.js:1047:19)
    at exec (/Users/weiran/repo/eslint/Makefile.js:1013:20)
    at /Users/weiran/repo/eslint/node_modules/shelljs/src/exec.js:124:9
    at ChildProcess.exithandler (child_process.js:298:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```

</details>

**Comment by platinumazure** [comment]
Hi @Aladdin-ADD, I see you've made a commit referencing this issue. Do you want to open a PR? Or is there more that needs to be done?
