### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by yoyo837** [eslint/eslint#10610]
**Tell us about your environment**

* **ESLint Version:** v4.19.1
* **Node Version:** v8.11.1
* **npm Version:** v5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
```
  parser: 'babel-eslint',
  extends: ['airbnb', 'prettier'],
```
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parser: 'babel-eslint',
  extends: ['airbnb', 'prettier'],
  env: {
    browser: true,
    node: true,
    es6: true,
    mocha: true,
    jest: true,
    jasmine: true,
  },
  rules: {
    'generator-star-spacing': [0],
    'consistent-return': [0],
    'react/forbid-prop-types': [0],
    'react/jsx-filename-extension': [1, { extensions: ['.js'] }],
    'global-require': [1],
    'import/prefer-default-export': [0],
    'react/jsx-no-bind': [0],
    'react/prop-types': [0],
    'react/prefer-stateless-function': [0],
    'react/jsx-one-expression-per-line': [0],
    'react/jsx-wrap-multilines': [
      'error',
      {
        declaration: 'parens-new-line',
        assignment: 'parens-new-line',
        return: 'parens-new-line',
        arrow: 'parens-new-line',
        condition: 'parens-new-line',
        logical: 'parens-new-line',
        prop: 'ignore',
      },
    ],
    'no-else-return': [0],
    'no-restricted-syntax': [0],
    'import/no-extraneous-dependencies': [0],
    'no-use-before-define': [0],
    'jsx-a11y/no-static-element-interactions': [0],
    'jsx-a11y/no-noninteractive-element-interactions': [0],
    'jsx-a11y/click-events-have-key-events': [0],
    'jsx-a11y/anchor-is-valid': [0],
    'no-nested-ternary': [0],
    'arrow-body-style': [0],
    'import/extensions': [0],
    'no-bitwise': [0],
    'no-cond-assign': [0],
    'import/no-unresolved': [0],
    'comma-dangle': [
      'error',
      {
        arrays: 'always-multiline',
        objects: 'always-multiline',
        imports: 'always-multiline',
        exports: 'always-multiline',
        functions: 'ignore',
      },
    ],
    'object-curly-newline': [0],
    'function-paren-newline': [0],
    'no-restricted-globals': [0],
    'require-yield': [1],
  },
  parserOptions: {
    ecmaFeatures: {
      experimentalObjectRestSpread: true,
    },
  },
  settings: {
    polyfills: ['fetch', 'promises'],
  },
};

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```jsx
<Form.Item  label="区域">
  <Select className={style.select}>
    <Select.Option value={123}>123</Select.Option>
  </Select>
</Form.Item>
```
I just typed a space after `<Form.Item>`

```bash

```

**What did you expect to happen?**

Eslint works fine.

**What actually happened? Please include the actual, raw output from ESLint.**

It report:
```
[Error - 15:39:44] TypeError: Cannot read property 'name' of undefined
    at getPropName (d:\source-control\git\ydmap-web-cloud\node_modules\eslint-plugin-react\lib\rules\jsx-props-no-multi-spaces.js:35:27)
    at checkSpacing (d:\source-control\git\ydmap-web-cloud\node_modules\eslint-plugin-react\lib\rules\jsx-props-no-multi-spaces.js:46:56)
    at JSXOpeningElement.node.attributes.reduce (d:\source-control\git\ydmap-web-cloud\node_modules\eslint-plugin-react\lib\rules\jsx-props-no-multi-spaces.js:57:11)
    at Array.reduce (native)
    at JSXOpeningElement (d:\source-control\git\ydmap-web-cloud\node_modules\eslint-plugin-react\lib\rules\jsx-props-no-multi-spaces.js:56:25)
    at listeners.(anonymous function).forEach.listener (d:\source-control\git\ydmap-web-cloud\node_modules\eslint\lib\util\safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (d:\source-control\git\ydmap-web-cloud\node_modules\eslint\lib\util\safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (d:\source-control\git\ydmap-web-cloud\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (d:\source-control\git\ydmap-web-cloud\node_modules\eslint\lib\util\node-event-generator.js:280:22)
```

**Comment by yoyo837** [comment]
Sorry, it should be sent to `eslint-plugin-react`
