### ISSUE TITLE
Issue with eslint --init

### ISSUE THREAD

**Issue by sumit480** [eslint/eslint#10618]
**Tell us about your environment**

ESLint Version: v5.1.0
Node Version: v8.11.2
npm Version: v5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

I installed eslint globally and then I'm doing eslint, providing all the questions asked when its going to create eslintrc.js file its failed saying package.json is not there. As I am running it globally I dont require a Package.json file.

```js

```

```
   sudo npm install -g eslint
   eslint --init

```

? How would you like to configure ESLint?  Answer questions about your style
? Which version of ECMAScript do you use?  ES5
? Where will your code run?  Browser, Node
? Do you use CommonJS?  Yes
? Do you use JSX? Yes
? Do you use React? Yes
? What style of indentation do you use? Tabs
? What quotes do you use for strings? Single
? What line endings do you use? Unix
? Do you require semicolons? Yes
? What format do you want your config file to be in? JavaScript
Could not find a package.json file. Run 'npm init' to create one.
Error: Could not find a package.json file. Run 'npm init' to create one.

**Comment by platinumazure** [comment]
Hi @sumit480, thanks for the issue.

Interesting... If I had to guess, I would say we are probably looking for a package.json so that we can put the ESLint config file in the right place if the command is run from a subdirectory. But it seems like a reasonable fallback could be creating the configuration file inside the current working directory.

Curious to see what the rest of the team thinks.

**Comment by yb66** [comment]
Hi,

I have the same problem, I initially ran init because of the following error message:

> Oops! Something went wrong! :(
> 
> ESLint: 5.2.0.
> ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:
> 
>     eslint --init
> 
> ESLint looked for configuration files in /Users/iainb/Desktop and its ancestors. I**f it found none, it then looked in your home directory.**

The last line implies that no `package.json` is required and the fall back is the home dir. `~/.config/eslint` would be even better, in my opinion. Sometimes I want to lint files that aren't part of a project (in the package.json sense).

**Comment by kaicataldo** [comment]
@sumit480 Can you share the error message you're getting? Is it [this one](https://github.com/eslint/eslint/blob/master/lib/config/config-initializer.js#L498)?

**Comment by jaredmcateer** [comment]
@kaicataldo I ran into this problem as well here's the full stack trace.

```bash
Error: Could not find a package.json file. Run 'npm init' to create one.
    at check (/home/jared/.nodenv/versions/10.11.0/lib/node_modules/eslint/lib/util/npm-utils.js:106:15)
    at Object.checkDevDeps (/home/jared/.nodenv/versions/10.11.0/lib/node_modules/eslint/lib/util/npm-utils.js:160:12)
    at getModulesList (/home/jared/.nodenv/versions/10.11.0/lib/node_modules/eslint/lib/config/config-initializer.js:112:40)
    at inquirer.prompt.then.answers (/home/jared/.nodenv/versions/10.11.0/lib/node_modules/eslint/lib/config/config-initializer.js:624:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by kaicataldo** [comment]
I see. It seems like a reasonable expectation to me that someone should have a package.json file in the directory in which they're running `eslint --init` (since it's necessary to install any plugins the user might want), but we could potentially only throw this error if packages need to be installed. The downside of doing this would be having someone go through the config process and having to start over later in the process (unless we could find a way to make the UX better here).

**Comment by jaredmcateer** [comment]
I think this is just a problem with me reading the user guide properly it's not really until the footnote that it implies you need a `package.json` for the previous instructions to work.

**Comment by getify** [comment]
This also bothered me when I was running `eslint --init` inside my home directory to great my user-wide config setting. I just made a `/tmp/foo` directory, ran `npm init` it, then `eslint --init`, then copied out the generated `eslintrc.json` file and deleted the temp directory. What a silly set of work-arounds. Annoying to put it mildly.

**Comment by hasen6** [comment]
Surprised there's no interest in fixing this since it's unusable like this.

**Comment by platinumazure** [comment]
@hasen6 A documentation fix would probably be accepted even with this issue closed. Otherwise, if you want to propose a different concrete fix, feel free to open a new issue. Thanks!

**Comment by hasen6** [comment]
Not sure how fixing the documentation would help with anything? The issue itself needs to be fixed. Loads of people here complained about it and then no one responded so it was automatically closed. As it is with this issue, all I could do is disable Eslint so there could hardly be any issues beyond this.

**Comment by not-an-aardvark** [comment]
I think the suggestion is to document the fact that `eslint --init` only supports local installations of ESLint. (In fact, if the user is running a global installation, we intentionally try to install a local version and tell them to use that instead.) Personally, I would recommend always using a local ESLint installation/config rather than a global installation/config.

**Comment by hasen6** [comment]
Why is the documentation wrong? I've never used Eslint before it seems that it must have been possible to install globally before but now it's not. If it's not going to be fixed for whatever reason then yes a documentation fix would be good so we at least don't get people reporting this same error again and again and will prevent people from installing it who don't want to install it locally for every single project.

> Personally, I would recommend always using a local ESLint installation/config rather than a global installation/config.

You don't have any choice, that's the only way to use it unless it's ever fixed.

**Comment by not-an-aardvark** [comment]
It is still possible to install ESLint globally. However, `eslint --init` only supports local installations. If you're sure you want to install ESLint globally, you can create a config file manually rather than generating one with `eslint --init`.

**Comment by getify** [comment]
@not-an-aardvark

You said "personally"... but is it also eslint's position that it *shouldn't* be used globally even though it physically can be?

How does withholding support for global uaage in one feature (--init) while not in others do anything but just confuse/irritate users?

**Comment by mysticatea** [comment]
I think that we, the eslint team, have the consensus to recommend local installation. But I have not confirmed it formally.

Personally, I *strongly* recommend using the local installation.

**Comment by yb66** [comment]
I don't know why I have to muck around with any of this, including a package.json file, just to lint some javascript. If the linting fails because of it then that's something for the linter to complain about. If not, then not.

Regardless, there's obviously no will to fix this inside the team so I'll be looking for an alternative. Thanks.

Good luck to my fellow weary linters!

**Comment by getify** [comment]
@mysticatea

Just a dissenting data point as to why some prefer global. I have over a dozen projects on my computer that I switch between. Since I run/control all of them, I have just one set of plugins and configs that I want enforced everywhere. It's beyond tedious to the point of maddening to keep updates installed for each (I've tried), as well as replicate my config and custom plugins for each. I just want eslint to work no matter which file in which project I open up.

----

I realize this is an outlier use-case you likely don't care much about, but I still don't see how such a preference (only use local) -- being selectively "enforced" by way of non-support in a feature like "--init" but not "enforced" in the rest of the product -- should come across as anything other dismissive or user-hostile?

If you want to prevent global usage, disable it across the board. If you just want to discourage, the less hostile (aka, almost passive aggressive) place to do so, IMO, is in docs, not just *some* features.

----

Plus, can it possibly be that difficult for "--init" to ignore the lack of a package.json file, considering that I literally only have to create an almost empty json file with nothing eslint-related in it to make "--init" work?

If eslint needed to install packages and wanted to record that in a package.json, couldn't it pretty trivially create a stub?

**Comment by hasen6** [comment]
> It is still possible to install ESLint globally. However, eslint --init only supports local installations. If you're sure you want to install ESLint globally, you can create a config file manually rather than generating one with eslint --init.

How do you do this then? How do you create the file and where should it be put to run Eslint globally?

**Comment by not-an-aardvark** [comment]
You can put a `.eslintrc.js` file in your project or your home directory. See the [Config File Documentation](https://eslint.org/docs/user-guide/configuring) for more info.

**Comment by hasen6** [comment]
> You can put a .eslintrc.js file in your project or your home directory. See the Config File Documentation for more info.

My 'home' directory is what on a Mac for example? I put it in one project directory and it will work globally for all projects? Are you sure? Not sure what you mean by these methods for using Eslint globally.

**Comment by mysticatea** [comment]
You can move to home directory with `cd ~`.

**Comment by not-an-aardvark** [comment]
You can see what your home directory is by entering `echo ~` in a terminal. It might very by macOS version, but I think the home directory is generally the folder `/Users/yourUsername/`.

If you put the config file in your home directory, it will work for all projects. If you put the config file in a project directory, it will only work for that project.

**Comment by hasen6** [comment]
So you manually create in the home directory the file that `eslint --init` fails to create and then it will work globally?

**Comment by hasen6** [comment]
Did you actually mean .eslintrc.json or should it be .eslintrc.js?

**Comment by not-an-aardvark** [comment]
Multiple file formats are supported (see [here](https://eslint.org/docs/user-guide/configuring#configuration-file-formats)).

**Comment by hasen6** [comment]
Ok yeah that seems to work globally now. So why not just add that to the documentation if `eslint --init` is not going to be fixed?
