### ISSUE TITLE
 Cannot find module 'prelude-ls'

### ISSUE THREAD

**Issue by Pomar81** [eslint/eslint#10663]
**Tell us about your environment**

* **ESLint Version:5.2.0
* **Node Version:8.11.3
* **npm Version:5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "extends": "airbnb",
    "installedESLint": true,
    "plugins": [
        "react"
    ]
}
package.json:
 "devDependencies": {
    "eslint": "^5.2.0",
    "eslint-config-airbnb-base": "^13.0.0",
    "eslint-plugin-import": "^2.13.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.10.0"
  }
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
```

```bash 
eslint --init
```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

D:\test projects\testFullstack\server> 
module.js:549
    throw err;
    ^
Error: Cannot find module 'prelude-ls'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\spomaraiko\AppData\Roaming\npm\node_modules\eslint\node_modules\optionator\lib\index.js:5:10)
    at Object.<anonymous> (C:\Users\spomaraiko\AppData\Roaming\npm\node_modules\eslint\node_modules\optionator\lib\index.js:465:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

**Comment by platinumazure** [comment]
prelude-ls is a dependency of optionator, which we use for option handling. It should have been installed when you installed ESLint.

Not sure what happened here, but maybe try reinstalling ESLint?

**Comment by Pomar81** [comment]
I've reinstalled it. And now it works globally. But I have problems in conjuction with Visual studio code.

**Comment by parmentf** [comment]
I got a `Error: Cannot find module 'optionator'` launching eslint just after installing it.
Re-installing it fixed the problem.

**Comment by parmentf** [comment]
The same today in another project. I was updating from eslint@5.8.0.

```bash
$ npm outdated
Package  Current  Wanted  Latest  Location
eslint     5.8.0   5.8.0   5.9.0  ezs-teeftfr
$ npm run lint

> ezs-teeftfr@2.0.0 lint /home/parmentf/prog/node-ezs-teeftfr
> eslint --ext=.js ./test/*.js ./src/*.js

$ npm i eslint@latest
npm WARN acorn-jsx@5.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ eslint@5.9.0
added 1 package from 1 contributor, removed 607 packages, updated 3 packages and audited 9659 packages in 24.957s
found 0 vulnerabilities
$ npm run lint

> ezs-teeftfr@2.0.0 lint /home/parmentf/prog/node-ezs-teeftfr
> eslint --ext=.js ./test/*.js ./src/*.js

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'optionator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/parmentf/prog/node-ezs-teeftfr/node_modules/eslint/lib/options.js:12:20)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ezs-teeftfr@2.0.0 lint: `eslint --ext=.js ./test/*.js ./src/*.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ezs-teeftfr@2.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/parmentf/.npm/_logs/2018-11-14T09_51_32_629Z-debug.log
$ npm i eslint@latest
npm WARN acorn-jsx@5.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ eslint@5.9.0
added 601 packages from 1009 contributors, updated 1 package and audited 9659 packages in 25.621s
found 0 vulnerabilities

$ npm run lint

> ezs-teeftfr@2.0.0 lint /home/parmentf/prog/node-ezs-teeftfr
> eslint --ext=.js ./test/*.js ./src/*.js
```
