### ISSUE TITLE
Exception on running ESLint when package.json file has UTF8 BOM

### ISSUE THREAD

**Issue by undeadcat** [eslint/eslint#10672]
Similar to [6556](https://github.com/eslint/eslint/issues/6556) but that issue is closed. It seems like UTF BOM is stripped from config files but not everywhere files are read.
Removing the the BOM allows ESLint to complete normally.

From looking at the code, it seems like there are a few places where readFile/readFileSync are used, I would guess all of them would need to be looked at, even if not all need to be fixed.

* **ESLint Version:** 5.2.0
* **Node Version:** 10.5.0
* **npm Version:** 6.1.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "version": "1.0.0",
  "devDependencies": {
    "eslint": "5.2.0"
  },
  "eslintConfig": {
    "rules": {
      "quotes": ["error", "single"],
      "max-len": [
        "error",
        10
      ]
    }
  }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
//test.js
console.log('hello, World!')
```

```bash
node_modules/.bin/eslint test.js
```

**What did you expect to happen?**
Expected errors for file to be shown
**What actually happened? Please include the actual, raw output from ESLint.**
```
Oops! Something went wrong! :(

ESLint: 5.2.0.
Failed to read JSON file at /Users/jetbrains/testProjects/newProjectWithEslint/package.json:

Unexpected token ﻿ in JSON at position 0
```

Interestingly, ESLint version v.4.19 produces a stacktrace where the error actually occurs:
```
unit-812:newProjectWithEslint jetbrains$ node_modules/.bin/eslint test.js
Unexpected token ﻿ in JSON at position 0
SyntaxError: Unexpected token ﻿ in JSON at position 0
    at JSON.parse (<anonymous>)
    at new IgnoredPaths (/Users/jetbrains/testProjects/newProjectWithEslint/node_modules/eslint/lib/ignored-paths.js:176:55)
    at lodash.memoize.optionsObj (/Users/jetbrains/testProjects/newProjectWithEslint/node_modules/eslint/lib/util/glob-util.js:115:13)
    at memoized (/Users/jetbrains/testProjects/newProjectWithEslint/node_modules/lodash/lodash.js:10551:27)
    at globPatterns.forEach.pattern (/Users/jetbrains/testProjects/newProjectWithEslint/node_modules/eslint/lib/util/glob-util.js:162:34)
    at Array.forEach (<anonymous>)
    at Object.listFilesToProcess (/Users/jetbrains/testProjects/newProjectWithEslint/node_modules/eslint/lib/util/glob-util.js:158:18)
    at CLIEngine.executeOnFiles (/Users/jetbrains/testProjects/newProjectWithEslint/node_modules/eslint/lib/cli-engine.js:518:35)
    at Object.execute (/Users/jetbrains/testProjects/newProjectWithEslint/node_modules/eslint/lib/cli.js:189:111)
    at Object.<anonymous> (/Users/jetbrains/testProjects/newProjectWithEslint/node_modules/eslint/bin/eslint.js:74:28)
```

**Comment by platinumazure** [comment]
Hi @undeadcat, thanks for the issue and very sorry this slipped through the cracks.

@eslint/eslint-team Is this a bug? Can JSON files be written with a BOM normally?

**Comment by g-plane** [comment]
ESLint can strip BOM:
https://github.com/eslint/eslint/blob/d45b184df23a2bbb00b9c1249cc4904235ebe5f7/lib/config/config-file.js#L64

Tests:
https://github.com/eslint/eslint/blob/d45b184df23a2bbb00b9c1249cc4904235ebe5f7/tests/lib/config/config-file.js#L971

**Comment by kaicataldo** [comment]
Given the test that @g-plane linked to above, this seems like a bug to me. Curious what the rest of the team thinks.
