### ISSUE TITLE
eslint crash on broken symlinks

### ISSUE THREAD

**Issue by puzrin** [eslint/eslint#1080]
Sometime you can get broken symlinks in your project folders. For example in ./node_modules/.bin/ , if you delete dependency folders manually.

In this case eslint will crash with trace:

```
fs.js:684
  return binding.stat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'node_modules/.bin/csso'
    at Object.fs.statSync (fs.js:684:18)
    at /home/vitaly/Кодинг/nodeca_dev/nodeca/node_modules/eslint/lib/util/traverse.js:59:27
    at Array.forEach (native)
    at traverse (/home/vitaly/Кодинг/nodeca_dev/nodeca/node_modules/eslint/lib/util/traverse.js:57:54)
    at /home/vitaly/Кодинг/nodeca_dev/nodeca/node_modules/eslint/lib/util/traverse.js:69:17
    at Array.forEach (native)
    at traverse (/home/vitaly/Кодинг/nodeca_dev/nodeca/node_modules/eslint/lib/util/traverse.js:57:54)
    at /home/vitaly/Кодинг/nodeca_dev/nodeca/node_modules/eslint/lib/util/traverse.js:69:17
    at Array.forEach (native)
    at traverse (/home/vitaly/Кодинг/nodeca_dev/nodeca/node_modules/eslint/lib/util/traverse.js:57:54)
```

**Comment by nzakas** [comment]
This has been open for a while, and looking at it again, it seems like the current behavior is the most useful. The error message might not be pretty, but at least it points out the filename that is causing the problem.
