### ISSUE TITLE
Eslint failed with 'Cannot read property '0' of null' when 'no-trailing-spaces' rule enabled

### ISSUE THREAD

**Issue by evgygor** [eslint/eslint#10825]
- ESLint Version: 5.5.0
- Node Version: 10.7.0
- npm Version: 6.1.0

*Using eslint-roku-plugin*

The configuration is 
```
{
  "extends": ["plugin:roku/recommended"],
  "rules": {
    "roku/no-print": "warn",
    "roku/no-stop": "error",
    "roku/sub-to-function": "error",
    "roku/function-no-return": "error",
    "no-trailing-spaces":"error",
    "no-multiple-empty-lines":"warn"
  }
}
```

The command is `eslint **/*.brs`
When the rule 'no-trailing-spaces' is not 'off' the following error appears:

```
Cannot read property '0' of null
TypeError: Cannot read property '0' of null
    at Traverser.enter [as _enter] (C:\Git_work\main\node_modules\eslint\lib\util\source-code.js:395:31)
    at Traverser._traverse (C:\Git_work\main\node_modules\eslint\lib\util\traverser.js:132:14)
    at Traverser._traverse (C:\Git_work\main\node_modules\eslint\lib\util\traverser.js:147:30)
    at Traverser._traverse (C:\Git_work\main\node_modules\eslint\lib\util\traverser.js:144:34)
    at Traverser.traverse (C:\Git_work\main\node_modules\eslint\lib\util\traverser.js:115:14)
    at Function.traverse (C:\Git_work\main\node_modules\eslint\lib\util\traverser.js:181:25)
    at SourceCode.getNodeByRangeIndex (C:\Git_work\main\node_modules\eslint\lib\util\source-code.js:392:19)
    at checkTrailingSpaces (C:\Git_work\main\node_modules\eslint\lib\rules\no-trailing-spaces.js:139:59)
    at listeners.(anonymous function).forEach.listener (C:\Git_work\main\node_modules\eslint\lib\util\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
error Command failed with exit code 2.
```

When rule is 'off' the eslint works well.

Thanks

**Comment by evgygor** [comment]
It's happening with the specific file only and cannot find the issue in the file that causes the exception.
I attached the problematic file and debug log of the run
[dvrFutureRecordingsItem.txt](https://github.com/eslint/eslint/files/2344531/dvrFutureRecordingsItem.txt)

Actual extension of the file is brs (brightscript), but GitHub doesn't allow to upload it, so I changed it to txt.

The debug log ass follow:
`$ eslint **/dvrFutureRecordingsItem.brs --debug
  eslint:cli CLI args: [ '**/dvrFutureRecordingsItem.brs', '--debug' ] +0ms
  eslint:cli Running on files +8ms
  eslint:glob-utils Creating list of files to process. +0ms
  eslint:ignored-paths baseDir = "C:\\Git_works\\main" +0ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/node_modules/*"
  eslint:ignored-paths   cooked   = "/node_modules/*" +2ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/bower_components/*"
  eslint:ignored-paths   cooked   = "/bower_components/*" +1ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = ".*"
  eslint:ignored-paths   cooked   = ".*" +1ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "!../"
  eslint:ignored-paths   cooked   = "!../" +1ms
  eslint:ignored-paths Looking for ignore file in C:\Git_works\main +1ms
  eslint:ignored-paths Loaded ignore file C:\Git_works\main\.eslintignore +1ms
  eslint:ignored-paths Adding C:\Git_works\main\.eslintignore +1ms
  eslint:ignored-paths addPatternRelativeToIgnoreFile:
  eslint:ignored-paths   original = "**/csource"
  eslint:ignored-paths   cooked   = "**/csource" +1ms
  eslint:ignored-paths addPatternRelativeToIgnoreFile:
  eslint:ignored-paths   original = "**/csource"
  eslint:ignored-paths   cooked   = "**/csource" +1ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/node_modules/*"
  eslint:ignored-paths   cooked   = "/node_modules/*" +1ms
  eslint:ignored-paths addPatternRelativeToCwd:
  eslint:ignored-paths   original = "/bower_components/*"
  eslint:ignored-paths   cooked   = "/bower_components/*" +1ms
  eslint:ignored-paths contains: +695ms
  eslint:ignored-paths   target = "C:\\Git_works\\main\\DFW\\components\\viewsRefactored\\libraryLayerViews\\dvrFu
tureRecordingsView\\dvrFutureRecordingsItem.brs" +0ms
  eslint:ignored-paths   result = false +1ms
  eslint:ignored-paths contains: +0ms
  eslint:ignored-paths   target = "C:\\Git_works\\main\\DFW\\components\\viewsRefactored\\libraryLayerViews\\dvrFu
tureRecordingsView\\dvrFutureRecordingsItem.brs" +1ms
  eslint:ignored-paths   result = false +0ms
  eslint:cli-engine Processing C:\Git_works\main\DFW\components\viewsRefactored\libraryLayerViews\dvrFutureRecordi
ngsView\dvrFutureRecordingsItem.brs +0ms
  eslint:cli-engine Linting C:\Git_works\main\DFW\components\viewsRefactored\libraryLayerViews\dvrFutureRecordings
View\dvrFutureRecordingsItem.brs +1ms
  eslint:config Constructing config file hierarchy for C:\Git_works\main\DFW\components\viewsRefactored\libraryLay
erViews\dvrFutureRecordingsView +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading C:\Git_works\main\.eslintrc.json +4ms
  eslint:config-file Loading JSON config file: C:\Git_works\main\.eslintrc.json +0ms
  eslint:config-file Loading plugin:roku/recommended +366ms
  eslint:config-file Attempting to resolve eslint-plugin-roku +1ms
  eslint:config-file Loading JS config file: C:\Git_works\main\node_modules\eslint-plugin-roku\dist\index.js +2ms
  eslint:plugins Loaded plugin roku (eslint-plugin-roku@1.1.0) (from C:\Git_works\main\node_modules\eslint-plugin-
roku\dist\index.js) +0ms
  eslint:config Using C:\Git_works\main\.eslintrc.json +784ms
  eslint:config-ops Using config from partial cache +0ms
  eslint:config-ops Apply environment settings to config +1ms
  eslint:linter Linting code for C:\Git_works\main\DFW\components\viewsRefactored\libraryLayerViews\dvrFutureRecor
dingsView\dvrFutureRecordingsItem.brs (pass 1) +0ms
  eslint:linter An error occurred while traversing +205ms
  eslint:linter Filename: C:\Git_works\main\DFW\components\viewsRefactored\libraryLayerViews\dvrFutureRecordingsVi
ew\dvrFutureRecordingsItem.brs +1ms
  eslint:linter Parser Options: { ecmaVersion: undefined } +2ms
  eslint:linter Parser Path: C:\Git_works\main\node_modules\eslint-plugin-roku\dist\index.js +2ms
  eslint:linter Settings: {} +0ms
Cannot read property '0' of null
TypeError: Cannot read property '0' of null
    at Traverser.enter [as _enter] (C:\Git_works\main\node_modules\eslint\lib\util\source-code.js:395:31)
    at Traverser._traverse (C:\Git_works\main\node_modules\eslint\lib\util\traverser.js:132:14)
    at Traverser._traverse (C:\Git_works\main\node_modules\eslint\lib\util\traverser.js:147:30)
    at Traverser._traverse (C:\Git_works\main\node_modules\eslint\lib\util\traverser.js:144:34)
    at Traverser.traverse (C:\Git_works\main\node_modules\eslint\lib\util\traverser.js:115:14)
    at Function.traverse (C:\Git_works\main\node_modules\eslint\lib\util\traverser.js:181:25)
    at SourceCode.getNodeByRangeIndex (C:\Git_works\main\node_modules\eslint\lib\util\source-code.js:392:19)
    at checkTrailingSpaces (C:\Git_works\main\node_modules\eslint\lib\rules\no-trailing-spaces.js:140:59)
    at listeners.(anonymous function).forEach.listener (C:\Git_works\main\node_modules\eslint\lib\util\safe-emitte
r.js:45:58)
    at Array.forEach (<anonymous>)
error Command failed with exit code 2.`
