### ISSUE TITLE
No files matching the pattern "node_modules/asn1.js" were found.

### ISSUE THREAD

**Issue by jastuccio** [eslint/eslint#10880]
**Tell us about your environment**
* **ESLint Version:** 4.19.1
* **Node Version:** 9.8.0
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**
"babel-eslint": "^9.0.0",
"eslint": "^5.6.0",
"eslint-config-airbnb": "^17.1.0",
"eslint-config-prettier": "^3.0.1",
"eslint-config-react": "^1.1.7",
"eslint-plugin-import": "^2.14.0",
"eslint-plugin-jsx-a11y": "^6.1.1",
"eslint-plugin-prettier": "^2.6.2",
"eslint-plugin-react": "^7.11.1",
"prettier": "^1.14.3"

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

.eslintrc
```js
{
  "extends": ["airbnb", "prettier", "prettier/react"],
  "rules": {
    "react/jsx-filename-extension": [
      "error",
      {
        "extensions": [".js", ".jsx"]
      }
    ],
    "react/react-in-jsx-scope": 0,
    "react/require-default-props": 0,
    "react/forbid-prop-types": 1,
    "react/prefer-stateless-function": 1,
    "jsx-a11y/anchor-is-valid": 0,
    "arrow-body-style": 0,
    "no-shadow": 0,
    "consistent-return": 0,
    "no-console": 1,
    "no-case-declarations": 0,
    "import/prefer-default-export": 0
  },
  "settings": {
    "import/core-modules": ["react", "prop-types"]
  },
  "globals": {
    "graphql": true
  },
  "plugins": ["prettier"],
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 2017,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "es6": true,
    "browser": true,
    "node": true
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
"scripts": {
    
    ...

    "lint": "eslint **/*.{js,jsx}",

    ...
  },

```

github branch at time of error: [github.com/jastuccio/Polling-app/tree/eslint-error](github.com/jastuccio/Polling-app/tree/eslint-error)

**I use fish v2.7.1** in case it matters

```bash
npm run lint
```

**What did you expect to happen?**
run linting

**What actually happened? Please include the actual, raw output from ESLint.**
```
> gatsby-starter-default@1.0.0 lint /Users/joe/Tutorials/polling-app
> eslint **/*.{js,jsx}


Oops! Something went wrong! :(

ESLint: 5.6.0.
No files matching the pattern "node_modules/asn1.js" were found.
Please check for typing mistakes in the pattern.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! gatsby-starter-default@1.0.0 lint: `eslint **/*.{js,jsx}`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the gatsby-starter-default@1.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joe/.npm/_logs/2018-09-21T10_35_26_485Z-debug.log
```

debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.8.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'lint' ]
2 info using npm@6.4.1
3 info using node@v9.8.0
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle gatsby-starter-default@1.0.0~prelint: gatsby-starter-default@1.0.0
6 info lifecycle gatsby-starter-default@1.0.0~lint: gatsby-starter-default@1.0.0
7 verbose lifecycle gatsby-starter-default@1.0.0~lint: unsafe-perm in lifecycle true
8 verbose lifecycle gatsby-starter-default@1.0.0~lint: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/joe/Tutorials/polling-app/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle gatsby-starter-default@1.0.0~lint: CWD: /Users/joe/Tutorials/polling-app
10 silly lifecycle gatsby-starter-default@1.0.0~lint: Args: [ '-c', 'eslint **/*.{js,jsx}' ]
11 silly lifecycle gatsby-starter-default@1.0.0~lint: Returned: code: 2  signal: null
12 info lifecycle gatsby-starter-default@1.0.0~lint: Failed to exec lint script
13 verbose stack Error: gatsby-starter-default@1.0.0 lint: `eslint **/*.{js,jsx}`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid gatsby-starter-default@1.0.0
15 verbose cwd /Users/joe/Tutorials/polling-app
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/Cellar/node/9.8.0/bin/node" "/usr/local/bin/npm" "run" "lint"
18 verbose node v9.8.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 2
22 error gatsby-starter-default@1.0.0 lint: `eslint **/*.{js,jsx}`
22 error Exit status 2
23 error Failed at the gatsby-starter-default@1.0.0 lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by platinumazure** [comment]
Hi @jastuccio, thanks for the issue.

Can you try quoting the glob archive when you call ESLint? Just curious to see if that will work properly.

**Comment by jastuccio** [comment]
Thank you platinum! Adding single quotes around the glob resolved the issue.

`"lint": "eslint '**/*.{js,jsx}' --quiet",`

I added a comment about the issue to the tutorial on medium also.
