### ISSUE TITLE
Invalid type in config parameter "plugins" (eslintrc.json) generates a stacktrace

### ISSUE THREAD

**Issue by cotonne** [eslint/eslint#10927]
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X ] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] New rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-proposal.md))
[ ] Changes an existing rule ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md))
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

**Tell us about your environment**

* **ESLint Version:**     "eslint": "^5.6.1"
* **Node Version:** v8.10.0
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>
File eslintrc.json
```js
{
  ...
  "plugins": [
    ["import"],
    [{ "node": "node"}],
    { "promise": "promise" }],
  ]
}
```

</details>

**What did you do? Please include the actual source code causing the issue.**
Provided an invalid json config file.
cf. configuration (generated with a fuzzer PyJFuzz)

**What did you expect to happen?**
A meaningful message should be displayed.

**What actually happened? Please include the actual, raw output from ESLint.**
Big exception:
```
TypeError: normalizedName.charAt is not a function
    at Object.normalizePackageName (xxx/node_modules/eslint/lib/util/naming.js:37:24)
```

**What changes did you make? (Give an overview)**
When a non-string parameter is provided to the configuration parameter "plugins",
an exception is thrown

**Is there anything you'd like reviewers to focus on?**

**Comment by kaigouthro** [comment]
they shoiuld get interested fast.. it's a breaking change of some sort.... eslint won't run in VScode with the newest webpack and redux   and react and all that... doesn't matter what i do, even just load any given singlenone plugin, i get that exact same error. i ca only run eslint with zero config file. 

```
 eslint src
normalizedName.charAt is not a function
TypeError: normalizedName.charAt is not a function
    at Object.normalizePackageName (C:\Users\Kai\AppData\Roaming\npm\node_modules\eslint\lib\util\naming.js:37:24)
    at Plugins.load (C:\Users\Kai\AppData\Roaming\npm\node_modules\eslint\lib\config\plugins.js:75:33)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (C:\Users\Kai\AppData\Roaming\npm\node_modules\eslint\lib\config\plugins.js:157:21)
    at loadFromDisk (C:\Users\Kai\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:506:35)
    at Object.load (C:\Users\Kai\AppData\Roaming\npm\node_modules\eslint\lib\config\config-file.js:564:20)
    at Config.getLocalConfigHierarchy (C:\Users\Kai\AppData\Roaming\npm\node_modules\eslint\lib\config.js:227:44)
    at Config.getConfigHierarchy (C:\Users\Kai\AppData\Roaming\npm\node_modules\eslint\lib\config.js:179:43)
    at Config.getConfigVector (C:\Users\Kai\AppData\Roaming\npm\node_modules\eslint\lib\config.js:286:21)
    at Config.getConfig (C:\Users\Kai\AppData\Roaming\npm\node_modules\eslint\lib\config.js:329:29)

```
