### ISSUE TITLE
Cannot read property 'range' of null error with one-var

### ISSUE THREAD

**Issue by jkrup** [eslint/eslint#10937]
**Tell us about your environment**

* **ESLint Version:** master
* **Node Version:** 8 / 10
* **npm Version:** 5

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  module.exports = {
    "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "rules": {
    'one-var': ['error', 'never'],
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
var a = 1, b = 2
```

```bash
eslint file.js
```

**What did you expect to happen?**
```
var a = 1; var b = 2
```

**What actually happened? Please include the actual, raw output from ESLint.**
```
TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenAfter (/Users/justink/eslintbugtest/node_modules/eslint/lib/token-store/index.js:320:18)
    at declaration.declarations.map.declarator (/Users/justink/eslintbugtest/node_modules/eslint/lib/rules/one-var.js:322:47)
    at Array.map (<anonymous>)
    at Object.fixer [as fix] (/Users/justink/eslintbugtest/node_modules/eslint/lib/rules/one-var.js:315:54)
    at normalizeFixes (/Users/justink/eslintbugtest/node_modules/eslint/lib/report-translator.js:176:28)
    at args (/Users/justink/eslintbugtest/node_modules/eslint/lib/report-translator.js:278:18)
    at Object.report (/Users/justink/eslintbugtest/node_modules/eslint/lib/linter.js:830:41)
    at checkVariableDeclaration (/Users/justink/eslintbugtest/node_modules/eslint/lib/rules/one-var.js:480:33)
    at listeners.(anonymous function).forEach.listener (/Users/justink/eslintbugtest/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
```

**Additional Details:**
This only happens if the last statement in the file is a `var X, Y, ...` statement (and does not terminate with a `;`)

**Comment by not-an-aardvark** [comment]
Thanks for the report, I can reproduce this issue.
