### ISSUE TITLE
Compatibility issue with typescript, rewire & jest

### ISSUE THREAD

**Issue by El-Fitz** [eslint/eslint#10947]
**Tell us about your environment**

* **ESLint Version:** 4.19.1
* **Node Version:** 10.2.1
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**: tslint ¯\_(ツ)_/¯

**Please show your full configuration:** None, really

Using typescript with rewire(https://github.com/jhnns/rewire) and jest(https://github.com/facebook/jest) for testing ended up with the following error:

    Cannot find module '../conf/replacements' from 'rules.js'
        at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
        at Object.<anonymous> (node_modules/rewire/node_modules/eslint/lib/rules.js:14:26)

This occurs because rewire requires eslint as a dependency and jest tries to do something with all imported modules, but seemingly can't handle .json files
 
It can be 'solved ' by adding the .json extension in rules.js ruleReplacements import

    const ruleReplacements = require("../conf/replacements.json").rules; 

and the following in a typescript project's package.json: 

```js
    "jest": {
        "transform": {
			"\\.json$": "<rootDir>/your/dummy/emptyFile.js"
		},
```

I hope this might help some people in the future

**Comment by El-Fitz** [comment]
No, you are not. Jest apparently doesn't bother checking wether it is a JS module or not. And I have no idea how much work it would take on their side to do that. On the other hand, simply adding the .json extension, while not a real fix for Jest's mishandling, helps fixing it.

I've just opened an issue on jest's. Because it shouldn't crash like this when some dependeny's random dependency requires a .json (see https://github.com/facebook/jest/issues/7158)

**Comment by platinumazure** [comment]
@El-Fitz I guess I'm not sure there's any harm in making the change on our end at this point, so let's see what the rest of the team thinks. Thanks for creating the issue on Jest!

**Comment by El-Fitz** [comment]
So... it was an error on my side. I messed up while customising some jest settings, and didn't even notice it. The lesson today for me will be: no matter the experience, messing up and not noticing does and will still happen, I guess.

But thanks for the willingness to help ! :-)

**Comment by platinumazure** [comment]
@El-Fitz Thanks for following up. Just out of curiosity, what was the problem? (In case someone experiences a similar problem and finds this ESLint issue)

**Comment by El-Fitz** [comment]
@platinumazure 
You're welcome ! And yes, you're definitely right.
In order to run tests in Typescript, I used ts-jest and had to customise jest's `"moduleFileExtensions"` parameter in my package.json, to add typescript files extensions, like so:

```
"moduleFileExtensions": [
			"ts",
			"tsx",
			"js"
		]
```

when I should have updated it like this:
```
"moduleFileExtensions": [
			"ts",
			"tsx",
			"js",
			"json"
		]
```

You see, by default it has .json in there, but setting it overwrites the defaults completely. And without .json in there, jest will fail when a file requires a .json file.
