### ISSUE TITLE
no-tabs with allowIndentationTabs is invalid

### ISSUE THREAD

**Issue by Alex-PK** [eslint/eslint#10975]
**Tell us about your environment**

I just created a new Vue project with vue-cli 3 and started defining eslint rules

* **ESLint Version:** 4.19.1
* **Node Version:** 10.12.0
* **npm Version:** 6.4.1
* **yarn Version:** 1.10.1

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**
```js
{
	"name": "test",
	"version": "0.1.0",
	"private": true,
	"scripts": {
		"serve": "vue-cli-service serve",
		"build": "vue-cli-service build",
		"lint": "vue-cli-service lint"
	},
	"dependencies": {
		"lodash": "^4.17.11",
		"uikit": "^3.0.0-rc.19",
		"vue": "^2.5.17",
		"vue-router": "^3.0.1",
		"vuex": "^3.0.1"
	},
	"devDependencies": {
		"@vue/cli-plugin-babel": "^3.0.5",
		"@vue/cli-plugin-eslint": "^3.0.5",
		"@vue/cli-service": "^3.0.5",
		"@vue/eslint-config-standard": "^3.0.5",
		"node-sass": "^4.9.0",
		"sass-loader": "^7.0.1",
		"vue-template-compiler": "^2.5.17"
	},
	"eslintConfig": {
		"root": true,
		"env": {
			"node": true
		},
		"extends": [
			"plugin:vue/essential",
			"@vue/standard"
		],
		"parserOptions": {
			"parser": "babel-eslint"
		},
		"rules": {
			"semi": ["error", "never"],
			"indent": ["error", "tab"],
			"no-tabs": ["error", {"allowIndentationTabs": true}],
			"vue/html-indent": "warning",
			"vue/max-attributes-per-line": ["warning", {"singleline": 5, "multiline": {"max": 1, "allowFirstLine": false}}],
			"vue/mustache-interpolation-spacing": "warning",
			"vue/name-property-casing": ["error", "PascalCase|kebab-case"],
			"vue/no-multi-spaces": "warning",
			"vue/attributes-order": "warning",
			"vue/html-quotes": "warning",
			"vue/no-confusing-v-for-v-if": "warning",
			"vue/this-in-template": "warning",
			"vue/html-closing-bracket-spacing": "warning",
			"vue/prop-name-casing": "warning",
			"vue/script-indent": ["error", "tab", {"baseIndent": 1, "switchcase": 1}]
		}
	},
	"postcss": {
		"plugins": {
			"autoprefixer": {}
		}
	},
	"browserslist": [
		"> 1%",
		"last 2 versions",
		"not ie <= 8"
	]
}
```

eslint fails parsing the above configuration with the following error:

```
Error: /home/alex/Projects/js/test/package.json:
	Configuration for rule "no-tabs" is invalid:
	Value [{"allowIndentationTabs":true}] should NOT have more than 0 items.


Error: /home/alex/Projects/js/test/package.json:
	Configuration for rule "no-tabs" is invalid:
	Value [{"allowIndentationTabs":true}] should NOT have more than 0 items.

    at validateRuleOptions (/home/alex/Projects/js/test/node_modules/eslint/lib/config/config-validator.js:119:19)
    at Object.keys.forEach.id (/home/alex/Projects/js/test/node_modules/eslint/lib/config/config-validator.js:162:9)
    at Array.forEach (<anonymous>)
    at validateRules (/home/alex/Projects/js/test/node_modules/eslint/lib/config/config-validator.js:161:30)
    at Object.validate (/home/alex/Projects/js/test/node_modules/eslint/lib/config/config-validator.js:239:5)
    at loadFromDisk (/home/alex/Projects/js/test/node_modules/eslint/lib/config/config-file.js:516:19)
    at Object.load (/home/alex/Projects/js/test/node_modules/eslint/lib/config/config-file.js:559:20)
    at Config.getLocalConfigHierarchy (/home/alex/Projects/js/test/node_modules/eslint/lib/config.js:227:44)
    at Config.getConfigHierarchy (/home/alex/Projects/js/test/node_modules/eslint/lib/config.js:179:43)
    at Config.getConfigVector (/home/alex/Projects/js/test/node_modules/eslint/lib/config.js:286:21)
Process finished with exit code -1
```

**Comment by not-an-aardvark** [comment]
Hi, thanks for the report. The `allowIndentationTabs` option was introduced in ESLint v5.7.0, but you seem to be using ESLint v4.19.1. Does the option work if you upgrade to the latest version of ESLint?

**Comment by Alex-PK** [comment]
Thanks for the quick reply.

I confirm it works after adding `"eslint": "^5.7"` in the `devDependencies`.

I was referring to this page: https://eslint.org/docs/rules/no-tabs where it says it was introduced in 3.2.0.
Could you please add a note on the option with the minimum version?

**Comment by kaicataldo** [comment]
@Alex-PK There's a discussion around your request [here](https://github.com/eslint/eslint.github.io/issues/485).

**Comment by kaicataldo** [comment]
Closing this issue as it looks like the question has been answered. Please feel free to visit us in the [ESLint Gitter](https://gitter.im/eslint/eslint) if you have any other issues!
