### ISSUE TITLE
ESLINT fails to parse webpack JS configuration file - TemplateLiteral results in TypeError: Cannot read property 'range' of null

### ISSUE THREAD

**Issue by petrdanecek** [eslint/eslint#11004]
**Tell us about your environment**

* **ESLint Version: 5.7.0**
* **Node Version: v8.11.3**
* **npm Version: 3.10.10**
* **babel-eslint: 10.0.1**

**What parser (default, Babel-ESLint, etc.) are you using?**
"parser": "babel-eslint",

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
// .eslintrc.json
{
  "parser": "babel-eslint",
  "env": {
    "browser": true,
    "commonjs": true,
    "es6": true,
    "node": true,
    "jest": true
  },
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true,
      "jsx": true
    }
  },
  "plugins": [
    "react",
    "babel",
    "html"
  ],
  "extends": [
    "eslint:recommended",
    "airbnb",
    "plugin:react/recommended"
  ],
  "rules": {
    "function-paren-newline": ["error", "consistent"],
    "key-spacing": ["error", {
      "beforeColon": false,
      "afterColon": true,
      "mode": "minimum"
    }]
  }
}


```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
// webpack configuration - merge
export const developmentConfig = (projPaths, { HMR_HOST, HMR_PORT }) => merge([
  {
    output: {
      publicPath: `http://${HMR_HOST}:${HMR_PORT}/`,
    },
  }
]};
```

eslint fails to parse the above TemplateLiteral string.
```bash
eslint webpack.snippets.js
TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenBefore (/home/pd/proj/node_modules/eslint/lib/token-store/index.js:303:18)
    at checkSpacingBefore (/home/pd/proj/node_modules/eslint/lib/rules/template-curly-spacing.js:52:42)
    at TemplateElement (/home/pd/proj/node_modules/eslint/lib/rules/template-curly-spacing.js:117:17)
    at listeners.(anonymous function).forEach.listener (/home/pd/proj/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/home/pd/proj/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/pd/proj/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/home/pd/proj/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/home/pd/proj/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/home/pd/proj/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)```
```

**What did you expect to happen?**
ESlinter to generate some warning or success

**What actually happened? Please include the actual, raw output from ESLint.**
Eslinter fails to parse token with error: TypeError: Cannot read property 'range' of null

**Comment by not-an-aardvark** [comment]
Hi, thanks for reporting an issue.

I can't seem to reproduce this bug in the [demo](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IHRlbXBsYXRlLWN1cmx5LXNwYWNpbmc6IGVycm9yICovXG5cbmV4cG9ydCBjb25zdCBkZXZlbG9wbWVudENvbmZpZyA9IChwcm9qUGF0aHMsIHsgSE1SX0hPU1QsIEhNUl9QT1JUIH0pID0+IG1lcmdlKFtcbiAge1xuICAgIG91dHB1dDoge1xuICAgICAgcHVibGljUGF0aDogYGh0dHA6Ly8ke0hNUl9IT1NUfToke0hNUl9QT1JUfS9gLFxuICAgIH0sXG4gIH1cbl0pOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6OSwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6eyJqc3giOnRydWV9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=). (Note: I replaced the `}` in the last line of your code with a `)`, since the code would be invalid otherwise -- I'm assuming this was a typo.) Are you able to reproduce this problem without using the `babel-eslint` parser? If not, it's possible that this is a bug in `babel-eslint`.

It looks like a similar bug has been reported to `babel-eslint` here: https://github.com/babel/babel-eslint/issues/681

**Comment by petrdanecek** [comment]
Hi,

thanks for quick turnaround. Yeah it was typo, you are right. The config is more complex, but I copied the problematic part only.
I do actually not work in shell, but I'm experiencing it in VSCode editor.
I tried to copy the code from your demo to new file, the eslint run results in same error:

```bash
eslint test.js
TypeError: Cannot read property 'range' of null

```

However replacing back tilde ` by regular string ' fixed it.
I'm not sure that the this is enough to avoid using babel-eslint parser, I tried to comment it out:
```js
// .eslintrc.json
{
  // disabling ?
  // "parser": "babel-eslint",
...
}
```

right after the problem disappeared.

**Comment by petrdanecek** [comment]
NOTE it seems that babel-eslint is not required at all
source: [Why Use babel-eslint](https://github.com/babel/babel-eslint)
You only need to use babel-eslint if you are using types (Flow) or experimental features not supported in ESLint itself yet. Otherwise try the default parser (you don't have to use it just because you are using Babel).
