### ISSUE TITLE
got "TypeError: Cannot read property 'loc' of undefined" after entering 'const' in typescript file in vscode

### ISSUE THREAD

**Issue by UncleYee** [eslint/eslint#11023]
**Tell us about your environment**

* **ESLint Version: v4.19.1** 
* **Node Version: v8.11.2**
* **npm Version: v5.6.0**

**What parser (default, Babel-ESLint, etc.) are you using?**
typescript-eslint-parser

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  "env": {
    "browser": true,
    "node": true,
    "es6": true
  },
  "extends": "eslint-config-alloy/typescript",
  "parser": "typescript-eslint-parser",
  "plugins": ["typescript"],
  "rules": {
    "indent": ["warn", 2], //  Cannot read property 'loc' of undefined
    "linebreak-style": ["error", "unix"],
    "quotes": ["error", "single"],
    "curly": [2, "all"],
    "typescript/class-name-casing": "error",
    "typescript/type-annotation-spacing": "warn",
    "typescript/member-ordering": "off",
    "no-undefined": "off",
    "no-console": "off",
    "no-var": "error",
    "no-eval": "off",
    "no-unused-vars": "warn",
    "semi": "off",
    "space-before-blocks": "warn",
    "key-spacing": "warn",
    "arrow-spacing": "warn",
    "comma-spacing": "warn",
    "space-infix-ops": "warn",
    "one-var": "off",
    "object-curly-spacing": "warn",
    "typescript/member-delimiter-style": "warn",
    "no-return-assign": "off",
    "eqeqeq": "off",
    "no-use-before-define": "warn",
    "space-before-function-paren": "warn",
    "no-fallthrough": "warn",
    "no-confusing-arrow": "warn",
    "keyword-spacing": "warn",
    "no-throw-literal": "off",
    "no-useless-constructor": "warn",
    "max-nested-callbacks": "off",
    "max-depth": "off",
    "complexity": "off"
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

After entering const

**What did you expect to happen?**
no error

**What actually happened? Please include the actual, raw output from ESLint.**

[Trace - 3:10:47 PM] Received notification 'window/logMessage'.
[Error - 3:10:47 PM] TypeError: Cannot read property 'loc' of undefined
    at Object.VariableDeclaration [as listener] (/openSource/koa-typescript-example/node_modules/eslint/lib/rules/indent.js:1317:69)
    at Program:exit.listenerCallQueue.filter.forEach.nodeInfo (/openSource/koa-typescript-example/node_modules/eslint/lib/rules/indent.js:1496:55)
    at Array.forEach (<anonymous>)
    at Program:exit (/openSource/koa-typescript-example/node_modules/eslint/lib/rules/indent.js:1496:26)
    at listeners.(anonymous function).forEach.listener (/openSource/koa-typescript-example/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/openSource/koa-typescript-example/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/openSource/koa-typescript-example/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/openSource/koa-typescript-example/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.leaveNode (/openSource/koa-typescript-example/node_modules/eslint/lib/util/node-event-generator.js:303:14)

**Comment by mysticatea** [comment]
Thank you for this report.

This causes by that `typescript-eslint-parser` generates wrong AST.
`const` with no declarator is a syntax error, but `typescript-eslint-parser` passes it. As the result, some core rules can throw errors.

I'd like to recommend to open an issue on `typescirpt-eslint-parser` repo.
