### ISSUE TITLE
no-useless-catch throw on catch block without binding

### ISSUE THREAD

**Issue by vsemozhetbyt** [eslint/eslint#11208]
**Tell us about your environment**

* **ESLint Version:** v5.11.0
* **Node Version:** 11.5.0
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?** default

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
'use strict';

try {
  console.log(true);
} catch {
  console.log(false);
}
```

```bash
eslint --no-eslintrc --parser-options=ecmaVersion:2019 --rule "no-useless-catch: 2" test.js
```

**What did you expect to happen?**

No errors.

**What actually happened? Please include the actual, raw output from ESLint.**

```sh
TypeError: Cannot read property 'type' of null
    at CatchClause (eslint\lib\rules\no-useless-catch.js:30:32)
    at listeners.(anonymous function).forEach.listener (eslint\lib\util\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (eslint\lib\util\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (eslint\lib\code-path-analysis\code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo (eslint\lib\linter.js:750:28)
    at Array.forEach (<anonymous>)
```

**Comment by Aladdin-ADD** [comment]
thanks for the report! it could be fixed by #11205
