### ISSUE TITLE
Init failed

### ISSUE THREAD

**Issue by Mikuu** [eslint/eslint#11269]
**The version of ESLint you are using**: 5.12.0
**What you did**: init
**The actual ESLint output complete with numbers**

```commandline
$ ./node_modules/.bin/eslint --init
? How would you like to configure ESLint? Use a popular style guide
? Which style guide do you want to follow? Airbnb (https://github.com/airbnb/javascript)
? Do you use React? No
? What format do you want your config file to be in? JSON
Checking peerDependencies of eslint-config-airbnb-base@latest
SyntaxError: Unexpected token } in JSON at position 169
Error: SyntaxError: Unexpected token } in JSON at position 169
    at check (/Users/ariman/Workspace/Webber/vcer-ui/test/node_modules/eslint/lib/util/npm-utils.js:112:23)
    at Object.checkDevDeps (/Users/ariman/Workspace/Webber/vcer-ui/test/node_modules/eslint/lib/util/npm-utils.js:160:12)
    at getModulesList (/Users/ariman/Workspace/Webber/vcer-ui/test/node_modules/eslint/lib/config/config-initializer.js:112:40)
    at inquirer.prompt.then.earlyAnswers (/Users/ariman/Workspace/Webber/vcer-ui/test/node_modules/eslint/lib/config/config-initializer.js:509:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**What you expected to happen instead**: init succeed.

**Comment by Artenes** [comment]
Faced the same issue and `sudo npm cache clean --force` seams to solve the problem.

**Comment by kaicataldo** [comment]
Closing this due to age. Please feel free to visit [our chat](https://gitter.im/eslint/eslint) if you have any others issues.
