### ISSUE TITLE
5.13.0 breaks shareable configs?

### ISSUE THREAD

**Issue by Aghassi** [eslint/eslint#11345]
**Tell us about your environment**

* **ESLint Version:** 5.13.0
* **Node Version:** 8.12.0
* **yarn Version:** v1.13.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

We have a shareable config that has the structure

<details>
<summary>Configuration</summary>

```js

module.exports = {
  extends: ['airbnb-base', 'prettier'],
  plugins: sharedPlugins,
  rules: sharedRules,
};
```

Where `sharedPlugins` and `sharedRules` are imported from another object. The sharedPlugins and rules are shared across multiple configs within this package so we can publish different types of configs (`jest`, `cypress`, etc), while still updating a shared set of objects.

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

The shared config is then published and resolved in a shared scripts package similar to `fbjs`. The scripts package has logic to expose and export the config path.

```js
const getESLintConfig = (type = 'src') => {
  switch (type.toLowerCase()) {
    case 'src':
      return require.resolve('eslint-config-shared');
    case 'jest':
      return require.resolve('eslint-config-shared/jest');
    case 'cypress':
      return require.resolve('eslint-config-shared/cypress');
    case 'infra':
      return require.resolve('eslint-config-shared/infra');
    default:
      throw new Error(`Invalid ESLint config type: ${type}`);
  }
};
```

This package is consumed via other packages and called in the ESLint RC file like this: 

```
const { getConfigPath } = require('@shared/infra-scripts');
module.exports = require(getConfigPath('eslint', 'infra'));
```

In ESLint 5.12.0, when I would run `yarn lint` and passed the config, I would have no issues. Only thing that was required was that teams would have to install all `plugin` dependencies so the shared config would not break. However, when running `yarn lint` on ESLint 5.13.0, now I get the error 

```
plugin-cli-create on  master is 📦 v1.1.2 via ⬢ v8.12.0 at ☸️ docker-for-desktop took 23s
➜ yarn lint
yarn run v1.13.0
$ yarn lint:js
$ eslint *.js --config=.eslintrc.js
Error: Cannot find module 'eslint-config-prettier'
Referenced from: /Users/daghassi/git/plugin-cli-create/.eslintrc.js
    at ModuleResolver.resolve (/Users/daghassi/git/plugin-cli-create/node_modules/eslint/lib/util/module-resolver.js:72:19)
    at resolve (/Users/daghassi/git/plugin-cli-create/node_modules/eslint/lib/config/config-file.js:484:28)
    at load (/Users/daghassi/git/plugin-cli-create/node_modules/eslint/lib/config/config-file.js:556:26)
    at configExtends.reduceRight (/Users/daghassi/git/plugin-cli-create/node_modules/eslint/lib/config/config-file.js:430:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/daghassi/git/plugin-cli-create/node_modules/eslint/lib/config/config-file.js:408:26)
    at loadFromDisk (/Users/daghassi/git/plugin-cli-create/node_modules/eslint/lib/config/config-file.js:528:22)
    at Object.load (/Users/daghassi/git/plugin-cli-create/node_modules/eslint/lib/config/config-file.js:564:20)
    at Config.loadSpecificConfig (/Users/daghassi/git/plugin-cli-create/node_modules/eslint/lib/config.js:148:46)
    at new Config (/Users/daghassi/git/plugin-cli-create/node_modules/eslint/lib/config.js:114:14)
```

I suspect this means something has changed in the resolution code since we didn't modify how the core config objects are resolved.

**What did you expect to happen?**

I expected to lint my code

**What actually happened? Please include the actual, raw output from ESLint.**

I was given an error unable to find an extended config module

```
plugin-cli-create on  master is 📦 v1.1.2 via ⬢ v8.12.0 at ☸️ docker-for-desktop took 23s
➜ yarn lint
yarn run v1.13.0
$ yarn lint:js
$ eslint *.js --config=.eslintrc.js
Error: Cannot find module 'eslint-config-prettier'
Referenced from: /Users/daghassi/git/plugin-cli-create/.eslintrc.js
    at ModuleResolver.resolve (/Users/daghassi/git/plugin-cli-create/node_modules/eslint/lib/util/module-resolver.js:72:19)
    at resolve (/Users/daghassi/git/plugin-cli-create/node_modules/eslint/lib/config/config-file.js:484:28)
    at load (/Users/daghassi/git/plugin-cli-create/node_modules/eslint/lib/config/config-file.js:556:26)
    at configExtends.reduceRight (/Users/daghassi/git/plugin-cli-create/node_modules/eslint/lib/config/config-file.js:430:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/daghassi/git/plugin-cli-create/node_modules/eslint/lib/config/config-file.js:408:26)
    at loadFromDisk (/Users/daghassi/git/plugin-cli-create/node_modules/eslint/lib/config/config-file.js:528:22)
    at Object.load (/Users/daghassi/git/plugin-cli-create/node_modules/eslint/lib/config/config-file.js:564:20)
    at Config.loadSpecificConfig (/Users/daghassi/git/plugin-cli-create/node_modules/eslint/lib/config.js:148:46)
    at new Config (/Users/daghassi/git/plugin-cli-create/node_modules/eslint/lib/config.js:114:14)
```

**Are you willing to submit a pull request to fix this bug?**
Yes if I can be pointed to what might have changed

Ultimately, I want clarity on if this is an intended change, or if this is a regression. If it is an intended change, how are users suppose to share configs going forward?

**Comment by Aghassi** [comment]
It's possible this is a case where `require.resolve` would help, but I'm not sure on how that fits in with `extends` that have syntax like `'plugin:eslint-comments/recommended'`

**Comment by not-an-aardvark** [comment]
Hi, thanks for reporting an issue.

I don't think much has changed in config resolution code since v5.12.0, although it's possible a regression was inadvertently introduced somewhere.

* For the purposes of narrowing down the issue: does the problem still occur with v5.12.1?
* Could you provide a reproducible case that causes this bug? 

Given that the error appears to be from loading `eslint-config-prettier`, it seems like your custom logic for `sharedPlugins` and `sharedRules` is probably unrelated to the issue. Have you installed `eslint-config-prettier` as a devDependency?

**Comment by Aghassi** [comment]
@not-an-aardvark 5.12.1 works. I think I typo'ed in my report. That was the version new are using.

Let me see if I can whip up a case where it would happen since these are internal libs. I have not added `eslint-config-prettier` as a devDependency because I was under the impression I didn't have to based on https://github.com/eslint/eslint/issues/3458. In addition, this guide makes it seem like I shouldn't have to https://eslint.org/docs/developer-guide/shareable-configs, but maybe I'm misunderstanding

**Comment by Aghassi** [comment]
So... I'm going to close this tentatively because I modified my shareable configs to do a `require.resolve` on the `extends` packages. I guess that was on me. Man, nested dependencies is always a pain. Sorry for the trouble!
