### ISSUE TITLE
no-useless-constructor crashes: Cannot read property 'body' of null

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint#11440]
**Tell us about your environment**

* **ESLint Version:** v5.14.1
* **Node Version:** n/a
* **npm Version:** n/a

**What parser (default, Babel-ESLint, etc.) are you using?**
`@typescript-eslint/parser`
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

```

```bash
>  eslint --ext={.ts,.js} .
```

**What did you expect to happen?**
no crashes.

**What actually happened? Please include the actual, raw output from ESLint.**
```bash
TypeError: Cannot read property 'body' of null
    at checkForConstructor (/Users/weiran/repo/work/sw/node_modules/eslint/lib/rules/no-useless-constructor.js:169:42)
    at listeners.(anonymous function).forEach.listener (/Users/weiran/repo/work/sw/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/weiran/repo/work/sw/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/weiran/repo/work/sw/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/weiran/repo/work/sw/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/weiran/repo/work/sw/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/weiran/repo/work/sw/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo (/Users/weiran/repo/work/sw/node_modules/eslint/lib/linter.js:750:28)
    at Array.forEach (<anonymous>)
```
**Are you willing to submit a pull request to fix this bug?**
atm no.

**Comment by platinumazure** [comment]
Thanks for the issue!

Do you happen to know what source file it crashes on? It would help to see the source code being linted if at all possible.

**Comment by g-plane** [comment]
They have similar rule: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-useless-constructor.md

**Comment by aladdin-add** [comment]
Unfortunately I cannot provide the source code -- I was running eslint on a mono repo(`node_modules` not ignored). 😭 

@g-plane thanks for the link! I was using its recommended preset, seems the rule is not included. what is the different with the core rule?

**Comment by mysticatea** [comment]
That considers TypeScript-specific syntax such as accessibility (e.g. `private constructor() {}` is not useless constructor.).

**Comment by aladdin-add** [comment]
Duplicate of #11464

**Comment by ypresto** [comment]
I agree with that that syntax is TypeScript specific, but also JS user can get annoying error message while typing.

![eslint-error](https://user-images.githubusercontent.com/400558/54547656-83442680-49e9-11e9-91e4-2f153491579b.gif)

**Comment by g-plane** [comment]
@ypresto I can't reproduce it. Can you provide more information?

**Comment by jacobrask** [comment]
See the workarounds in https://github.com/typescript-eslint/typescript-eslint/pull/167
