### ISSUE TITLE
Specifying `--ignore-pattern` when also specifying an `--ignore-path` outside of the current directory causes a crash.

### ISSUE THREAD

**Issue by spiltcoffee** [eslint/eslint#11479]
**Tell us about your environment**

* **ESLint Version:** 5.15.0
* **Node Version:** 10.15.0
* **npm Version:** 6.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "extends": [
    "eslint:recommended"
  ],
  "parserOptions": {
    "ecmaVersion": 2018
  },
  "env": {
    "node": true,
    "es6": true
  },
  "root": true
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```bash
eslint "**/*.js" --ignore-path ./../.gitignore --ignore-pattern anything
```

**What did you expect to happen?**
To not crash

**What actually happened? Please include the actual, raw output from ESLint.**
The following error occurs:
```shell
TypeError: globPattern.startsWith is not a function
    at relativize (node_modules\eslint\lib\util\ignored-paths.js:106:32)
    at IgnoredPaths.addPatternRelativeToCwd (node_modules\eslint\lib\util\ignored-paths.js:250:15)
    at new IgnoredPaths (node_modules\eslint\lib\util\ignored-paths.js:232:22)
    at lodash.memoize.optionsObj (node_modules\eslint\lib\util\glob-utils.js:193:13)
    at memoized (node_modules\eslint\node_modules\lodash\lodash.js:10553:27)
    at resolvedGlobPatterns.map.pattern (node_modules\eslint\lib\util\glob-utils.js:224:30)
    at Array.map (<anonymous>)
    at Object.listFilesToProcess (node_modules\eslint\lib\util\glob-utils.js:203:61)
    at CLIEngine.executeOnFiles (node_modules\eslint\lib\cli-engine.js:586:36)
    at Object.execute (node_modules\eslint\lib\cli.js:197:111)
```

I think the bug is here:
https://github.com/eslint/eslint/blob/5018378131fd5190bbccca902c0cf4276ee1581a/lib/util/ignored-paths.js#L245-L253

The variable `pattern` can be an array (due to the use of `--ignored-pattern` on the command line), which causes the call to `relativize()` falls over.

**Are you willing to submit a pull request to fix this bug?**
Yes, but I'm not sure what the correct code looks like here. Once that's determined, I'd be happy to make a PR.

**Comment by katanagari7c1** [comment]
Looks related to issue #11429 , maybe?
