### ISSUE TITLE
Installing eslint prevents devDependencies from being installed

### ISSUE THREAD

**Issue by enoh-barbu** [eslint/eslint#11825]
I tried a fresh install on a new npm project and I found out that most of the devDependencies eg shelljs, are not installed after I run "npm install eslint". 

I copied all the dependencies and devDepencies from eslint/package.json into my local package.json and run "npm install" but I got two blockers:

    `"eslint-config-eslint": "file:packages/eslint-config-eslint",`
    **Could not install from "packages\eslint-config-eslint" as it does not contain a package.json file.**

    `"eslint-plugin-internal-rules": "file:tools/internal-rules",`
    **Could not install from "tools\internal-rules" as it does not contain a package.json file.**

If I remove these two lines and run again "npm install" all the devDependecies are installed properly so I could find then inside _/node_modules_
Not sure if the problem is related to these two described above but the problem is that eslint does not install devDependencies

OS: windows 10

**Comment by g-plane** [comment]
devDependencies are for contributors of ESLint when they're developing ESLint, not for end users. We recommend you to read documentation of npm to get more help.

**Comment by enoh-barbu** [comment]
@g-plane yes, I understand but I can not use eslint because it fails installing shelljs and therefore it throws this error: `internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'shelljs'`

**Comment by platinumazure** [comment]
Could you please summarize your exact steps for how to reproduce this issue on a new repository? If we're exposing shelljs somewhere, we have a real bug. But we need to understand exactly how you got here in order to know for sure. Thanks!

**Comment by kaicataldo** [comment]
Filling out the full bug report template would help us a lot. Thanks!

**Comment by enoh-barbu** [comment]
I end up here by upgrading eslint from v3.19.0 to 5.16.0 and I tried to run my project (some gulp stuff) but I got that error `internal/modules/cjs/loader.js:584 throw err; ^ Error: Cannot find module 'shelljs'` . I had to debug this until I figured out that that this is related to eslint module. I took a look over both versions and I noticed in the newest version,**Makefile.js** uses shelljs at line 32 `const { cat, cd, cp, echo, exec, exit, find, ls, mkdir, pwd, rm, test } = require("shelljs");`  I'm not sure what that file is used for but in the prior version the shelljs was not required.

**Comment by enoh-barbu** [comment]
@platinumazure not sure what you mean by exposing it (maybe imported) but yes it is used (required) at line 32 in **Makefile.js**

**Comment by mysticatea** [comment]
I'm not sure what you are doing.

- How do you install eslint? Why `shelljs` or `Makefile.js` appeared? Our released package doesn't include those because those are development tools.
- How do you use eslint? Please tell us your command (or source code to use).

Thanks.

**Comment by enoh-barbu** [comment]
I only did **npm install eslint** and I tried to run again the project but it crashes, nothing more. If I do install the old version v3.19.0, the shelljs problem it's not referenced anymore.

**Comment by mysticatea** [comment]
- `Makefile.js` isn't included in the `eslint` package in npm. Why did you see `Makefile.js`?
- How do you use eslint? Please tell us your command (or source code to use). We don't know the mean of "run again the project".

**Comment by mysticatea** [comment]
For a reference, the following files are all files the `eslint` v5.16.0 package includes.

<details>

```
~\dev\eslint [(v5.16.0)]> npm pack
npm notice
npm notice package: eslint@5.16.0
npm notice === Tarball Contents ===
npm notice 3.8kB   package.json
npm notice 378.1kB CHANGELOG.md
npm notice 1.1kB   LICENSE
npm notice 16.3kB  README.md
npm notice 2.5kB   bin/eslint.js
npm notice 3.0kB   conf/category-list.json
npm notice 1.6kB   conf/config-schema.js
npm notice 649B    conf/default-cli-options.js
npm notice 2.3kB   conf/environments.js
npm notice 929B    conf/eslint-all.js
npm notice 401B    conf/eslint-recommended.js
npm notice 1.1kB   conf/replacements.json
npm notice 597B    lib/api.js
npm notice 16.3kB  lib/built-in-rules-index.js
npm notice 28.5kB  lib/cli-engine.js
npm notice 7.7kB   lib/cli.js
npm notice 20.0kB  lib/code-path-analysis/code-path-analyzer.js
npm notice 7.4kB   lib/code-path-analysis/code-path-segment.js
npm notice 44.7kB  lib/code-path-analysis/code-path-state.js
npm notice 7.0kB   lib/code-path-analysis/code-path.js
npm notice 6.5kB   lib/code-path-analysis/debug-helpers.js
npm notice 7.7kB   lib/code-path-analysis/fork-context.js
npm notice 959B    lib/code-path-analysis/id-generator.js
npm notice 13.9kB  lib/config.js
npm notice 12.2kB  lib/config/autoconfig.js
npm notice 4.8kB   lib/config/config-cache.js
npm notice 20.9kB  lib/config/config-file.js
npm notice 23.0kB  lib/config/config-initializer.js
npm notice 15.6kB  lib/config/config-ops.js
npm notice 9.5kB   lib/config/config-rule.js
npm notice 9.7kB   lib/config/config-validator.js
npm notice 2.2kB   lib/config/environments.js
npm notice 5.7kB   lib/config/plugins.js
npm notice 1.7kB   lib/formatters/checkstyle.js
npm notice 4.8kB   lib/formatters/codeframe.js
npm notice 1.5kB   lib/formatters/compact.js
npm notice 327B    lib/formatters/html-template-message.html
npm notice 3.6kB   lib/formatters/html-template-page.html
npm notice 164B    lib/formatters/html-template-result.html
npm notice 4.7kB   lib/formatters/html.js
npm notice 1.1kB   lib/formatters/jslint-xml.js
npm notice 408B    lib/formatters/json-with-metadata.js
npm notice 349B    lib/formatters/json.js
npm notice 2.3kB   lib/formatters/junit.js
npm notice 3.3kB   lib/formatters/stylish.js
npm notice 3.8kB   lib/formatters/table.js
npm notice 3.1kB   lib/formatters/tap.js
npm notice 1.5kB   lib/formatters/unix.js
npm notice 1.5kB   lib/formatters/visualstudio.js
npm notice 42.5kB  lib/linter.js
npm notice 1.4kB   lib/load-rules.js
npm notice 7.0kB   lib/options.js
npm notice 3.7kB   lib/rules.js
npm notice 5.4kB   lib/rules/accessor-pairs.js
npm notice 9.7kB   lib/rules/array-bracket-newline.js
npm notice 9.1kB   lib/rules/array-bracket-spacing.js
npm notice 8.2kB   lib/rules/array-callback-return.js
npm notice 9.4kB   lib/rules/array-element-newline.js
npm notice 10.4kB  lib/rules/arrow-body-style.js
npm notice 5.9kB   lib/rules/arrow-parens.js
npm notice 5.2kB   lib/rules/arrow-spacing.js
npm notice 3.7kB   lib/rules/block-scoped-var.js
npm notice 5.1kB   lib/rules/block-spacing.js
npm notice 7.9kB   lib/rules/brace-style.js
npm notice 6.5kB   lib/rules/callback-return.js
npm notice 8.5kB   lib/rules/camelcase.js
npm notice 10.8kB  lib/rules/capitalized-comments.js
npm notice 3.6kB   lib/rules/class-methods-use-this.js
npm notice 12.0kB  lib/rules/comma-dangle.js
npm notice 6.7kB   lib/rules/comma-spacing.js
npm notice 12.1kB  lib/rules/comma-style.js
npm notice 5.0kB   lib/rules/complexity.js
npm notice 6.8kB   lib/rules/computed-property-spacing.js
npm notice 6.7kB   lib/rules/consistent-return.js
npm notice 5.0kB   lib/rules/consistent-this.js
npm notice 13.8kB  lib/rules/constructor-super.js
npm notice 15.9kB  lib/rules/curly.js
npm notice 2.9kB   lib/rules/default-case.js
npm notice 3.3kB   lib/rules/dot-location.js
npm notice 6.4kB   lib/rules/dot-notation.js
npm notice 3.9kB   lib/rules/eol-last.js
npm notice 6.3kB   lib/rules/eqeqeq.js
npm notice 4.4kB   lib/rules/for-direction.js
npm notice 6.9kB   lib/rules/func-call-spacing.js
npm notice 10.1kB  lib/rules/func-name-matching.js
npm notice 6.0kB   lib/rules/func-names.js
npm notice 2.9kB   lib/rules/func-style.js
npm notice 9.3kB   lib/rules/function-paren-newline.js
npm notice 7.1kB   lib/rules/generator-star-spacing.js
npm notice 6.2kB   lib/rules/getter-return.js
npm notice 2.4kB   lib/rules/global-require.js
npm notice 2.4kB   lib/rules/guard-for-in.js
npm notice 3.0kB   lib/rules/handle-callback-err.js
npm notice 4.1kB   lib/rules/id-blacklist.js
npm notice 4.2kB   lib/rules/id-length.js
npm notice 8.4kB   lib/rules/id-match.js
npm notice 2.9kB   lib/rules/implicit-arrow-linebreak.js
npm notice 45.5kB  lib/rules/indent-legacy.js
npm notice 69.2kB  lib/rules/indent.js
npm notice 4.5kB   lib/rules/init-declarations.js
npm notice 3.0kB   lib/rules/jsx-quotes.js
npm notice 25.4kB  lib/rules/key-spacing.js
npm notice 21.7kB  lib/rules/keyword-spacing.js
npm notice 4.3kB   lib/rules/line-comment-position.js
npm notice 3.3kB   lib/rules/linebreak-style.js
npm notice 15.9kB  lib/rules/lines-around-comment.js
npm notice 7.8kB   lib/rules/lines-around-directive.js
npm notice 5.2kB   lib/rules/lines-between-class-members.js
npm notice 1.7kB   lib/rules/max-classes-per-file.js
npm notice 4.7kB   lib/rules/max-depth.js
npm notice 14.0kB  lib/rules/max-len.js
npm notice 7.1kB   lib/rules/max-lines-per-function.js
npm notice 4.7kB   lib/rules/max-lines.js
npm notice 3.6kB   lib/rules/max-nested-callbacks.js
npm notice 3.1kB   lib/rules/max-params.js
npm notice 7.5kB   lib/rules/max-statements-per-line.js
npm notice 5.5kB   lib/rules/max-statements.js
npm notice 14.7kB  lib/rules/multiline-comment-style.js
npm notice 3.5kB   lib/rules/multiline-ternary.js
npm notice 9.7kB   lib/rules/new-cap.js
npm notice 2.0kB   lib/rules/new-parens.js
npm notice 9.8kB   lib/rules/newline-after-var.js
npm notice 8.1kB   lib/rules/newline-before-return.js
npm notice 3.6kB   lib/rules/newline-per-chained-call.js
npm notice 4.0kB   lib/rules/no-alert.js
npm notice 1.4kB   lib/rules/no-array-constructor.js
npm notice 1.1kB   lib/rules/no-async-promise-executor.js
npm notice 2.8kB   lib/rules/no-await-in-loop.js
npm notice 3.6kB   lib/rules/no-bitwise.js
npm notice 1.3kB   lib/rules/no-buffer-constructor.js
npm notice 1.2kB   lib/rules/no-caller.js
npm notice 1.9kB   lib/rules/no-case-declarations.js
npm notice 2.5kB   lib/rules/no-catch-shadow.js
npm notice 1.7kB   lib/rules/no-class-assign.js
npm notice 1.9kB   lib/rules/no-compare-neg-zero.js
npm notice 5.1kB   lib/rules/no-cond-assign.js
npm notice 2.5kB   lib/rules/no-confusing-arrow.js
npm notice 4.3kB   lib/rules/no-console.js
npm notice 1.5kB   lib/rules/no-const-assign.js
npm notice 8.7kB   lib/rules/no-constant-condition.js
npm notice 875B    lib/rules/no-continue.js
npm notice 3.2kB   lib/rules/no-control-regex.js
npm notice 947B    lib/rules/no-debugger.js
npm notice 965B    lib/rules/no-delete-var.js
npm notice 1.2kB   lib/rules/no-div-regex.js
npm notice 2.4kB   lib/rules/no-dupe-args.js
npm notice 3.7kB   lib/rules/no-dupe-class-members.js
npm notice 4.0kB   lib/rules/no-dupe-keys.js
npm notice 1.3kB   lib/rules/no-duplicate-case.js
npm notice 4.5kB   lib/rules/no-duplicate-imports.js
npm notice 10.5kB  lib/rules/no-else-return.js
npm notice 2.0kB   lib/rules/no-empty-character-class.js
npm notice 4.7kB   lib/rules/no-empty-function.js
npm notice 1.2kB   lib/rules/no-empty-pattern.js
npm notice 2.5kB   lib/rules/no-empty.js
npm notice 1.2kB   lib/rules/no-eq-null.js
npm notice 9.5kB   lib/rules/no-eval.js
npm notice 1.4kB   lib/rules/no-ex-assign.js
npm notice 7.1kB   lib/rules/no-extend-native.js
npm notice 5.8kB   lib/rules/no-extra-bind.js
npm notice 4.4kB   lib/rules/no-extra-boolean-cast.js
npm notice 4.9kB   lib/rules/no-extra-label.js
npm notice 30.1kB  lib/rules/no-extra-parens.js
npm notice 4.2kB   lib/rules/no-extra-semi.js
npm notice 4.9kB   lib/rules/no-fallthrough.js
npm notice 2.4kB   lib/rules/no-floating-decimal.js
npm notice 2.0kB   lib/rules/no-func-assign.js
npm notice 2.8kB   lib/rules/no-global-assign.js
npm notice 10.3kB  lib/rules/no-implicit-coercion.js
npm notice 1.8kB   lib/rules/no-implicit-globals.js
npm notice 6.1kB   lib/rules/no-implied-eval.js
npm notice 2.2kB   lib/rules/no-inline-comments.js
npm notice 2.6kB   lib/rules/no-inner-declarations.js
npm notice 4.1kB   lib/rules/no-invalid-regexp.js
npm notice 3.8kB   lib/rules/no-invalid-this.js
npm notice 8.9kB   lib/rules/no-irregular-whitespace.js
npm notice 1.1kB   lib/rules/no-iterator.js
npm notice 2.2kB   lib/rules/no-label-var.js
npm notice 4.3kB   lib/rules/no-labels.js
npm notice 3.5kB   lib/rules/no-lone-blocks.js
npm notice 3.7kB   lib/rules/no-lonely-if.js
npm notice 6.0kB   lib/rules/no-loop-func.js
npm notice 5.9kB   lib/rules/no-magic-numbers.js
npm notice 6.2kB   lib/rules/no-misleading-character-class.js
npm notice 6.9kB   lib/rules/no-mixed-operators.js
npm notice 7.1kB   lib/rules/no-mixed-requires.js
npm notice 4.6kB   lib/rules/no-mixed-spaces-and-tabs.js
npm notice 1.2kB   lib/rules/no-multi-assign.js
npm notice 5.0kB   lib/rules/no-multi-spaces.js
npm notice 1.7kB   lib/rules/no-multi-str.js
npm notice 5.9kB   lib/rules/no-multiple-empty-lines.js
npm notice 2.9kB   lib/rules/no-native-reassign.js
npm notice 2.7kB   lib/rules/no-negated-condition.js
npm notice 1.1kB   lib/rules/no-negated-in-lhs.js
npm notice 986B    lib/rules/no-nested-ternary.js
npm notice 1.3kB   lib/rules/no-new-func.js
npm notice 923B    lib/rules/no-new-object.js
npm notice 960B    lib/rules/no-new-require.js
npm notice 1.3kB   lib/rules/no-new-symbol.js
npm notice 1.1kB   lib/rules/no-new-wrappers.js
npm notice 913B    lib/rules/no-new.js
npm notice 1.1kB   lib/rules/no-obj-calls.js
npm notice 1.4kB   lib/rules/no-octal-escape.js
npm notice 886B    lib/rules/no-octal.js
npm notice 6.5kB   lib/rules/no-param-reassign.js
npm notice 1.5kB   lib/rules/no-path-concat.js
npm notice 1.7kB   lib/rules/no-plusplus.js
npm notice 1.0kB   lib/rules/no-process-env.js
npm notice 1.1kB   lib/rules/no-process-exit.js
npm notice 1.1kB   lib/rules/no-proto.js
npm notice 1.7kB   lib/rules/no-prototype-builtins.js
npm notice 3.2kB   lib/rules/no-redeclare.js
npm notice 3.8kB   lib/rules/no-regex-spaces.js
npm notice 3.8kB   lib/rules/no-restricted-globals.js
npm notice 10.1kB  lib/rules/no-restricted-imports.js
npm notice 6.0kB   lib/rules/no-restricted-modules.js
npm notice 6.6kB   lib/rules/no-restricted-properties.js
npm notice 2.0kB   lib/rules/no-restricted-syntax.js
npm notice 2.5kB   lib/rules/no-return-assign.js
npm notice 3.8kB   lib/rules/no-return-await.js
npm notice 1.1kB   lib/rules/no-script-url.js
npm notice 6.6kB   lib/rules/no-self-assign.js
npm notice 1.8kB   lib/rules/no-self-compare.js
npm notice 4.0kB   lib/rules/no-sequences.js
npm notice 2.1kB   lib/rules/no-shadow-restricted-names.js
npm notice 7.0kB   lib/rules/no-shadow.js
npm notice 2.4kB   lib/rules/no-spaced-func.js
npm notice 1.1kB   lib/rules/no-sparse-arrays.js
npm notice 1.6kB   lib/rules/no-sync.js
npm notice 2.1kB   lib/rules/no-tabs.js
npm notice 1.1kB   lib/rules/no-template-curly-in-string.js
npm notice 793B    lib/rules/no-ternary.js
npm notice 10.2kB  lib/rules/no-this-before-super.js
npm notice 1.2kB   lib/rules/no-throw-literal.js
npm notice 6.3kB   lib/rules/no-trailing-spaces.js
npm notice 2.1kB   lib/rules/no-undef-init.js
npm notice 2.3kB   lib/rules/no-undef.js
npm notice 2.1kB   lib/rules/no-undefined.js
npm notice 7.6kB   lib/rules/no-underscore-dangle.js
npm notice 3.7kB   lib/rules/no-unexpected-multiline.js
npm notice 11.9kB  lib/rules/no-unmodified-loop-condition.js
npm notice 6.6kB   lib/rules/no-unneeded-ternary.js
npm notice 6.4kB   lib/rules/no-unreachable.js
npm notice 4.0kB   lib/rules/no-unsafe-finally.js
npm notice 2.8kB   lib/rules/no-unsafe-negation.js
npm notice 4.8kB   lib/rules/no-unused-expressions.js
npm notice 3.3kB   lib/rules/no-unused-labels.js
npm notice 24.9kB  lib/rules/no-unused-vars.js
npm notice 7.6kB   lib/rules/no-use-before-define.js
npm notice 2.8kB   lib/rules/no-useless-call.js
npm notice 1.6kB   lib/rules/no-useless-catch.js
npm notice 3.3kB   lib/rules/no-useless-computed-key.js
npm notice 3.2kB   lib/rules/no-useless-concat.js
npm notice 5.6kB   lib/rules/no-useless-constructor.js
npm notice 9.0kB   lib/rules/no-useless-escape.js
npm notice 5.2kB   lib/rules/no-useless-rename.js
npm notice 11.8kB  lib/rules/no-useless-return.js
npm notice 11.9kB  lib/rules/no-var.js
npm notice 1.1kB   lib/rules/no-void.js
npm notice 5.6kB   lib/rules/no-warning-comments.js
npm notice 3.4kB   lib/rules/no-whitespace-before-property.js
npm notice 785B    lib/rules/no-with.js
npm notice 4.4kB   lib/rules/nonblock-statement-body-position.js
npm notice 10.9kB  lib/rules/object-curly-newline.js
npm notice 11.3kB  lib/rules/object-curly-spacing.js
npm notice 3.7kB   lib/rules/object-property-newline.js
npm notice 20.1kB  lib/rules/object-shorthand.js
npm notice 2.8kB   lib/rules/one-var-declaration-per-line.js
npm notice 21.5kB  lib/rules/one-var.js
npm notice 7.9kB   lib/rules/operator-assignment.js
npm notice 10.2kB  lib/rules/operator-linebreak.js
npm notice 10.3kB  lib/rules/padded-blocks.js
npm notice 20.6kB  lib/rules/padding-line-between-statements.js
npm notice 11.4kB  lib/rules/prefer-arrow-callback.js
npm notice 16.8kB  lib/rules/prefer-const.js
npm notice 9.9kB   lib/rules/prefer-destructuring.js
npm notice 4.0kB   lib/rules/prefer-named-capture-group.js
npm notice 3.8kB   lib/rules/prefer-numeric-literals.js
npm notice 9.3kB   lib/rules/prefer-object-spread.js
npm notice 5.5kB   lib/rules/prefer-promise-reject-errors.js
npm notice 4.6kB   lib/rules/prefer-reflect.js
npm notice 3.3kB   lib/rules/prefer-rest-params.js
npm notice 2.8kB   lib/rules/prefer-spread.js
npm notice 11.7kB  lib/rules/prefer-template.js
npm notice 11.7kB  lib/rules/quote-props.js
npm notice 11.4kB  lib/rules/quotes.js
npm notice 5.3kB   lib/rules/radix.js
npm notice 12.6kB  lib/rules/require-atomic-updates.js
npm notice 3.1kB   lib/rules/require-await.js
npm notice 3.7kB   lib/rules/require-jsdoc.js
npm notice 2.0kB   lib/rules/require-unicode-regexp.js
npm notice 2.1kB   lib/rules/require-yield.js
npm notice 4.0kB   lib/rules/rest-spread-spacing.js
npm notice 7.8kB   lib/rules/semi-spacing.js
npm notice 5.1kB   lib/rules/semi-style.js
npm notice 11.8kB  lib/rules/semi.js
npm notice 9.3kB   lib/rules/sort-imports.js
npm notice 4.9kB   lib/rules/sort-keys.js
npm notice 4.1kB   lib/rules/sort-vars.js
npm notice 5.7kB   lib/rules/space-before-blocks.js
npm notice 5.1kB   lib/rules/space-before-function-paren.js
npm notice 9.6kB   lib/rules/space-in-parens.js
npm notice 5.5kB   lib/rules/space-infix-ops.js
npm notice 12.6kB  lib/rules/space-unary-ops.js
npm notice 12.7kB  lib/rules/spaced-comment.js
npm notice 10.6kB  lib/rules/strict.js
npm notice 5.3kB   lib/rules/switch-colon-spacing.js
npm notice 2.0kB   lib/rules/symbol-description.js
npm notice 4.2kB   lib/rules/template-curly-spacing.js
npm notice 2.9kB   lib/rules/template-tag-spacing.js
npm notice 2.2kB   lib/rules/unicode-bom.js
npm notice 1.0kB   lib/rules/use-isnan.js
npm notice 20.6kB  lib/rules/valid-jsdoc.js
npm notice 3.0kB   lib/rules/valid-typeof.js
npm notice 5.1kB   lib/rules/vars-on-top.js
npm notice 6.0kB   lib/rules/wrap-iife.js
npm notice 1.9kB   lib/rules/wrap-regex.js
npm notice 4.3kB   lib/rules/yield-star-spacing.js
npm notice 11.3kB  lib/rules/yoda.js
npm notice 21.6kB  lib/testers/rule-tester.js
npm notice 2.0kB   lib/token-store/backward-token-comment-cursor.js
npm notice 1.7kB   lib/token-store/backward-token-cursor.js
npm notice 2.3kB   lib/token-store/cursor.js
npm notice 3.9kB   lib/token-store/cursors.js
npm notice 1.0kB   lib/token-store/decorative-cursor.js
npm notice 1.2kB   lib/token-store/filter-cursor.js
npm notice 2.0kB   lib/token-store/forward-token-comment-cursor.js
npm notice 1.8kB   lib/token-store/forward-token-cursor.js
npm notice 24.9kB  lib/token-store/index.js
npm notice 1.1kB   lib/token-store/limit-cursor.js
npm notice 1.6kB   lib/token-store/padded-token-cursor.js
npm notice 1.2kB   lib/token-store/skip-cursor.js
npm notice 3.4kB   lib/token-store/utils.js
npm notice 862B    lib/util/ajv.js
npm notice 7.2kB   lib/util/apply-disable-directives.js
npm notice 45.7kB  lib/util/ast-utils.js
npm notice 4.5kB   lib/util/config-comment-parser.js
npm notice 4.6kB   lib/util/file-finder.js
npm notice 4.2kB   lib/util/fix-tracker.js
npm notice 10.5kB  lib/util/glob-utils.js
npm notice 1.9kB   lib/util/glob.js
npm notice 1.1kB   lib/util/hash.js
npm notice 13.3kB  lib/util/ignored-paths.js
npm notice 764B    lib/util/interpolate.js
npm notice 917B    lib/util/keywords.js
npm notice 5.5kB   lib/util/lint-result-cache.js
npm notice 430B    lib/util/logging.js
npm notice 3.0kB   lib/util/module-resolver.js
npm notice 3.6kB   lib/util/naming.js
npm notice 11.4kB  lib/util/node-event-generator.js
npm notice 6.0kB   lib/util/npm-utils.js
npm notice 2.5kB   lib/util/path-utils.js
npm notice 8.1kB   lib/util/patterns/letters.js
npm notice 10.0kB  lib/util/report-translator.js
npm notice 4.6kB   lib/util/rule-fixer.js
npm notice 2.1kB   lib/util/safe-emitter.js
npm notice 4.7kB   lib/util/source-code-fixer.js
npm notice 3.9kB   lib/util/source-code-utils.js
npm notice 18.9kB  lib/util/source-code.js
npm notice 3.4kB   lib/util/timing.js
npm notice 5.4kB   lib/util/traverser.js
npm notice 345B    lib/util/unicode/index.js
npm notice 12.8kB  lib/util/unicode/is-combining-character.js
npm notice 367B    lib/util/unicode/is-emoji-modifier.js
npm notice 397B    lib/util/unicode/is-regional-indicator-symbol.js
npm notice 471B    lib/util/unicode/is-surrogate-pair.js
npm notice 936B    lib/util/xml-escape.js
npm notice 578B    messages/all-files-ignored.txt
npm notice 223B    messages/extend-config-missing.txt
npm notice 60B     messages/failed-to-read-json.txt
npm notice 110B    messages/file-not-found.txt
npm notice 412B    messages/no-config-found.txt
npm notice 621B    messages/plugin-missing.txt
npm notice 291B    messages/whitespace-found.txt
npm notice === Tarball Details ===
npm notice name:          eslint
npm notice version:       5.16.0
npm notice filename:      eslint-5.16.0.tgz
npm notice package size:  535.1 kB
npm notice unpacked size: 2.6 MB
npm notice shasum:        38c5ed48c0d2d0f2bbaaf0d667c487d779773a92
npm notice integrity:     sha512-l+iVwmanxXil2[...]TJ3s1IdBpWGtQ==
npm notice total files:   374
npm notice
```

</details>

`Makefile.js` doesn't exist.

**Comment by enoh-barbu** [comment]
@mysticatea I didn't said that, I only saw the reference to sheljjs in the file, I don't even know that's used for, although shelljs it's used as a dependency is package.json. I only came with some thoughts that you might help me.

**Comment by platinumazure** [comment]
Hi @enoh-barbu. At this point we are very confused by what you're trying to do, to the point that we can't tell if you are trying to *use* ESLint (in a project), or *develop* ESLint (to contribute to the project). Please answer the questions raised by eslintbot so we can understand exactly what you're trying to do. Thanks!

**Comment by enoh-barbu** [comment]
Hi @platinumazure I'm trying to use it... sorry for confusing you, my bad.

**Comment by mysticatea** [comment]
Please answer:

- How do you use eslint? Please tell us your command (or source code to use).

**Comment by enoh-barbu** [comment]
I have **.eslintrc.js** file configured and that's all. I did nothing more than just upgrading the eslint version. By running the project I mean running some gulp tasks to build the FE and nothing more. I can not give you more details on the gulp commands, I'm thinking this might be also a problem related to _npm_

**Comment by mysticatea** [comment]
OK. I'd like to change my question.

- Would you provide the full error message that includes the stacktrace?

I suspect the error came from another place than ESLint.

Old ESLint has `shelljs` as a dependency, but recent ESLint doesn't depend on `shelljs`. This means `npm install eslint` removed `shelljs` from your `node_modules` if other package didn't use `shelljs`. In this situation, if your code imports `shelljs`, then it throws module not found error.

**Comment by enoh-barbu** [comment]
`$ gulp watch
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'shelljs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\enohb\Desktop\go-aysist\frontend\gulp\build.js:16:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)`

Hope it helps, that's all the stacktrace

**Comment by mysticatea** [comment]
Thanks. Looks like `C:\Users\enohb\Desktop\go-aysist\frontend\gulp\build.js:16:15` is the cause.

**Comment by enoh-barbu** [comment]
```
$ gulp watch
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'shelljs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\frontend\gulp\build.js:16:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

**Comment by mysticatea** [comment]
Thanks. Looks like `C:\Users\enohb\Desktop\go-aysist\frontend\gulp\build.js:16:15` is the cause.

**Comment by enoh-barbu** [comment]
Not sure what to say, but I would prefer to keep that line hidden if possible, could you please remove it or hide the path?

**Comment by enoh-barbu** [comment]
oh right, so actually it is used there so it's as you said that _Old ESLint had shelljs as a dependency_ now I have to install it manually and the problem should be fixed! Thank you!

**Comment by enoh-barbu** [comment]
@mysticatea yes it works! I will close the issue, thanks again 👍

**Comment by mysticatea** [comment]
Thanks. Looks like `C:\Users\frontend\gulp\build.js:16:15` is the cause. (I deleted my previous comment that included another path.)

----

If you use a package in your code, you must have the package in your `package.json`.

If you use a package that another package depends on, it will be broken if the "another package" is uninstalled. Such a package is called "extraneous package". If you want to detect the use of extraneous packages, you can use [node/no-extraneous-require](https://www.npmjs.com/package/eslint-plugin-node#-rules) or [import/no-extraneous-dependencies](https://www.npmjs.com/package/eslint-plugin-import#rules).

**Comment by platinumazure** [comment]
Based on your stack trace, it looks like your build.js calls `require("shelljs")` and you haven't specified shelljs as a dependency or devDependency in your project. You were getting lucky because ESLint had a dependency on it at one point.

In general, you should always add dependencies or devDependencies to package.json directly if they are used in code you write.

**Comment by enoh-barbu** [comment]
Yes, that was the problem but I wasn't aware of it as the project is new for me too. I only went to upgrade eslint but I couldn't realize that in the beginning.
