### ISSUE TITLE
ESLint v6 cannot install vue plugin

### ISSUE THREAD

**Issue by francoism90** [eslint/eslint#11875]
**Tell us about your environment**

* **ESLint Version:** v6.0.0
* **Node Version:** v11.15.0
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?** defailt

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": [
        "plugin:vue/essential",
        "standard"
    ],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "plugins": [
        "vue"
    ],
    "rules": {
    }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
{
  "name": "project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "license": "MIT",
  "devDependencies": {
    "eslint": "^6.0.0",
    "eslint-plugin-vue": "^5.2.2"
  }
}
```

```bash
$ yarn run eslint --init
```

**What did you expect to happen?**
Successfully install the vue-plugin

**What actually happened? Please include the actual, raw output from ESLint.**
```
Checking peerDependencies of eslint-config-standard@latest
Checking peerDependencies of eslint-config-plugin:vue/essential,standard@latest
The config that you've selected requires the following dependencies:

eslint-plugin-vue@latest eslint-config-plugin:vue/essential,standard@latest
? Would you like to install them now with npm? Yes
Installing eslint-plugin-vue@latest, eslint-config-plugin:vue/essential,standard@latest
npm ERR! code ENOLOCAL
npm ERR! Could not install from "eslint-config-plugin:vue/essential,standard@latest" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-06-22T10_17_54_465Z-debug.log
An error occurred while generating your JavaScript config file. A config file was still generated, but the config file itself may not follow your linting rules.
Error: Failed to load plugin 'vue' declared in 'BaseConfig': Cannot find module 'eslint/lib/util/traverser'
Referenced from: BaseConfig
Error: An error occurred while generating your JavaScript config file. A config file was still generated, but the config file itself may not follow your linting rules.
Error: Failed to load plugin 'vue' declared in 'BaseConfig': Cannot find module 'eslint/lib/util/traverser'
Referenced from: BaseConfig
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/user/Documents/project/node_modules/eslint-plugin-vue/lib/rules/order-in-components.js:8:19)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Are you willing to submit a pull request to fix this bug?**
No, sorry.

**Comment by fisker** [comment]
I had made a PR https://github.com/vuejs/eslint-plugin-vue/pull/910 3 hours ago, will fix this

**Comment by francoism90** [comment]
@fisker Thanks for the PR, hope it will be merged soon. :)

I'll stick with Eslint V5 until it has been fixed.
