### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by BryceLee** [eslint/eslint#11944]
**Tell us about your environment**

* **ESLint Version:**6.0.1
* **Node Version:**4.1.2
* **npm Version:**7.7.3

**What parser (default, Babel-ESLint, etc.) are you using?**default

input eslint --version
```
/usr/local/lib/node_modules/eslint/lib/cli-engine/cli-engine.js:257
        ...calculateStatsPerFile(messages)
        ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/eslint/lib/cli-engine/index.js:3:23)

```

**Comment by mysticatea** [comment]
Your Node.js version is too old. ESLint 6 requires 8 or newer, but you are using `4.1.2`

**Comment by BryceLee** [comment]
@MylesBorins got it!Thanks!

**Comment by dyspop** [comment]
Seeing this as well
```
node --version
v8.0.0

npm --version
6.10.2

which eslint
/Users/dblack/.nodenv/shims/eslint

which node
/Users/dblack/.nodenv/shims/node

which npm
/Users/dblack/.nodenv/shims/npm
```

**Comment by platinumazure** [comment]
@dyspop What is your ESLint version? Did you configure `parserOptions.ecmaVersion` properly? Please open a new issue as your issue is likely for a different reason, and please fill out the full issue template when you do so. Thanks!
