### ISSUE TITLE
v6.2.0 throws an error that v6.1.0  and earlier does not

### ISSUE THREAD

**Issue by Xotic750** [eslint/eslint#12132]
**Tell us about your environment**

* **ESLint Version:**
6.2.0
* **Node Version:**
8.11.4
* **npm Version:**
6.10.1
**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

https://github.com/Xotic750/string-starts-with-x

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

I don't know what is causing it. It was working before 6.2.0

https://github.com/Xotic750/string-starts-with-x

```bash
> eslint -f 'node_modules/eslint-friendly-formatter' --ext .js,.json . "--fix"

TypeError: Cannot read property 'type' of undefined
Occurred while linting /Users/grahamfairweather/.private/project-updater-x/tmp/string-starts-with-x/__tests__/string-starts-with-x.test.js:1
    at getStringIfConstant (/Users/grahamfairweather/.private/project-updater-x/tmp/string-starts-with-x/node_modules/eslint-utils/index.js:756:14)
    at Program (/Users/grahamfairweather/.private/project-updater-x/tmp/string-starts-with-x/node_modules/eslint/lib/rules/no-misleading-character-class.js:184:35)
    at /Users/grahamfairweather/.private/project-updater-x/tmp/string-starts-with-x/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/grahamfairweather/.private/project-updater-x/tmp/string-starts-with-x/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/grahamfairweather/.private/project-updater-x/tmp/string-starts-with-x/node_modules/eslint/lib/linter/node-event-generator.js:253:26)
    at NodeEventGenerator.applySelectors (/Users/grahamfairweather/.private/project-updater-x/tmp/string-starts-with-x/node_modules/eslint/lib/linter/node-event-generator.js:282:22)
    at NodeEventGenerator.enterNode (/Users/grahamfairweather/.private/project-updater-x/tmp/string-starts-with-x/node_modules/eslint/lib/linter/node-event-generator.js:296:14)
    at CodePathAnalyzer.enterNode (/Users/grahamfairweather/.private/project-updater-x/tmp/string-starts-with-x/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:646:23)
    at /Users/grahamfairweather/.private/project-updater-x/tmp/string-starts-with-x/node_modules/eslint/lib/linter/linter.js:916:32
npm ERR! code ELIFECYCLE
npm ERR! errno 2

```

**What did you expect to happen?**

For it to work as previously.

**What actually happened? Please include the actual, raw output from ESLint.**

It throws and points to:
```js
function getStringIfConstant(node, initialScope = null) {
    // Handle the literals that the platform doesn't support natively.
    if (node.type === "Literal" && node.value === null) {
        if (node.regex) {
            return `/${node.regex.pattern}/${node.regex.flags}`
        }
        if (node.bigint) {
            return node.bigint
        }
    }

    const evaluated = getStaticValue(node, initialScope);
    return evaluated && String(evaluated.value)
}
```
**Are you willing to submit a pull request to fix this bug?**
Willing, but unlikely.

**Comment by mysticatea** [comment]
Thank you for your report.

Would you try the latest ESLint?
It should have been fixed already.

**Comment by Xotic750** [comment]
Aha, I didn't see there was a new release just 40 mins ago. :) I will give it a try.

**Comment by Xotic750** [comment]
With 6.2.1 all now seems fine, thanks.
