### ISSUE TITLE
cygpath not found on windows with MINGW shell

### ISSUE THREAD

**Issue by crystalfp** [eslint/eslint#12211]
**Tell us about your environment**

* **ESLint Version:** 6.3.0
* **Node Version:** 10.15.0
* **npm Version:** 6.11.3
Windows 10 64bits
Using MSYS and MINGW (unknown version) to emulate Unix shell

**What parser (default, Babel-ESLint, etc.) are you using?** "@typescript-eslint/parser"

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
	"parser": "@typescript-eslint/parser",
	"plugins": [
		"node",
		"promise",
		"import",
		"@typescript-eslint",
		"no-useless-assign",
		"eslint-comments",
		"dollar-sign",
		"optimize-regex",
		"const-case"
	],
    "extends": [
		"eslint:recommended",
		"plugin:eslint-comments/recommended",
		"plugin:promise/recommended",
		"plugin:node/recommended",
		"plugin:import/errors",
		"plugin:import/warnings",
		"plugin:import/typescript",
		"plugin:@typescript-eslint/recommended"
	],
	"parserOptions": {
		"ecmaVersion": 8,
		"impliedStrict": true
	},
	"env": {
		"es6": true,
		"node": true
	},
    "rules": {
		"node/no-missing-require": "off",
		"node/no-deprecated-api": "error",
		"node/exports-style": ["error", "exports"],
		"node/no-unsupported-features/node-builtins": ["error", {"version": ">=10.9.0"}],
		"node/no-unsupported-features/es-builtins": ["error", {"version": ">=10.9.0"}],
		"node/no-unsupported-features/es-syntax": ["off", {"version": ">=10.9.0"}],
		"node/no-unpublished-require": "off",
		"no-buffer-constructor": "error",
		"no-redeclare": ["error", { "builtinGlobals": true }],
        "no-unused-vars": "error",
        "no-undef": "error",
        "no-extend-native": "error",
        "no-sequences": "error",
        "no-new": "error",
        "no-bitwise": "error",
        "quotes": [ "warn", "double", {"avoidEscape": true} ],
        "semi": [ "error", "always" ],
        "eqeqeq": [ "error", "always" ],
        "strict": [ "error", "global" ],
        "no-loop-func": "error",
        "no-unused-expressions": "error",
        "max-len": [ "warn", 140 ],
		"space-before-function-paren": ["error", {
			"anonymous": "never",
			"named": "never",
			"asyncArrow": "always"
		}],
		"space-before-blocks": "warn",
		"no-shadow": [ "error", { "hoist": "all", "builtinGlobals": true, "allow": ["$", "event", "self"] } ],
        "comma-spacing": [ "error", { "before": false, "after": true } ],
        "keyword-spacing": [ "warn", { "before": true, "after": false, "overrides": {"else": {"after": true}, "return": {"after": true}, "try": {"after": true}, "case": {"after": true}, "const": {"after": true}, "throw": {"after": true}, "let": {"after": true}, "do": {"after": true}, "of": {"after": true}, "finally": {"after": true}, "from": {"after": true}, "import": {"after": true}, "export": {"after": true}, "default": {"after": true}}}],
        "no-trailing-spaces": "warn",
        "id-length": ["warn", {"exceptions": ["$", "i", "j", "x", "y", "w", "h", "g"]}],
		"prefer-const": "warn",

		"for-direction": "error",
		"no-template-curly-in-string": "error",
		"consistent-return": "error",
		"no-unmodified-loop-condition": "error",
		"handle-callback-err": "error",
		"array-bracket-spacing": ["warn", "never"],
		"brace-style": ["warn", "stroustrup", {"allowSingleLine": true}],
		"spaced-comment": ["warn", "always", { "markers": [":", "-", "+", "::", "/"] }],
		"no-var": "error",

		"block-scoped-var": "error",
		"yoda": "error",
		"camelcase": ["warn", { "properties": "never" }],
		"max-depth": ["warn", 4],
		"arrow-parens": "error",
		"no-confusing-arrow": ["error", {"allowParens": false}],
		"dot-location": ["error", "property"],
		"no-else-return": "error",
		"no-throw-literal": "error",
		"require-await": "error",
		"eol-last": ["error", "always"],
		"newline-per-chained-call": ["error", { "ignoreChainWithDepth": 3 }],

		"nonblock-statement-body-position": ["warn", "beside"],
		"space-infix-ops": "warn",
		"semi-spacing": "error",
		"global-require": "error",
		"operator-assignment": ["error", "always"],
		"object-shorthand": ["error", "properties", { "avoidQuotes": true }],
		"no-process-exit": "error",
		"no-negated-condition": "warn",
		"prefer-destructuring": ["error", {
			"VariableDeclarator": {
				"array": false,
				"object": true
			},
			"AssignmentExpression": {
				"array": false,
				"object": false
			}
		}, {
			"enforceForRenamedProperties": false
		}],

		"linebreak-style": [ "off", "windows" ],
        "no-extra-parens": [ "off", "all" ],
        "indent": [ "off", "tab" ],
        "no-tabs": "off",
		"no-use-before-define": "off",
		"prefer-template": "off",
		"one-var": ["off", "always"],
        "no-mixed-spaces-and-tabs": "off",
		"no-multi-spaces": "off",
        "prefer-arrow-callback": "off",
        "no-plusplus": ["off", { "allowForLoopAfterthoughts": true }],
        "no-console": "off",

		"dollar-sign/dollar-sign": ["warn", "ignoreProperties"],
		"no-useless-assign/no-useless-assign": "warn",

		"@typescript-eslint/indent": ["off", "tab"],
		"@typescript-eslint/no-use-before-define": "off",
		"@typescript-eslint/no-non-null-assertion": "off",

		"optimize-regex/optimize-regex": "warn",

		"const-case/uppercase": "error",

		"eslint-comments/no-unused-disable": "error",
		"import/no-unresolved": "error"
	},
	"settings": {
		"import/parsers": {
			"@typescript-eslint/parser": [".ts", ".tsx"]
		},
		"import/resolver": {
		  "typescript": {}
		},
		"import/extensions": [
			".js",
			".jsx",
			".ts"
		]
	},
    "globals": {
        "requirejs": false,
		"__dirname": false,
		"document": false,
		"fetch": false,
		"window": false
    }
}

```
</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

eslint cannot run from bash shell on Windows because cygpath is not found.
Anyway, commenting the following lines in  ./node_modules/.bin/eslint makes eslint works without problems:
```bash
case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

```

```bash
sh.exe"-3.1$ ./node_modules/.bin/eslint --version
./node_modules/.bin/eslint: line 5: cygpath: command not found
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'd:\eslint\bin\eslint.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
sh.exe"-3.1$

```

**What did you expect to happen?**
eslint works

**What actually happened? Please include the actual, raw output from ESLint.**
See above

**Comment by crystalfp** [comment]
I reinstalled MINGW and MSYS just to see if cygpath is installed with some package, but was unable to find it (also the package cygutil does not provide cygpath). I suggest to change the case to detect only `*CYGWIN*` or remove it altogether.

The workaround is to change in the scripts `./node_modules/.bin/eslint` to `node ./node_modules/eslint/bin/eslint.js`

Thanks for considering!
mario

**Comment by mysticatea** [comment]
Thank you for your report.

However, `./node_modules/.bin/eslint` is not a part of ESLint. It's a part of `npm`. Therefore, we cannot control that file.

If you have problems in `./node_modules/.bin/eslint`, it's npm's problem. I'd like to recommend to open an issue on npm's repository.

Thank you.
