### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by ericsoco** [eslint/eslint#12227]
**Tell us about your environment**

* **ESLint Version:**
5.16.0
* **Node Version:**
10.16.0
* **npm Version:**
6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**
`babel-eslint@10.0.1`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

https://gist.github.com/ericsoco/4fcaacaed0bb083fd72688fee5ee381f
```js
{
  "globals": {
    "afterAll": false,
    "afterEach": false,
    "beforeAll": false,
    "beforeEach": false,
    "describe": false,
    "expect": false,
    "fit": false,
    "it": false,
    "jasmine": false,
    "jest": false,
    "pending": false,
    "pit": false,
    "require": false,
    "test": false,
    "xdescribe": false,
    "xit": false,
    "xtest": false,
    "clearInterval": false,
    "clearTimeout": false,
    "console": false,
    "setInterval": false,
    "setTimeout": false,
    "URL": false,
    "URLSearchParams": false,
    "Array": false,
    "ArrayBuffer": false,
    "Boolean": false,
    "constructor": false,
    "DataView": false,
    "Date": false,
    "decodeURI": false,
    "decodeURIComponent": false,
    "encodeURI": false,
    "encodeURIComponent": false,
    "Error": false,
    "escape": false,
    "eval": false,
    "EvalError": false,
    "Float32Array": false,
    "Float64Array": false,
    "Function": false,
    "hasOwnProperty": false,
    "Infinity": false,
    "Int16Array": false,
    "Int32Array": false,
    "Int8Array": false,
    "isFinite": false,
    "isNaN": false,
    "isPrototypeOf": false,
    "JSON": false,
    "Map": false,
    "Math": false,
    "NaN": false,
    "Number": false,
    "Object": false,
    "parseFloat": false,
    "parseInt": false,
    "Promise": false,
    "propertyIsEnumerable": false,
    "Proxy": false,
    "RangeError": false,
    "ReferenceError": false,
    "Reflect": false,
    "RegExp": false,
    "Set": false,
    "String": false,
    "Symbol": false,
    "SyntaxError": false,
    "toLocaleString": false,
    "toString": false,
    "TypeError": false,
    "Uint16Array": false,
    "Uint32Array": false,
    "Uint8Array": false,
    "Uint8ClampedArray": false,
    "undefined": false,
    "unescape": false,
    "URIError": false,
    "valueOf": false,
    "WeakMap": false,
    "WeakSet": false,
    "__NODE__": false,
    "__BROWSER__": false,
    "__DEV__": false
  },
  "env": {
    "jest/globals": true,
    "shared-node-browser": true,
    "es6": true
  },
  "rules": {
    "flowtype/boolean-style": [
      2,
      "boolean"
    ],
    "flowtype/define-flow-type": 1,
    "flowtype/delimiter-dangle": 0,
    "flowtype/generic-spacing": [
      "off",
      "never"
    ],
    "flowtype/no-mixed": 0,
    "flowtype/no-types-missing-file-annotation": 2,
    "flowtype/no-weak-types": 0,
    "flowtype/require-parameter-type": 0,
    "flowtype/require-readonly-react-props": 0,
    "flowtype/require-return-type": 0,
    "flowtype/require-valid-file-annotation": [
      "error",
      "always"
    ],
    "flowtype/semi": 0,
    "flowtype/space-after-type-colon": [
      "off",
      "always"
    ],
    "flowtype/space-before-generic-bracket": [
      2,
      "never"
    ],
    "flowtype/space-before-type-colon": [
      2,
      "never"
    ],
    "flowtype/type-id-match": 0,
    "flowtype/union-intersection-spacing": [
      2,
      "always"
    ],
    "flowtype/use-flow-type": 1,
    "react/display-name": 2,
    "react/jsx-key": 2,
    "react/jsx-no-comment-textnodes": 2,
    "react/jsx-no-duplicate-props": 2,
    "react/jsx-no-target-blank": 2,
    "react/jsx-no-undef": 2,
    "react/jsx-uses-react": 2,
    "react/jsx-uses-vars": 2,
    "react/no-children-prop": 2,
    "react/no-danger-with-children": 2,
    "react/no-deprecated": 2,
    "react/no-direct-mutation-state": 2,
    "react/no-find-dom-node": 2,
    "react/no-is-mounted": 2,
    "react/no-render-return-value": 2,
    "react/no-string-refs": 2,
    "react/no-unescaped-entities": 2,
    "react/no-unknown-property": 2,
    "react/no-unsafe": 0,
    "react/prop-types": "off",
    "react/react-in-jsx-scope": 2,
    "react/require-render-return": 2,
    "jest/no-alias-methods": "warn",
    "jest/no-disabled-tests": "warn",
    "jest/no-focused-tests": "error",
    "jest/no-identical-title": "error",
    "jest/no-jest-import": "error",
    "jest/no-jasmine-globals": "warn",
    "jest/no-test-prefixes": "error",
    "jest/valid-describe": "error",
    "jest/valid-expect": "error",
    "jest/valid-expect-in-promise": "error",
    "import/no-unresolved": [
      "error",
      {
        "commonjs": true,
        "caseSensitive": true
      }
    ],
    "import/named": "error",
    "import/default": "error",
    "import/namespace": "off",
    "import/export": "error",
    "import/no-named-as-default": "error",
    "import/no-named-as-default-member": "error",
    "import/no-deprecated": "off",
    "import/no-extraneous-dependencies": [
      "error",
      {
        "optionalDependencies": false
      }
    ],
    "import/no-mutable-exports": "error",
    "import/no-commonjs": "off",
    "import/no-amd": "error",
    "import/no-nodejs-modules": "off",
    "import/first": [
      "error"
    ],
    "import/no-duplicates": "error",
    "import/no-namespace": "off",
    "import/extensions": [
      "error",
      "never"
    ],
    "import/order": "error",
    "import/newline-after-import": "error",
    "import/prefer-default-export": "off",
    "import/no-restricted-paths": "off",
    "import/max-dependencies": "off",
    "import/no-absolute-path": "error",
    "import/no-dynamic-require": "error",
    "import/no-internal-modules": "off",
    "import/unambiguous": "off",
    "import/no-webpack-loader-syntax": "error",
    "import/no-unassigned-import": "off",
    "import/no-named-default": "error",
    "import/no-anonymous-default-export": "off",
    "import/exports-last": "off",
    "accessor-pairs": "off",
    "array-bracket-newline": "off",
    "array-bracket-spacing": "off",
    "array-callback-return": "off",
    "array-element-newline": "off",
    "arrow-body-style": "off",
    "arrow-parens": "off",
    "arrow-spacing": "off",
    "block-scoped-var": "off",
    "block-spacing": "off",
    "brace-style": "off",
    "callback-return": "off",
    "camelcase": "off",
    "capitalized-comments": "off",
    "class-methods-use-this": "off",
    "comma-dangle": "off",
    "comma-spacing": "off",
    "comma-style": "off",
    "complexity": "off",
    "computed-property-spacing": "off",
    "consistent-return": "off",
    "consistent-this": "off",
    "constructor-super": "error",
    "curly": 0,
    "default-case": "off",
    "dot-location": "off",
    "dot-notation": "off",
    "eol-last": "off",
    "eqeqeq": "off",
    "for-direction": "error",
    "func-call-spacing": "off",
    "func-name-matching": "off",
    "func-names": "off",
    "func-style": "off",
    "function-paren-newline": "off",
    "generator-star-spacing": "off",
    "getter-return": "error",
    "global-require": "off",
    "guard-for-in": "off",
    "handle-callback-err": "off",
    "id-blacklist": "off",
    "id-length": "off",
    "id-match": "off",
    "implicit-arrow-linebreak": "off",
    "indent": "off",
    "indent-legacy": "off",
    "init-declarations": "off",
    "jsx-quotes": "off",
    "key-spacing": "off",
    "keyword-spacing": "off",
    "line-comment-position": "off",
    "linebreak-style": "off",
    "lines-around-comment": 0,
    "lines-around-directive": "off",
    "lines-between-class-members": "off",
    "max-classes-per-file": "off",
    "max-depth": "off",
    "max-len": 0,
    "max-lines": "off",
    "max-lines-per-function": "off",
    "max-nested-callbacks": "off",
    "max-params": "off",
    "max-statements": "off",
    "max-statements-per-line": "off",
    "multiline-comment-style": "off",
    "multiline-ternary": "off",
    "new-cap": "off",
    "new-parens": "off",
    "newline-after-var": "off",
    "newline-before-return": "off",
    "newline-per-chained-call": "off",
    "no-alert": "off",
    "no-array-constructor": "off",
    "no-async-promise-executor": "off",
    "no-await-in-loop": "off",
    "no-bitwise": "off",
    "no-buffer-constructor": "off",
    "no-caller": "off",
    "no-case-declarations": "error",
    "no-catch-shadow": "off",
    "no-class-assign": "error",
    "no-compare-neg-zero": "error",
    "no-cond-assign": "error",
    "no-confusing-arrow": 0,
    "no-console": "error",
    "no-const-assign": "error",
    "no-constant-condition": "error",
    "no-continue": "off",
    "no-control-regex": "error",
    "no-debugger": "error",
    "no-delete-var": "error",
    "no-div-regex": "off",
    "no-dupe-args": "error",
    "no-dupe-class-members": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-duplicate-imports": "off",
    "no-else-return": "off",
    "no-empty": "error",
    "no-empty-character-class": "error",
    "no-empty-function": "off",
    "no-empty-pattern": "error",
    "no-eq-null": "off",
    "no-eval": "off",
    "no-ex-assign": "error",
    "no-extend-native": "off",
    "no-extra-bind": "off",
    "no-extra-boolean-cast": "error",
    "no-extra-label": "off",
    "no-extra-parens": "off",
    "no-extra-semi": "off",
    "no-fallthrough": "error",
    "no-floating-decimal": "off",
    "no-func-assign": "error",
    "no-global-assign": "error",
    "no-implicit-coercion": "off",
    "no-implicit-globals": "off",
    "no-implied-eval": "off",
    "no-inline-comments": "off",
    "no-inner-declarations": "error",
    "no-invalid-regexp": "error",
    "no-invalid-this": "off",
    "no-irregular-whitespace": "error",
    "no-iterator": "off",
    "no-label-var": "off",
    "no-labels": "off",
    "no-lone-blocks": "off",
    "no-lonely-if": "off",
    "no-loop-func": "off",
    "no-magic-numbers": "off",
    "no-misleading-character-class": "off",
    "no-mixed-operators": 0,
    "no-mixed-requires": "off",
    "no-mixed-spaces-and-tabs": "off",
    "no-multi-assign": "off",
    "no-multi-spaces": "off",
    "no-multi-str": "off",
    "no-multiple-empty-lines": "off",
    "no-native-reassign": "off",
    "no-negated-condition": "off",
    "no-negated-in-lhs": "off",
    "no-nested-ternary": "off",
    "no-new": "off",
    "no-new-func": "off",
    "no-new-object": "off",
    "no-new-require": "off",
    "no-new-symbol": "error",
    "no-new-wrappers": "off",
    "no-obj-calls": "error",
    "no-octal": "error",
    "no-octal-escape": "off",
    "no-param-reassign": "off",
    "no-path-concat": "off",
    "no-plusplus": "off",
    "no-process-env": "off",
    "no-process-exit": "off",
    "no-proto": "off",
    "no-prototype-builtins": "off",
    "no-redeclare": "error",
    "no-regex-spaces": "error",
    "no-restricted-globals": "off",
    "no-restricted-imports": "off",
    "no-restricted-modules": "off",
    "no-restricted-properties": "off",
    "no-restricted-syntax": "off",
    "no-return-assign": "off",
    "no-return-await": "off",
    "no-script-url": "off",
    "no-self-assign": "error",
    "no-self-compare": "off",
    "no-sequences": "off",
    "no-shadow": "off",
    "no-shadow-restricted-names": "off",
    "no-spaced-func": "off",
    "no-sparse-arrays": "error",
    "no-sync": "off",
    "no-tabs": 0,
    "no-template-curly-in-string": "off",
    "no-ternary": "off",
    "no-this-before-super": "error",
    "no-throw-literal": "off",
    "no-trailing-spaces": "off",
    "no-undef": "off",
    "no-undef-init": "off",
    "no-undefined": "off",
    "no-underscore-dangle": "off",
    "no-unexpected-multiline": 0,
    "no-unmodified-loop-condition": "off",
    "no-unneeded-ternary": "off",
    "no-unreachable": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unused-expressions": "off",
    "no-unused-labels": "error",
    "no-unused-vars": [
      "error",
      {
        "vars": "all",
        "args": "none",
        "ignoreRestSiblings": true
      }
    ],
    "no-use-before-define": "off",
    "no-useless-call": "off",
    "no-useless-catch": "off",
    "no-useless-computed-key": "off",
    "no-useless-concat": "off",
    "no-useless-constructor": "off",
    "no-useless-escape": "error",
    "no-useless-rename": "off",
    "no-useless-return": "off",
    "no-var": "off",
    "no-void": "off",
    "no-warning-comments": "off",
    "no-whitespace-before-property": "off",
    "no-with": "off",
    "nonblock-statement-body-position": "off",
    "object-curly-newline": "off",
    "object-curly-spacing": "off",
    "object-property-newline": "off",
    "object-shorthand": "off",
    "one-var": "off",
    "one-var-declaration-per-line": "off",
    "operator-assignment": "off",
    "operator-linebreak": "off",
    "padded-blocks": "off",
    "padding-line-between-statements": "off",
    "prefer-arrow-callback": "off",
    "prefer-const": "off",
    "prefer-destructuring": "off",
    "prefer-named-capture-group": "off",
    "prefer-numeric-literals": "off",
    "prefer-object-spread": "off",
    "prefer-promise-reject-errors": "off",
    "prefer-reflect": "off",
    "prefer-rest-params": "off",
    "prefer-spread": "off",
    "prefer-template": "off",
    "quote-props": "off",
    "quotes": 0,
    "radix": "off",
    "require-atomic-updates": 0,
    "require-await": "off",
    "require-jsdoc": "off",
    "require-unicode-regexp": "off",
    "require-yield": "error",
    "rest-spread-spacing": "off",
    "semi": "off",
    "semi-spacing": "off",
    "semi-style": "off",
    "sort-imports": "off",
    "sort-keys": "off",
    "sort-vars": "off",
    "space-before-blocks": "off",
    "space-before-function-paren": "off",
    "space-in-parens": "off",
    "space-infix-ops": "off",
    "space-unary-ops": "off",
    "spaced-comment": "off",
    "strict": "off",
    "switch-colon-spacing": "off",
    "symbol-description": "off",
    "template-curly-spacing": "off",
    "template-tag-spacing": "off",
    "unicode-bom": "off",
    "use-isnan": "error",
    "valid-jsdoc": "off",
    "valid-typeof": "error",
    "vars-on-top": "off",
    "wrap-iife": "off",
    "wrap-regex": "off",
    "yield-star-spacing": "off",
    "yoda": "off",
    "generator-star": "off",
    "no-arrow-condition": "off",
    "no-comma-dangle": "off",
    "no-reserved-keys": "off",
    "no-space-before-semi": "off",
    "no-wrap-func": "off",
    "space-after-function-name": "off",
    "space-after-keywords": "off",
    "space-before-function-parentheses": "off",
    "space-before-keywords": "off",
    "space-in-brackets": "off",
    "space-return-throw-case": "off",
    "space-unary-word-ops": "off",
    "prettier/prettier": [
      "none",
      {
        "printWidth": 80,
        "tabWidth": 2,
        "useTabs": false,
        "semi": true,
        "singleQuote": true,
        "trailingComma": "es5",
        "bracketSpacing": false,
        "jsxBracketSameLine": false,
        "rangeStart": 0,
        "rangeEnd": null
      }
    ],
    "cup/no-undef": [
      "error"
    ],
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn",
    "flowtype/type-import-style": [
      "error",
      "identifier",
      {
        "ignoreTypeDefault": true
      }
    ],
    "import/no-useless-path-segments": "error",
    "import/no-cycle": "error",
    "import/no-self-import": "error",
    "jsdoc/require-jsdoc": [
      "error",
      {
        "publicOnly": true,
        "require": {
          "ArrowFunctionExpression": true,
          "ClassDeclaration": true,
          "ClassExpression": true,
          "FunctionDeclaration": true,
          "MethodDefinition": true,
          "FunctionExpression": false
        },
        "exemptEmptyFunctions": false
      }
    ],
    "jsdoc/require-description": "error"
  },
  "parserOptions": {
    "ecmaVersion": 2017,
    "ecmaFeatures": {
      "jsx": true
    },
    "sourceType": "module"
  },
  "parser": "..../node_modules/babel-eslint/lib/index.js",
  "plugins": [
    "flowtype",
    "react",
    "jest",
    "eslint-plugin-import",
    "eslint-plugin-prettier",
    "eslint-plugin-cup",
    "eslint-plugin-flowtype",
    "eslint-plugin-react",
    "eslint-plugin-react-hooks",
    "jsdoc"
  ],
  "settings": {
    "flowtype": {
      "onlyFilesWithFlowAnnotation": false
    },
    "import/resolver": {
      "node": {
        "extensions": [
          ".js",
          ".json"
        ]
      }
    },
    "import/extensions": [
      ".js"
    ],
    "import/core-modules": [],
    "import/ignore": [],
    "react": {
      "version": "latest"
    }
  },
  "extends": [
    "eslint:recommended",
    "..../node_modules/eslint-config-prettier/index.js",
    "..../node_modules/eslint-config-uber-base/index.js",
    "..../node_modules/eslint-config-uber-base-stage-3/index.js",
    "..../node_modules/eslint-config-cup/eslintrc.js",
    "plugin:flowtype/recommended",
    "plugin:react/recommended",
    "plugin:jest/recommended",
    "./rules/imports.js",
    "..../node_modules/eslint-config-uber-universal-stage-3/index.js",
    "..../node_modules/eslint-config-fusion/index.js"
  ]
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

Minimal repro seems to include spreading an object in a const definition, followed by a function declaration or expression.

```js
const foo = {...{}};
function bar() {}
```

```bash
./node_modules/.bin/eslint src
```

**What did you expect to happen?**
Lints as usual

**What actually happened? Please include the actual, raw output from ESLint.**
```
TypeError: Cannot read property 'type' of undefined
Occurred while linting ..../src/temp-lint-test.test.js:2
    at getSymbol (..../node_modules/eslint-plugin-jsdoc/dist/exportParser.js:73:16)
    at node.properties.forEach.prop (..../node_modules/eslint-plugin-jsdoc/dist/exportParser.js:145:27)
    at Array.forEach (<anonymous>)
    at getSymbol (..../node_modules/eslint-plugin-jsdoc/dist/exportParser.js:144:25)
    at createSymbol (..../node_modules/eslint-plugin-jsdoc/dist/exportParser.js:194:31)
    at node.declarations.forEach.declaration (..../node_modules/eslint-plugin-jsdoc/dist/exportParser.js:327:26)
    at Array.forEach (<anonymous>)
    at mapVariables (..../node_modules/eslint-plugin-jsdoc/dist/exportParser.js:324:27)
    at node.body.forEach.childNode (..../node_modules/eslint-plugin-jsdoc/dist/exportParser.js:302:13)
    at Array.forEach (<anonymous>)
```

**Are you willing to submit a pull request to fix this bug?**
Probably not, not much knowledge of eslint internals / AST structure

**Comment by platinumazure** [comment]
Hi @ericsoco, thanks for the issue.

Just out of curiosity, is this issue reproducible with the default parser?

**Comment by ericsoco** [comment]
@platinumazure is there a sandbox env somewhere where I can easily swap out parsers? Swapping in my project unsurprisingly generates a ton of parser errors (but does complete linting without crashing, which is maybe all the answer you need).

Also of note, my colleague found the workaround to be:
```
const foo = {...{}};
/**
 * JSDoc header
 */
function bar() {}
```

So the issue appears to be related to `eslint-plugin-jsdoc`. Let me know if I should move this issue over to there. Thanks!

**Comment by mysticatea** [comment]
Yes, this looks like a bug in `eslint-plugin-jsdoc`. Please open an issue on their repo.

**Comment by ericsoco** [comment]
Moved to `eslint-plugin-jsdoc`: https://github.com/gajus/eslint-plugin-jsdoc/issues/378
