### ISSUE TITLE
Object-Curly-Spacing has a NullReferenceError potential

### ISSUE THREAD

**Issue by nchutchind** [eslint/eslint#12430]
* ESLint 6.5.1
* Node 11.14.0
* npm 6.11.3

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint, @typescript-eslint/parser, vue-eslint-parser

**What did you expect to happen?**
I expected my file to get linted.

**What actually happened? Please include the actual, raw output from ESLint.**
I get a null reference error in the ESLint output.

```
[Error - 12:34:29 PM] ESLint stack trace:
[Error - 12:34:29 PM] TypeError: Cannot read property 'type' of null
Occurred while linting C:\dev\redacted.project.name\src\modules\general\dashboards\views\layout.vue:86
    at validateBraceSpacing (C:\dev\redacted.project.name\node_modules\eslint\lib\rules\object-curly-spacing.js:180:119)
    at EventEmitter.checkForObject (C:\dev\redacted.project.name\node_modules\eslint\lib\rules\object-curly-spacing.js:231:13)
    at EventEmitter.emit (events.js:187:15)
    at NodeEventGenerator.applySelector (C:\dev\redacted.project.name\node_modules\vue-eslint-parser\index.js:3273:26)
    at NodeEventGenerator.applySelectors (C:\dev\redacted.project.name\node_modules\vue-eslint-parser\index.js:3287:22)
    at NodeEventGenerator.enterNode (C:\dev\redacted.project.name\node_modules\vue-eslint-parser\index.js:3295:14)
    at traverse (C:\dev\redacted.project.name\node_modules\vue-eslint-parser\index.js:113:13)
    at traverse (C:\dev\redacted.project.name\node_modules\vue-eslint-parser\index.js:125:13)
    at traverse (C:\dev\redacted.project.name\node_modules\vue-eslint-parser\index.js:125:13)
    at traverse (C:\dev\redacted.project.name\node_modules\vue-eslint-parser\index.js:120:21)
```

**Are you willing to submit a pull request to fix this bug?**
Yes. I have prepared one and will reference this issue in it.

**Comment by kaicataldo** [comment]
As commented [here](https://github.com/eslint/eslint/pull/12431#issuecomment-542042893), this is caused by a bug in 3rd party parsers.
