### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by suchverynice** [eslint/eslint#12595]
**Tell us about your environment**
Node version: v10.13.0
npm version: v6.4.1
Local ESLint version: v6.6.0
Global ESLint version: v6.6.0 (Currently used)

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

Given this to lint:
```js
function printPathNoParens(path, options, print, args) {
  // ...
  switch (n.type) {
    case 'DoWhileStatement': {
      var clause = adjustClause(n.body, path.call(print, 'body'));
      var doBody = group$10(concat$11(['do', clause]));
      parts = [doBody];

      if (n.body.type === 'BlockStatement') {
        parts.push(' ');
      } else {
        parts.push(hardline$8);
      }

      // ...
    }
    // more cases
  }
}
```
With my custom rule:
```js
const {traverse} = require('eslint/lib/shared/traverser');

module.exports = {
  // ...
  rules: {
    create(context) {
      return {
        FunctionDeclaration(node) {
          if (node.id.name === 'printPathNoParens') {
            traverse(node, {
              enter(nodes) {
                if (nodes.type === 'IfStatement' && nodes.parent.parent.test.value === 'DoWhileStatement') {
                  // modify code
                }
              }
            });
          }
        }
      };
    }
  }
};
```
Expected condition to return `true` per `console.log()`:
```js
if (nodes.type === 'IfStatement' && nodes.parent.parent.type === 'SwitchCase') {
  console.log(nodes.parent.parent.test.value); // => DoWhileStatement
}
```
Actual result:
```shell
TypeError: Cannot read property 'value' of undefined
Occurred while linting C:\www\master\test\raw.js:43
    at Traverser.enter [as _enter] (C:\www\master\test\node_modules\eslint-plugin-prettiest.js:95:71)
    at Traverser._traverse (C:\www\node\node_modules\eslint\lib\shared\traverser.js:134:14)
    at Traverser._traverse (C:\www\node\node_modules\eslint\lib\shared\traverser.js:146:34)
    at Traverser._traverse (C:\www\node\node_modules\eslint\lib\shared\traverser.js:149:30)
    at Traverser.traverse (C:\www\node\node_modules\eslint\lib\shared\traverser.js:117:14)
    at traverse (C:\www\node\node_modules\eslint\lib\shared\traverser.js:183:25)
    at FunctionDeclaration (C:\www\master\test\node_modules\eslint-plugin-prettiest.js:78:8)
    at listeners.(anonymous function).forEach.listener (C:\www\node\node_modules\eslint\lib\linter\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (C:\www\node\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! test@0.0.1 run: `eslint raw.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the test@0.0.1 run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Please advise what am I missing?

**Comment by kaicataldo** [comment]
Just to clarify, is the code you’re writing here a snippet of a custom rule you’re writing? And if so, does the error occur when running it? Or are you running into this issue when linting the code snippets above?

**Comment by suchverynice** [comment]
> 
> 
> Just to clarify, is the code you’re writing here a snippet of a custom rule you’re writing? And if so, does the error occur when running it? Or are you running into this issue when linting the code snippets above?

The first snippet is what I wanted to lint... or codemod rather

**Comment by kaicataldo** [comment]
So it sounds like this is occurring while linting and ESLint is crashing. In that case, can you share the stack trace you’re seeing in the output? Seeing the full error would be very helpful.

**Comment by suchverynice** [comment]
Here you go:
```shell
TypeError: Cannot read property 'value' of undefined
Occurred while linting C:\www\master\test\raw.js:43
    at Traverser.enter [as _enter] (C:\www\master\test\node_modules\eslint-plugin-prettiest.js:95:71)
    at Traverser._traverse (C:\www\node\node_modules\eslint\lib\shared\traverser.js:134:14)
    at Traverser._traverse (C:\www\node\node_modules\eslint\lib\shared\traverser.js:146:34)
    at Traverser._traverse (C:\www\node\node_modules\eslint\lib\shared\traverser.js:149:30)
    at Traverser.traverse (C:\www\node\node_modules\eslint\lib\shared\traverser.js:117:14)
    at traverse (C:\www\node\node_modules\eslint\lib\shared\traverser.js:183:25)
    at FunctionDeclaration (C:\www\master\test\node_modules\eslint-plugin-prettiest.js:78:8)
    at listeners.(anonymous function).forEach.listener (C:\www\node\node_modules\eslint\lib\linter\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (C:\www\node\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! test@0.0.1 run: `eslint raw.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the test@0.0.1 run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by kaicataldo** [comment]
If this is a linting error can you please fill out the [bug report template](https://github.com/eslint/eslint/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md), as requested? We ask for this information so that we can better triage issues.

**Comment by suchverynice** [comment]
> 
> 
> If this is a linting error can you please fill out the [bug report template](https://github.com/eslint/eslint/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md), as requested? We ask for this information so that we can better triage issues.

??? What further info is needed?

Basically, the main issue appears that the `value` can't be read as an `if` condition. Expected to return `true` per `console.log()`.

**Comment by mdjermanovic** [comment]
@suchverynice I'm guessing that `nodes.parent.parent.test.value` crashes on some other `if` statement, not the one from the example.

If that isn't the case, could you please post the entire content of both files?

**Comment by suchverynice** [comment]
Yes, you are right! Silly me, why didn't I think of that?

Thanks for taking your time to help me!
