### ISSUE TITLE
config-array-factory swallows errors

### ISSUE THREAD

**Issue by NickHeiner** [eslint/eslint#12817]
* **ESLint Version:** v6.8.0
* **Node Version:** v12.14.1

I have a plugin that contains custom rules. If a rule throws an error, ESLint swallows it:

```js
// rule.js
throw new Error('total destruction');
module.exports = { meta, create };
```

When I run `eslint` on a file, this manifests as: 

```
Environment key "some-env/from-my-plugin" is unknown
```

That error occurs because, when my rule threw an error, it caused the entire plugin to fail to load. That makes sense, but it would have been nice if ESLint had shown me what that error was.

Adding this console log line made it immediately obvious what was going on:

```diff
        debug("Failed to load plugin '%s' declared in '%s'.", name, importerName);
        error.message = `Failed to load plugin '${name}' declared in '${importerName}': ${error.message}`;
+     console.log({
+           error,
+           id,
+           importerName,
+           importerPath
+        });
        return new ConfigDependency({
            error,
            id,
            importerName,
            importerPath
        });
```

**Comment by kaicataldo** [comment]
I'm unable to reproduce this. These are the steps I took:

1. Create a new repo
2. `npm install eslint eslint-plugin-react`
3. Create a `.eslintrc.json` file in the  root of the project with the following contents:
```json
{
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "plugins": [
    "react"
  ],
  "rules": {
    "react/jsx-uses-react": "error"
  }
}
```
4. Add `throw new Error('uh oh')` on line 110 in `node_modules/eslint-plugin-react/index.js`. (https://github.com/yannickcr/eslint-plugin-react/blob/master/index.js#L110)
5. Run `eslint .`
6. I get the following output:
```sh
 eslint .

Error: Failed to load plugin 'react' declared in '.eslintrc.json': uh oh
    at Object.<anonymous> (/Users/kai/Code/test/eslint-test/node_modules/eslint-plugin-react/index.js:111:7)
    at Module._compile (/Users/kai/Code/test/eslint-test/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (/Users/kai/Code/test/eslint-test/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at ConfigArrayFactory._loadPlugin (/Users/kai/Code/test/eslint-test/node_modules/eslint/lib/cli-engine/config-array-factory.js:978:42)
    at /Users/kai/Code/test/eslint-test/node_modules/eslint/lib/cli-engine/config-array-factory.js:848:33
    at Array.reduce (<anonymous>)
npm ERR! Test failed.  See above for more details.
```

When I instead put the error in a rule, like on line 27 in `node_modules/eslint-plugin-react/lib/rules/jsx-uses-react.js` (https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-uses-react.js#L27), I get the following error:

```sh
> eslint .

Error: Error while loading rule 'react/jsx-uses-react': oh no
Occurred while linting /Users/kai/Code/test/eslint-test/index.js
    at Object.create (/Users/kai/Code/test/eslint-test/node_modules/eslint-plugin-react/lib/rules/jsx-uses-react.js:27:11)
    at createRuleListeners (/Users/kai/Code/test/eslint-test/node_modules/eslint/lib/linter/linter.js:746:21)
    at /Users/kai/Code/test/eslint-test/node_modules/eslint/lib/linter/linter.js:916:31
    at Array.forEach (<anonymous>)
    at runRules (/Users/kai/Code/test/eslint-test/node_modules/eslint/lib/linter/linter.js:861:34)
    at Linter._verifyWithoutProcessors (/Users/kai/Code/test/eslint-test/node_modules/eslint/lib/linter/linter.js:1157:31)
    at Linter._verifyWithConfigArray (/Users/kai/Code/test/eslint-test/node_modules/eslint/lib/linter/linter.js:1255:21)
    at Linter.verify (/Users/kai/Code/test/eslint-test/node_modules/eslint/lib/linter/linter.js:1210:25)
    at Linter.verifyAndFix (/Users/kai/Code/test/eslint-test/node_modules/eslint/lib/linter/linter.js:1400:29)
    at verifyText (/Users/kai/Code/test/eslint-test/node_modules/eslint/lib/cli-engine/cli-engine.js:230:48)
npm ERR! Test failed.  See above for more details.
```

Any chance you can share more information or create a reproduction case repository so we can try to get to the bottom of this?
