### ISSUE TITLE
TypeError: Cannot read property 'range' of null with arrow-body-style

### ISSUE THREAD

**Issue by paulschreiber** [eslint/eslint#12884]
**Tell us about your environment**
* **ESLint Version:** 6.8.0
* **Node Version:** 10.16.3
* **npm Version:** 6.13.7

**Please show your full configuration:**
```js
{
    "parserOptions": {
        "ecmaVersion": 2015
    },
    "rules": {
        "arrow-body-style": ["error", "always"]
    }
}

```

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
87        parsedYears     = _map(years, (year) => (
88            {
89                index : year,
90                title : splitYear(year)
91            }
92        ));

```

```bash
./node_modules/.bin/eslint src --fix --ext=js --ext=jsx
```

**What did you expect to happen?**

The linter ran to completion

**What actually happened? Please include the actual, raw output from ESLint.**
```
TypeError: Cannot read property 'range' of null
Occurred while linting /home/paul/src/node_modules/my-parser/soccer.js:87
    at SourceCode.getTokenBefore (/home/paul/node_modules/eslint/lib/source-code/token-store/index.js:298:18)
    at Object.isParenthesised (/home/paul/node_modules/eslint/lib/rules/utils/ast-utils.js:257:38)
    at findClosingParen (/home/paul/node_modules/eslint/lib/rules/arrow-body-style.js:96:30)
    at Object.fix (/home/paul/node_modules/eslint/lib/rules/arrow-body-style.js:225:50)
    at normalizeFixes (/home/paul/node_modules/eslint/lib/linter/report-translator.js:178:28)
    at args (/home/paul/node_modules/eslint/lib/linter/report-translator.js:343:49)
    at Object.report (/home/paul/node_modules/eslint/lib/linter/linter.js:905:41)
    at validate (/home/paul/node_modules/eslint/lib/rules/arrow-body-style.js:202:29)
    at listeners.(anonymous function).forEach.listener (/home/paul/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
error Command failed with exit code 2.
```

Other rules work as expected (arrow-parens, keyword-spacing, indent, etc.)

**Comment by mdjermanovic** [comment]
Hi @paulschreiber, thanks for the bug report!

Confirmed in our [Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50ICBcImFycm93LWJvZHktc3R5bGVcIjogW1wiZXJyb3JcIiwgXCJhbHdheXNcIl0gKi9cblxucGFyc2VkWWVhcnMgPSBfbWFwKHllYXJzLCAoeWVhcikgPT4gKFxuICAgIHtcbiAgICAgICAgaW5kZXggOiB5ZWFyLFxuICAgICAgICB0aXRsZSA6IHNwbGl0WWVhcih5ZWFyKVxuICAgIH1cbikpOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6OCwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==), working on this.
