### ISSUE TITLE
Failed to load plugin 'react-hooks' declared in '.eslintrc » eslint-config-react-app': Cannot find module 'eslint-plugin-react-hooks'

### ISSUE THREAD

**Issue by wzup** [eslint/eslint#12946]
I'm getting this error message in PHPStorm. How to fix?

<img width="884" alt="Screen Shot 2020-02-21 at 16 19 01" src="https://user-images.githubusercontent.com/3880497/75028336-145b3180-54c6-11ea-8f27-0d3afb7426a5.png">

Full error message:
```
Error: Failed to load plugin 'react-hooks' declared in '.eslintrc » eslint-config-react-app': Cannot find module 'eslint-plugin-react-hooks'
Require stack:
  - /Users/admin/apps/cp-basic/__placeholder__.js

Error: Failed to load plugin 'react-hooks' declared in '.eslintrc » eslint-config-react-app': Cannot find module 'eslint-plugin-react-hooks'
Require stack:
  - /Users/admin/apps/cp-basic/__placeholder__.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
at Function.resolve (internal/modules/cjs/helpers.js:30:19)
at Object.resolve (/Users/admin/apps/cp-basic/node_modules/eslint/lib/shared/relative-module-resolver.js:44:50)
at ConfigArrayFactory._loadPlugin (/Users/admin/apps/cp-basic/node_modules/eslint/lib/cli-engine/config-array-factory.js:959:39)
at names.reduce (/Users/admin/apps/cp-basic/node_modules/eslint/lib/cli-engine/config-array-factory.js:848:33)
at Array.reduce (<anonymous>)
  at ConfigArrayFactory._loadPlugins (/Users/admin/apps/cp-basic/node_modules/eslint/lib/cli-engine/config-array-factory.js:844:22)
  at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/admin/apps/cp-basic/node_modules/eslint/lib/cli-engine/config-array-factory.js:667:32)
  at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/admin/apps/cp-basic/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20)
```

**Tell us about your environment**

**PLEASE, PROVIDE ONE CLI COMMAND FOR THIS!**

Mac
Phpstorm
```
  "devDependencies": {
    "babel-eslint": "^10.0.2",
    "eslint": "^6.1.0",
    "eslint-config-react-app": "^5.0.1",
    "eslint-config-react-tools": "^1.1.7",
    "eslint-plugin-flowtype": "^4.2.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.14.3",
    "serve": "^11.1.0"
  }
```

* **ESLint Version:**
```
  "devDependencies": {
    "babel-eslint": "^10.0.2",
    "eslint": "^6.1.0",
    "eslint-config-react-app": "^5.0.1",
    "eslint-config-react-tools": "^1.1.7",
    "eslint-plugin-flowtype": "^4.2.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.14.3",
    "serve": "^11.1.0"
  }
```
* **Node Version:**
v11.6.0
* **npm Version:**
6.11.3
**What parser (default, Babel-ESLint, etc.) are you using?**
My **.babelrc** file:
```
{
  "presets": ["react-static/babel-preset.js"]
}

```
**Please show your full configuration:**

**HOW? Please, provide one CLI command for that!**

<details>
<summary>Configuration</summary>

```js
{
  "name": "react-static-example-basic",
  "private": true,
  "scripts": {
    "start": "react-static start",
    "stage": "react-static build --staging",
    "build": "react-static build",
    "analyze": "react-static build --analyze",
    "serve": "serve dist -p 3000"
  },
  "dependencies": {
    "@reach/router": "^1.2.1",
    "axios": "^0.19.0",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-static": "^7.2.0",
    "react-static-plugin-reach-router": "^7.2.0",
    "react-static-plugin-sitemap": "^7.2.0",
    "react-static-plugin-source-filesystem": "^7.2.0"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.2",
    "eslint": "^6.1.0",
    "eslint-config-react-app": "^5.0.1",
    "eslint-config-react-tools": "^1.1.7",
    "eslint-plugin-flowtype": "^4.2.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.14.3",
    "serve": "^11.1.0"
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

I'm getting this error in my PHPStorm:

<img width="884" alt="Screen Shot 2020-02-21 at 16 19 01" src="https://user-images.githubusercontent.com/3880497/75028336-145b3180-54c6-11ea-8f27-0d3afb7426a5.png">

**What did you expect to happen?**

No error message

**What actually happened? Please include the actual, raw output from ESLint.**

```
Error: Failed to load plugin 'react-hooks' declared in '.eslintrc » eslint-config-react-app': Cannot find module 'eslint-plugin-react-hooks'
Require stack:
  - /Users/admin/apps/cp-basic/__placeholder__.js

Error: Failed to load plugin 'react-hooks' declared in '.eslintrc » eslint-config-react-app': Cannot find module 'eslint-plugin-react-hooks'
Require stack:
  - /Users/admin/apps/cp-basic/__placeholder__.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
at Function.resolve (internal/modules/cjs/helpers.js:30:19)
at Object.resolve (/Users/admin/apps/cp-basic/node_modules/eslint/lib/shared/relative-module-resolver.js:44:50)
at ConfigArrayFactory._loadPlugin (/Users/admin/apps/cp-basic/node_modules/eslint/lib/cli-engine/config-array-factory.js:959:39)
at names.reduce (/Users/admin/apps/cp-basic/node_modules/eslint/lib/cli-engine/config-array-factory.js:848:33)
at Array.reduce (<anonymous>)
  at ConfigArrayFactory._loadPlugins (/Users/admin/apps/cp-basic/node_modules/eslint/lib/cli-engine/config-array-factory.js:844:22)
  at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/admin/apps/cp-basic/node_modules/eslint/lib/cli-engine/config-array-factory.js:667:32)
  at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/admin/apps/cp-basic/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20)

```

**Comment by yeonjuan** [comment]
@wzup 
Hi :)
Have you ever tried to install `eslint-plugin-react-hooks`? 
It seems you should install it.

```bash
$ npm i eslint-plugin-react-hooks
```
