### ISSUE TITLE
Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.json': Cannot find module './_baseToString'

### ISSUE THREAD

**Issue by dumoko** [eslint/eslint#13169]
**Tell us about your environment**

* **ESLint Version:** 6.8.0
* **Node Version:** v10.19.0
* **npm Version:** 6.13.4
* **yarn Version:** 1.15.2

**What parser (default, Babel-ESLint, etc.) are you using?**
```bash
"@typescript-eslint/parser": "2.19.0",
```

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```
OS: Ubuntu
</details>

**What did you do?**

```bash
yarn lint
```
Which translates to:
`"lint": "eslint './src/**/*.{ts,tsx}'"`

**What did you expect to happen?**
```bash
+ yarn lint
yarn run v1.15.2
$ eslint './src/**/*.{ts,tsx}'
Done in 56.51s.
```

**What actually happened? Please include the actual, raw output from ESLint.**
```bash
+ yarn lint
yarn run v1.15.2
$ eslint './src/**/*.{ts,tsx}'
Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.json': Cannot find module './_baseToString'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/ubuntu/workspace/_NCK-10446-update-ci-jenkinsfile/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/ubuntu/workspace/_NCK-10446-update-ci-jenkinsfile/node_modules/lodash/toString.js:1:82)
    at Module._compile (/home/ubuntu/workspace/_NCK-10446-update-ci-jenkinsfile/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**What did I research before creating this bug?**
https://github.com/eslint/eslint/issues/11990
https://github.com/eslint/eslint/issues/11891
https://github.com/eslint/eslint/issues/12854
https://github.com/eslint/eslint/issues/12376

Please let me know what else I can share with you to help narrowing down the problem...
Thanks a lot for your work!

**Comment by aladdin-add** [comment]
have you tried eslint v7 (it's still in alpha)?

**Comment by dumoko** [comment]
I will try and come back with a result. 
Thanks for the suggestion!
