### ISSUE TITLE
SourceCode not optimize for RuleTester changes

### ISSUE THREAD

**Issue by SuperOleg39** [eslint/eslint#13293]
**Tell us about your environment**

* **ESLint Version: 7**

**What parser (default, Babel-ESLint, etc.) are you using?**

1. babel-eslint
2. @typescript-eslint/parser

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

We using RuleTester for custom rule, and have this code inside rule:

```js
// context: Rule.RuleContext
const sourceCode = context.getSourceCode();
const comments = sourceCode.getComments(nodeSource).leading;
```

After updating to Eslint 7, have a error, because `source-code.js` use deprecated by `rule-tester.js` node properties.

**What did you expect to happen?**

My tests passes succesfull

**What actually happened? Please include the actual, raw output from ESLint.**

```bash
Use token.range[0] instead of token.start
    Occurred while linting <input>:3

      68 |       const chunkName = last(propName.split('/'));
      69 |       const sourceCode = context.getSourceCode();
    > 70 |       const comments = sourceCode.getComments(nodeSource).leading;
         |                                   ^
      71 | 
      72 |       if (!comments || comments.length === 0) {
      73 |         return context.report({

      at Object.get (node_modules/eslint/lib/rule-tester/rule-tester.js:223:23)
      at SourceCode.getComments (node_modules/eslint/lib/source-code/source-code.js:352:50)
      at checkImport (packages/eslint/src/config/rules/bundle-chunk-name.ts:70:35)
      at ImportExpression (packages/eslint/src/config/rules/bundle-chunk-name.ts:134:16)
      at listeners.(anonymous function).forEach.listener (node_modules/eslint/lib/linter/safe-emitter.js:45:58)
          at Array.forEach (<anonymous>)
      at Object.emit (node_modules/eslint/lib/linter/safe-emitter.js:45:38)
      at NodeEventGenerator.applySelector (node_modules/eslint/lib/linter/node-event-generator.js:254:26)
      at NodeEventGenerator.applySelectors (node_modules/eslint/lib/linter/node-event-generator.js:283:22)
      at NodeEventGenerator.enterNode (node_modules/eslint/lib/linter/node-event-generator.js:297:14)
```

**Are you willing to submit a pull request to fix this bug?**

Yes

**Comment by SuperOleg39** [comment]
also, SourceCode unit tests failed in my branch with fix, and i see a difference between start, end and range

https://github.com/eslint/eslint/blob/master/lib/source-code/source-code.js#L352

```js
console.log(currentToken.start, currentToken.end, currentToken.range) // the same - 0, 42, [ 0, 42]
console.log(node.parent.start, node.parent.end, node.parent.range) // different - 0, 101, [ 43, 54 ]
```

**Comment by SuperOleg39** [comment]
Difference between range and start, end - it is adaptation to [Esprima behaviour](https://github.com/eslint/espree/blob/master/lib/espree.js#L156)

**Comment by kaicataldo** [comment]
As mentioned [here](https://github.com/eslint/eslint/pull/13296#pullrequestreview-411278341), `SourceCode#getComments()` is deprecated and we recommend using  `SourceCode#getCommentsBefore()`, `SourceCode#getCommentsAfter()`, and `SourceCode#getCommentsInside()` instead.

**Comment by SuperOleg39** [comment]
`SouceCode#getComments()` is [deprecated](https://eslint.org/docs/developer-guide/working-with-rules#deprecated), so i just add `@deprecated` comment and close this issue
