### ISSUE TITLE
Catch syntax is incorrect

### ISSUE THREAD

**Issue by michael-evenchick** [eslint/eslint#13419]
> eslint . --ext .json --ext .js
...../node_modules/eslint/bin/eslint.js:93
         } catch {
                 ^
 SyntaxError: Unexpected token {
     at createScript (vm.js:80:10)
     at Object.runInThisContext (vm.js:139:10)
     at Module._compile (module.js:617:28)
     at Object.Module._extensions..js (module.js:664:10)
     at Module.load (module.js:566:32)
     at tryModuleLoad (module.js:506:12)
     at Function.Module._load (module.js:498:3)
     at Function.Module.runMain (module.js:694:10)
     at startup (bootstrap_node.js:204:16)
     at bootstrap_node.js:625:3

eslint 7.2.0
node v11.12.0
npm 6.14.2

**Comment by ljharb** [comment]
That's valid syntax in node 11. Are you sure that's the node version eslint is using?

**Comment by anikethsaha** [comment]
I guess, `parserOption.ecmaVersion` should be `2019` in eslint config file

**Comment by yeonjuan** [comment]
@michael-evenchick 
I tested with node v11.12.0, but I can't reproduce it.
Can you check your node version?

**Comment by michael-evenchick** [comment]
You can close this -- it does work on node 11 - it failed in a pipeline that was running an earlier version of node - I upgraded the pipeline and it is working fine.

**Comment by daniloprates** [comment]
I'm having this issue on node 11 and 12. Any clues?
