### ISSUE TITLE
no-useless-constructor: "Cannot read property 'body' of null from" *.d.ts declaration

### ISSUE THREAD

**Issue by Tragetaschen** [eslint/eslint#13509]
**Tell us about your environment**

```
Environment Info:

Node version: v12.17.0
npm version: v6.14.4
Local ESLint version: v7.5.0 (Currently used)
Global ESLint version: Not found
```

**What parser (default, Babel-ESLint, etc.) are you using?**
`@typescript-eslint/parser` 3.6.1

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    root: true,
    ignorePatterns: ["node_modules", "wwwroot", "yocto"],
    parser: '@typescript-eslint/parser',
    plugins: [
        '@typescript-eslint',
    ],
    extends: [
        'eslint:recommended',
        'plugin:@typescript-eslint/recommended',
    ],
    rules: {
        "no-var": 2,
        "@typescript-eslint/ban-ts-comment": 2,
        "@typescript-eslint/explicit-function-return-type": 2,
        "@typescript-eslint/no-explicit-any": 2,
        "@typescript-eslint/no-inferrable-types": 2,
        "@typescript-eslint/no-namespace": 2,
        "@typescript-eslint/no-non-null-assertion": 2,
        "@typescript-eslint/no-var-requires": 2,
        "@typescript-eslint/prefer-namespace-keyword": 2,
        "@typescript-eslint/triple-slash-reference": 2,
        "no-new-func": 2,
        "no-useless-constructor": 2,
    },
    overrides: [
        {
            files: ["webpack*.js", "postcss*", "build-manual.js", "*eslintrc.js"],
            env: { node: true },
            rules: {
                "@typescript-eslint/no-var-requires": 0,
                "@typescript-eslint/explicit-function-return-type": 0,
            }
        }
    ]
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

https://gist.github.com/strothj/708afcf4f01dd04de8f49c92e88093c3

```bash
eslint . --ext .js,.ts
```

**What did you expect to happen?**
No crash

**What actually happened? Please include the actual, raw output from ESLint.**
```
> eslint . --ext .js,.ts


Oops! Something went wrong! :(

ESLint: 7.5.0

TypeError: Cannot read property 'body' of null
Occurred while linting …\path\to\ResizeObserver.d.ts:73
    at checkForConstructor (…\node_modules\eslint\lib\rules\no-useless-constructor.js:165:42)
    at …\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (…\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (…\node_modules\eslint\lib\linter\node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (…\node_modules\eslint\lib\linter\node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (…\node_modules\eslint\lib\linter\node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (…\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:673:23)
    at …\node_modules\eslint\lib\linter\linter.js:949:32
    at Array.forEach (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! app@1.0.0 eslint: `eslint . --ext .js,.ts`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the app@1.0.0 eslint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by anikethsaha** [comment]
Thanks for the issue. 

eslint doesn't support `typescript`  from the core. You need to turn off the eslint's `no-useless-constructor` and turn on [`@typescript-eslint/no-useless-constructor`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-useless-constructor.md).

**Comment by Tragetaschen** [comment]
Yup, that does the trick.

How can I figure that out by myself?

**Comment by anikethsaha** [comment]
docs for [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) is pretty good. I guess that would help
