### ISSUE TITLE
TypeError: Failed to load plugin 'react' declared in '--config': createRequire is not a function

### ISSUE THREAD

**Issue by EnPython** [eslint/eslint#13539]
hi, i meet some trouble like the following, when i used the eslint to scan my local .jsx file 
for detail i used the command line as this :
`node /usr/share/node/bin/eslint -f json --output-file /home/admin/tesla-agent/.default/temp/tesla-agent/229431/.scannerwork/.sonartmp/16360860956120844706.tmp --config /home/admin/tesla-agent/.default/temp/tesla-agent/229431/.eslintrc /home/admin/tesla-agent/.default/temp/tesla-agent/229431/src/pages/IDQMaxDetailLayer.jsx`

i have been installed react plugin but did not work. is it the bug or something
please help me 
thank you so much 

```
Oops! Something went wrong! :(

ESLint: 7.5.0

TypeError: Failed to load plugin 'react' declared in '--config': createRequire is not a function
Referenced from: /home/admin/tesla-agent/.default/temp/tesla-agent/229431/.eslintrc
    at Object.resolve (/usr/share/node/lib/node_modules/eslint/lib/shared/relative-module-resolver.js:28:20)
    at ConfigArrayFactory._loadPlugin (/usr/share/node/lib/node_modules/eslint/lib/cli-engine/config-array-factory.js:992:39)
    at ConfigArrayFactory._loadExtendedPluginConfig (/usr/share/node/lib/node_modules/eslint/lib/cli-engine/config-array-factory.js:812:29)
    at ConfigArrayFactory._loadExtends (/usr/share/node/lib/node_modules/eslint/lib/cli-engine/config-array-factory.js:761:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/usr/share/node/lib/node_modules/eslint/lib/cli-engine/config-array-factory.js:702:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/usr/share/node/lib/node_modules/eslint/lib/cli-engine/config-array-factory.js:647:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadFile (/usr/share/node/lib/node_modules/eslint/lib/cli-engine/config-array-factory.js:459:16)
    at createCLIConfigArray (/usr/share/node/lib/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:160:35)
```

**Comment by EnPython** [comment]
for convenient i post the part of .eslintrc file 
```
 "plugins": [
    "react",
    "import"
  ],
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:import/errors",
    "plugin:import/warnings"
  ],
  "settings": {
    "react": {
      "pragma": "AJX"
    },
    "import/resolver": {
      "node": {
        "extensions": [
          ".js",
          "jsx",
          ".json"
        ]
      }
    },
    "import/extensions": [
      ".js",
      ".jsx"
    ],  
```

**Comment by anikethsaha** [comment]
Thanks for the report. 

Can you share your node version? 

also, output for `--debug`

**Comment by EnPython** [comment]
Sure, my server's node version is v10.9.0

**Comment by EnPython** [comment]
debug information as following
![image](https://user-images.githubusercontent.com/40432658/88992104-09c68300-d315-11ea-9c76-b3e3c7f29e26.png)

**Comment by EnPython** [comment]
i trid to use the eslint@6.8 to scan the .jsx file and succeeded.

**Comment by aladdin-add** [comment]
it's a breaking change in eslint v7.0.0. please consider upgrading node to required version:
https://github.com/eslint/eslint/blob/16b10fe8ba3c78939d5ada4a25caf2f0c9e6a058/package.json#L144

**Comment by EnPython** [comment]
it work after i upgraded my node version to 12.18.3
thanks for your attention and help
