### ISSUE TITLE
Use catch(e) format

### ISSUE THREAD

**Issue by jmakuc** [eslint/eslint#13624]
Hi there

OSX 10.13.6
node: 8.15.0
npm 6.8.0
gulp:
CLI version: 2.3.0
Local version: 4.0.2

I'm using a bootstrap template that contains eslint as one it's packages. 

Running the "getting started" commands involved a gulp script which failed because of a parsing problem on a eslint file:

```
Jonathans-MBP:Falcon-v2.7.2 jmakuc$ gulp
[11:59:23] Using gulpfile ~/Falcon-v2.7.2/gulpfile.js
[11:59:23] Starting 'default'...
[11:59:23] Starting 'copy:dependency'...
[11:59:24] Finished 'copy:dependency' after 343 ms
[11:59:24] Starting 'scss'...
[11:59:25] Finished 'scss' after 1.73 s
[11:59:25] Starting 'scss:dark'...
[11:59:27] Finished 'scss:dark' after 1.62 s
[11:59:27] Starting 'scss:rtl'...
[11:59:29] Finished 'scss:rtl' after 1.65 s
[11:59:29] Starting 'scss:dark:rtl'...
[11:59:30] Finished 'scss:dark:rtl' after 1.69 s
[11:59:30] Starting 'js'...
[11:59:30] Starting 'js:bootstrap'...
[11:59:30] Starting 'js:theme'...
[11:59:30] Starting 'js:config-vertical-navbar'...
[11:59:31] 'js:theme' errored after 464 ms
[11:59:31] Falcon-v2.7.2/node_modules/eslint/lib/cli-engine/cli-engine.js:994
                } catch {
                        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> ( Falcon-v2.7.2/node_modules/eslint/lib/cli-engine/index.js:3:23)
[11:59:31] 'js' errored after 465 ms
[11:59:31] 'default' errored after 7.49 s
```

The problem is the } catch { syntax. Even when modern JS accepts this, it is not very backward compatible. 

I fixed the problem by replacing all the ocurrences with sed:

`find *|grep "js"|xargs sed -i.bck  's/} catch {/} catch(e) {/g'`

I think that this should be applied to the codebase to allow a more broad compatibility. 

Best!

**Comment by anikethsaha** [comment]
Thanks for the issue.

You need to upgrade your node version as `8` is not supported by us.

Use `12.x.x` (recommended )

**Comment by jmakuc** [comment]
I know, but since it is such a small change to allow older versions to run,
I believe it's worth it.

Just my 2 cents :)


Jonathan Makuc

*Bit**haus Software Boutique*
# --------------------------------------------------------
0x77 bithaus.cl
0x74 +56994191736
0x3F Suecia 0142, Of 1204, Providencia, Santiago, Chile
Truth is out there

**Comment by kaicataldo** [comment]
We intentionally dropped support for Node 8 in the last major release. We recommend upgrading to Node 10, as Node 8 is no longer maintained by the Node core team and no longer receives any updates, bug fixes, or security patches.
