### ISSUE TITLE
TypeError: Cannot read property 'body' of null

### ISSUE THREAD

**Issue by gregveres** [eslint/eslint#13674]
**Tell us about your environment**

* **ESLint Version:** 7.8.1
* **Node Version:** 12.14.1
* **npm Version:** 6.14.5

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
@typescript-eslint/parser

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  root: true,

  env: {
    node: true,
    browser: true
  },

  extends: [
    'plugin:vue/strongly-recommended',
    '@vue/airbnb',
    '@vue/typescript',
    'plugin:prettier/recommended',
    'prettier',
    'prettier/@typescript-eslint',
    'prettier/vue'
  ],

  parserOptions: {
    ecmaVersion: 2020,
    parser: '@typescript-eslint/parser',
    sourceType: 'module'
  },

  rules: {
    'no-console': 'off',
    'no-debugger': 'off',
    '@typescript-eslint/no-empty-function': 'off',
    '@typescript-eslint/no-namespace': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/no-non-null-assertion': 'off',
    '@typescript-eslint/no-non-null-asserted-optional-chain': 'off',
    'class-methods-use-this': 'off',
    'vue/component-name-in-template-casing': ['error', 'PascalCase'],
    'vue/no-v-html': 'off',
    'no-shadow': 'off',
    'vue/max-attributes-per-line': [
      2,
      {
        singleline: 20,
        multiline: {
          max: 1,
          allowFirstLine: false
        }
      }
    ],
    'prettier/prettier': 'warn'
  },

  overrides: [
    {
      files: ['**/*.test.ts'],
      env: {
        jest: true
      }
    }
  ]
};

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

tiptap-extensions.d.ts
```js
declare module 'tiptap-extensions' {
  import { Extension, Node, Mark } from 'tiptap';
  import { Node as PromsemirrorNode } from 'prosemirror-model';

  export interface PlaceholderOptions {
    emptyNodeClass?: string;
    emptyNodeText?: ((node: PromsemirrorNode) => string | undefined) | string;
    showOnlyWhenEditable?: boolean;
    showOnlyCurrent?: boolean;
    emptyEditorClass: string;
  }
  export class Placeholder extends Extension {
    constructor(options?: PlaceholderOptions);
  }

  export interface TrailingNodeOptions {
    /**
     * Node to be at the end of the document
     *
     * defaults to 'paragraph'
     */
    node: string;
    /**
     * The trailing node will not be displayed after these specified nodes.
     */
    notAfter: string[];
  }
  export class TrailingNode extends Extension {
    constructor(options?: TrailingNodeOptions);
  }

  export interface HeadingOptions {
    levels?: number[];
  }

  export class History extends Extension {}

  export class Bold extends Mark {}
  export class Code extends Mark {}
  export class Italic extends Mark {}
  export class Link extends Mark {}
  export class Strike extends Mark {}
  export class Underline extends Mark {}

  export class Blockquote extends Node {}
  export class BulletList extends Node {}
  export class CodeBlock extends Node {}
  export class HardBreak extends Node {}
  export class Heading extends Node {
    constructor(options?: HeadingOptions);
  }
  export class HorizontalRule extends Node {}
  export class Image extends Node {}
  export class ListItem extends Node {}
  export class OrderedList extends Node {}
  export class Table extends Node {}
  export class TableCell extends Node {}
  export class TableRow extends Node {}
  export class TableHeader extends Node {}
  export class TodoItem extends Node {}
  export class TodoList extends Node {}
}
```

```bash
vue-cli-service lint
```

**What did you expect to happen?**
I expect eslint to tell me there is an error with the file or not without crashing

**What actually happened? Please include the actual, raw output from ESLint.**
 ERROR  TypeError: Cannot read property 'body' of null
Occurred while linting \SkyCourt.UI\ui\src\typings\tiptap-extensions.d.ts:13
TypeError: Cannot read property 'body' of null
Occurred while linting SkyCourt.UI\ui\src\typings\tiptap-extensions.d.ts:13
    at checkForConstructor (SkyCourt.UI\ui\node_modules\eslint\lib\rules\no-useless-constructor.js:165:42)
    at SkyCourt.UI\ui\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (SkyCourt.UI\ui\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (SkyCourt.UI\ui\node_modules\eslint\lib\linter\node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (SkyCourt.UI\ui\node_modules\eslint\lib\linter\node-event-generator.js:283:22)
    at CodePathAnalyzer.enterNode (SkyCourt.UI\ui\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:711:23)
    at SkyCourt.UI\ui\node_modules\eslint\lib\linter\linter.js:952:32
    at Array.forEach (<anonymous>)
    at runRules (SkyCourt.UI\ui\node_modules\eslint\lib\linter\linter.js:947:15)
    at Linter._verifyWithoutProcessors (SkyCourt.UI\ui\node_modules\eslint\lib\linter\linter.js:1173:31)
    at Linter._verifyWithConfigArray (SkyCourt.UI\ui\node_modules\eslint\lib\linter\linter.js:1271:21)
    at Linter.verify (SkyCourt.UI\ui\node_modules\eslint\lib\linter\linter.js:1226:25)
    at Linter.verifyAndFix (SkyCourt.UI\ui\node_modules\eslint\lib\linter\linter.js:1416:29)
    at verifyText (SkyCourt.UI\ui\node_modules\eslint\lib\cli-engine\cli-engine.js:224:48)
error Command failed with exit code 1.

**Are you willing to submit a pull request to fix this bug?**
I don't presume to understand the eslint code enough to be able to provide a fix.

**Comment by gregveres** [comment]
I get the same error when eslinting tiptap.d.ts:

```JS
declare module 'tiptap' {
  import {
    MarkSpec,
    MarkType,
    Node as ProsemirrorNode,
    NodeSpec,
    NodeType,
    ParseOptions,
    Schema
  } from 'prosemirror-model';
  import { EditorState, Plugin, Transaction } from 'prosemirror-state';
  import { Command, CommandFunction } from 'tiptap-commands';
  import { EditorProps, EditorView } from 'prosemirror-view';
  import { VueConstructor } from 'vue';

  export const EditorContent: VueConstructor;
  export const EditorMenuBubble: VueConstructor;
  export const EditorMenuBar: VueConstructor;
  export type ExtensionOption = Extension | Node | Mark;

  // there are some props available
  // `node` is a Prosemirror Node Object
  // `updateAttrs` is a function to update attributes defined in `schema`
  // `view` is the ProseMirror view instance
  // `options` is an array of your extension options
  // `selected`
  export interface NodeView {
    /** A Prosemirror Node Object */
    node?: ProsemirrorNode;
    /** A function to update attributes defined in `schema` */
    updateAttrs?: (attrs: { [key: string]: any }) => any;
    /** The ProseMirror view instance */
    view?: EditorView;
    /** An array of your extension options */
    options?: { [key: string]: any };
    /** Whether the node view is selected */
    selected?: boolean;
  }

  export type CommandGetter =
    | { [key: string]: (() => Command) | Command }
    | (() => Command)
    | Command
    | (() => Command)[];

  export interface EditorUpdateEvent {
    state: EditorState;
    getHTML: () => string;
    getJSON: () => any;
    transaction: Transaction;
  }

  export interface EditorOptions {
    editorProps?: EditorProps;
    /** defaults to true */
    editable?: boolean;
    /** defaults to false */
    autoFocus?: boolean;
    extensions?: ExtensionOption[];
    content?: Record<string, any> | string;
    emptyDocument?: {
      type: 'doc';
      content: [
        {
          type: 'paragraph';
        }
      ];
    };
    /** defaults to false */
    useBuiltInExtensions?: boolean;
    /** defaults to false */
    disableInputRules?: boolean;
    /** defaults to false */
    disablePasteRules?: boolean;
    dropCursor?: any;
    parseOptions?: ParseOptions;
    /** defaults to true */
    injectCSS?: boolean;
    onInit?: ({ view, state }: { view: EditorView; state: EditorState }) => void;
    onTransaction?: (event: EditorUpdateEvent) => void;
    onUpdate?: (event: EditorUpdateEvent) => void;
    onFocus?: ({
      event,
      state,
      view
    }: {
      event: FocusEvent;
      state: EditorState;
      view: EditorView;
    }) => void;
    onBlur?: ({
      event,
      state,
      view
    }: {
      event: FocusEvent;
      state: EditorState;
      view: EditorView;
    }) => void;
    onPaste?: (...args: any) => void;
    onDrop?: (...args: any) => void;
  }

  class ExtensionManager {
    constructor (extensions: Extension[], editor: Editor);
    extensions: Extension[];
    nodes: Node[];
    marks: Mark[];
    options: {[extensionName: string]: any };
    plugins: Plugin[];
    keymaps ({ schema }: { schema: Schema }): any[];
    inputRules ({ schema, excludedExtensions }: { schema: Schema, excludedExtensions: Extension[] }): any[];
    parstRules({ schema, excludedExtensions }: { schema: Schema, excludedExtensions: Extension[] }): any[];
    commands ({ schema, view }: { schema: Schema, view: EditorView }): any;
  }


  export class Editor {
    commands: { [key: string]: Command };
    defaultOptions: { [key: string]: any };
    element: Element;
    extensions: ExtensionManager;
    inputRules: any[];
    keymaps: any[];
    marks: Mark[];
    nodes: Node[];
    pasteRules: any[];
    plugins: Plugin[];
    schema: Schema;
    state: EditorState;
    view: EditorView;
    activeMarks: { [markName: string]: () => boolean };
    activeNodes: { [nodeName: string]: () => boolean };
    activeMarkAttrs: { [markName: string]: { [attr: string]: any } };

    /**
     * Creates an [Editor]
     * @param options - An object of Editor options.
     */
    constructor(options?: EditorOptions);

    /**
     * Replace the current content. You can pass an HTML string or a JSON document that matches the editor's schema.
     * @param content Defaults to {}.
     * @param emitUpdate Defaults to false.
     */
    setContent(content?: string | unknown, emitUpdate?: boolean): void;

    /**
     * Clears the current editor content.
     *
     * @param emitUpdate Whether or not the change should trigger the onUpdate callback.
     */
    clearContent(emitUpdate?: boolean): void;

    /**
     * Overwrites the current editor options.
     * @param options Options an object of Editor options
     */
    setOptions(options: EditorOptions): void;

    /**
     * Register a ProseMirror plugin.
     * @param plugin
     */
    registerPlugin(plugin: Plugin): void;

    /** Get the current content as JSON. */
    getJSON(): any;

    /** Get the current content as HTML. */
    getHTML(): string;

    /** Focus the editor */
    focus(): void;

    /** Removes the focus from the editor. */
    blur(): void;

    /** Destroy the editor and free all Prosemirror-related objects from memory.
     * You should always call this method on beforeDestroy() lifecycle hook of the Vue component wrapping the editor.
     */
    destroy(): void;

    on(event: string, callbackFn: (params: any) => void): void;

    off(event: string, callbackFn: (params: any) => void): void;

    getMarkAttrs(markName: string): { [attributeName: string]: any };
  }

  export class Extension<Options = any> {
    /** Define a name for your extension */
    name?: string | null;
    /** Define some default options.The options are available as this.$options. */
    defaultOptions?: Options;
    /** Define a list of Prosemirror plugins. */
    plugins?: Plugin[];
    /** Called when options of extension are changed via editor.extensions.options */
    update?: (view: EditorView) => any;
    /** Options for that are either passed in from the extension constructor or set by defaultOptions() */
    options?: Options;

    constructor(options?: Options);

    /** Define some keybindings. */
    keys?({
      schema
    }: {
      schema: Schema | NodeSpec | MarkSpec;
    }): { [keyCombo: string]: CommandFunction };

    /** Define commands. */
    commands?({
      schema,
      attrs
    }: {
      schema: Schema | NodeSpec | MarkSpec;
      attrs: { [key: string]: string };
    }): CommandGetter;

    inputRules?({ schema }: { schema: Schema }): any[];

    pasteRules?({ schema }: { schema: Schema }): Plugin[];
  }

  export class Node<V extends NodeView = any> extends Extension {
    schema?: NodeSpec;
    /** Reference to a view component constructor
     *  See https://stackoverflow.com/questions/38311672/generic-and-typeof-t-in-the-parameters
     */
    view?: { new (): V };

    commands?({
      type,
      schema,
      attrs
    }: {
      type: NodeType;
      schema: NodeSpec;
      attrs: { [key: string]: string };
    }): CommandGetter;

    keys?({
      type,
      schema
    }: {
      type: NodeType;
      schema: NodeSpec;
    }): { [keyCombo: string]: CommandFunction };

    inputRules?({ type, schema }: { type: NodeType; schema: Schema }): any[];

    pasteRules?({ type, schema }: { type: NodeType; schema: Schema }): Plugin[];
  }

  export class Mark<V extends NodeView = any> extends Extension {
    schema?: MarkSpec;
    /** Reference to a view component constructor
     *  See https://stackoverflow.com/questions/38311672/generic-and-typeof-t-in-the-parameters
     */
    view?: { new (): V };

    commands?({
      type,
      schema,
      attrs
    }: {
      type: MarkType;
      schema: MarkSpec;
      attrs: { [key: string]: string };
    }): CommandGetter;

    keys?({
      type,
      schema
    }: {
      type: MarkType;
      schema: MarkSpec;
    }): { [keyCombo: string]: CommandFunction };

    inputRules?({ type, schema }: { type: MarkType; schema: Schema }): any[];

    pasteRules?({ type, schema }: { type: MarkType; schema: Schema }): Plugin[];
  }

  export class Text extends Node {}

  export class Paragraph extends Node {}

  export class Doc extends Node {}

  /** A set of commands registered to the editor. */
  export interface EditorCommandSet {
    [key: string]: Command;
  }

  /**
   * The properties passed into <editor-menu-bar /> component
   */
  export interface MenuData {
    /** Whether the editor has focus. */
    focused: boolean;
    /** Function to focus the editor. */
    focus: () => void;
    /** A set of commands registered. */
    commands: EditorCommandSet;
    /** Check whether a node or mark is currently active. */
    isActive: IsActiveChecker;
    /** A function to get all mark attributes of the current selection.  */
    getMarkAttrs: (markName: string) => { [attributeName: string]: any };
    /** A link to the editor */
    editor: Editor;
  }

  export interface FloatingMenuData extends MenuData {
    /** An object for positioning the menu. */
    menu: MenuDisplayData;
  }

  /**
   * A data object passed to a menu bubble to help it determine its position
   * and visibility.
   */
  export interface MenuDisplayData {
    /** Left position of the cursor. */
    left: number;
    /** Bottom position of the cursor. */
    bottom: number;
    /** Whether or not there is an active selection. */
    isActive: boolean;
  }

  /**
   * A map containing functions to check if a node/mark is currently selected.
   * The name of the node/mark is used as the key.
   */
  export interface IsActiveChecker {
    [name: string]: () => boolean;
  }
}
```

The output from eslint in the output tab of VSCode:
```JS
[Error - 9:31:07 p.m.] ESLint stack trace:
[Error - 9:31:07 p.m.] TypeError: Cannot read property 'body' of null
Occurred while linting SkyCourt.UI\ui\src\typings\tiptap.d.ts:105
    at checkForConstructor (SkyCourt.UI\ui\node_modules\eslint\lib\rules\no-useless-constructor.js:165:42)
    at SkyCourt.UI\ui\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (SkyCourt.UI\ui\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (SkyCourt.UI\ui\node_modules\eslint\lib\linter\node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (SkyCourt.UI\ui\node_modules\eslint\lib\linter\node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (SkyCourt.UI\ui\node_modules\eslint\lib\linter\node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (SkyCourt.UI\ui\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:711:23)
    at SkyCourt.UI\ui\node_modules\eslint\lib\linter\linter.js:952:32
    at Array.forEach (<anonymous>)
    at runRules (SkyCourt.UI\ui\node_modules\eslint\lib\linter\linter.js:947:15)
    at Linter._verifyWithoutProcessors (SkyCourt.UI\ui\node_modules\eslint\lib\linter\linter.js:1173:31)
    at Linter._verifyWithConfigArray (SkyCourt.UI\ui\node_modules\eslint\lib\linter\linter.js:1271:21)
    at Linter.verify (SkyCourt.UI\ui\node_modules\eslint\lib\linter\linter.js:1226:25)
    at Linter.verifyAndFix (SkyCourt.UI\ui\node_modules\eslint\lib\linter\linter.js:1416:29)
    at verifyText (SkyCourt.UI\ui\node_modules\eslint\lib\cli-engine\cli-engine.js:224:48)
```

**Comment by mdjermanovic** [comment]
Hi @gregveres, thanks for the issue!

The core `no-useless-constructor` rule doesn't support typescript syntax, and it's crashing if a constructor doesn't have body.

Can you try with the following rule from [ESLint Plugin TypeScript](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#eslint-plugin-typescript) instead:

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-useless-constructor.md

```json
{
  "no-useless-constructor": "off",
  "@typescript-eslint/no-useless-constructor": ["error"]
}
```

**Comment by gregveres** [comment]
@mdjermanovic Yup that gets me by the crashes. 

I guess one of the rule sets I am pulling in with extends must turn on that rule. My extends set is definitely crappy for typescript. I am now hitting a rule where it is saying I can't have more than 1 class in a file, which just doesn't work for .d.ts files. 

Thanks, off to do some more research on how to setup eslint for a good set of typescript rules.

**Comment by mdjermanovic** [comment]
In general, rules listed in [Extension Rules](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#extension-rules) should be used instead of the corresponding built-in rules.

**Comment by gregveres** [comment]
Yea, that makes sense. I had mistakenly assumed that if somebody was suggesting a config (ie a set of extend packages) that it would have worked out all those kinks and favoured the extension rules. I was wrong, but I am on the right path now. I know what to look for in the future and I have started a set of overrides for .d.ts files in my config.

Thanks again for such a quick response!

**Comment by nzakas** [comment]
Looks like this is resolved, so closing.
