### ISSUE TITLE
No files matching the pattern "'**/*.js'" were found

### ISSUE THREAD

**Issue by phamleduy04** [eslint/eslint#13736]
**Tell us about your environment** Windows 10 Build 2004

* **ESLint Version:** 7.10.0
* **Node Version:** 12.18.4
* **npm Version:** 6.14.6

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?** airbnb-base

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": [
        "airbnb-base"
    ],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "rules": {
        "linebreak-style": "off",
        "no-console": "off"
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
I tried to run eslint in script written in package.json file

```js
  "scripts": {
    "start": "node index.js",
    "test": "node build/test.js",
    "eslint": "eslint '**/*.js'"
  }
```

```bash
npm run eslint
```

**What did you expect to happen?**
Show error if it have or none

**What actually happened? Please include the actual, raw output from ESLint.**
```js
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'eslint'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.4
4 verbose run-script [ 'preeslint', 'eslint', 'posteslint' ]
5 info lifecycle aki-api@5.1.1~preeslint: aki-api@5.1.1
6 info lifecycle aki-api@5.1.1~eslint: aki-api@5.1.1
7 verbose lifecycle aki-api@5.1.1~eslint: unsafe-perm in lifecycle true
8 verbose lifecycle aki-api@5.1.1~eslint: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\phaml\Documents\GitHub\aki-api\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\phaml\.windows-build-tools\python27\;C:\Users\phaml\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\phaml\AppData\Local\Programs\Python\Python38-32\;C:\Users\phaml\AppData\Local\Microsoft\WindowsApps;C:\Users\phaml\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\phaml\AppData\Roaming\npm;C:\Users\phaml\AppData\Local\GitHubDesktop\bin;C:\MinGW\bin;
9 verbose lifecycle aki-api@5.1.1~eslint: CWD: C:\Users\phaml\Documents\GitHub\aki-api
10 silly lifecycle aki-api@5.1.1~eslint: Args: [ '/d /s /c', "eslint '**/*.js'" ]
11 silly lifecycle aki-api@5.1.1~eslint: Returned: code: 2  signal: null
12 info lifecycle aki-api@5.1.1~eslint: Failed to exec eslint script
13 verbose stack Error: aki-api@5.1.1 eslint: `eslint '**/*.js'`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid aki-api@5.1.1
15 verbose cwd C:\Users\phaml\Documents\GitHub\aki-api
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "eslint"
18 verbose node v12.18.4
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 2
22 error aki-api@5.1.1 eslint: `eslint '**/*.js'`
22 error Exit status 2
23 error Failed at the aki-api@5.1.1 eslint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Are you willing to submit a pull request to fix this bug?** Nah

The main thing is, I tried to install eslint globally and run `eslint "**/*.js"` and eslint work perfectly

**Comment by phamleduy04** [comment]
nvm I fixed it
