### ISSUE TITLE
Failed to load plugin 'js' declared in 'CLIOptions': Cannot find module 'eslint-plugin-js'

### ISSUE THREAD

**Issue by Joshua-Leee** [eslint/eslint#13824]
I don't know why, when I open the project in Vscode, it always reports this error, and I can't find the solution, and I don't know what this thing is. Does anyone have the same experience as me? Are there any recommended solutions?
(Currently, I have installed eslint plug-in in Vscode and eslint globally.)
```
Failed to load plugin 'js' declared in 'CLIOptions': Cannot find module 'eslint-plugin-js'
Require stack:
- /Applications/MAMP/htdocs/demo/demo-react/teach-system-react/__placeholder__.js
Happened while validating /Applications/MAMP/htdocs/demo/demo-react/teach-system-react/src/pages/Layout/layoutSider/index.js
This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
2. If ESLint is installed globally, then make sure 'eslint-plugin-js' is installed globally as well.
3. If ESLint is installed locally, then 'eslint-plugin-js' isn't installed correctly.

Consider running eslint --debug /Applications/MAMP/htdocs/demo/demo-react/teach-system-react/src/pages/Layout/layoutSider/index.js from a terminal to obtain a trace about the configuration files used.
```
I hope someone can help me. Thank you very much(url)

**Comment by Joshua-Leee** [comment]
Ok, here's what it looks like: I have the ESlint plug-in installed in the VSCode editor, and I also have the ESlint tool installed globally, but eslint always reports this error whether it's on the VUE project or the React project：
```
Failed to load plugin 'js' declared in 'CLIOptions': Cannot find module 'eslint-plugin-js'
Require stack:
- /Applications/MAMP/htdocs/shengxue/admin-backend/__placeholder__.js
Happened while validating /Applications/MAMP/htdocs/shengxue/admin-backend/src/App.vue
This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
2. If ESLint is installed globally, then make sure 'eslint-plugin-js' is installed globally as well.
3. If ESLint is installed locally, then 'eslint-plugin-js' isn't installed correctly.

Consider running eslint --debug /Applications/MAMP/htdocs/shengxue/admin-backend/src/App.vue from a terminal to obtain a trace about the configuration files used.
```
I have even reinstalled Vscode several times, but it still doesn't work. The following is the content of my vscode configuration file. I hope someone can give me some Suggestions on how to solve this problem:
```
{
  "workbench.colorTheme": "One Dark Pro",
  "workbench.iconTheme": "vscode-icons",
  "editor.wordWrap": "on",
  "cssrem.rootFontSize": 100,
  "editor.detectIndentation": false,
  "editor.tabSize": 2,
  "editor.formatOnSave": true,
  "editor.formatOnPaste": true,
  "javascript.updateImportsOnFileMove.enabled": "always",
  "files.associations": {
    "*.wxss": "css",
    "*.tpl": "html",
    "*.wxml": "wxml",
    "*.vue": "vue",
    "*.scss": "scss",
    "*.cjson": "jsonc",
    "*.wxs": "javascript"
  },
  "emmet.triggerExpansionOnTab": true,
  "emmet.includeLanguages": {
    "vue-html": "html",
    "vue": "html",
    "wxml": "html"
  },
  "eslint.options": {
    "plugins": ["js", "vue", "jsx", "scss"]
  },
  "eslint.validate": ["javascript", "javascriptreact", "html", "vue", "jsx"],
  "liveServer.settings.donotShowInfoMsg": true,
  "javascript.implicitProjectConfig.experimentalDecorators": true,
  "workbench.statusBar.visible": true,
  "workbench.activityBar.visible": true,
  "extensions.autoUpdate": true,
  "git.confirmSync": false,
  "git.autofetch": true,
  "git.enableSmartCommit": true,
  "search.followSymlinks": false,
  "window.zoomLevel": 0,
  "terminal.integrated.rendererType": "dom",
  "[less]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "typescript.updateImportsOnFileMove.enabled": "always",
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[vue]": {
    "editor.defaultFormatter": "octref.vetur"
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "prettier.jsxBracketSameLine": true,
  "prettier.singleQuote": true,
  "prettier.jsxSingleQuote": true,
  "prettier.semi": false,
  "vetur.format.defaultFormatter.html": "prettyhtml",
  "vetur.format.defaultFormatter.js": "prettier-eslint",
  "vetur.format.defaultFormatterOptions": {
    "prettyhtml": {
      "printWidth": 100,
      "singleQuote": false,
      "wrapAttributes": true,
      "sortAttributes": true
    },
    "prettier": {
      "semi": false,
      "singleQuote": true,
      "eslintIntegration": true,
      "parser": "babylon"
    }
  },
  "typescript.locale": "zh-CN",
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "fileheader.Author": "Joshua",
  "fileheader.LastModifiedBy": "Joshua",
  "jsdoc.author": "Joshua",
  "editor.fontSize": 14,
  "merge-conflict.autoNavigateNextConflict.enabled": true,
  "eslint.alwaysShowStatus": true,
  "eslint.packageManager": "yarn"
}
```
I installed ESlint globally with the 'YARN Global add Eslint' command and was prompted with success. Then I initialized with the 'eslint -- init' command, but again an error was reported:
```
➜  ~ yarn global add eslint
yarn global v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "eslint@7.13.0" with binaries:
      - eslint
✨  Done in 15.62s.
➜  ~ eslint --init
✔ How would you like to use ESLint? · problems
✔ What type of modules does your project use? · esm
✔ Which framework does your project use? · vue
✔ Does your project use TypeScript? · No / Yes
✔ Where does your code run? · browser, node
✔ What format do you want your config file to be in? · JavaScript

Oops! Something went wrong! :(

ESLint: 7.13.0

Error: Could not find a package.json file. Run 'npm init' to create one.
    at check (/Users/Joshua/.config/yarn/global/node_modules/eslint/lib/init/npm-utils.js:104:15)
    at Object.checkDevDeps (/Users/Joshua/.config/yarn/global/node_modules/eslint/lib/init/npm-utils.js:156:12)
    at getModulesList (/Users/Joshua/.config/yarn/global/node_modules/eslint/lib/init/config-initializer.js:131:40)
    at /Users/Joshua/.config/yarn/global/node_modules/eslint/lib/init/config-initializer.js:590:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/Users/Joshua/.config/yarn/global/node_modules/eslint/bin/eslint.js:137:9)
➜  ~ 

```
The above is all my questions. I didn't find the answer I wanted in Google, so I came here to put forward the following questions. I hope someone can give me some Suggestions

**Comment by yeonjuan** [comment]
Hi :) @Joshua-Leee 

>  ~ eslint --init
> Oops! Something went wrong! :(
ESLint: 7.13.0
Error: Could not find a package.json file. Run 'npm init' to create one.

Why don't you run "eslint --init"  command in the directory? (where the "package.json" file place)
If your project has not "package.json" yet, please run `npm init` as the error message described.


>Failed to load plugin 'js' declared in 'CLIOptions': Cannot find module 'eslint-plugin-js'
Require stack: - /Applications/MAMP/htdocs/shengxue/admin-backend/__placeholder__.js
Happened while validating /Applications/MAMP/htdocs/shengxue/admin-backend/src/App.vue

 I'm not familiar with vscode settings but the "eslint.options" seems to use [CLIEngine Options](https://eslint.org/docs/developer-guide/nodejs-api#cliengine). So maybe you should install the `eslint-plugin-js`.But seems there is no corresponding package in the public NPM registry. So please check the `eslint.options` in vscode settings.

**Comment by Joshua-Leee** [comment]
Hey, buddy, thank you so much. According to your train of thought, I went to look at my Vscode configuration file and the question really came from 'eslint.options'.
The problem has been solved, thank you for your help, let me solve my problem

**Comment by yeonjuan** [comment]
issue closed because it is not an ESLint issue.
