### ISSUE TITLE
ESLint couldn't find the config "standard-with-typescript" to extend from.

### ISSUE THREAD

**Issue by Alexlikh** [eslint/eslint#13906]
**Tell us about your environment**

* **ESLint Version:** 7.14.0
* **Node Version:** 14.13.1
* **npm Version:** 6.14.9
* **yarn Version:** 1.22.10

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?** 
default

**Please show your full configuration:**

<details>
<summary>.package.json</summary>

```
  "devDependencies": {
    "@types/faker": "5.1.4",
    "@typescript-eslint/eslint-plugin": "4.9.0",
    "eslint": "7.14.0",
    "eslint-config-standard-with-typescript": "19.0.1",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-node": "11.1.0",
    "eslint-plugin-promise": "4.2.1",
    "eslint-plugin-react": "7.21.5",
    "eslint-plugin-standard": "5.0.0",
    "typescript": "4.1.2"
  }

```
</details>

<details>
<summary>.eslintrc.json</summary>

```
 {
  "root": true,
  "extends": [
    "standard-with-typescript",
    "plugin:react/recommended"
  ],
  "parserOptions": {
    "project": [
      "./tsconfig.json",
      "./devUtils/server/tsconfig.json"
    ],
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "plugins": [
    "react-hooks"
  ],
  "settings": {
    "react": {
      "version": "detect"
    }
  },
  "rules": {
    "@typescript-eslint/strict-boolean-expressions": 0,
    "@typescript-eslint/explicit-function-return-type": 0,
    "@typescript-eslint/no-floating-promises": 0,
    "@typescript-eslint/consistent-type-definitions":0,
    "no-return-assign": 0,
    "operator-linebreak": 0,
    "react/jsx-tag-spacing": 2,
    "react/prop-types": 0,
    "react/display-name": 0,
    "@typescript-eslint/return-await": 0,
    "react-hooks/rules-of-hooks": 2,
    "react-hooks/exhaustive-deps": 2
  }
}


```
</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

run command

```bash
yarn eslint "src/**"
```

**What did you expect to happen?**
ESLint find that config

**What actually happened? Please include the actual, raw output from ESLint.**
```bash
yarn run v1.22.10
$ /node_modules/.bin/eslint 'src/**'

Oops! Something went wrong! :(

ESLint: 7.14.0

ESLint couldn't find the config "standard-with-typescript" to extend from. Please check that the name of the config is correct.

The config "standard-with-typescript" was referenced from the config file in ".../.eslintrc.json".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.

error Command failed with exit code 2.

```

**PS**
Main issue is when i try run these commands:

```
yarn install --production
yarn run build
```
I got error described above. I know about --production flag, but with previous version eslint 6.8.0 everything was alright.

**Comment by yeonjuan** [comment]
@Alexlikh Have you try `yarn` or `yarn install` (without `--production`)? 
`yarn install --production` seems not to install `devDependencies` - see [yarn install --production](https://classic.yarnpkg.com/en/docs/cli/install/#toc-yarn-install-production-true-false).
And `standard-with-typescript` is specified in `devDependencies`  in you package.json

**Comment by Alexlikh** [comment]
Like i said, i know about --production flag. With previous version ```eslint 6.8.0``` everything work as intended without errors.
And ```yarn eslint "src/**"``` error occurs, what about that?

**Comment by yeonjuan** [comment]
@Alexlikh Oh Sorry, I missed, what you said in **PS**.  :) Could you provide a reproducible way or github repo? I tried but all failed to run when using "yarn install --production".

**Comment by Alexlikh** [comment]
@yeonjuan unfortunately, i can't provide neither a reproducible way or github repo, but i can share previous configuration before migration.

```
"devDependencies": {
    "@typescript-eslint/eslint-plugin": "4.4.0",
    "eslint": "6.8.0",
    "eslint-config-standard-with-typescript": "19.0.1",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-node": "11.1.0",
    "eslint-plugin-promise": "4.2.1",
    "eslint-plugin-react": "7.21.4",
    "eslint-plugin-standard": "4.0.1",
    "typescript": "4.0.5"
  }
```

```
{
  "extends": [
    "standard-with-typescript",
    "plugin:react/recommended"
  ],
  "parserOptions": {
    "project": [
      "./tsconfig.json",
      "./devUtils/server/tsconfig.json"
    ],
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "settings": {
    "react": {
      "version": "detect"
    }
  },
  "rules": {
    "@typescript-eslint/strict-boolean-expressions": 0,
    "@typescript-eslint/explicit-function-return-type": 0,
    "@typescript-eslint/no-floating-promises": 0,
    "@typescript-eslint/consistent-type-definitions":0,
    "no-return-assign": 0,
    "operator-linebreak": 0,
    "react/jsx-tag-spacing": 2,
    "react/prop-types": 0,
    "react/display-name": 0,
    "@typescript-eslint/return-await": 0
  }
}
```

**Comment by yeonjuan** [comment]
@Alexlikh  I tried with your configuration :)  If it's not reproduced maybe it was a bug in "yarn" or a mistake in installing. Anyway, I think it's not related to eslint.

**Comment by Alexlikh** [comment]
I assume it might be connected with these issues:
https://github.com/eslint/eslint/issues/13283
https://github.com/eslint/eslint/issues/11914

But still don't know what changes needs to be done with my configuration.

**Comment by mdjermanovic** [comment]
@Alexlikh can you run eslint with [--debug](https://eslint.org/docs/user-guide/command-line-interface#-debug) and share the output?

**Comment by Alexlikh** [comment]
@mdjermanovic  Sure, here it is.

<details>
<summary>debug output</summary>


```js
yarn run v1.22.10
$ /Users/---/Documents/---/---/node_modules/.bin/eslint 'src/**' --debug
  eslint:cli CLI args: [ 'src/**', '--debug' ] +0ms
  eslint:cli Running on files +3ms
  eslintrc:config-array-factory Loading .eslintignore file: /Users/---/Documents/---/---/.eslintignore +0ms
  eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/Users/---/Documents/---/---', loose: false } ] +0ms
  eslint:ignore-pattern   processed: { basePath: '/Users/---/Documents/---/---', patterns: [ '/**/node_modules/*' ] } +2ms
  eslint:ignore-pattern Create with: [ IgnorePattern { patterns: [ '/**/node_modules/*' ], basePath: '/Users/---/Documents/---/---', loose: false } ] +0ms
  eslint:ignore-pattern   processed: { basePath: '/Users/---/Documents/---/---', patterns: [ '/**/node_modules/*' ] } +0ms
  eslint:file-enumerator Start to iterate files: [ 'src/**' ] +0ms
  eslint:file-enumerator Glob: /Users/---/Documents/---/---/src/** +1ms
  eslint:file-enumerator recursive? true +1ms
  eslint:file-enumerator Enter the directory: /Users/---/Documents/---/---/src +0ms
  eslintrc:cascading-config-array-factory Load config files for /Users/---/Documents/---/---/src. +0ms
  eslintrc:cascading-config-array-factory No cache found: /Users/---/Documents/---/---/src. +0ms
  eslintrc:config-array-factory Config file not found on /Users/---/Documents/---/---/src +7ms
  eslintrc:cascading-config-array-factory No cache found: /Users/---/Documents/---/---. +0ms
  eslintrc:config-array-factory Loading JSON config file: /Users/---/Documents/---/---/.eslintrc.json +0ms
  eslintrc:config-array-factory Config file found: /Users/---/Documents/---/---/.eslintrc.json +1ms
  eslintrc:config-array-factory Loading {extends:"standard-with-typescript"} relative to /Users/---/Documents/---/---/.eslintrc.json +0ms

Oops! Something went wrong! :(

ESLint: 7.14.0

ESLint couldn't find the config "standard-with-typescript" to extend from. Please check that the name of the config is correct.

The config "standard-with-typescript" was referenced from the config file in "/Users/---/Documents/---/---/.eslintrc.json".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.

error Command failed with exit code 2.

```

</details>

**Comment by Alexlikh** [comment]
Worth to mention, error orrur after runnig
```
yarn install --production
yarn run build
```
and i would think this is problem with yarn, but it happend after eslint update, not after yarn update.

**Comment by mdjermanovic** [comment]
Can you check if `/Users/---/Documents/---/---/node_modules/eslint-config-standard-with-typescript` exists?

Also, can you run `node -p "require.resolve('eslint-config-standard-with-typescript')"` and `yarn node -p "require.resolve('eslint-config-standard-with-typescript')"` from `/Users/---/Documents/---/---/` dir?

> ```
> yarn install --production
> yarn run build
> ```

I'm not sure how you have `/Users/---/Documents/---/---/node_modules/.bin/eslint` after `yarn install --production`, isn't `--production` supposed to _not_ install dev dependencies?

**Comment by Alexlikh** [comment]
@mdjermanovic Hello!
After deleting node_modules, yarn.lock and running commands:
```
yarn install --production
yarn test
yarn run build
```
`/Users/---/Documents/---/---/node_modules/eslint-config-standard-with-typescript`, not exists.

After running `node -p "require.resolve('eslint-config-standard-with-typescript')"`, i got this:

```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'eslint-config-standard-with-typescript'
Require stack:
- /Users/---/Documents/---/---/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at [eval]:1:9
    at Script.runInThisContext (vm.js:132:18)
    at Object.runInThisContext (vm.js:309:38)
    at internal/process/execution.js:77:19
    at [eval]-wrapper:6:22
    at evalScript (internal/process/execution.js:76:60)
    at internal/main/eval_string.js:23:3 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/---/Documents/---/---/[eval]' ]
}

```

After running `yarn node -p "require.resolve('eslint-config-standard-with-typescript')"`, i got this:
```
yarn node v1.22.10
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'eslint-config-standard-with-typescript'
Require stack:
- /Users/---/Documents/---/---/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at [eval]:1:9
    at Script.runInThisContext (vm.js:132:18)
    at Object.runInThisContext (vm.js:309:38)
    at internal/process/execution.js:77:19
    at [eval]-wrapper:6:22
    at evalScript (internal/process/execution.js:76:60)
    at internal/main/eval_string.js:23:3 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/---/Documents/---/---/[eval]' ]
}
error Command failed.
Exit code: 1
Command: /usr/local/Cellar/node/14.13.1_1/bin/node
Arguments: -p require.resolve('eslint-config-standard-with-typescript')
Directory: /Users/---/Documents/---/Front
Output:

info Visit https://yarnpkg.com/en/docs/cli/node for documentation about this command.
```

I didn't understand either how this should work, but after install, `/Users/---/Documents/---/---/node_modules/.bin/eslint` exists.

**Comment by Alexlikh** [comment]
And this in /node_modules/
![image](https://user-images.githubusercontent.com/41023100/101343341-eb5d2f00-3894-11eb-8f30-8a828c6e677c.png)

**Comment by mdjermanovic** [comment]
Thanks for the info!

This is the expected behavior of ESLint, as it seems that `eslint-config-standard-with-typescript` isn't installed.

> after install, `/Users/---/Documents/---/---/node_modules/.bin/eslint` exists.

It could be that ESLint is a dependency or peer dependency of a package you have in `"dependencies"`, so it gets installed even with `--production`.

**Comment by nzakas** [comment]
Closing, as there is no further action here.
