### ISSUE TITLE
RangeError exception from node-ignore package when checking path

### ISSUE THREAD

**Issue by so-o** [eslint/eslint#13949]
Problem with flycheck which runs a command like:

/usr/bin/eslint --format\=json --stdin --stdin-filename /www/objectivejs.org/objectivejs/Objective.js < /www/objectivejs.org/objectivejs/Objective.js 
path should be a `path.relative()`d string, but got "../../../../www/objectivejs.org/objectivejs/Objective.js"
RangeError: path should be a `path.relative()`d string, but got "../../../../www/objectivejs.org/objectivejs/Objective.js"
    at throwError (/usr/share/nodejs/ignore/index.js:337:9)
    at checkPath (/usr/share/nodejs/ignore/index.js:356:12)
    at Ignore._test (/usr/share/nodejs/ignore/index.js:473:5)
    at Ignore.ignores (/usr/share/nodejs/ignore/index.js:512:17)
    at /usr/share/nodejs/ignore/index.js:516:26
    at Array.filter (<anonymous>)
    at Ignore.filter (/usr/share/nodejs/ignore/index.js:520:29)
    at IgnoredPaths.contains (/usr/share/nodejs/eslint/lib/ignored-paths.js:289:39)
    at CLIEngine.executeOnText (/usr/share/nodejs/eslint/lib/cli-engine.js:679:46)
    at Object.execute (/usr/share/nodejs/eslint/lib/cli.js:197:46)

If I run the same command without the `--stdin --stdin-filenam`e options with the same path, no problem.

Ubuntu 20.04, python 3.8.4, eslint-5.0.1, node-ignore 5.1.4-3.

**Comment by mdjermanovic** [comment]
Hi @so-o, thanks for the issue!

> node-ignore 5.1.4-3

This looks like a problem with the installation, `eslint` requires `"ignore": "^4.0.6"` (or older, since you're using eslint 5).

**Comment by nzakas** [comment]
Converting to a discussion, as we don't support ESLint v5.x
