### ISSUE TITLE
ESLint Initialization Results in "TypeError: Invalid Version: undefined"

### ISSUE THREAD

**Issue by jasel-lewis** [eslint/eslint#13978]
When initializing ESLint, receiving a TypeError in relation to sermver.

Environment:
Node v14.15.3
npm v6.14.9

Repro:
1. `npx create-electron-app my-app`
2. `npm install eslint --save-dev`
3. `./node_modules/.bin/eslint --init`

Config selections:
- To check syntax, find problems, and enforce code style
- JavaScript modules (import/export)
- React
- Does your project use TypeScript: No
- Where does your code run? Browser
- Use a popular style guide
- Standard: https://github.com/standard/standard
- What format do you want your config file to be in? JavaScript

Results:
```txt
Checking peerDependencies of eslint-config-standard@latest

Oops! Something went wrong! :(

ESLint: 7.10.0

TypeError: Invalid Version: undefined
    at new SemVer (D:\Repos.Private\my-app\node_modules\semver\classes\semver.js:19:13)
    at outside (D:\Repos.Private\my-app\node_modules\semver\ranges\outside.js:12:13)
    at Object.ltr (D:\Repos.Private\my-app\node_modules\semver\ranges\ltr.js:3:42)
    at TogglePrompt.message (D:\Repos.Private\my-app\node_modules\eslint\lib\init\config-initializer.js:569:37)
    at Object.exports.resolve (D:\Repos.Private\my-app\node_modules\enquirer\lib\utils.js:43:18)
    at TogglePrompt.resolve (D:\Repos.Private\my-app\node_modules\enquirer\lib\prompt.js:373:18)
    at TogglePrompt.element (D:\Repos.Private\my-app\node_modules\enquirer\lib\prompt.js:249:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async TogglePrompt.message (D:\Repos.Private\my-app\node_modules\enquirer\lib\prompt.js:270:19)
    at async TogglePrompt.render (D:\Repos.Private\my-app\node_modules\enquirer\lib\prompts\toggle.js:91:19)
```

Possibly similar in relation to ["Invalid Version: undefined" semver on version 3.x flow-typed](https://github.com/flow-typed/flow-typed/issues/3809).

**Comment by armordog** [comment]
For what it's worth, I'm having this same issue.
I've bisected it to between v7.2.0 and v7.3.0

**Comment by mdjermanovic** [comment]
Thanks for the bug report!

> Oops! Something went wrong! :(
> 
> ESLint: 7.10.0

I can reproduce this with ESLint v7.10.0, there's a bug with the question to upgrade/downgrade ESLint.

Can you try with the latest ESLint v7.17.0? The same problem in the code exists in v7.17.0, but it shouldn't be observable just because this version satisfies the actual eslint-config-standard's peer dependency requirements (`"eslint": "^7.12.1"`).

I'm working on the fix.
