### ISSUE TITLE
Cannot load `eslint-plugin-react-security`

### ISSUE THREAD

**Issue by hnipps** [eslint/eslint#13996]
**Tell us about your environment**

* **ESLint Version:** 7.7.0 
* **Node Version:** 12.3.0
* **npm Version:** 6.12.0

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
`@babel/eslint-parser`

**Please show your full configuration:**
Cannot print full config.

`eslint --print-config package.json` results in:
```
Oops! Something went wrong! :(

ESLint: 7.7.0

ESLint couldn't find the plugin "eslint-plugin-react-securit".

(The package "eslint-plugin-react-securit" was not found when loaded as a Node module from the directory "/Users/dave.vannoten/repos/control-panel".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-react-securit@latest --save-dev

The plugin "eslint-plugin-react-securit" was referenced from the config file in "package.json".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
```

<details>
<summary>Configuration with issue</summary>

```js
// Excerpt from package.json
"eslintConfig": {
    "extends": [
      "@spothero",
      "plugin:prettier/recommended",
      "prettier/babel",
      "prettier/react",
      "plugin:react-security"
    ],
    "plugins": [
      "react-security"
    ],
    "overrides": [
      {
        "files": [
          "**/*.js"
        ],
        "rules": {
          "func-names": 0
        }
      }
    ]
  },
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
Added `eslint-plugin-react-security`.

```json
// Excerpt from package.json
"eslintConfig": {
    "extends": [
      "@spothero",
      "plugin:prettier/recommended",
      "prettier/babel",
      "prettier/react",
      "plugin:react-security"
    ],
    "plugins": [
      "react-security"
    ],
    "overrides": [
      {
        "files": [
          "**/*.js"
        ],
        "rules": {
          "func-names": 0
        }
      }
    ]
  },
```

No command run manually. This happens when using the VSCode extension.

**What did you expect to happen?**
The `react-security` plugin would be loaded.

**What actually happened? Please include the actual, raw output from ESLint.**
Plugin doesn't load. For some reason the `y` is dropped from the end of the package name.

This is the console output:
```
node:90437) UnhandledPromiseRejectionWarning: Error: Failed to load plugin 'react-securit' declared in 'package.json': Cannot find module 'eslint-plugin-react-securit'
Require stack:
- /Users/dave.vannoten/repos/control-panel/__placeholder__.js
Referenced from: /Users/dave.vannoten/repos/control-panel/package.json
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
    at Function.resolve (internal/modules/cjs/helpers.js:80:19)
    at Object.resolve (/Users/dave.vannoten/repos/control-panel/node_modules/eslint/lib/shared/relative-module-resolver.js:28:50)
    at ConfigArrayFactory._loadPlugin (/Users/dave.vannoten/repos/control-panel/node_modules/eslint/lib/cli-engine/config-array-factory.js:992:39)
    at ConfigArrayFactory._loadExtendedPluginConfig (/Users/dave.vannoten/repos/control-panel/node_modules/eslint/lib/cli-engine/config-array-factory.js:812:29)
    at ConfigArrayFactory._loadExtends (/Users/dave.vannoten/repos/control-panel/node_modules/eslint/lib/cli-engine/config-array-factory.js:761:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/dave.vannoten/repos/control-panel/node_modules/eslint/lib/cli-engine/config-array-factory.js:702:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/dave.vannoten/repos/control-panel/node_modules/eslint/lib/cli-engine/config-array-factory.js:647:20)
    at _normalizeObjectConfigData.next (<anonymous>)
(node:90437) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:90437) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:90437) UnhandledPromiseRejectionWarning: Error: Failed to load plugin 'react-securit' declared in 'package.json': Cannot find module 'eslint-plugin-react-securit'
Require stack:
- /Users/dave.vannoten/repos/control-panel/__placeholder__.js
Referenced from: /Users/dave.vannoten/repos/control-panel/package.json
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
    at Function.resolve (internal/modules/cjs/helpers.js:80:19)
    at Object.resolve (/Users/dave.vannoten/repos/control-panel/node_modules/eslint/lib/shared/relative-module-resolver.js:28:50)
    at ConfigArrayFactory._loadPlugin (/Users/dave.vannoten/repos/control-panel/node_modules/eslint/lib/cli-engine/config-array-factory.js:992:39)
    at ConfigArrayFactory._loadExtendedPluginConfig (/Users/dave.vannoten/repos/control-panel/node_modules/eslint/lib/cli-engine/config-array-factory.js:812:29)
    at ConfigArrayFactory._loadExtends (/Users/dave.vannoten/repos/control-panel/node_modules/eslint/lib/cli-engine/config-array-factory.js:761:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/dave.vannoten/repos/control-panel/node_modules/eslint/lib/cli-engine/config-array-factory.js:702:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/dave.vannoten/repos/control-panel/node_modules/eslint/lib/cli-engine/config-array-factory.js:647:20)
    at _normalizeObjectConfigData.next (<anonymous>)
(node:90437) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Are you willing to submit a pull request to fix this bug?**
Depends how complicated the solution is.

**Comment by anikethsaha** [comment]
Thanks for the issue

I think `plugin:` needs to have a config name too. 

[docs](https://eslint.org/docs/user-guide/configuring#using-the-configuration-from-a-plugin)

**Comment by nzakas** [comment]
That's correct. You can't just put "plugin:foo" in as a config name, it must always have a `/`.

It looks like `eslint-plugin-react-security` doesn't actually have any configs exported, so you should be able to remove that line.
