### ISSUE TITLE
No linting: "runtime_lint_utils_1.isCircular is not a function" for files nested in folders with similar/same name

### ISSUE THREAD

**Issue by parksj10** [eslint/eslint#14082]
**Tell us about your environment**

* **ESLint Version:** 7.19.0 (7.2.0 was version throwing error)
* **Node Version:** 15.6.0 (eslint running in node v12.18.3)
* **npm Version:** 6.14.11
* **Operating System:** OSX

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
`"@typescript-eslint/parser": "^2.34.0",`
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "root": true,
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 2018,
    "sourceType": "module",
    "project": "./tsconfig.base.json"
  },
  "ignorePatterns": ["**/node_modules/**/*", "**/dist/**/*"],
  "plugins": ["@typescript-eslint", "@nrwl/nx", "react", "jest"],
  "extends": [
    "airbnb-typescript",
    "airbnb/hooks",
    "plugin:@typescript-eslint/recommended",
    "plugin:jest/recommended",
    "prettier",
    "prettier/react",
    "prettier/@typescript-eslint",
    "plugin:prettier/recommended"
  ],
  "env": {
    "browser": true,
    "es6": true,
    "jest": true
  },
  "rules": {
    "@typescript-eslint/explicit-member-accessibility": "off",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/no-parameter-properties": "off",
    "import/prefer-default-export": "off",
    "import/no-extraneous-dependencies": [
      "error",
      {
        "devDependencies": [
          "**/*.stories.ts",
          "**/*.stories.tsx",
          "**/*.test.ts",
          "**/*.test.tsx"
        ]
      }
    ],
    "@nrwl/nx/enforce-module-boundaries": [
      "error",
      {
        "enforceBuildableLibDependency": true,
        "allow": [],
        "depConstraints": [
          { "sourceTag": "*", "onlyDependOnLibsWithTags": ["*"] }
        ]
      }
    ],
    "linebreak-style": "off",
    "prettier/prettier": [
      "error",
      {
        "endOfLine": "auto"
      }
    ]
  },
  "overrides": [
    {
      "files": ["*.tsx", "*.ts", "*.js", "*.jsx"],
      "rules": {
        "@typescript-eslint/no-unused-vars": "off"
      }
    }
  ]
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
import React from 'react';

export const QuestionIcon = () => {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48.19 48.19">
      <title>Question</title>
      <polygon
        points="1 1 1 1"
        fill="none"
        stroke="#231f20"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <text
        transform="translate(16.55 31.4)"
        fontSize="26.36"
        fill="#231f20"
        fontFamily="ArialMT, Arial"
      >
        ?
      </text>
    </svg>
  );
};
```

```vscode
"editor.codeActionsOnSave": { "source.fixAll.eslint": true },
```

**What did you expect to happen?**
Lint the file

**What actually happened? Please copy-paste the actual, raw output from ESLint.**
The editor doesn't format or list errors in file

**Steps to reproduce this issue:**
create a tsx file inside of a directory of the same name or containing the first portion of the name:
e.g. `/reflect/apps/browser-overlay/src/assets/svg/svgExports.tsx`

Note: in eslint 7.2.0 I was getting the error: 

```
[Info  - 11:19:22 PM] runtime_lint_utils_1.isCircular is not a function Occurred while linting /Users/josh/Code/js/reflect/apps/browser-overlay/src/components/SelectionToolTip/SelectionToolTip.tsx:1
```
~~In eslint 7.19.0. the eslint output is silent, but the linting still doesn't work~~
Nevermind, same errors still happening

Error also occurs in zsh:
```
╰─ eslint /Users/josh/Code/js/reflect/apps/browser-overlay/src/components/SelectionToolTip/SelectionToolTip.tsx                                 ─╯

Oops! Something went wrong! :(

ESLint: 7.19.0

TypeError: runtime_lint_utils_1.isCircular is not a function
Occurred while linting /Users/josh/Code/js/reflect/apps/browser-overlay/src/components/SelectionToolTip/SelectionToolTip.tsx:1
    at ImportDeclaration (/Users/josh/Code/js/reflect/node_modules/@nrwl/eslint-plugin-nx/src/rules/enforce-module-boundaries.js:109:42)
    at /usr/local/lib/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/usr/local/lib/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/usr/local/lib/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/usr/local/lib/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/usr/local/lib/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/usr/local/lib/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /usr/local/lib/node_modules/eslint/lib/linter/linter.js:952:32
    at Array.forEach (<anonymous>)
```

**Comment by parksj10** [comment]
nevermind, deeper dive showed that there is an issue with the nrwl/nx plugin as seen [here](https://github.com/nrwl/nx/issues/4731)
