### ISSUE TITLE
Crash when linting interpolated string - Cannot read property 'range' of null

### ISSUE THREAD

**Issue by ghiculescu** [eslint/eslint#14248]
**Tell us about your environment**

```
Node version: v14.8.0
npm version: v6.14.7
Local ESLint version: v7.22.0 (Currently used)
Global ESLint version: Not found
```

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?** `babel-eslint`. This is my package.json:

```json
  "devDependencies": {
    "babel-eslint": "^10.1.0",
    "eslint": "^7.22.0",
    "webpack-dev-server": "^3.11.2"
  }
```

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    "env": {
        "browser": true,
        "node": true,
        "es2021": true
    },
    "extends": "eslint:recommended",
    "parser": "babel-eslint",
    "parserOptions": {
        "ecmaVersion": 12,
        "sourceType": "module"
    },
    "rules": {
        "semi": ["error", "never"],
        "indent": ["error", 2],
        "prefer-const": ["error"]
    },
    "globals": {
        "google": "readonly"
    }
};

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
export default class {
  getMetaValue(name) {
    return document.head.querySelector(`meta[name="${name}"]`)
  }
}
```

```bash
yarn run eslint <filename>
```

**What did you expect to happen?**

Either print a lint error or exit cleanly.

**What actually happened? Please include the actual, raw output from ESLint.**

Crash:

```
Oops! Something went wrong! :(

ESLint: 7.22.0

TypeError: Cannot read property 'range' of null
Occurred while linting ROOT/app/javascript/controllers/foo_controller.js:1
    at OffsetStorage.setDesiredOffset (ROOT/node_modules/eslint/lib/rules/indent.js:341:45)
    at ROOT/node_modules/eslint/lib/rules/indent.js:1397:29
    at Array.forEach (<anonymous>)
    at Object.TemplateLiteral [as listener] (ROOT/node_modules/eslint/lib/rules/indent.js:1389:34)
    at ROOT/node_modules/eslint/lib/rules/indent.js:1635:55
    at Array.forEach (<anonymous>)
    at Program:exit (ROOT/node_modules/eslint/lib/rules/indent.js:1635:26)
    at ROOT/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (ROOT/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
```

Changing the code to this fixes the crash:

```js
export default class {
  getMetaValue(name) {
    return document.head.querySelector('meta[name="' + name + '"]')
  }
}
```

If I've missed some sort of configuration needed to use JS string interpolation, I think it would be better if eslint said so explicitly.

**Comment by mdjermanovic** [comment]
Hi @ghiculescu, thanks for the issue!

This is a known issue with `babel-eslint` v10.1.0. Can you try with the latest version of [@babel/eslint-parser](https://www.npmjs.com/package/@babel/eslint-parser)?

(`babel-eslint` is now `@babel/eslint-parser`).

**Comment by ghiculescu** [comment]
Thanks! That worked great.

**Comment by ghiculescu** [comment]
Sorry about that.
