### ISSUE TITLE
Eslint --cache --fix command failing

### ISSUE THREAD

**Issue by nemonemi** [eslint/eslint#14281]
**Tell us about your environment**

* **ESLint Version:** *7.21.0*
* **Node Version:** *14.16.0*
* **npm Version:** *6.14.11*
* **yarn Version:** *1.22.10*

* **Operating System:** *Windows 10*

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
**@typescript-eslint/parser**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "root": true,
  "plugins": ["@nrwl/nx"],
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],
      "parserOptions": {
        "project": "./tsconfig.*?.json"
      },
      "rules": {
        "@nrwl/nx/enforce-module-boundaries": [
          "error",
          {
            "allow": [],
            "depConstraints": [
              {
                "sourceTag": "*",
                "onlyDependOnLibsWithTags": ["*"]
              }
            ],
            "enforceBuildableLibDependency": true
          }
        ]
      }
    },
    {
      "files": ["*.ts", "*.tsx"],
      "extends": ["plugin:@nrwl/nx/typescript"],
      "parserOptions": {
        "project": "./tsconfig.*?.json"
      },
      "rules": {}
    },
    {
      "files": ["*.js", "*.jsx"],
      "extends": ["plugin:@nrwl/nx/javascript"],
      "rules": {}
    }
  ],
  "extends": ["prettier"]
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

<details>
<summary>Package.json</summary>

```js
{
  "name": "qwe",
  "version": "1.0.0",
  "private": true,
  "license": "MIT",
  "scripts": {
    "affected": "nx affected",
    "affected:apps": "nx affected:apps",
    "affected:build": "nx affected:build",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected:e2e": "nx affected:e2e --plain --base=origin/master --headless",
    "affected:libs": "nx affected:libs --plain --base=origin/master --parallel --maxParallel=3",
    "affected:lint": "nx affected:lint --plain --base=origin/master --parallel --maxParallel=3",
    "affected:test": "nx affected:test --plain --base=origin/master --parallel --maxParallel=3",
    "build": "nx build --configuration=dev --baseHref=. --deployUrl=./",
    "build:all": "nx run-many --target=build --all --parallel --maxParallel=8 --configuration=prod --deployUrl=./",
    "changelog": "conventional-changelog -p $(pwd)/conventional-changelog-sirius -i CHANGELOG.md -s",
    "changelog:init": "conventional-changelog -p $(pwd)/conventional-changelog-sirius -i CHANGELOG.md -r 0",
    "commit": "git-cz",
    "dep-graph": "nx dep-graph",
    "dev:bd-certificate-overview": "nx serve bd-certificate-overview --port 4201 --open",
    "dev:survey-form": "nx serve survey-form --port 4202 --open",
    "e2e": "nx e2e",
    "e2e:all": "nx run-many --target=e2e --all --headless",
    "format": "nx format:write",
    "format:check": "nx format:check",
    "format:write": "nx format:write",
    "help": "nx help",
    "lint": "nx workspace-lint && nx lint",
    "nx": "nx",
    "start": "nx serve",
    "ui:storybook": "nx run ui:storybook",
    "test": "nx test",
    "test:all": "nx run-many --target=test --all",
    "test:all:coverage": "nx run-many --target=test --all --codeCoverage",
    "test:coverage": "yarn run affected:test --codeCoverage",
    "test:coverage:merge": "lcov-result-merger coverage/**/lcov.info coverage/lcov.merged.info",
    "workspace-generator": "nx workspace-generator"
  },
  "dependencies": {
    "@material-ui/core": "4.11.3",
    "@material-ui/icons": "~4.11.2",
    "axios": "~0.21.1",
    "core-js": "~3.9.1",
    "document-register-element": "1.13.1",
    "i18next": "~19.9.1",
    "i18next-xhr-backend": "~3.2.2",
    "lodash": "~4.17.21",
    "postscribe": "2.0.8",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-error-boundary": "3.1.1",
    "react-i18next": "11.8.8",
    "react-is": "17.0.1",
    "react-query": "3.12.0",
    "react-router-dom": "~5.2.0",
    "react-transition-group": "~4.4.1",
    "styled-components": "5.2.1",
    "tslib": "2.1.0"
  },
  "devDependencies": {
    "@babel/core": "7.13.8",
    "@babel/helper-builder-react-jsx-experimental": "7.12.11",
    "@babel/helper-regex": "7.10.5",
    "@babel/preset-env": "7.13.9",
    "@babel/preset-react": "7.12.13",
    "@babel/preset-typescript": "7.13.0",
    "@nrwl/cli": "11.4.0",
    "@nrwl/cypress": "11.4.0",
    "@nrwl/eslint-plugin-nx": "11.4.0",
    "@nrwl/jest": "11.4.0",
    "@nrwl/react": "11.4.0",
    "@nrwl/schematics": "8.12.11",
    "@nrwl/storybook": "11.4.0",
    "@nrwl/tao": "11.4.0",
    "@nrwl/web": "11.4.0",
    "@nrwl/workspace": "11.4.0",
    "@storybook/addon-essentials": "6.1.21",
    "@storybook/addon-knobs": "6.1.11",
    "@storybook/react": "6.1.11",
    "@svgr/webpack": "5.4.0",
    "@testing-library/cypress": "7.0.4",
    "@testing-library/jest-dom": "5.11.9",
    "@testing-library/react": "11.2.5",
    "@testing-library/react-hooks": "5.1.0",
    "@testing-library/user-event": "12.8.1",
    "@types/faker": "~5.1.7",
    "@types/jest": "26.0.20",
    "@types/lodash": "4.14.168",
    "@types/node": "14.14.31",
    "@types/react": "17.0.2",
    "@types/react-dom": "17.0.1",
    "@types/react-is": "17.0.0",
    "@types/react-router-dom": "5.1.7",
    "@types/react-transition-group": "~4.4.1",
    "@types/styled-components": "5.1.7",
    "@types/webpack": "4.41.26",
    "@typescript-eslint/eslint-plugin": "4.16.1",
    "@typescript-eslint/parser": "4.16.1",
    "babel-jest": "26.6.3",
    "babel-loader": "8.2.2",
    "babel-plugin-styled-components": "1.12.0",
    "commitizen": "~4.2.2",
    "conventional-changelog-cli": "2.1.1",
    "cypress": "6.6.0",
    "cz-customizable": "~6.3.0",
    "dotenv": "6.2.0",
    "eslint": "7.21.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "2.11.2",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsx-a11y": "6.4.1",
    "eslint-plugin-react": "7.21.5",
    "eslint-plugin-react-hooks": "4.2.0",
    "faker": "~5.1.0",
    "jest": "26.6.3",
    "jest-styled-components": "7.0.3",
    "lcov-result-merger": "~3.1.0",
    "lint-staged": "10.5.4",
    "miragejs": "~0.1.41",
    "prettier": "2.2.1",
    "simple-git-hooks": "2.2.0",
    "ts-jest": "26.5.3",
    "ts-node": "9.1.1",
    "tslint": "6.1.3",
    "typescript": "4.2.3",
    "typescript-styled-plugin": "~0.15.0",
    "url-loader": "3.0.0"
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-customizable"
    }
  },
  "volta": {
    "node": "14.16.0",
    "yarn": "1.22.10"
  },
  "resolutions": {
    "styled-components": "^5"
  },
  "lint-staged": {
    "*{.js,jsx,ts,tsx,json,md}": [
      "eslint --cache --fix",
      "prettier --write"
    ],
    "*.js": "eslint --cache --fix",
    "*.format:write": "prettier --write"
  },
  "simple-git-hooks": {
    "pre-commit": "npx lint-staged"
  }
}

```
</details>

```bash
npx eslint --cache --fix .
```

**What did you expect to happen?**
Command to execute successfully

**What actually happened? Please copy-paste the actual, raw output from ESLint.**
```
λ npx eslint --cache --fix .

Oops! Something went wrong! :(

ESLint: 7.21.0

Error: Cannot read config file: C:\www\frontends\node_modules\eslint-config-prettier\@typescript-eslint.js
Error: "prettier/@typescript-eslint" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
Referenced from: C:\www\frontends\node_modules\@nrwl\eslint-plugin-nx\src\index.js
    at Object.<anonymous> (C:\www\frontends\node_modules\eslint-config-prettier\@typescript-eslint.js:1:69)
    at Module._compile (C:\www\frontends\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.require (C:\www\frontends\node_modules\@nrwl\tao\src\compat\compat.js:7:40)
    at module.exports (C:\www\frontends\node_modules\import-fresh\index.js:32:59)
    at loadJSConfigFile (C:\www\frontends\node_modules\@eslint\eslintrc\lib\config-array-factory.js:225:16)
    at loadConfigFile (C:\www\frontends\node_modules\@eslint\eslintrc\lib\config-array-factory.js:309:20)
```

**Steps to reproduce this issue:**

1. 
1. 
1. 

**Are you willing to submit a pull request to fix this bug?**
Unfortunately, I don't know what is causing the issue, and the repo where it is occurring is private.

**Comment by nzakas** [comment]
Can you create a public repo with a minimal reproduction case so we can take a look?

**Comment by nemanjamilosavljevic-newtron** [comment]
Sure, I'll do it as soon as possible.

**Comment by nzakas** [comment]
@nemonemi do you still intend to create a repo for this?

**Comment by nemonemi** [comment]
Hi @nzakas, yes I do, however, at the moment I'm busy with other things. If you think it makes sense, we can close the ticket until the time I can come back to it?

**Comment by nzakas** [comment]
Sounds good. Thanks.
