### ISSUE TITLE
Unexpected top-level property "files"

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint#14330]
**Tell us about your environment**

Environment Info:

Node version: v15.12.0
npm version: v7.7.6
Local ESLint version: 7.24.0
Global ESLint version: Not found
Operating System: darwin 20.4.0

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
// .eslintrc
const eslintrc = require('./config/eslintrc')
const eslintrcLegacy = require('./config/eslintrc-legacy')

module.exports = {
  overrides: [
    eslintrc,
    eslintrcLegacy,
  ]
}
```

```js
// config/eslintrc.js
module.exports = {
  files: [
    'src/**/*.{js,jsx,ts,tsx,json}',
  ],
  excludedFiles: require('./eslint-legacy.js').files,
  rules: {...}
}
```
```js
// config/eslintrc-legacy.js
module.exports = {
  files: [
    'src/common/components/**/*.{js,jsx,ts,tsx,json}',
    'src/{containers,reducers}/**/*.{js,jsx,ts,tsx,json}',
  ],
  extends: [path.join(__dirname, './eslintrc.js')],
  rules: {...},
}
```
</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

```

```bash
npx eslint src/index.js
```

**What did you expect to happen?**
linting and no crash.

**What actually happened? Please copy-paste the actual, raw output from ESLint.**
```bash
➜  honor git:(chore/clean-eslintrc) ✗ npx eslint src/index.js

Oops! Something went wrong! :(

ESLint: 7.24.0

Error: ESLint configuration in .eslintrc.js#overrides[1] » /Users/weiran/repo/dian/honor/config/eslintrc is invalid:
        - Unexpected top-level property "files".

Referenced from: /Users/weiran/repo/dian/honor/.eslintrc.js
    at ConfigValidator.validateConfigSchema (/Users/weiran/repo/dian/honor/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:271:19)
    at ConfigArrayFactory._normalizeConfigData (/Users/weiran/repo/dian/honor/node_modules/@eslint/eslintrc/lib/config-array-factory.js:644:19)
    at ConfigArrayFactory._loadConfigData (/Users/weiran/repo/dian/honor/node_modules/@eslint/eslintrc/lib/config-array-factory.js:609:21)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/weiran/repo/dian/honor/node_modules/@eslint/eslintrc/lib/config-array-factory.js:889:21)
    at ConfigArrayFactory._loadExtends (/Users/weiran/repo/dian/honor/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/weiran/repo/dian/honor/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/weiran/repo/dian/honor/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/weiran/repo/dian/honor/node_modules/@eslint/eslintrc/lib/config-array-factory.js:758:25)
```

**Steps to reproduce this issue:**

I'll make a repo later.

**Are you willing to submit a pull request to fix this bug?**
not yet.

**Comment by aladdin-add** [comment]
https://github.com/aladdin-add/eslint-issue14330

**Comment by ljharb** [comment]
Is this perhaps caused by the top-level config having nothing *but* overrides?

**Comment by aladdin-add** [comment]
seems no. After comment out this line: https://github.com/aladdin-add/eslint-issue14330/blob/a7b866632162cb9b905a7a38272125e362993080/config/eslintrc-legacy.js#L4, the error did not occur.

**Comment by ljharb** [comment]
well sure, you tried to "extends" a config that has "files" in it - in other words, `eslintrc.js` only ever would work inside `overrides`. Valid overrides objects aren't extendable configs.
