### ISSUE TITLE
Cannot read property 'replace' of undefined while writing an import statement in .tsx file 

### ISSUE THREAD

**Issue by lawandothman** [eslint/eslint#14537]
**Tell us about your environment**

* **ESLint Version:** `v7.25.0`
* **Node Version:** `v16.0.0`
* **npm Version:** `v7.10.0`
* **Operating System:**  `macOS Big Sur v11.3`

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?** `@typescript-eslint/parser`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "env": {
        "browser": true,
        "es2021": true
    },
    "extends": [
        "plugin:react/recommended",
        "airbnb"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 12,
        "sourceType": "module"
    },
    "plugins": [
        "react",
        "@typescript-eslint"
    ],
    "rules": {
        "semi": [
            "error",
            "never"
        ],
        "quotes": [
            "error",
            "single"
        ],
        "jsx-quotes": [
            "error",
            "prefer-single"
        ],
        "react/react-in-jsx-scope": "off",
        "react/jsx-filename-extension": [
            1,
            {
                "extensions": [
                    ".ts",
                    ".tsx"
                ]
            }
        ],
        "react/jsx-props-no-spreading": "off",
        "react/prop-types": "off"
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

write import statement in tsx files 

```ts
import '../styles/globals.css'
import type { AppProps } from 'next/app'

function MyApp({ Component, pageProps } : AppProps) {
  return <Component {...pageProps} />
}

export default MyApp

```

```bash

```

**What did you expect to happen?**
No error messages to pop up 

**What actually happened? Please copy-paste the actual, raw output from ESLint.**
```
[Error - 12:25:38] ESLint stack trace:
[Error - 12:25:38] TypeError: Cannot read property 'replace' of undefined
Occurred while linting /Users/lawandothman/Developer/personal/nextjs-project/frontend/pages/_app.tsx:2
    at checkFileExtension (/Users/lawandothman/Developer/personal/nextjs-project/frontend/node_modules/eslint-plugin-import/lib/rules/extensions.js:148:52)
    at /Users/lawandothman/Developer/personal/nextjs-project/frontend/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/lawandothman/Developer/personal/nextjs-project/frontend/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/lawandothman/Developer/personal/nextjs-project/frontend/node_modules/eslint/lib/linter/node-event-generator.js:256:26)
    at NodeEventGenerator.applySelectors (/Users/lawandothman/Developer/personal/nextjs-project/frontend/node_modules/eslint/lib/linter/node-event-generator.js:285:22)
    at NodeEventGenerator.enterNode (/Users/lawandothman/Developer/personal/nextjs-project/frontend/node_modules/eslint/lib/linter/node-event-generator.js:299:14)
    at CodePathAnalyzer.enterNode (/Users/lawandothman/Developer/personal/nextjs-project/frontend/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /Users/lawandothman/Developer/personal/nextjs-project/frontend/node_modules/eslint/lib/linter/linter.js:954:32
    at Array.forEach (<anonymous>)
```

**Steps to reproduce this issue:**

1. Create Next Js and configure it to use TypeScript
2. write import statement in .tsx file 

**Are you willing to submit a pull request to fix this bug?**

**Comment by aladdin-add** [comment]
seems the error was from `eslint-plugin-import`, which is not maintained by the eslint team.

please file the issue in that repo. :)
