### ISSUE TITLE
`indent` throws TypeError: Cannot read property 'loc' of undefined

### ISSUE THREAD

**Issue by DanielSWolf** [eslint/eslint#14538]
**Tell us about your environment**

* **ESLint Version:** v7.25.0
* **Node Version:** v14.16.0
* **npm Version:** 6.14.11 (Yarn 1.22.4)
* **Operating System:** macOS Catalina 10.15.7

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

I'm using `@typescript-eslint/parser`. The problem does *not* occur when using the default parser.

**Please show your full configuration:**

The problem can be reproduced with this minimal configuration:

```json
{
  "parser": "@typescript-eslint/parser",
  "rules": {
    "indent": "error"
  }
}
```

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

The problem occurs whenever there is an incomplete variable declaration. It's sufficient to write `var` or `const` without a following identifier.

```js
var
```

This happens all the time when programming in VS code: Each time I'm in the middle of declaring a new variable, an error toast pops up.

Command:
```bash
eslint test.ts
```

**What did you expect to happen?**

ESLint should run normally and output a parsing error, as it does when using the default parser.

**What actually happened? Please copy-paste the actual, raw output from ESLint.**

```text
Oops! Something went wrong! :(

ESLint: 7.25.0

TypeError: Cannot read property 'loc' of undefined
Occurred while linting /Users/wolf/dev/crossmip/test.ts:1
    at Object.VariableDeclaration [as listener] (/Users/wolf/dev/crossmip/node_modules/eslint/lib/rules/indent.js:1423:69)
    at /Users/wolf/dev/crossmip/node_modules/eslint/lib/rules/indent.js:1635:55
    at Array.forEach (<anonymous>)
    at Program:exit (/Users/wolf/dev/crossmip/node_modules/eslint/lib/rules/indent.js:1635:26)
    at /Users/wolf/dev/crossmip/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/wolf/dev/crossmip/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/wolf/dev/crossmip/node_modules/eslint/lib/linter/node-event-generator.js:256:26)
    at NodeEventGenerator.applySelectors (/Users/wolf/dev/crossmip/node_modules/eslint/lib/linter/node-event-generator.js:285:22)
    at NodeEventGenerator.leaveNode (/Users/wolf/dev/crossmip/node_modules/eslint/lib/linter/node-event-generator.js:308:14)
```

**Steps to reproduce this issue:**

1. Use the minimal configuration given above
1. Run ESLint on a *.ts* file containing only `var`

**Are you willing to submit a pull request to fix this bug?**

Yes, the fix should be trivial.

**Comment by DanielSWolf** [comment]
It appears that the fix is indeed a one-liner and I'd be happy to create a pull request. However, I'm not sure how to write a unit test that uses `@typescript-eslint/parser`. Or should I just fix the code without adding a new unit test?

**Comment by DanielSWolf** [comment]
Hi @mdjermanovic, thanks for your explanation!

I did create [an issue with `typescript-eslint/parser`](https://github.com/typescript-eslint/typescript-eslint/issues/3326). However, it turns out that they've [been aware of the problem](https://github.com/typescript-eslint/typescript-eslint/issues/1852) for more than a year now, and it doesn't look as if a fix was imminent.

Is there any chance of fixing this in this repo? The fix would be as trivial as adding `node.declarations.length > 0 &&` to a single condition.

**Comment by KillyMXI** [comment]
This is very annoying.
And it seems `typescript-eslint` team has a lot to do before being able to resolve it properly...

"Eslint: Quiet" setting in VScode doesn't seem to silence these notifications.

**Comment by DanielSWolf** [comment]
@mdjermanovic If I created a PR that only added `node.declarations.length > 0 &&` to a single condition, would there be any chance of getting it merged?

All other ESLint rules that we use work fine with the output of `typescript-eslint/parser`. This is the only one that causes problems, and this simple change would make our coding experience so much better!

**Comment by mdjermanovic** [comment]
I'm really not in favor of adding these checks as there could be a lot of places where various rules can crash with a broken AST.

Can you try with the [IgnoredNodes](https://eslint.org/docs/rules/indent#ignorednodes) option?

I just tried with the following configuration:

```json
{
    "parser": "@typescript-eslint/parser",
    "rules": {
        "indent": ["error", 4, { "ignoredNodes": ["VariableDeclaration[declarations.length=0]"] }]
    }
}
```

test code:

```js
  var 
  var x;
```

It correctly reports wrong indentation on the `var x` line, but ignores the `var`-only line and doesn't throw errors.

**Comment by DanielSWolf** [comment]
Wow, that's brilliant! I did a quick test, and it appears to be working great.

Thank you very much!
