### ISSUE TITLE
fatal error if $HOME is not set

### ISSUE THREAD

**Issue by zba** [eslint/eslint#1465]
Here is requered user home to be set.
https://github.com/eslint/eslint/blob/83154840562f5da6d0ed6f0a247573f354ab3380/lib/config.js#L29

If I run eslint commandline without $HOME (case of building package, or via  git-shell) it cause error:

    path.js:360
        throw new TypeError('Arguments to path.join must be strings');
              ^
    TypeError: Arguments to path.join must be strings
        at path.js:360:15
        at Array.filter (native)
        at Object.exports.join (path.js:358:36)
        at Object.<anonymous> (node_modules/eslint/lib/config.js:29:33)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)

Even if I set `-c` option.

 I think it is wrong, it should be checked some way.

**Comment by sindresorhus** [comment]
> Seems like maybe an issue with user-home returning null. @sindresorhus is that expected?

Unfortunately yes. On some systems/envs the $HOME env var isn't set.

It's a shame Node don't provide us with a less fragile way to get it. (https://github.com/libuv/libuv/issues/11)

**Comment by nzakas** [comment]
Working on this.
