### ISSUE TITLE
template-curly-spacing error when use template-curly in 'import(`${xxx}`)'

### ISSUE THREAD

**Issue by rencoo** [eslint/eslint#14861]
**Tell us about your environment**

* **ESLint Version: v7.26.0**
* **Node Version: v12.20.0**
* **npm Version: 6.14.8**
* **Operating System:** 

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  root: true,
  parser: 'vue-eslint-parser',
  parserOptions: {
    parser: 'babel-eslint',
    ecmaVersion: 12,
    sourceType: 'module'
  },
  env: {
    browser: true,
    es2021: true,
    commonjs: true,
    node: true
  },
  plugins: [
    'html',
    'vue'
  ],
  globals: {
    global: true,
    wx: true,
    $: true,
    Vue: true,
    process: true,
    __dirname: true
  },
  settings: {
    'html/html-extensions': ['.html', '.hb']
  },
  extends: ['eslint:recommended', 'standard', 'plugin:vue/essential'],
  rules: {
    'constructor-super': 'error',
    'for-direction': 'error',
    'getter-return': 'error',
    'no-async-promise-executor': 'error',
    'no-case-declarations': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': 'error',
    'no-const-assign': 'error',
    'no-constant-condition': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    'no-dupe-args': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-else-if': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty': 'error',
    'no-empty-character-class': 'error',
    'no-empty-pattern': 'error',
    'no-ex-assign': 'error',
    'no-extra-boolean-cast': 'error',
    'no-extra-semi': 'error',
    'no-fallthrough': 'error',
    'no-func-assign': 'error',
    'no-global-assign': 'error',
    'no-import-assign': 'error',
    'no-inner-declarations': 'error',
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-misleading-character-class': 'error',
    'no-mixed-spaces-and-tabs': 'error',
    'no-new-symbol': 'error',
    'no-obj-calls': 'error',
    'no-octal': 'error',
    'no-prototype-builtins': 'error',
    'no-redeclare': 'error',
    'no-regex-spaces': 'error',
    'no-self-assign': 'error',
    'no-setter-return': 'error',
    'no-shadow-restricted-names': 'error',
    'no-sparse-arrays': 'error',
    'no-this-before-super': 'error',
    'no-undef': 'error',
    'no-unexpected-multiline': 'error',
    'no-unreachable': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'no-unused-labels': 'error',
    'no-unused-vars': 'error',
    'no-useless-catch': 'error',
    'no-useless-escape': 'error',
    'no-with': 'error',
    'require-yield': 'error',
    'use-isnan': 'error',
    'valid-typeof': 'error'
  }
};

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
// template-curly-spacing-test.js
const loadComponent = (name, component) => {
  return () => import(`./views/${name}/${component}.vue`);
};
```

```bash
npx eslint src/template-curly-spacing-test.js
```

**What did you expect to happen?**
eslint not throw error

**What actually happened? Please copy-paste the actual, raw output from ESLint.**
```bash
TypeError: Cannot read property 'value' of null
Occurred while linting /Users/zhouhang/rencoo/www/demos/eslint-project/src/template-curly-spacing-test.js:2
    at checkSpacingBefore (/Users/zhouhang/rencoo/www/demos/eslint-project/node_modules/eslint/lib/rules/template-curly-spacing.js:53:24)
    at TemplateElement (/Users/zhouhang/rencoo/www/demos/eslint-project/node_modules/eslint/lib/rules/template-curly-spacing.js:137:17)
    at /Users/zhouhang/rencoo/www/demos/eslint-project/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/zhouhang/rencoo/www/demos/eslint-project/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/zhouhang/rencoo/www/demos/eslint-project/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/Users/zhouhang/rencoo/www/demos/eslint-project/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (/Users/zhouhang/rencoo/www/demos/eslint-project/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (/Users/zhouhang/rencoo/www/demos/eslint-project/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /Users/zhouhang/rencoo/www/demos/eslint-project/node_modules/eslint/lib/linter/linter.js:960:32
```

**Steps to reproduce this issue:**

1.  install eslint related devDependencies
2.  eslint the specify file use template-curly
3.  watch the eslint output

**Below is my devDependencies for reproduce this case**
```json
{
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^4.28.1",
    "@typescript-eslint/parser": "^4.28.1",
    "@vue/eslint-config-typescript": "^7.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^7.31.0",
    "eslint-config-standard": "^15.0.1",
    "eslint-plugin-html": "^6.1.1",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.1.0",
    "eslint-plugin-vue": "^7.1.0",
    "husky": "^6.0.0",
    "typescript": "^4.3.3"
  }
}
```

**Are you willing to submit a pull request to fix this bug?**
it depends

**Comment by mdjermanovic** [comment]
Hi @rencoo, thanks for the issue!

This is a known bug in `babel-eslint`, please try with the latest version of [@babel/eslint-parser](https://www.npmjs.com/package/@babel/eslint-parser).

(`babel-eslint` is now `@babel/eslint-parser`)
