### ISSUE TITLE
ES6/JSX Template Strings Crash ESLint

### ISSUE THREAD

**Issue by iammerrick** [eslint/eslint#1489]
A file with the source:

```javascript
var example = `I am a template string!`;
```

Will produce the follow stack trace:

```
/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:412
                current = candidates.length;
                                    ^
TypeError: Cannot read property 'length' of undefined
    at Controller.traverse (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:412:37)
    at Object.traverse (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:557:27)
    at Object.analyze (/usr/local/lib/node_modules/eslint/node_modules/escope/escope.js:854:20)
    at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/eslint/lib/eslint.js:599:36)
    at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:131:27)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:226:30
    at walk (/usr/local/lib/node_modules/eslint/lib/util/traverse.js:77:9)
    at /usr/local/lib/node_modules/eslint/lib/util/traverse.js:97:9
    at Array.forEach (native)
    at traverse (/usr/local/lib/node_modules/eslint/lib/util/traverse.js:96:11)
```

It is looking up a visitor for TemplateLiteral, which simply doesn't exist.

**Comment by nzakas** [comment]
This was fixed with #1706.
