### ISSUE TITLE
eslint@es6jsx crashes on consistent-return with arrow operator

### ISSUE THREAD

**Issue by tcoopman** [eslint/eslint#1493]
this code:

``` js
var x = () => {
  return {};
};
```

crashes:

```
node_modules\eslint\lib\rules\consistent-return.js:42
                returnTypeDefined = "type" in returnInfo;
                                              ^
TypeError: Cannot use 'in' operator to search for 'type' in undefined
    at EventEmitter.ReturnStatement (c:\Workspace\rio-inspecties\node_modules\eslint\lib\rules\consistent-return.js:42:47)
    at EventEmitter.emit (events.js:117:20)
    at Controller.controller.traverse.enter (c:\Workspace\rio-inspecties\node_modules\eslint\lib\eslint.js:679:25)
    at Controller.__execute (c:\Workspace\rio-inspecties\node_modules\eslint\node_modules\estraverse\estraverse.js:318:31)
    at Controller.traverse (c:\Workspace\rio-inspecties\node_modules\eslint\node_modules\estraverse\estraverse.js:394:28)
    at EventEmitter.module.exports.api.verify (c:\Workspace\rio-inspecties\node_modules\eslint\lib\eslint.js:652:24)
    at processFile (c:\Workspace\rio-inspecties\node_modules\eslint\lib\cli-engine.js:131:27)
    at c:\Workspace\rio-inspecties\node_modules\eslint\lib\cli-engine.js:226:30
    at walk (c:\Workspace\rio-inspecties\node_modules\eslint\lib\util\traverse.js:77:9)
    at c:\Workspace\rio-inspecties\node_modules\eslint\lib\util\traverse.js:97:9
```

while this succeeds:

``` js
var x = function() {
  return {};
};
```

I have ecmascript = 6. in settings

**Comment by sam-github** [comment]
Has anyone seen this on something other than an arrow function? Because I'm getting on a recent eslint update, and am trying to track down why (and it's pure node javascript, no es6 features).

**Comment by nzakas** [comment]
@sam-github can you open a new issue? If it's not related to arrow functions, then it's a new issue.
