### ISSUE TITLE
Bug: TypeError with a dynamic import

### ISSUE THREAD

**Issue by maicol07** [eslint/eslint#15114]
### Environment

Node version: v16.10.0
npm version: v7.24.1
Local ESLint version: v7.32.0 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.22463

### What parser are you using?

@babel/eslint-parser

### What did you do?

<details>
<summary>Configuration</summary>

```
{
    "extends": [
        "@openstamanager"
    ],
    "parserOptions": {
        "requireConfigFile": false
    }
}

```
> Note: `@openstamanager` is a custom config available [here](https://github.com/maicol07/eslint-config-openstamanager)
</details>

```js
import(`./Views/${name}.jsx`);
```

### What did you expect to happen?

Linting works

### What actually happened?

Error:
```
PS C:\Users\Maicol\Documents\Projects\Web\osm_rewrite> eslint resources/js/app.js

Oops! Something went wrong! :(

ESLint: 7.32.0

TypeError: Cannot read properties of null (reading 'value')
Occurred while linting C:\Users\Maicol\Documents\Projects\Web\osm_rewrite\resources\js\app.js:27
    at checkSpacingBefore (C:\Users\Maicol\Documents\Projects\Web\osm_rewrite\node_modules\.pnpm\eslint@7.32.0\node_modules\eslint\lib\rules\template-curly-spacing.js:52:24)
    at TemplateElement (C:\Users\Maicol\Documents\Projects\Web\osm_rewrite\node_modules\.pnpm\eslint@7.32.0\node_modules\eslint\lib\rules\template-curly-spacing.js:136:17)
    at C:\Users\Maicol\Documents\Projects\Web\osm_rewrite\node_modules\.pnpm\eslint@7.32.0\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Users\Maicol\Documents\Projects\Web\osm_rewrite\node_modules\.pnpm\eslint@7.32.0\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Users\Maicol\Documents\Projects\Web\osm_rewrite\node_modules\.pnpm\eslint@7.32.0\node_modules\eslint\lib\linter\node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (C:\Users\Maicol\Documents\Projects\Web\osm_rewrite\node_modules\.pnpm\eslint@7.32.0\node_modules\eslint\lib\linter\node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (C:\Users\Maicol\Documents\Projects\Web\osm_rewrite\node_modules\.pnpm\eslint@7.32.0\node_modules\eslint\lib\linter\node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (C:\Users\Maicol\Documents\Projects\Web\osm_rewrite\node_modules\.pnpm\eslint@7.32.0\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:711:23)
    at C:\Users\Maicol\Documents\Projects\Web\osm_rewrite\node_modules\.pnpm\eslint@7.32.0\node_modules\eslint\lib\linter\linter.js:960:32
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Note that the issue is related to an ESLint rule

**Comment by mdjermanovic** [comment]
Hi @maicol07, thanks for the issue!

> Note that the issue is related to an ESLint rule

This error is observable in `template-curly-spacing` and `indent` rules, but it's actually a bug in `@babel/eslint-parser` or one of its dependencies. The bug was fixed a long time ago but still appears for some users, even with newer versions of `@babel/eslint-parser`. I suspect that some of package.json `dependencies` between babel packages haven't been updated to leave non-fixed versions out of range and therefore don't enforce installing the fixed version.

Can you try to install the latest version of `@babel/eslint-parser`? If this error still occurs, can you please open an issue in [babel/babel](https://github.com/babel/babel) repository?

**Comment by maicol07** [comment]
Maybe it's because of [https://github.com/gajus/eslint-plugin-flowtype](https://github.com/gajus/eslint-plugin-flowtype) since they use the old `babel-eslint`. However, they have a PR open to migrate to the new eslint parser: gajus/eslint-plugin-flowtype#479

**Comment by mdjermanovic** [comment]
> Maybe it's because of https://github.com/gajus/eslint-plugin-flowtype since they use the old `babel-eslint`. However, they have a PR open to migrate to the new eslint parser: [gajus/eslint-plugin-flowtype#479](https://github.com/gajus/eslint-plugin-flowtype/pull/479)

It's possible. I didn't check the configs since you mentioned `@babel/eslint-parser`. If your configuration uses `babel-eslint`, then that's the most likely cause, and the error should be fixed by upgrading to the latest `@babel/eslint-parser`.
