### ISSUE TITLE
After Upgrade Eslint 8.0.0

### ISSUE THREAD

**Issue by miladezzat** [eslint/eslint#15148]
### Environment

Environment Info:

Node version: v14.17.6
npm version: v8.0.0
Local ESLint version: v8.0.0 (Currently used)
Global ESLint version: v8.0.0
Operating System: linux 5.13.19-200.fc34.x86_64

```bash
Oops! Something went wrong! :(

ESLint: 8.0.0

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/util/glob-util' is not defined by "exports" in /home/milad/Desktop/sakneen/sakneen-api/node_modules/eslint/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:299:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:522:3)
    at resolveExports (internal/modules/cjs/loader.js:449:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:489:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (/home/milad/Desktop/sakneen/sakneen-api/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/milad/Desktop/sakneen/sakneen-api/node_modules/eslint-plugin-import/lib/rules/no-unused-modules.js:43:34)
    at Module._compile (/home/milad/Desktop/sakneen/sakneen-api/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)

```

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
<!-- Paste your configuration here -->
```
</details>

```js
<!-- Paste your code here -->
```

### What did you expect to happen?

no

### What actually happened?

Oops! Something went wrong! :(

ESLint: 8.0.0

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/util/glob-util' is not defined by "exports" in /home/milad/Desktop/sakneen/sakneen-api/node_modules/eslint/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:299:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:522:3)
    at resolveExports (internal/modules/cjs/loader.js:449:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:489:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (/home/milad/Desktop/sakneen/sakneen-api/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/milad/Desktop/sakneen/sakneen-api/node_modules/eslint-plugin-import/lib/rules/no-unused-modules.js:43:34)
    at Module._compile (/home/milad/Desktop/sakneen/sakneen-api/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ljharb** [comment]
If you’d used npm 7+ to install it, it would have warned you that eslint 8 and eslint-plugin-import aren’t compatible yet.

**Comment by aurelien-reeves** [comment]
We encounter the same issue with @cucumber/cucumber-expressions: https://github.com/cucumber/cucumber-expressions/pull/29

@ljharb what do you mean? I cannot find any warning in the GHA logs. I have tried myself to install eslint using npm 7 and 8 and showed no warning of any kind. 

```console
$ npm --version
8.0.0

$ npm i -D eslint

added 77 packages, and audited 172 packages in 1s

17 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by miladezzat** [comment]
This occurred with airbnb
```js
    "eslint": "^8.0.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-plugin-import": "^2.24.2",
```
@aurelien-reeves

**Comment by kimbaudi** [comment]
I'm getting the same error message as the OP and a bunch of warnings after upgrading to eslint 8. 

```
warning " > eslint-config-airbnb@18.2.1" has incorrect peer dependency "eslint@^5.16.0 || ^6.8.0 || ^7.2.0".
warning "eslint-config-airbnb > eslint-config-airbnb-base@14.2.1" has incorrect peer dependency "eslint@^5.16.0 || ^6.8.0 || ^7.2.0".
warning " > eslint-config-airbnb-typescript@14.0.1" has incorrect peer dependency "@typescript-eslint/eslint-plugin@^4.29.3".
warning " > eslint-config-airbnb-typescript@14.0.1" has incorrect peer dependency "@typescript-eslint/parser@^4.29.3".
warning " > eslint-plugin-import@2.24.2" has incorrect peer dependency "eslint@^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0".
warning " > eslint-plugin-jsx-a11y@6.4.1" has incorrect peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7".
warning " > eslint-plugin-react@7.26.1" has incorrect peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7".
warning " > eslint-plugin-react-hooks@4.2.0" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0".
```

I guess I need to wait for all these packages to support eslint 8 before I can upgrade.

**Comment by ljharb** [comment]
Yep, every time anything that has a plugin system bumps a major (eslint, babel, typescript, react, etc), you always have to wait until the plugin ecosystem catches up.

That's just part of the tradeoffs that must be made when one combines "a plugin system" with "breaking changes".
