### ISSUE TITLE
Bug: TypeError: Module.createRequire is not a function

### ISSUE THREAD

**Issue by justinTM** [eslint/eslint#15211]
### Environment

Node version: 10.13
npm version: 6.4.1
Local ESLint version: 8.1.0
Global ESLint version: 8.1.0
Operating System: ubuntu docker image 

### What parser are you using?

Default (Espree)

### What did you do?

![image](https://user-images.githubusercontent.com/9123665/138793835-a39b7fba-9b54-43f5-95f5-3ce7c059a394.png)

```console
npm install eslint
node_modules/.bin/eslint
```

### What did you expect to happen?

Get the linting results, or nothing

### What actually happened?

```console
root@f9b800f6f3d3:/usr/local/src/---------# ./node_modules/.bin/eslint --version

Oops! Something went wrong! :(

ESLint: 8.1.0

TypeError: Module.createRequire is not a function
    at Object.<anonymous> (/usr/local/src/---------/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2359:26)
    at Module._compile (/usr/local/src/---------/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (/usr/local/src/---------/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/usr/local/src/---------/node_modules/eslint/lib/cli-engine/cli-engine.js:33:5)
    at Module._compile (/usr/local/src/---------/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
```

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by OladapoAjala** [comment]
Had this issue while I used fnm as my node version manager. Switching to nvm fixed it for me.
