### ISSUE TITLE
Bug: UnhandledPromiseRejectionWarning in version 8.2.0

### ISSUE THREAD

**Issue by fabgrel10** [eslint/eslint#15269]
### Environment

Node version: 16.3.0
npm version: 8.1.2
Local ESLint version: 8.2.0
Global ESLint version: 
Operating System: KDE Neon User Edition

Using ESLint via VS Code extension (along with prettier)

[eslintrc.zip](https://github.com/eslint/eslint/files/7491718/eslintrc.zip)

### What parser are you using?

@typescript-eslint/parser

### What did you do?

ESLint server is not able to run in VS Code when using v8.2.0 due to a UnhandledPromiseRejectionWarning. Problem is solved by downgrading to version 7^

<summary>Configuration</summary>
<details>

```json
{
  "root": true,
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 2021,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "settings": {
    "react": {
      "version": "detect"
    }
  },
  "env": {
    "browser": true,
    "amd": true,
    "node": true
  },
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:jsx-a11y/recommended",
    "plugin:react-hooks/recommended",
    "prettier"
  ],
  "plugins": [
    "prettier",
    "react",
    "jsx-a11y"
  ],
  "rules": {
    "prettier/prettier": [
      "error",
      {
        "singleQuote": true,
        "arrowParens": "avoid",
        "printWidth": 80,
        "trailingComma": "none"
      },
      {
        "usePrettierrc": true
      }
    ],
    "@typescript-eslint/explicit-function-return-type": "off",
    "no-unused-vars": 1,
    "jsx-a11y/accessible-emoji": 1,
    "react/react-in-jsx-scope": 1,
    "react/prop-types": "off",
    "jsx-a11y/anchor-is-valid": [
      "error",
      {
        "components": [
          "Link"
        ],
        "specialLink": [
          "hrefLeft",
          "hrefRight"
        ],
        "aspects": [
          "invalidHref",
          "preferButton"
        ]
      }
    ]
  }
}
```
</details>

```js

```

### What did you expect to happen?

```bash
[Info  - 22:29:59] ESLint server is starting
[Info  - 22:30:00] ESLint server running in node v14.16.0
[Info  - 22:30:00] ESLint server is running.
[Info  - 22:30:01] ESLint library loaded from: /home/fabricio/Proyectos/React/vite-react-eslint-prettier/node_modules/eslint/lib/api.js
```

### What actually happened?

```bash
[Info  - 22:27:43] ESLint server is starting
[Info  - 22:27:44] ESLint server running in node v14.16.0
[Info  - 22:27:44] ESLint server is running.
[Info  - 22:27:45] ESLint library loaded from: /home/fabricio/Proyectos/React/vite-react-eslint-prettier/node_modules/eslint/lib/api.js
(node:67409) UnhandledPromiseRejectionWarning: Error: Invalid Options:
- Unknown options: extensinons
    at processOptions (/home/fabricio/Proyectos/React/vite-react-eslint-prettier/node_modules/eslint/lib/eslint/eslint.js:288:15)
    at new ESLint (/home/fabricio/Proyectos/React/vite-react-eslint-prettier/node_modules/eslint/lib/eslint/eslint.js:435:34)
    at Object.e.newESLintClass (/home/fabricio/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:167243)
    at Ce (/home/fabricio/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:186299)
    at h.then.o.validate (/home/fabricio/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:177282)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `code --trace-warnings ...` to show where the warning was created)
(node:67409) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:67409) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:67409) UnhandledPromiseRejectionWarning: Error: Invalid Options:
- Unknown options: extensinons
    at processOptions (/home/fabricio/Proyectos/React/vite-react-eslint-prettier/node_modules/eslint/lib/eslint/eslint.js:288:15)
    at new ESLint (/home/fabricio/Proyectos/React/vite-react-eslint-prettier/node_modules/eslint/lib/eslint/eslint.js:435:34)
    at Object.e.newESLintClass (/home/fabricio/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:167243)
    at Ce (/home/fabricio/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:186299)
    at h.then.o.validate (/home/fabricio/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:177282)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:67409) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

ESLint server is not able to run in VS Code when using v8.2.0 due to a UnhandledPromiseRejectionWarning. **Problem is solved by downgrading to version 7^**

<summary>Configuration</summary>
<details>

```json

```
</details>

```js
<!-- Paste your code here -->
```

**Comment by ljharb** [comment]
The stack trace implies that the error is coming from the `vite-react-eslint-prettier` package.

**Comment by fabgrel10** [comment]
@ljharb I just used create-react-app to verify and got the same result.

**Comment by ljharb** [comment]
The same stack trace?

**Comment by mdjermanovic** [comment]
> ```shell
> (node:67409) UnhandledPromiseRejectionWarning: Error: Invalid Options:
> - Unknown options: extensinons
>     at processOptions (/home/fabricio/Proyectos/React/vite-react-eslint-prettier/node_modules/eslint/lib/eslint/eslint.js:288:15)
>     at new ESLint (/home/fabricio/Proyectos/React/vite-react-eslint-prettier/node_modules/eslint/lib/eslint/eslint.js:435:34)
>     at Object.e.newESLintClass (/home/fabricio/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:167243)
> ```

It seems that vscode-eslint calls eslint with an unknown option `extensinons`, which is most likely a typo. If it was meant to be `extensions`, then there's an extra "n".

This could be a problem in vscode-eslint itself, or in your configuration for vscode-eslint.

Can you check your VS Code settings, and see if you have `"extensinons"` key under `"eslint.options"`?

**Comment by fabgrel10** [comment]
@mdjermanovic you were right: it was a typo in the VS Code settings everything worked as expected after fixing it.

**Comment by mdjermanovic** [comment]
Closing, as the issue has been resolved.
