### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by avashavash** [eslint/eslint#15374]
Tell us about your environment

**Gulp-ESLint Version:**6.0.0
**Node Version:**17.1.0
**npm Version:**8.1.4

``` Running 'gulp.js ' in /Users/at552/Dev/clients/clientName/projects/aem/shop3/content/src/main/content/jcr_root
/Users/at552/Dev/clients/clientName/projects/aem/shop3/content/src/main/content/jcr_root/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/cli-engine.js:256
...calculateStatsPerFile(messages)
^^^
SyntaxError: Unexpected token ...
at Object.exports.runInThisContext (vm.js:76:16)
at Module._compile (module.js:542:28)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object. (/Users/at552/Dev/clients/clientName/projects/aem/shop3/content/src/main/content/jcr_root/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/index.js:3:23)
at Module._compile (module.js:570:32) ```

Somebody knows what could be the issue here?

**Comment by nzakas** [comment]
Please open a bug report and fill in all of the info. There is not enough info here to respond.
