### ISSUE TITLE
Bug: (Can't run npx eslint --init)

### ISSUE THREAD

**Issue by tati-simonenko** [eslint/eslint#15391]
### Environment

Node version: v10.15.3
npm version: 6.4.1
Local ESLint version: 8.4.0 
shows that it was installed https://loom.com/i/d22d5f9f45a64210bf023751f840c11c
but result of eslint -v is command not found https://www.loom.com/i/b07196e1751145cdaeaa4d03f4149b27
Operating System: macOS Catalina 10.15

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

I was going through this documentation: https://eslint.org/docs/user-guide/getting-started

I ran npm install eslint --save-dev
https://loom.com/i/2ad381d7fac64ffea01b5650668524cd

Then npx eslint --init
and git an error
https://loom.com/i/d7e363a8e08b4195864394340d3e0fd0

### What did you expect to happen?

I wanted to set up a configuration file

### What actually happened?

error

MacBook-Air-Tatyana:test-prettier tatyanasimonenko$ npx eslint --init

Oops! Something went wrong! :(

ESLint: 8.4.0

TypeError: Module.createRequire is not a function
    at Object.<anonymous> (/Users/tatyanasimonenko/Desktop/1/test-prettier/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2359:26)
    at Module._compile (/Users/tatyanasimonenko/Desktop/1/test-prettier/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/Users/tatyanasimonenko/Desktop/1/test-prettier/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/tatyanasimonenko/Desktop/1/test-prettier/node_modules/eslint/lib/init/config-initializer.js:26:9)
    at Module._compile (/Users/tatyanasimonenko/Desktop/1/test-prettier/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Configuration file was created
https://loom.com/i/6a1183e7c5fc45f0910f5a813305ba85

**Comment by aladdin-add** [comment]
hi, eslint v8 requires Node.js >= 12.220. please try to upgrade Node.js and retry.
