### ISSUE TITLE
0.11 alpha 0 issue: TypeError: Cannot read property 'loc' of undefined

### ISSUE THREAD

**Issue by MoOx** [eslint/eslint#1545]
```console
$ eslint test/*.js

/whatever/node_modules/eslint/lib/rules/no-multi-spaces.js:73
						left.loc.end.line === right.loc.start.line &&
								^
TypeError: Cannot read property 'loc' of undefined
		at validate (/whatever/node_modules/eslint/lib/rules/no-multi-spaces.js:73:17)
		at validateBetween (/whatever/node_modules/eslint/lib/rules/no-multi-spaces.js:95:9)
		at EventEmitter.<anonymous> (/whatever/node_modules/eslint/lib/rules/no-multi-spaces.js:150:17)
		at EventEmitter.emit (events.js:117:20)
		at Controller.controller.traverse.enter (/whatever/node_modules/eslint/lib/eslint.js:677:25)
		at Controller.__execute (/whatever/node_modules/eslint/node_modules/estraverse/estraverse.js:395:31)
		at Controller.traverse (/whatever/node_modules/eslint/node_modules/estraverse/estraverse.js:493:28)
		at EventEmitter.module.exports.api.verify (/whatever/node_modules/eslint/lib/eslint.js:650:24)
		at processFile (/whatever/node_modules/eslint/lib/cli-engine.js:134:27)
		at /whatever/node_modules/eslint/lib/cli-engine.js:230:26
```

The same stupid files works with eslint@0.10.

**Comment by qorbani** [comment]
I had same issue and fixed it by replacing with RegEx. After re-run I get couple of validation errors from "comma-spacing" rule for following code:
```js
.pipe(replace, /<!-- \/?PROD(.)*?>/g, '')
```

Errors:
```
  31:31  error  A space is required after ','        comma-spacing
  31:31  error  There should be no space before ','  comma-spacing
```

**Comment by nzakas** [comment]
Fixed on master branch.
