### ISSUE TITLE
Bug: (Error running eslint init)

### ISSUE THREAD

**Issue by cek333** [eslint/eslint#15512]
### Environment

Node version: v14.17.3
npm version: 6.14.8
Local ESLint version: installed by `eslint --init`
Global ESLint version: Installed via `npm -g`? None
Operating System: Win 10

### What parser are you using?

Other

### What did you do?

<details>
First I created a new project:

`npm init -y`

Then I installed eslint:

`npm install --save-dev eslint`

Then setup eslint:

`npx eslint --init`

<summary>Configuration</summary>

```
√ How would you like to use ESLint? · style
√ What type of modules does your project use? · esm
√ Which framework does your project use? · react
√ Does your project use TypeScript? · No
√ Where does your code run? · browser
√ How would you like to define a style for your project? · guide
√ Which style guide do you want to follow? · standard
√ What format do you want your config file to be in? · JavaScript
Checking peerDependencies of eslint-config-standard@latest
The config that you've selected requires the following dependencies:

eslint-plugin-react@latest eslint-config-standard@latest eslint@^7.12.1 eslint-plugin-import@^2.22.1 eslint-plugin-node@^11.1.0 eslint-plugin-promise@^4.2.1 || ^5.0.0
√ Would you like to install them now with npm? · Yes
Installing eslint-plugin-react@latest, eslint-config-standard@latest, eslint@^7.12.1, eslint-plugin-import@^2.22.1, eslint-plugin-node@^11.1.0, eslint-plugin-promise@^4.2.1 || ^5.0.0
npm WARN eslint_config@1.0.0 No description
npm WARN eslint_config@1.0.0 No repository field.

+ eslint-config-standard@16.0.3
+ eslint-plugin-promise@5.2.0
+ eslint-plugin-node@11.1.0
+ eslint-plugin-react@7.28.0
+ eslint-plugin-import@2.25.4
+ eslint@7.32.0
added 108 packages from 49 contributors, updated 18 packages and audited 196 packages in 23.462s

45 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


Oops! Something went wrong! :(

ESLint: 8.6.0

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/util/glob-util' is not defined by "exports" in S:\VS2017\Bootcamp\HOMEWORK\TUTORIALS\DELETE_React_NoBuild\eslint_config\node_modules\eslint\package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:508:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (S:\VS2017\Bootcamp\HOMEWORK\TUTORIALS\DELETE_React_NoBuild\eslint_config\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (S:\VS2017\Bootcamp\HOMEWORK\TUTORIALS\DELETE_React_NoBuild\eslint_config\node_modules\eslint-plugin-import\lib\rules\no-unused-modules.js:40:7)
    at Module._compile (S:\VS2017\Bootcamp\HOMEWORK\TUTORIALS\DELETE_React_NoBuild\eslint_config\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
```
</details>

```js
No code yet. Empty project.
```

### What did you expect to happen?

Complete without error.

### What actually happened?

```
Oops! Something went wrong! :(

ESLint: 8.6.0

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/util/glob-util' is not defined by "exports" in S:\VS2017\Bootcamp\HOMEWORK\TUTORIALS\DELETE_React_NoBuild\eslint_config\node_modules\eslint\package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:508:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (S:\VS2017\Bootcamp\HOMEWORK\TUTORIALS\DELETE_React_NoBuild\eslint_config\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (S:\VS2017\Bootcamp\HOMEWORK\TUTORIALS\DELETE_React_NoBuild\eslint_config\node_modules\eslint-plugin-import\lib\rules\no-unused-modules.js:40:7)
    at Module._compile (S:\VS2017\Bootcamp\HOMEWORK\TUTORIALS\DELETE_React_NoBuild\eslint_config\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
```

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

I'm also confused by the `ESLint: 8.6.0` in the on-screen message. The `package.json` shows a different eslint version:
```
{
  "name": "eslint_config",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "eslint": "^7.32.0",
    "eslint-config-standard": "^16.0.3",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^5.2.0",
    "eslint-plugin-react": "^7.28.0"
  }
}
```

**Comment by aladdin-add** [comment]
it should have been fixed in the `@eslint/create-config`. can you try `npm init @eslint/config`?

**Comment by cek333** [comment]
Yes, that works. This time, during the setup, I'm prompted to downgrade eslint. Here's the full output:
```
$ npm init @eslint/config
npx: installed 40 in 13.681s
√ How would you like to use ESLint? · style
√ What type of modules does your project use? · esm
√ Which framework does your project use? · react
√ Does your project use TypeScript? · No
√ Where does your code run? · browser
√ How would you like to define a style for your project? · guide
√ Which style guide do you want to follow? · standard
√ What format do you want your config file to be in? · JavaScript
Checking peerDependencies of eslint-config-standard@latest
√ The style guide "standard" requires eslint@^7.12.1. You are currently using eslint@8.6.0.
  Do you want to downgrade? · Yes
The config that you've selected requires the following dependencies:

eslint-plugin-react@latest eslint-config-standard@latest eslint@^7.12.1 eslint-plugin-import@^2.22.1 eslint-plugin-node@^11.1.0 eslint-plugin-promise@^4.2.1 || ^5.0.0
√ Would you like to install them now with npm? · Yes
Installing eslint-plugin-react@latest, eslint-config-standard@latest, eslint@^7.12.1, eslint-plugin-import@^2.22.1, eslint-plugin-node@^11.1.0, eslint-plugin-promise@^4.2.1 || ^5.0.0
npm WARN eslint_config@1.0.0 No description
npm WARN eslint_config@1.0.0 No repository field.

+ eslint@7.32.0
+ eslint-plugin-promise@5.2.0
+ eslint-plugin-node@11.1.0
+ eslint-plugin-import@2.25.4
+ eslint-plugin-react@7.28.0
+ eslint-config-standard@16.0.3
added 108 packages from 49 contributors, updated 18 packages and audited 196 packages in 20.511s

45 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Successfully created .eslintrc.js file in S:\VS2017\Bootcamp\HOMEWORK\TUTORIALS\DELETE_React_NoBuild\eslint_config
```
Let me know if there is anything I can do to help resolve the discrepancy between `npx eslint --init` and `npm init @eslint/config`.

**Comment by cek333** [comment]
Oh, I just saw [the pull request #15150](https://github.com/eslint/eslint/pull/15150). It seems `npm init @eslint/config` is intended to be the new method of doing the setup. Is that correct?

**Comment by aladdin-add** [comment]
yes, it's just merged but not released yet.
