### ISSUE TITLE
Change Request: Migrate the ESLint repository to ESM

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#15560]
### ESLint version

v8.8.0

### What problem do you want to solve?

Currently, the ESLint codebase uses CommonJS `require()`s.

### What do you think is the correct solution?

We'd like to migrate the repository to use ES Modules.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

We added this to the roadmap in the 2022-01-27 TSC meeting.

**Comment by aladdin-add** [comment]
I'm willing to take this one. ;) There are mainly 2 ways to publish esm:

1. esm only
2. dual mode (esm and cjs)

From a maintainer's perspective, I slightly prefer the esm-only way:
* No need to build, less maintenance costs
* Dependencies. some eslint dependencies were published esm only.(e.g. `chalk`), means we cannot upgrade to latest versions if choose dual mode (esm cannot be required).

surely, I'm totally open to dual mode if the community has a heavy need for cjs. let me know what you think!

**Comment by 3x071c** [comment]
This sounds great! Trying to move a project to ESM while dependencies such as eslint are still using `require` is a real mess, which is kind of ironic considering esm is supposed to consolidate all other module formats...

**Comment by btmills** [comment]
At least as of RFC72 a year ago, we chose to go dual-mode with a CJS build step for `espree`. My anecdotal impression is that the community hasn't shifted significantly enough to warrant a change to ESM-only quite yet. I'd welcome any data to the contrary that allows us to go with the simpler ESM-only approach.

**Comment by aladdin-add** [comment]
Given eslint v8 has dropped Node.js < v12(and will likely drop <14 in v9), I hope it won't be a too substantial change. Technically it's allowed to import cjs modules in esm, so the plugins/configs do not have to be esm. I'll put an RFC to explore compatibility.

**Comment by ljharb** [comment]
Please do not go ESM-only; that will be a huge burden on the ecosystem. As a maintainer of the most popular shared config and three of the most used plugins, I can't guarantee it will be feasible to maintain any of them with eslint being ESM-only. To be quite frank, it would be an unmitigated disaster.

Literally the only advantage to going ESM-only I'm aware of is top-level await, and the only part of a program that would truly ever need that is a CLI entry point.

If it helps, pick literally any sindre module that's migrated to ESM-only, and click the "versions" tab on its npm package page. You'll see - even on the packages that made the switch over a year ago - that virtually nobody is using the ESM-only versions. That's because they, or their intermediary dependents, *can't upgrade* to it.

**Comment by aladdin-add** [comment]
Is there anything blocking converting eslint configs/plugins to esm? Or it will  just take a bit longer?

As more packages are going to be esm-only(i.e. babel https://github.com/babel/babel/issues/11701#issuecomment-777118858), I was concerned that we won't be able to upgrade them. An alternative is to take a dual-mode in eslint v9, and esm-only in eslint v10 - to give users a longer time to do the converting.

**Comment by mdjermanovic** [comment]
ESM-only package can be a big change for dependents because ESM modules cannot be imported synchronously from CJS modules.

As for configs and plugins, I'm not sure why this change would affect them. @ljharb can you clarify that?

**Comment by 3x071c** [comment]
The way I see it, esm-only would allow cjs imports, but the current approach doesn’t work the other way around (cjs can’t  require an es6 module). I see a move to esm-only as a win-win for all users, especially as the ecosystem is slowly moving towards es6 modules in favor of commonjs, because it looks nicer and is standardized.

**Comment by ljharb** [comment]
@mdjermanovic anything that is currently required - even the “use at your own risk stuff” which many plugins still depend on - is my concern. I could certainly go through and audit, and I’m sure there’s a subset of files that could go ESM-only safely, but what is the benefit?

@3x071c the ecosystem is not actually moving towards ESM-only - if you subtract out a single package author, it’s essentially not moving at all. One author does not the ecosystem make.

**Comment by siric** [comment]
I believe the main reason why the ecosystem hasn't fully moved to esm yet is because JS tooling hasn't allowed them to do so. Once ESLint and Babel add support for esm, I reckon a lot of us will switch in a heartbeat.

**Comment by aladdin-add** [comment]
To clarify, eslint has supported esm for a long while(`parserOptions.sourceType: "module"`). The point here: esm-only eslint is moving the eslint community (plugins/configs/parsers/...) to esm(at least provide an esm entry).

**Comment by ljharb** [comment]
@coderaiser ok, so 4 authors? Still not even a blip in terms of the number of authors, and only one of those authors is a significant percentage of packages or usage.

node-native ESM can’t work in browsers at all if it uses the filesystem (ie, most of eslint), as well as anything using a bare specifier can’t work without the still non-standard import maps; and anything using node’s core modules (including fs stuff) likely can’t work without a build process in deno. Painting ESM as some kind of universal portable standard simply isn’t accurate.

**Comment by JounQin** [comment]
@dreyks You can try something like https://github.com/rx-ts/synckit. [eslint-mdx](https://github.com/mdx-js/eslint-mdx/blob/master/packages/eslint-mdx/src/worker.ts#L12) is using it perfectly now.

**Comment by dreyks** [comment]
thx for the responses!

**Comment by ImanMahmoudinasab** [comment]
Hi everyone. I'm wondering what is the last state of this migration. 
In our case, we have updated our webpack config to EMS (webpack.mjs)  and then I tried to use `eslint-plugin-import` and pass the webpack config for path resolving. And finally, I found out that eslint is only running in common js and I can't have esm webpack config.

**Comment by JounQin** [comment]
commonjs is fine to be imported in ESM, what is the actual issue?

**Comment by ImanMahmoudinasab** [comment]
@JounQin Thanks for the reply. The issue is the eslint is only published as commonjs and when IDE's like vs code or Jetbrians finds the executable of eslint in the node packages and run it, it always will be run as commonjs and all imported packages have to be commonjs. This is my understanding from the error message thrown by eslint server (on both IDEs):
```
[Info  - 12:40:36 PM] ESLint server is starting
[Info  - 12:40:36 PM] ESLint server running in node v16.13.2
[Info  - 12:40:36 PM] ESLint server is running.
[Info  - 12:40:36 PM] ESLint library loaded from: /Users/iman/Projects/a/node_modules/eslint/lib/api.js
[Info  - 12:40:36 PM] ESLint library loaded from: /Users/i/Proj/node_modules/eslint/lib/api.js
Error resolving webpackConfig Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/i/Proj/packages/src/config/webpack.prod.mjs not supported.
Instead change the require of /Users/i/Proj/packages/src/config/webpack.prod.mjs to a dynamic import() which is available in all CommonJS modules.
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Object.exports.resolve (/Users/i/Proj/node_modules/eslint-import-resolver-webpack/index.js:86:25)
    at v2 (/Users/i/Proj/node_modules/eslint-module-utils/resolve.js:116:23)
    at withResolver (/Users/i/Proj/node_modules/eslint-module-utils/resolve.js:121:14)
    at fullResolve (/Users/i/Proj/node_modules/eslint-module-utils/resolve.js:138:22)
    at relative (/Users/i/Proj/node_modules/eslint-module-utils/resolve.js:83:10)
    at resolve (/Users/i/Proj/node_modules/eslint-module-utils/resolve.js:219:12)
    at checkSourceValue (/Users/i/Proj/node_modules/eslint-plugin-import/lib/rules/no-unresolved.js:38:53)
    at checkSourceValue (/Users/i/Proj/node_modules/eslint-module-utils/moduleVisitor.js:29:5)
    at checkSource (/Users/i/Proj/node_modules/eslint-module-utils/moduleVisitor.js:34:5)
    at ruleErrorHandler (/Users/i/Proj/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /Users/i/Proj/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/i/Proj/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/i/Proj/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/Users/i/Proj/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/Users/i/Proj/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/Users/i/Proj/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
    at /Users/i/Proj/node_modules/eslint/lib/linter/linter.js:1149:32
    at Array.forEach (<anonymous>)
    at runRules (/Users/i/Proj/node_modules/eslint/lib/linter/linter.js:1144:15)
    at Linter._verifyWithoutProcessors (/Users/i/Proj/node_modules/eslint/lib/linter/linter.js:1393:31)
    at Linter._verifyWithConfigArray (/Users/i/Proj/node_modules/eslint/lib/linter/linter.js:1757:21)
    at Linter.verify (/Users/i/Proj/node_modules/eslint/lib/linter/linter.js:1475:65)
    at Linter.verifyAndFix (/Users/i/Proj/node_modules/eslint/lib/linter/linter.js:2004:29)
    at verifyText (/Users/i/Proj/node_modules/eslint/lib/cli-engine/cli-engine.js:245:48)
    at CLIEngine.executeOnText (/Users/i/Proj/node_modules/eslint/lib/cli-engine/cli-engine.js:917:26)
    at ESLint.lintText (/Users/i/Proj/node_modules/eslint/lib/eslint/eslint.js:592:23)
    at /Users/i/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:23205
    at E (/Users/i/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:18310)
    at Object.e.validate (/Users/i/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:23164)
    at /Users/i/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:210200 {
  code: 'ERR_REQUIRE_ESM'
}
```
And this is the config (`.eslintrc.js`)
```
const config = {
  env: {
    browser: true,
    node: true,
    jest: true,
    es6: true,
  },
  // some more configs ...
  settings: {
    'import/resolver': {
      node: { extensions: ['.js', '.mjs'] },
      webpack: {
        config: './packages/src/config/webpack.prod.mjs',
      },
    },
  },
};

module.exports = config;
```

**Comment by ljharb** [comment]
@ImanMahmoudinasab supporting that requires eslint to support async, via `import()` - it does NOT require any change of eslint itself to ESM.

**Comment by JounQin** [comment]
@ImanMahmoudinasab 

See also https://github.com/import-js/eslint-plugin-import/issues/2069#issuecomment-1189581492

You can contribute to integrate https://github.com/rx-ts/synckit as I mentioned above into `eslint-import-resolver-webpack`, so that it'll not be a blocked.

**Comment by giltayar** [comment]
> @coderaiser ok, so 4 authors? Still not even a blip in terms of the number of authors, and only one of those authors is a significant percentage of packages or usage.

Not exactly: on February, we were at 13.5% of high impact packages: https://twitter.com/wooorm/status/1622661060623835143. 

Progress towards ESM is proceeding nicely, and if I would hazard a guess, is going to accelerate as more packages join. This means that the problem of ESlint plugins needing to use ESM-only packages is only going to get worse as time progresses.

Yes, ESlint could continue to be CJS and add support for async plugins (which would solve the problem of using ESM-only packages in plugins), but that would anyway be a breaking change in that its entry points would need to be async _anway_. So as long as we're there (changing the entry points to be async), you can go full ESM and have any CJS code that needs to import ESLint just use `await import()`.

**Comment by ljharb** [comment]
@giltayar "high impact packages", i suspect, are disproportionatey represented by a small number of authors, myself included. I'd be much more interested in stats that show *publishers* rather than packages. I can make a package "high impact" simply by adding it to a high-impact package, so I don't think it's a meaningful metric.

**Comment by giltayar** [comment]
What would you think a better metric of the breadth of the migration would be?

**Comment by ljharb** [comment]
Publishers, though, are what determine which packages will be migrated or not. I realize it's a less marketable/buzzwordy metric, but it paints a much more accurate picture.

**Comment by michaelfaith** [comment]
Curious if this is still on the roadmap?

**Comment by magne4000** [comment]
It's currently pretty hard to correctly bundle `eslint` with `esbuild`, even if FlatConfig seems to help a little.
In it's current state tree-shaking the code when bundling is almost impossible, everything seems to be bundled at once (like `espree` even if I don't use it).
It uses `require.resolve`, which does not work with ESM and is impossible to tree-shake.
Also some packages, like `esquery`, are working well with CJS but not with ESM (probably an `esquery` issue though).

You can check the workaround I had to put in place to be able to bundle eslint https://github.com/batijs/bati/blob/92b3745621fe21483508b16908136861733945dc/packages/core/tsup.config.ts#L5

Migrating the codebase to ESM would virtually solve all those issues.

**Comment by ljharb** [comment]
It’s not possible to treeshake if it’s dynamic, which applies to ESM `import()` also - if it’s a hardcoded string, it’s identically possible to treeshake with both module systems.

**Comment by nzakas** [comment]
**TSC Summary:** This issue tracks converting the `eslint` repo to ESM. This was opened in 2022, and since then, we've decided to rewrite the core (in ESM) in a separate repo.

**TSC Question:** Do we still want to pursue converting the `eslint` repo to ESM?

**Comment by sam3k** [comment]
Per 2024-06-13 tsc-meeting decision, we are not going to go ahead with this request at the moment as we are planning on doing a full rewrite in ESM in the future. The cost/benefit of converting the ESLint repo to ESM doesn't seem justifiable at the moment.
