### ISSUE TITLE
Bug: this.cliEngineCtor is not a constructor

### ISSUE THREAD

**Issue by ksielyov** [eslint/eslint#15677]
### Environment

Node version: v14.17.5
npm version: v7.21.1
Local ESLint version: v8.10.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 21.1.0

### What parser are you using?

@typescript-eslint/parser

### What did you do?

1. yarn add eslint -D
2. npx eslint --init
3. It generates eslint config below:

```
{
    "env": {
        "browser": true,
        "es2021": true
    },
    "extends": [
        "plugin:react/recommended",
        "airbnb"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": "latest",
        "sourceType": "module"
    },
    "plugins": [
        "react",
        "@typescript-eslint"
    ],
    "rules": {
    }
}

```

### What did you expect to happen?

I expect working eslint configuration, without following error.

### What actually happened?

TypeError: this.cliEngineCtor is not a constructor

TypeError: this.cliEngineCtor is not a constructor
    at ESLintPlugin.invokeESLint (/Applications/WebStorm.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin.js:103:25)
    at ESLintPlugin.getErrors (/Applications/WebStorm.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin.js:82:21)
    at ESLintPlugin.onMessage (/Applications/WebStorm.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin.js:56:64)
    at Interface.<anonymous> (/Applications/WebStorm.app/Contents/plugins/JavaScriptLanguage/jsLanguageServicesImpl/js-language-service.js:105:39)
    at Interface.emit (events.js:400:28)
    at Interface._onLine (readline.js:364:10)
    at Interface._normalWrite (readline.js:509:12)
    at Socket.ondata (readline.js:216:10)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
Process finished with exit code -1

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

This error comes from WebStorm

**Comment by mdjermanovic** [comment]
Hi @ksielyov, thanks for the issue!

> TypeError: this.cliEngineCtor is not a constructor
> 
> TypeError: this.cliEngineCtor is not a constructor at ESLintPlugin.invokeESLint (/Applications/WebStorm.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin.js:103:25) at ESLintPlugin.getErrors (/Applications/WebStorm.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin.js:82:21) at ESLintPlugin.onMessage (/Applications/WebStorm.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin.js:56:64) at Interface. (/Applications/WebStorm.app/Contents/plugins/JavaScriptLanguage/jsLanguageServicesImpl/js-language-service.js:105:39)

Per  https://youtrack.jetbrains.com/issue/WEB-52236 the solution is to update WebStorm to at least [2021.2.2](https://blog.jetbrains.com/webstorm/2021/09/webstorm-2021-2-2/)
