### ISSUE TITLE
Bug: Invalid rangeEnd value. Expected an integer, but received "Infinity".

### ISSUE THREAD

**Issue by paymog** [eslint/eslint#15788]
### Environment

Node version: 14.19.1
npm version: 6.14.16
Local ESLint version: 4.19.1
Global ESLint version: NA
Operating System: MacOS 12.3.1

### What parser are you using?

@babel/eslint-parser

### What did you do?

I recently went through a very large upgrade of dependencies on a project and now eslint isn't working and is failing with the following error:

```
Error: Invalid rangeEnd value. Expected an integer, but received "Infinity".
    at _loop (/Users/paymahn/code/tripvector/tripvector/node_modules/prettier/index.js:8058:63)
    at Normalizer._applyNormalization (/Users/paymahn/code/tripvector/tripvector/node_modules/prettier/index.js:8171:13)
    at applyNormalization (/Users/paymahn/code/tripvector/tripvector/node_modules/prettier/index.js:7992:49)
    at Normalizer.normalize (/Users/paymahn/code/tripvector/tripvector/node_modules/prettier/index.js:7998:9)
    at normalizeOptions (/Users/paymahn/code/tripvector/tripvector/node_modules/prettier/index.js:8431:31)
    at Object.normalizeApiOptions (/Users/paymahn/code/tripvector/tripvector/node_modules/prettier/index.js:8593:10)
    at normalize$1 (/Users/paymahn/code/tripvector/tripvector/node_modules/prettier/index.js:9832:28)
    at formatWithCursor (/Users/paymahn/code/tripvector/tripvector/node_modules/prettier/index.js:13525:12)
    at /Users/paymahn/code/tripvector/tripvector/node_modules/prettier/index.js:44207:15
    at Object.format (/Users/paymahn/code/tripvector/tripvector/node_modules/prettier/index.js:44226:12)
```

Here's the full debug log:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/paymahn/.nvm/versions/node/v14.19.1/bin/node',
1 verbose cli   '/Users/paymahn/.nvm/versions/node/v14.19.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'lint'
1 verbose cli ]
2 info using npm@6.14.16
3 info using node@v14.19.1
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle tripvector@2.0.1~prelint: tripvector@2.0.1
6 info lifecycle tripvector@2.0.1~lint: tripvector@2.0.1
7 verbose lifecycle tripvector@2.0.1~lint: unsafe-perm in lifecycle true
8 verbose lifecycle tripvector@2.0.1~lint: PATH: /Users/paymahn/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/paymahn/code/tripvector/tripvector/node_modules/.bin:/Users/paymahn/.nvm/versions/node/v14.19.1/bin:/Users/paymahn/.nvm/versions/node/v14.19.1/bin:/Users/paymahn/.nvm/versions/node/v12.22.11/bin:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/paymahn/.meteor:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/usr/local/bin:/Users/paymahn/.pyenv/bin:/Users/paymahn/go/bin:/Users/paymahn/.nvm/versions/node/v17.6.0/bin:/Users/paymahn/.pyenv/shims:/Users/paymahn/.poetry/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/paymahn/.meteor:/Users/paymahn/.pyenv/bin:/Users/paymahn/go/bin:/Users/paymahn/.nvm/versions/node/v17.6.0/bin:/Users/paymahn/.pyenv/shims:/Users/paymahn/.poetry/bin:/Users/paymahn/.cargo/bin:/usr/local/opt/fzf/bin
9 verbose lifecycle tripvector@2.0.1~lint: CWD: /Users/paymahn/code/tripvector/tripvector
10 silly lifecycle tripvector@2.0.1~lint: Args: [ '-c', 'eslint .' ]
11 silly lifecycle tripvector@2.0.1~lint: Returned: code: 1  signal: null
12 info lifecycle tripvector@2.0.1~lint: Failed to exec lint script
13 verbose stack Error: tripvector@2.0.1 lint: `eslint .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/paymahn/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/Users/paymahn/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid tripvector@2.0.1
15 verbose cwd /Users/paymahn/code/tripvector/tripvector
16 verbose Darwin 21.4.0
17 verbose argv "/Users/paymahn/.nvm/versions/node/v14.19.1/bin/node" "/Users/paymahn/.nvm/versions/node/v14.19.1/bin/npm" "run" "lint"
18 verbose node v14.19.1
19 verbose npm  v6.14.16
20 error code ELIFECYCLE
21 error errno 1
22 error tripvector@2.0.1 lint: `eslint .`
22 error Exit status 1
23 error Failed at the tripvector@2.0.1 lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Here's my full package.json

```
{
  "name": "tripvector",
  "version": "2.0.1",
  "description": "Take the tricky part of out travel planning",
  "private": true,
  "license": "MIT",
  "meteor": {
    "mainModule": {
      "client": "startup/client/index.js",
      "server": "startup/server/index.js"
    }
  },
  "engines": {
    "node": "12.x"
  },
  "scripts": {
    "dev": "meteor --settings settings-development.json",
    "staging": "DEPLOY_HOSTNAME=us-east-1.galaxy-deploy.meteor.com meteor deploy pup-staging.cleverbeagle.com --settings settings-staging.json",
    "production": "npm run set-heroku-vars && git push heroku master",
    "bundle": "meteor --extra-packages bundle-visualizer --production --settings settings-development.json",
    "lint": "eslint .",
    "lint:all": "eslint --fix .",
    "lint:file": "eslint --fix",
    "test": "jest",
    "test-watch": "jest --watch --verbose false",
    "test-e2e": "testcafe chrome ui/**/*.e2e.js",
    "set-heroku-vars": "heroku config:set METEOR_SETTINGS=\"$(cat settings-production.json)\""
  },
  "dependencies": {
    "@apollo/client": "^3.5.10",
    "@babel/runtime": "^7.13.7",
    "@cleverbeagle/seeder": "^2.0.3",
    "@fortawesome/free-solid-svg-icons": "^5.15.4",
    "@google/maps": "^0.5.5",
    "@graphql-tools/schema": "^8.3.9",
    "@headlessui/react": "^1.5.0",
    "@sendgrid/mail": "^7.6.2",
    "@sentry/browser": "^5.30.0",
    "@sentry/node": "^5.30.0",
    "@stripe/stripe-js": "^1.27.0",
    "@tippy.js/react": "^2.2.3",
    "@tripvector/map-helpers": "^0.4.0",
    "adm-zip": "^0.5.9",
    "ajv": "^5.5.2",
    "algoliasearch": "^4.13.0",
    "apollo-server": "^3.6.7",
    "apollo-server-express": "^3.6.7",
    "aws-sdk": "^2.1116.0",
    "b64-to-blob": "^1.2.19",
    "babel-plugin-lodash": "^3.3.4",
    "bcrypt": "^3.0.8",
    "buffer": "^6.0.3",
    "classnames": "^2.2.6",
    "clipboard-copy": "^3.2.0",
    "commonmark": "^0.28.1",
    "cookies-js": "^1.2.3",
    "core-js": "^2.6.12",
    "cors": "^2.8.5",
    "emoji-mart": "^3.0.1",
    "express": "^4.17.3",
    "extract-zip": "^2.0.1",
    "file-saver": "^1.3.8",
    "formik": "^2.2.9",
    "fs": "0.0.1-security",
    "geo-convex-hull": "^1.3.0",
    "geolib": "^3.3.3",
    "google-geocode-parser": "^1.4.5",
    "google-map-react": "^1.1.7",
    "graphql": "^16.3.0",
    "graphql-subscriptions": "^2.0.0",
    "graphql-tag": "^2.12.6",
    "graphql-type-json": "^0.3.2",
    "handlebars": "^4.7.7",
    "humanparser": "^1.11.0",
    "immutability-helper": "^3.1.1",
    "indexof": "0.0.1",
    "install": "^0.13.0",
    "isomorphic-fetch": "^2.2.1",
    "jszip": "^3.9.1",
    "juice": "^4.3.2",
    "lodash": "^4.17.11",
    "lodash-es": "^4.17.21",
    "lodash.flowright": "^3.5.0",
    "meteor-node-stubs": "^1.2.1",
    "moment": "^2.29.3",
    "moment-timezone": "^0.5.34",
    "node-fetch": "^2.6.7",
    "npm": "^6.14.16",
    "parse-address": "^1.1.2",
    "parse-address-string": "0.0.3",
    "polished": "^1.9.2",
    "prop-types": "^15.6.1",
    "query-string": "^6.14.1",
    "random-location": "^1.1.3",
    "randomcolor": "^0.5.4",
    "rc-time-picker": "^3.7.3",
    "react": "^16.14.0",
    "react-autobind": "^1.0.6",
    "react-avatar-editor": "^11.1.0",
    "react-beautiful-dnd": "^13.1.0",
    "react-bootstrap": "^0.32.4",
    "react-color": "^2.19.3",
    "react-confirm-alert": "^2.8.0",
    "react-datepicker": "^2.16.0",
    "react-dates": "^20.3.0",
    "react-dom": "^16.14.0",
    "react-google-login": "^5.2.2",
    "react-helmet": "^5.2.1",
    "react-image-crop": "^8.6.12",
    "react-is": "^16.7.0",
    "react-load-script": "0.0.6",
    "react-markdown": "^3.3.0",
    "react-multiline-clamp": "^2.0.0",
    "react-native-listener": "^1.1.0",
    "react-range": "^1.8.12",
    "react-responsive-carousel": "^3.2.23",
    "react-router": "^4.2.0",
    "react-router-bootstrap": "^0.24.4",
    "react-router-dom": "^4.2.2",
    "react-select": "^5.3.0",
    "react-spinners": "^0.6.1",
    "react-spring-bottom-sheet": "^3.4.0",
    "react-transition-group": "^4.4.2",
    "react-virtuoso": "^2.9.2",
    "react-with-direction": "^1.4.0",
    "redis": "^3.1.2",
    "redux": "^4.1.2",
    "redux-thunk": "^2.4.1",
    "sanitize-html": "^1.27.5",
    "simpl-schema": "^1.12.0",
    "slugify": "^1.6.5",
    "sockjs": "^0.3.24",
    "sockjs-client": "^1.6.0",
    "store": "^2.0.12",
    "stripe": "^8.217.0",
    "styled-components": "^4.0.2",
    "subscriptions-transport-ws": "^0.9.19",
    "togeojson": "^0.16.0",
    "underscore": "^1.13.2",
    "uuid": "^3.4.0",
    "validator": "^11.1.0",
    "xml": "^1.0.1",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@babel/core": "^7.17.9",
    "@babel/preset-env": "^7.16.11",
    "@babel/preset-react": "^7.16.7",
    "autoprefixer": "^10.4.4",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^8.2.6",
    "babel-jest": "^23.6.0",
    "enzyme": "^3.11.0",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-prettier": "^2.10.0",
    "eslint-import-resolver-meteor": "^0.4.0",
    "eslint-plugin-babel": "^5.3.1",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jest": "^21.27.1",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-meteor": "^4.2.0",
    "eslint-plugin-prettier": "^2.7.0",
    "eslint-plugin-react": "^7.29.4",
    "eslint-plugin-testcafe": "^0.2.1",
    "husky": "^1.0.0-rc.13",
    "jest": "^23.6.0",
    "jest-cli": "^23.6.0",
    "lint-staged": "^7.2.2",
    "npdev-react-loadable-babel": "^1.1.0",
    "postcss": "^8.4.12",
    "postcss-load-config": "^3.1.4",
    "prettier": "^1.19.1",
    "tailwindcss": "^2.2.19",
    "testcafe": "^0.23.0"
  },
  "optionalDependencies": {
    "fsevents": "2.3.2"
  },
  "eslintConfig": {
    "parser": "babel-eslint",
    "parserOptions": {
      "ecmaFeatures": {
        "jsx": true
      }
    },
    "plugins": [
      "babel",
      "jest",
      "meteor",
      "prettier",
      "react",
      "testcafe"
    ],
    "extends": [
      "airbnb",
      "plugin:prettier/recommended",
      "plugin:meteor/recommended",
      "plugin:react/recommended",
      "plugin:testcafe/recommended",
      "plugin:jest/recommended"
    ],
    "env": {
      "browser": true
    },
    "globals": {
      "expect": false,
      "google": true
    },
    "rules": {
      "react/display-name": "off",
      "arrow-parens": [
        2,
        "always"
      ],
      "import/no-unresolved": 0,
      "import/no-extraneous-dependencies": 0,
      "import/extensions": 0,
      "indent": 0,
      "jsx-a11y/anchor-is-valid": [
        "error",
        {
          "components": [
            "Link"
          ],
          "specialLink": [
            "to"
          ]
        }
      ],
      "max-len": 0,
      "no-alert": 0,
      "no-console": 0,
      "no-restricted-globals": 0,
      "no-return-assign": [
        "error",
        "except-parens"
      ],
      "no-underscore-dangle": [
        "error",
        {
          "allow": [
            "_id",
            "_ensureIndex",
            "_verifyEmailToken",
            "_resetPasswordToken",
            "_name"
          ]
        }
      ],
      "class-methods-use-this": 0,
      "prettier/prettier": 2,
      "react/jsx-filename-extension": 0,
      "react/forbid-prop-types": 0
    },
    "settings": {
      "import/resolver": "meteor"
    }
  },
  "lint-staged": {
    "*.{js,json,css,md}": [
      "./.githooks/pre-commit.sh",
      "git add"
    ]
  },
  "prettier": {
    "printWidth": 100,
    "tabWidth": 2,
    "useTabs": false,
    "semi": true,
    "singleQuote": true,
    "trailingComma": "all",
    "bracketSpacing": true,
    "jsxBracketSameLine": false,
    "arrowParens": "always",
    "rangeStart": 0,
    "rangeEnd": "Infinity",
    "parser": "babylon",
    "proseWrap": "preserve"
  }
}
```

### What did you expect to happen?

I expect eslint to not fail with an error message about getting a value of infinity

### What actually happened?

eslint failed with the following error message

```
Error: Invalid rangeEnd value. Expected an integer, but received "Infinity".
    at _loop (/Users/paymahn/code/tripvector/tripvector/node_modules/prettier/index.js:8058:63)
    at Normalizer._applyNormalization (/Users/paymahn/code/tripvector/tripvector/node_modules/prettier/index.js:8171:13)
    at applyNormalization (/Users/paymahn/code/tripvector/tripvector/node_modules/prettier/index.js:7992:49)
    at Normalizer.normalize (/Users/paymahn/code/tripvector/tripvector/node_modules/prettier/index.js:7998:9)
    at normalizeOptions (/Users/paymahn/code/tripvector/tripvector/node_modules/prettier/index.js:8431:31)
    at Object.normalizeApiOptions (/Users/paymahn/code/tripvector/tripvector/node_modules/prettier/index.js:8593:10)
    at normalize$1 (/Users/paymahn/code/tripvector/tripvector/node_modules/prettier/index.js:9832:28)
    at formatWithCursor (/Users/paymahn/code/tripvector/tripvector/node_modules/prettier/index.js:13525:12)
    at /Users/paymahn/code/tripvector/tripvector/node_modules/prettier/index.js:44207:15
    at Object.format (/Users/paymahn/code/tripvector/tripvector/node_modules/prettier/index.js:44226:12)
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
The error message indicates that this error is coming from Prettier. I’m guessing that’s coming from `plugin:prettier/recommended` and it probably has something to do with babel-ESLint returning an invalid value.

Note: Babel-eslint is the old version. You should be using @Babel/eslint-parser.

You can probably use the builtin parser directly unless you’re using experimental syntax. Just set parserOptions.ecmaVersion to “latest”.
