### ISSUE TITLE
Bug: eslint crash at startup

### ISSUE THREAD

**Issue by Gxmadix** [eslint/eslint#15827]
### Environment

Node version: v16.14.2
npm version: 8.5.0
Local ESLint version: tried from 8.12 to  8.14 (latest)
Global ESLint version: 8.1.0
Operating System: Ubuntu 20.04

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>

I used to have eslint check configured with husky for commits. 
```
// packages.json
"lint-staged": {
    "*.{js,jsx,ts,tsx,json}": [
      "eslint --fix"
    ]
  },
  "devDependencies": {
    "@faker-js/faker": "^6.2.0",
    "@react-native-community/eslint-config": "^3.0.1",
    "@typescript-eslint/eslint-plugin": "^5.17.0",
    "@typescript-eslint/parser": "^5.17.0",
    "eslint": "^8.12.0",
    "eslint-config-next": "^12.1.1",
    "eslint-import-resolver-alias": "^1.1.2",
    "eslint-import-resolver-typescript": "^2.7.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-json-format": "^2.0.1",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.29.4",
    "eslint-plugin-react-hooks": "^4.3.0",
    "eslint-plugin-unused-imports": "^2.0.0",
    "husky": "^7.0.4",
    "jest": "^28.0.3",
    "lerna": "^4.0.0",
    "lint-staged": "^12.3.7",
    "ts-node": "^10.7.0",
    "typescript": "^4.6.3"
  }
```
This is used to work, but since today this is not, after I reinstalled the app, what I also did yesterday, but yesterday it was working fine. So clearly something changed between yesterday and now. I am sure I didn't change anything on my side, no package upgrade or changed.

<summary>Configuration</summary>

I have a monorepo, with at the root directory. 
```
    // .eslintrc.js
    const stricter1 = 'off';
const stricter2 = 'warn';

module.exports = {
  root: true,
  env: {
    commonjs: true,
    node: true,
    jest: true,
  },
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-checking',
    'plugin:import/recommended',
    'plugin:import/typescript',
  ],
  plugins: [
    '@typescript-eslint',
    'prettier',
    'import',
    'json-format',
    '@typescript-eslint/eslint-plugin',
    'unused-imports',
  ],
  parserOptions: {
    sourceType: 'module',
    project: ['./tsconfig.eslint.json', '*/tsconfig.json'],
    tsconfigRootDir: __dirname,
  },
  parser: '@typescript-eslint/parser',
  ignorePatterns: [
    '**/.eslintrc*.js',
    '**/node_modules/*',
    '**/dist',
    '**/yarn.lock',
    '**/package-lock.json',
  ],
  rules: {
    'import/order': [
      'error',
      {
        pathGroups: [
          {
            pattern: '@nearvibz/**',
            group: 'internal',
          },
          {
            pattern: '@web/**',
            group: 'parent',
            position: 'before',
          },
          {
            pattern: '@mobile/**',
            group: 'parent',
            position: 'before',
          },
        ],
        groups: [
          'builtin',
          'external',
          'internal',
          'parent',
          'sibling',
          'index',
        ],
      },
    ],

    semi: 'error',
    'prettier/prettier': 'error',
    'prettier/prettier': [
      'error',
      {
        endOfLine: 'auto',
      },
    ],
    'no-undef': 'error',
    'no-console': ['error', { allow: ['warn', 'error'] }],
    'comma-dangle': ['error', 'always-multiline'],
    'no-self-compare': 'error',
    'import/namespace': stricter1,

    '@typescript-eslint/no-unused-vars': 'off', // replaced by rule below
    'unused-imports/no-unused-imports': 'error',
    'unused-imports/no-unused-vars': [
      stricter2,
      {
        vars: 'all',
        varsIgnorePattern: '^_',
        args: 'after-used',
        argsIgnorePattern: '^_',
      },
    ],

    '@typescript-eslint/no-explicit-any': stricter1,
    '@typescript-eslint/no-unsafe-assignment': stricter1,
    '@typescript-eslint/no-unsafe-member-access': stricter1,
    '@typescript-eslint/no-unsafe-return': stricter1,
    '@typescript-eslint/no-unsafe-call': stricter1,
    '@typescript-eslint/no-unsafe-argument': stricter1,
    '@typescript-eslint/ban-types': stricter1,

    '@typescript-eslint/no-floating-promises': 'warn',
    'import/no-extraneous-dependencies': 'error',

    'arrow-parens': 'off',
    'linebreak-style': 'off',
    'import/default': 'off',
    'import/no-named-as-default': 'off',
    'import/no-named-as-default-member': 'off',
    '@typescript-eslint/ban-ts-comment': stricter1,
    '@typescript-eslint/restrict-template-expressions': stricter1,
  },
  settings: {
    'import/resolver': {
      typescript: {
        alwaysTryTypes: true,
        project: [
          'api/tsconfig.json',
          'mobile/tsconfig.json',
          'web/tsconfig.json',
        ],
      },
    },
    'json/json-with-comments-files': ['**/tsconfig*.json', '.vscode/**'],
  },
  overrides: [
    {
      files: ['**/index.ts'],
      rules: {
        'no-unused-vars': 'off',
        '@typescript-eslint/no-unused-vars': ['off'],
      },
    },
  ],
};
```

Then multiple repos, like this mobile one, that inherit from the parent file above

```
// mobile/.eslintrc.js
const stricter1 = 'off';
const stricter2 = 'warn';

module.exports = {
  env: {
    'react-native/react-native': true,
  },
  extends: ['../.eslintrc.front'],
  plugins: ['react-native'],

  ignorePatterns: [
    'android/',
    'ios/',
    '__mocks__/',
    'metro.config.js',
    'jest.config.js',
    'babel.config.js',
  ],
  rules: {
    // react native
    'react-native/no-inline-styles': stricter2,
    'react-native/no-unused-styles': stricter2,
    'react-native/no-color-literals': 'error',
    'react-native/split-platform-components': 'error',
    'react-native/no-raw-text': stricter1,

    '@typescript-eslint/no-shadow': ['error'],
    'no-shadow': 'off',
    'no-undef': 'off',
  },
  settings: {
    'import/resolver': {
      alias: {
        map: [['@env', 'react-native-dotenv']],
      },
    },
  },
};
```

**I haven't set type in any of my packages.json**
</details>

### What did you expect to happen?

The linter to check code, but it fails to launch

### What actually happened?

> git commit -m "xxxx"
yarn run v1.22.18
$ project/node_modules/.bin/lint-staged
✔ Preparing lint-staged...
⚠ Running tasks for staged files...
  ❯ package.json — 6 files
    ❯ *.{js,jsx,ts,tsx,json} — 6 files
      ✖ eslint --fix [FAILED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ eslint --fix:

Oops! Something went wrong! :(

ESLint: 8.14.0

Error [ERR_REQUIRE_ESM]: require() of ES Module project/node_modules/sort-package-json/index.js from project/node_modules/eslint-plugin-json-format/lib/utils.js not supported.
Instead change the require of index.js in project/node_modules/eslint-plugin-json-format/lib/utils.js to a dynamic import() which is available in all CommonJS modules.
    at require (project/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (project/node_modules/eslint-plugin-json-format/lib/utils.js:6:25)
    at Module._compile (project/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at require (project/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (project/node_modules/eslint-plugin-json-format/lib/index.js:7:86)
    at Module._compile (project/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at ConfigArrayFactory._loadPlugin (project/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3395:42)
    at project/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3267:33
    at Array.reduce (<anonymous>)
    at ConfigArrayFactory._loadPlugins (project/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3263:22)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (project/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3063:44)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (project/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3003:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (project/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3058:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (project/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3003:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (project/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3058:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (project/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3003:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (project/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2849:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (project/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3833:46)
    at CascadingConfigArrayFactory.getConfigArrayForFile (project/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3754:18)
    at FileEnumerator._iterateFilesWithFile (project/node_modules/eslint/lib/cli-engine/file-enumerator.js:366:43)
    at FileEnumerator._iterateFiles (project/node_modules/eslint/lib/cli-engine/file-enumerator.js:347:25)
    at FileEnumerator.iterateFiles (project/node_modules/eslint/lib/cli-engine/file-enumerator.js:297:59)
    at iterateFiles.next (<anonymous>)
    at CLIEngine.executeOnFiles (project/node_modules/eslint/lib/cli-engine/cli-engine.js:788:48)
    at ESLint.lintFiles (project/node_modules/eslint/lib/eslint/eslint.js:550:23)
    at Object.execute (project/node_modules/eslint/lib/cli.js:301:36)
    at main (project/node_modules/eslint/bin/eslint.js:138:52)
    at Object.<anonymous> (project/node_modules/eslint/bin/eslint.js:142:2)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
husky - pre-commit hook exited with code 1 (error)

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

 - No changes on my side from a working state yesterday
 - I haven't set type in any of my packages.json

**Comment by mdjermanovic** [comment]
Hi @Gxmadix, thanks for the issue!

> Error [ERR_REQUIRE_ESM]: require() of ES Module project/node_modules/sort-package-json/index.js from project/node_modules/eslint-plugin-json-format/lib/utils.js not supported.
> Instead change the require of index.js in project/node_modules/eslint-plugin-json-format/lib/utils.js to a dynamic import() which is available in all CommonJS modules.

This is a problem with `eslint-plugin-json-format`, in particular with its dependency `sort-package-json` which has been released with a breaking change https://github.com/keithamus/sort-package-json/pull/256 in a minor version v1.56.0.

I'm closing this issue since this is not a problem in ESLint.

**Comment by Gxmadix** [comment]
Thanks @mdjermanovic, I am reporting the issue to right repo.
