### ISSUE TITLE
Bug: Cannot read config file .eslintrc.js 

### ISSUE THREAD

**Issue by eng-dibo** [eslint/eslint#15881]
### Environment

Node version: 16.15.0
npm version:  8.8.0
Local ESLint version: 8.15.0
Global ESLint version: -
Operating System: windows 8.1 x64

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
module.exports={}
```
</details>

```
> eslint file.js
```
```
Oops! Something went wrong! :(

ESLint: 8.15.0

TypeError: Cannot read config file: .eslintrc.js
Error: callsites is not a function
    at module.exports (node_modules\parent-module\index.js:5:17)
    at Object.module.exports [as default] (node_modules\import-fresh\index.js:11:21)
    at loadJSConfigFile (node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2559:47)
    at loadConfigFile (node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2643:20)
    at ConfigArrayFactory.loadInDirectory (node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2840:34)
    at CascadingConfigArrayFactory._loadConfigInAncestors (node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3833:46)
    at CascadingConfigArrayFactory.getConfigArrayForFile (node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3754:18)
    at FileEnumerator._iterateFilesWithFile (node_modules\eslint\lib\cli-engine\file-enumerator.js:366:43)
    at FileEnumerator._iterateFiles (node_modules\eslint\lib\cli-engine\file-enumerator.js:347:25)
    at FileEnumerator.iterateFiles (node_modules\eslint\lib\cli-engine\file-enumerator.js:297:59)
```

### What did you expect to happen?

to read .eslintrc.js file and to lint without any error

### What actually happened?

I got the error `callsites is not a function` even though I removed all plugins and rules.
I updated `eslint` to the latest version

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by snitin315** [comment]
@eng-dibo Can you share a repo in which this is reproducable? I am not able to reproduce this locally.

**Comment by eng-dibo** [comment]
> Can you share a repo

https://github.com/eng-dibo/dibo/tree/feat/eslint

**Comment by aladdin-add** [comment]
I was not able to repro too. :-O

It looks like the module `callsites` was not correctly installed. can you try to clean the npm cache (`npm cache clean -f`) and retry?
