### ISSUE TITLE
Bug: (fill in)

### ISSUE THREAD

**Issue by likyh** [eslint/eslint#15908]
### Environment

Node version: 
npm version: 
Local ESLint version: 
Global ESLint version: 
Operating System: 

### What parser are you using?

@babel/eslint-parser

### What did you do?

<details>
<summary>Configuration</summary>

```
{
  "root": true,
  "parser": "babel-eslint",
  "extends": [
    "standard",
    "standard-jsx",
    "standard-react",
    "plugin:react-hooks/recommended"
  ],
  "ignorePatterns": [
    "dist/*",
    "/packages/*",
    "/cypress/",
    "/config/",
    "/node_modules/"
  ],
  "env": {
    "browser": true,
    "jest": true
  },
  "plugins": [
    "unicorn",
    "babel",
    "header"
  ],
  "settings": {
    "import/resolver": {
      "alias": {
        "extensions": [".js"],
        "map": [
          [
            "@", "./src/"
          ],
          [
            "@config", "./config/"
          ]
        ]
      },
      "babel-module": {
        "extensions": [
          ".js",
          ".jsx",
          ".ts"
        ]
      }
    }
  },
  "rules": {
    "camelcase": "off",
    "max-len": [1, 140, 2],
    "import/no-named-as-default": "off",
    "comma-dangle": "off",
    "react/prop-types": "off",
    "react/jsx-boolean-value": 0,
    "header/header": ["error", ".file-headerrc"]
  }
}

```
</details>

```js
import React from 'react'

const PipelineIndicator = (props) => {
  const {
    pipeline,
  } = props

  return (
    <>
      {pipeline?.tasks?.map((t, tIdx) => (
        <div
          key={`pipeline-task-key-${tIdx}`}
        >
        </div>
      ))}
    </>
  )
}

export default PipelineIndicator

```

### What did you expect to happen?

lint success

### What actually happened?

```
eslint ./src --ext .jsx --ext .js
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

Oops! Something went wrong! :(

ESLint: 7.32.0

TypeError: Cannot read property 'value' of null
Occurred while linting ~/src/components/widgets/PipelineIndicator.jsx:12
    at checkSpacingBefore (~/node_modules/eslint/lib/rules/template-curly-spacing.js:52:24)
    at TemplateElement (~/node_modules/eslint/lib/rules/template-curly-spacing.js:136:17)
    at ~/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (~/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (~/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (~/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (~/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (~/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at ~/node_modules/eslint/lib/linter/linter.js:960:32

```

I‘m very sure that `key={\`pipeline-task-key-${tIdx}\`}` got error because it works when I delete this line.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aladdin-add** [comment]
you could use `"parser": "@babel/eslint-parser"` instead.
