### ISSUE TITLE
Bug: ESLint crashes with Error: Invalid Options: - Unknown options: allowTrailingCommas

### ISSUE THREAD

**Issue by hidragos** [eslint/eslint#16214]
### Environment

Node version: v16.13.0
npm version: v7.6.0
Local ESLint version: v8.22.0
Global ESLint version: Not found
Operating System: darwin 21.5.0

### What parser are you using?

@angular-eslint/template-parser

### What did you do?

<details>
<summary>Repro steps</summary>

```
1. Create Angular application
2. Add @angular-eslint/schematics via `ng add @angular-eslint/schematics`
3. In VSCode, open the Output view and select ESLint. An error will be thrown any time ESLint tries to parse the text. The error is:

Error: Invalid Options:
- Unknown options: allowTrailingCommas
```
</details>

### What did you expect to happen?

ESLint is expected to run on with default configuration.

### What actually happened?

ESLint throws the following error:
```
Error: Invalid Options:
- Unknown options: allowTrailingCommas
    at processOptions (/Users/username/test-eslint/node_modules/eslint/lib/eslint/eslint.js:281:15)
    at new ESLint (/Users/username/test-eslint/node_modules/eslint/lib/eslint/eslint.js:428:34)
    at q (/Users/username/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:17975)
    at Object.E [as withClass] (/Users/username/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:18312)
    at D.then.g.validate (/Users/username/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:21057)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/username/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/server/out/eslintServer.js:1:210071```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

**Comment by nzakas** [comment]
Please contact the angular-eslint team for this.
