### ISSUE TITLE
Bug: 'this.libOptions.parse is not a function' error after upgrading to ESLint 8.23.0

### ISSUE THREAD

**Issue by jooy2** [eslint/eslint#16250]
### Environment

Node version: 16.17.0
npm version: 8.18.0
Local ESLint version: 8.23.0
Global ESLint version: none
Operating System: Windows 10 x64 21H2

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
{
  "parserOptions": {
    "sourceType": "module",
    "ecmaVersion": 2020
  },
  "env": {
    "browser": true,
    "node": true,
    "es6": true
  },
  "globals": {
    "Atomics": "readonly",
    "SharedArrayBuffer": "readonly"
  },
  "rules": {
    "linebreak-style": ["error", "windows"]
  }
}
```
</details>

```js
console.log('Hello!');
```

### What did you expect to happen?

The ESLint error should not be displayed in Jetbrain IDE(IntelliJ Webstorm), and the grammar check should proceed properly.

### What actually happened?

![image](https://user-images.githubusercontent.com/48266008/187008330-c316fcab-31a9-429b-81d7-adfa8939ada4.png)

**Reproduce GitHub repo: https://github.com/jooy2/eslint-liboptions-parse-is-not-a-function**

I don't know if this is only happening in the **IntelliJ Webstorm IDE**, but it worked fine in the old environment and I haven't modified any other settings in the recent IDE.

After upgrading ESLint to `8.23.0`, the check fails with the following error in the IDE:

```
TypeError: this.libOptions.parse is not a function
    at ESLint8Plugin.<anonymous> (C:\Program Files\JetBrains\WebStorm 2020.2.2\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint8-plugin.js:139:64)
    at step (C:\Program Files\JetBrains\WebStorm 2020.2.2\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint8-plugin.js:44:23)
    at Object.next (C:\Program Files\JetBrains\WebStorm 2020.2.2\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint8-plugin.js:25:53)
    at C:\Program Files\JetBrains\WebStorm 2020.2.2\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint8-plugin.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Program Files\JetBrains\WebStorm 2020.2.2\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint8-plugin.js:15:12)
    at ESLint8Plugin.invokeESLint (C:\Program Files\JetBrains\WebStorm 2020.2.2\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint8-plugin.js:133:16)
    at ESLint8Plugin.<anonymous> (C:\Program Files\JetBrains\WebStorm 2020.2.2\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint8-plugin.js:120:44)
    at step (C:\Program Files\JetBrains\WebStorm 2020.2.2\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint8-plugin.js:44:23)
    at Object.next (C:\Program Files\JetBrains\WebStorm 2020.2.2\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint8-plugin.js:25:53)
Process finished with exit code -1
```

Even with only the `eslint` package installed, the problem occurs whether the `.eslintrc` file exists or not.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by prescience-data** [comment]
Also just received this after upgrading: 

![image](https://user-images.githubusercontent.com/65471523/187009196-59ed133f-a4f0-454a-82bc-269e96a03d9f.png)


```error
TypeError: this.libOptions.parse is not a function

TypeError: this.libOptions.parse is not a function
    at ESLint8Plugin.<anonymous> (C:\Users\samue\AppData\Local\JetBrains\Toolbox\apps\WebStorm\ch-0\222.3739.57\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint8-plugin.js:139:64)
    at step (C:\Users\samue\AppData\Local\JetBrains\Toolbox\apps\WebStorm\ch-0\222.3739.57\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint8-plugin.js:44:23)
    at Object.next (C:\Users\samue\AppData\Local\JetBrains\Toolbox\apps\WebStorm\ch-0\222.3739.57\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint8-plugin.js:25:53)
    at C:\Users\samue\AppData\Local\JetBrains\Toolbox\apps\WebStorm\ch-0\222.3739.57\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint8-plugin.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\samue\AppData\Local\JetBrains\Toolbox\apps\WebStorm\ch-0\222.3739.57\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint8-plugin.js:15:12)
    at ESLint8Plugin.invokeESLint (C:\Users\samue\AppData\Local\JetBrains\Toolbox\apps\WebStorm\ch-0\222.3739.57\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint8-plugin.js:133:16)
    at ESLint8Plugin.<anonymous> (C:\Users\samue\AppData\Local\JetBrains\Toolbox\apps\WebStorm\ch-0\222.3739.57\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint8-plugin.js:120:44)
    at step (C:\Users\samue\AppData\Local\JetBrains\Toolbox\apps\WebStorm\ch-0\222.3739.57\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint8-plugin.js:44:23)
    at Object.next (C:\Users\samue\AppData\Local\JetBrains\Toolbox\apps\WebStorm\ch-0\222.3739.57\plugins\JavaScriptLanguage\languageService\eslint\bin\eslint8-plugin.js:25:53)
Process finished with exit code -1
```

**Comment by JackieCheung** [comment]
I got the same problem

**Comment by mdjermanovic** [comment]
Thanks for all the details!

> #### WebStorm Plugin Source
> https://gist.github.com/prescience-data/fa82f9b26e00cd74be8ea262b3048f08#file-eslint8-plugin-ts-L21

Per this line of code, it seems that the plugin is reaching into the `eslint` package to load an internal module. ESLint's public API is defined in [`package.exports`](https://github.com/eslint/eslint/blob/dcf178e3c41e7777ee76ae9582387be85118118b/package.json#L12). Since the `lib/options.js` module isn't public, its API can change in non-major versions, as it did in the latest version v8.23.0.

I think this problem should be fixed on the plugin's side, and there's already a raised issue in the JetBrains' issue tracker:

https://youtrack.jetbrains.com/issue/WEB-57089/ESLint823-TypeError-thislibOptionsparse-is-not-a-function

**Comment by hansfpc** [comment]
I got the same problem :c

**Comment by RDIL** [comment]
Is a backwards compatibility shim possible/viable in the short term, until JetBrains is able to fix the issue?

**Comment by daLeiStrive** [comment]
Just fix eslint to 8.22
npm install eslint@8.22.0 --save-exact

**Comment by jooy2** [comment]
Thanks for everyone's interest. I will close this issue as it will be fixed in the **next update (2022.2.2)** of all families of IntelliJ.

See: https://youtrack.jetbrains.com/issue/WEB-57089/ESLint823-TypeError-thislibOptionsparse-is-not-a-function

**Comment by mdjermanovic** [comment]
> Is a backwards compatibility shim possible/viable in the short term, until JetBrains is able to fix the issue?

In the short term, a workaround is to pin the `eslint` dependency to `"8.22.0"` or an earlier version.

**Comment by aksalsf** [comment]
Otherwise, instead of change your project's eslint version, you can use manual eslint configuration to targetting eslint package in global scope. Assumes that you install eslint globally with lower version.

**Comment by mdnorman** [comment]
This is still happening with the latest version, `8.23.1`. I believe it was supposed to be fixed, is that correct?

BTW, the workaround to revert the version is somewhat painful when you have several repos and Renovate running on them.

**Comment by verifiedanswer** [comment]
[[Solved] TypeError: this.libOptions.parse is not a function](https://verifiedanswer.com/typeerror-this-liboptions-parse-is-not-a-function/)
