### ISSUE TITLE
lint mjs => TypeError: Key "plugins": Cannot redefine plugin "n".

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint#16277]
### Environment

Node version: v18.8.0
npm version: v8.19.1
Local ESLint version: v8.23.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 22.1.0

### What parser are you using?

Default (Espree)

### What did you do?

added an empty file "t.mjs" in the eslint codebase, and running `npx eslint t.mjs`. it throws an error:

```bash
➜  eslint git:(42bfbd7b7) npx eslint t.mjs

Oops! Something went wrong! :(

ESLint: 8.23.0

TypeError: Key "plugins": Cannot redefine plugin "n".
    at ObjectSchema.merge (/Users/weiran/repo/github/eslint/lib/config/flat-config-schema.js:272:23)
    at /Users/weiran/repo/github/eslint/node_modules/@humanwhocodes/object-schema/src/object-schema.js:176:54
    at Array.reduce (<anonymous>)
    at ObjectSchema.merge (/Users/weiran/repo/github/eslint/node_modules/@humanwhocodes/object-schema/src/object-schema.js:169:24)
    at /Users/weiran/repo/github/eslint/node_modules/@humanwhocodes/config-array/api.js:739:41
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfig (/Users/weiran/repo/github/eslint/node_modules/@humanwhocodes/config-array/api.js:738:32)
    at FlatConfigArray.isIgnored (/Users/weiran/repo/github/eslint/node_modules/@humanwhocodes/config-array/api.js:755:14)
    at /Users/weiran/repo/github/eslint/lib/eslint/eslint-helpers.js:144:38
    at Array.forEach (<anonymous>)
```

### What did you expect to happen?

lint susscessfully.

### What actually happened?

the error happened.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

it was firstly reported in https://github.com/weiran-zsd/eslint-plugin-node/pull/51#issuecomment-1234232548.

**Comment by aladdin-add** [comment]
👍 I've confirmed it was fixed if returns the same object. will make a PR later.
