### ISSUE TITLE
Spread operator in JSX element crashes ESLint

### ISSUE THREAD

**Issue by agrauch** [eslint/eslint#1634]
This code:
```javascript
var React = require('react/addons');

module.exports = React.createClass({
  render: function() {
    return <div {...this.props} />;
  }
});
```
Crashes ESLint and generates this stack trace:
```
/Users/agrauch/projects/agrauch/eslint/node_modules/estraverse/estraverse.js:515
                        throw new Error('Unknown node type ' + nodeType + '.')
                              ^
Error: Unknown node type XJSSpreadAttribute.
    at Controller.traverse (/Users/agrauch/projects/agrauch/eslint/node_modules/estraverse/estraverse.js:515:31)
    at Object.traverse (/Users/agrauch/projects/agrauch/eslint/node_modules/estraverse/estraverse.js:707:27)
    at Object.analyze (/Users/agrauch/projects/agrauch/eslint/node_modules/escope/escope.js:854:20)
    at EventEmitter.module.exports.api.verify (/Users/agrauch/projects/agrauch/eslint/lib/eslint.js:601:36)
    at processFile (/Users/agrauch/projects/agrauch/eslint/lib/cli-engine.js:134:27)
    at /Users/agrauch/projects/agrauch/eslint/lib/cli-engine.js:230:26
    at walk (/Users/agrauch/projects/agrauch/eslint/lib/util/traverse.js:81:9)
    at /Users/agrauch/projects/agrauch/eslint/lib/util/traverse.js:102:9
    at Array.forEach (native)
    at traverse (/Users/agrauch/projects/agrauch/eslint/lib/util/traverse.js:101:11)
```

**Comment by nzakas** [comment]
Are you using the es6jsx branch?

**Comment by agrauch** [comment]
Yep, with this .eslintrc file:
```javascript
{
  "env": {
    "browser": true,
    "node": true
  },
  "rules": {
    "no-multi-spaces": false,
    "no-multi-str": false,
    "quotes": [1, "single"]
  },
  "settings": {
    "ecmascript": 6,
    "jsx": true
  }
}
```

**Comment by nzakas** [comment]
Okay, looks like we missed support the spread operator. We've stopped developing in that branch as we're switching parsers, but I'll leave this open to make sure we cover our bases with the new parser.
