### ISSUE TITLE
Bug: Eslint cannot load `@typescript-eslint/parser` via Node.js API 

### ISSUE THREAD

**Issue by matczak** [eslint/eslint#16942]
### Environment

Node version: v14.20.0
npm version: 7.24.2
Local ESLint version:  8.35.0
Global ESLint version: 
Operating System: Windows 11

### What parser are you using?

@typescript-eslint/parser

### What did you do?

Eslint cannot load `@typescript-eslint/parser`

I've created a small repo to reproduce this bug:
https://github.com/matczak/eslint-bug

### What did you expect to happen?

ESlint can load `@typescript-eslint/parser` correctly 

### What actually happened?

```
Error: Failed to load parser '@typescript-eslint/parser' declared in 'BaseConfig': Cannot find module '@typescript-eslint/parser'
Require stack:
- C:\eslint-bug\two\__placeholder__.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:107:19)
    at Object.resolve (C:\eslint-bug\one\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2325:46)
    at ConfigArrayFactory._loadParser (C:\eslint-bug\one\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3304:39)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (C:\eslint-bug\one\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3078:43)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (C:\eslint-bug\one\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3019:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.create (C:\eslint-bug\one\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2814:16)
    at createBaseConfigArray (C:\eslint-bug\one\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3564:48) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\eslint-bug\\two\\__placeholder__.js' ]

```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @matczak, thanks for the issue!

Parser referenced by its name in `baseConfig` will be resolved relative to `cwd`. In your example, `@typescript-eslint/parser` isn't installed directly in `two/node_modules/` so resolving it from `two/` fails as expected.

Instead of the name, you could pass in the absolute path to the parser [here](https://github.com/matczak/eslint-bug/blob/52becca7c56619abe84d80dcd9eae79e91719d09/one/index.js#L7):

```diff
-parser: '@typescript-eslint/parser',
+parser: require.resolve('@typescript-eslint/parser'),
```
