### ISSUE TITLE
Bug: TypeError: Cannot read properties of null (reading 'range')

### ISSUE THREAD

**Issue by alilland** [eslint/eslint#17070]
### Environment

Node version: 
v16.15.0

npm version: 
yarn 1.22.19

Local ESLint version: 
v5.4.0

Global ESLint version: 
-

Operating System: 
Mac OS 13.3 - 2.4 GHz 8-Core Intel Core i9

Parser:
babel-eslint@10.1.0 (cant upgrade to @babel/eslint-parser without breaking changes)

### What parser are you using?

Other

### What did you do?

https://github.com/standard/standard/issues/1898

See issue on Standard library

### What did you expect to happen?

expected linting output

### What actually happened?

```
$ /Users/aronlilland/Documents/dev/controlair/backbone-ui/applications/backbone/node_modules/.bin/standard
standard: Unexpected linter output:

TypeError: Cannot read properties of null (reading 'range')
    at SourceCode.getTokenBefore (/Users/aronlilland/Documents/dev/controlair/backbone-ui/applications/backbone/node_modules/eslint/lib/token-store/index.js:303:18)
    at checkSpacingBefore (/Users/aronlilland/Documents/dev/controlair/backbone-ui/applications/backbone/node_modules/eslint/lib/rules/template-curly-spacing.js:52:42)
    at TemplateElement (/Users/aronlilland/Documents/dev/controlair/backbone-ui/applications/backbone/node_modules/eslint/lib/rules/template-curly-spacing.js:117:17)
    at /Users/aronlilland/Documents/dev/controlair/backbone-ui/applications/backbone/node_modules/eslint/lib/util/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/aronlilland/Documents/dev/controlair/backbone-ui/applications/backbone/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/aronlilland/Documents/dev/controlair/backbone-ui/applications/backbone/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/aronlilland/Documents/dev/controlair/backbone-ui/applications/backbone/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/aronlilland/Documents/dev/controlair/backbone-ui/applications/backbone/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/aronlilland/Documents/dev/controlair/backbone-ui/applications/backbone/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
    ```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by fasttime** [comment]
Thanks for the issue @alilland. Your version of ESLint is no longer maintained. Have you tried to upgrade to the current version of ESLint 8?

**Comment by nzakas** [comment]
Closing as this is an older version of ESLint and no further info provided.
