### ISSUE TITLE
Bug: SyntaxError: Invalid regular expression

### ISSUE THREAD

**Issue by billouboq** [eslint/eslint#17201]
### Environment

Node version: 18.6.0
npm version: >9
Local ESLint version: 8.41.0
Global ESLint version: 8.41.0
Operating System: MacOS

While upgrading from eslint 7 to 8 I noticed that I got that error every time I start eslint :

```
Oops! Something went wrong! :(

ESLint: 8.41.0

SyntaxError: Invalid regular expression: /(?:^|\s*,\s*)no\-restricted\-syntax(?:\s*,\s*|$)/: Invalid escape
    at new RegExp (<anonymous>)
    at /Users/aurelienboquet/beedeez/beedeez-main/node_modules/eslint/lib/linter/apply-disable-directives.js:90:23
    at Array.map (<anonymous>)
    at createIndividualDirectivesRemoval (/Users/aurelienboquet/beedeez/beedeez-main/node_modules/eslint/lib/linter/apply-disable-directives.js:87:23)
    at /Users/aurelienboquet/beedeez/beedeez-main/node_modules/eslint/lib/linter/apply-disable-directives.js:196:19
    at Array.flatMap (<anonymous>)
    at processUnusedDisableDirectives (/Users/aurelienboquet/beedeez/beedeez-main/node_modules/eslint/lib/linter/apply-disable-directives.js:186:28)
    at applyDirectives (/Users/aurelienboquet/beedeez/beedeez-main/node_modules/eslint/lib/linter/apply-disable-directives.js:261:23)
    at module.exports (/Users/aurelienboquet/beedeez/beedeez-main/node_modules/eslint/lib/linter/apply-disable-directives.js:338:34)
    at Linter._verifyWithoutProcessors (/Users/aurelienboquet/beedeez/beedeez-main/node_modules/eslint/lib/linter/linter.js:1363:16)
    at Linter._verifyWithConfigArray (/Users/aurelienboquet/beedeez/beedeez-main/node_modules/eslint/lib/linter/linter.js:1706:21)
    at Linter.verify (/Users/aurelienboquet/beedeez/beedeez-main/node_modules/eslint/lib/linter/linter.js:1412:65)
    at Linter.verifyAndFix (/Users/aurelienboquet/beedeez/beedeez-main/node_modules/eslint/lib/linter/linter.js:1967:29)
    at verifyText (/Users/aurelienboquet/beedeez/beedeez-main/node_modules/eslint/lib/cli-engine/cli-engine.js:245:48)
    at CLIEngine.executeOnFiles (/Users/aurelienboquet/beedeez/beedeez-main/node_modules/eslint/lib/cli-engine/cli-engine.js:825:28)
    at ESLint.lintFiles (/Users/aurelienboquet/beedeez/beedeez-main/node_modules/eslint/lib/eslint/eslint.js:551:23)
    at Object.execute (/Users/aurelienboquet/beedeez/beedeez-main/node_modules/eslint/lib/cli.js:391:36)
    at async main (/Users/aurelienboquet/beedeez/beedeez-main/node_modules/eslint/bin/eslint.js:135:24)
```

### What parser are you using?

@babel/eslint-parser

### What did you do?

Started yarn eslint 

Rules :
```
const ALL_RULES = {
	'max-classes-per-file': 0,
	camelcase: 0,
	curly: ['error', 'all'],
	'new-cap': 0,
	'max-len': 0,
	'comma-dangle': 0,
	'no-dupe-keys': 2,
	'no-tabs': 0,
	'spaced-comment': 'off',
	'no-underscore-dangle': 0,
	'no-case-declarations': 0,
	'no-confusing-arrow': 0,
	'no-unused-vars': 'off',
	'no-use-before-define': 'off',
	'no-plusplus': 0,
	'no-shadow': 'off',
	'no-bitwise': 0,
	'no-mixed-operators': 0,
	'no-param-reassign': 0,
	'no-mixed-spaces-and-tabs': 0,
	'no-useless-escape': 0,
	'no-return-assign': 0,
	'no-multi-assign': 1,
	'no-console': ['error', { allow: ['warn', 'error'] }],
	'linebreak-style': 0,
	'object-curly-newline': 'off',
	'function-paren-newline': 'off',
	'id-length': 'warn',
	'consistent-return': 0,
	'default-case': 0,
	'class-methods-use-this': 0,
	'implicit-arrow-linebreak': 0,
	'operator-linebreak': 0,
	'array-callback-return': 0,
	'arrow-parens': 0,
	'arrow-body-style': ['error', 'always'],
	'react/prefer-es6-class': 0,
	'react/jsx-no-duplicate-props': 2,
	'react/no-multi-comp': 0,
	'react/jsx-filename-extension': 0,
	'react/jsx-indent-props': [2, 'tab'],
	'react/destructuring-assignment': 'warn',
	'react/prop-types': 0,
	'react/no-find-dom-node': 1,
	'react/no-deprecated': 2,
	'react/forbid-prop-types': 0,
	'react/jsx-boolean-value': ['error', 'never'],
	'react/prefer-stateless-function': 0,
	'react/jsx-no-bind': 'error',
	'react/self-closing-comp': 'error',
	'react/sort-comp': 0,
	'react/require-default-props': 0,
	'react/no-string-refs': 0,
	'react/jsx-fragments': ['warn', 'syntax'],
	'react/jsx-props-no-spreading': 'warn',
	'react/jsx-key': 'error',
	'react/state-in-constructor': 0,
	'react/static-property-placement': 0,
	'react/react-in-jsx-scope': 'off',
	'react/jsx-uses-react': 'off',
	'jsx-a11y/media-has-caption': 1,
	'jsx-a11y/no-static-element-interactions': 1,
	'jsx-a11y/label-has-for': 'warn',
	'jsx-a11y/label-has-associated-control': 'warn',
	'jsx-a11y/anchor-is-valid': ['warn', { aspects: ['invalidHref'] }],
	'jsx-a11y/click-events-have-key-events': 'warn',
	'jsx-a11y/interactive-supports-focus': 'warn',
	'prefer-destructuring': 0,
	'simple-import-sort/imports': [
		'error',
		{
			groups: [
				// Side effect imports.
				['^\\u0000'],
				// Packages execpt @beedeez ones
				['^(?!@beedeez)'],
				// beedeez imports
				['^@beedeez'],
				// // Relative imports.
				// // Anything that starts with a dot.
				['^\\.'],
			],
		},
	],
	'simple-import-sort/exports': 'error',
	'import/first': 'error',
	'import/newline-after-import': 'error',
	'import/no-duplicates': 'error',
	'import/prefer-default-export': 0,
	'import/no-cycle': 0,
	'import/no-named-as-default': 0,
	'import/no-named-as-default-member': 1,
	'import/extensions': [
		'error',
		'never',
		{
			json: 'always',
			png: 'always',
			jpg: 'always',
			jpeg: 'always',
			gif: 'always',
		},
	],
	'import/no-unresolved': [2, { ignore: ['^shim-components/'] }],
	'import/no-extraneous-dependencies': [
		'error',
		{
			devDependencies: true,
			optionalDependencies: false,
			peerDependencies: true,
		},
	],
	'no-restricted-imports': [
		'error',
		{
			patterns: [
				// server side
				'**/../bdz-common/**/*',
				'**/../db-model/**/*',

				'@beedeez/bdz-common/src/**/*',
				'@beedeez/beedeez-db-model/src/**/*',

				// front side
				'@beedeez/beedeez-mobile-core-js/**/*',
				'@beedeez/common-react-components/**/*',
				'@beedeez/bdz-components-lib/**/*',
				'@beedeez/native-common/**/*',

				'@beedeez/front-lib-core/lib/**/*',
				'@beedeez/front-lib-react-components/lib/**/*',
				'@beedeez/front-lib-app-common/lib/**/*',
				'@beedeez/front-lib-native-shims/lib/**/*',
				'@beedeez/front-lib-components/lib/**/*',

				'**/../core/**/*',
				'**/../front-react-components/**/*',
				'**/../front-react-native-components/**/*',
				'**/../bdz-components-lib/**/*',

				// common
				'**/../lib/**/*',
			],
		},
	],
	'unicorn/prefer-string-starts-ends-with': 'error',
	'unicorn/prefer-math-trunc': 'error',
	'unicorn/prefer-includes': 'error',
	'unicorn/prefer-array-some': 'error',
	'unicorn/prefer-array-flat-map': 'warn',
	'unicorn/prefer-array-find': 'error',
	'unicorn/no-lonely-if': 'warn',
	'unicorn/prefer-string-slice': 'warn',
	'unicorn/no-instanceof-array': 'error',
	'unicorn/require-array-join-separator': 'error',
	'unicorn/consistent-function-scoping': 'warn',
	'unicorn/prefer-string-starts-ends-with': 'error',
	'unicorn/prefer-string-trim-start-end': 'error',
	'unicorn/no-nested-ternary': 'error',
	'unicorn/no-new-buffer': 'error',
	'unicorn/prefer-date-now': 'error',
	'unicorn/no-unreadable-array-destructuring': 'warn',
	'unicorn/no-array-push-push': 'warn',
	'unicorn/better-regex': 'error',
	'unicorn/no-useless-spread': 'error',
	'unicorn/no-useless-fallback-in-spread': 'error',
	'unicorn/no-invalid-remove-event-listener': 'error',
	'unicorn/prefer-set-size': 'error',
	'unicorn/filename-case': ['error', { case: 'kebabCase' }],
	'sonarjs/no-all-duplicated-branches': 'error',
	'sonarjs/no-element-overwrite': 'error',
	'sonarjs/no-extra-arguments': 'error',
	'sonarjs/no-identical-conditions': 'error',
	'sonarjs/no-identical-expressions': 'error',
	'sonarjs/no-duplicated-branches': 'warn',
	'sonarjs/no-identical-functions': 'warn',
	'sonarjs/no-inverted-boolean-check': 'error',
	'sonarjs/no-redundant-boolean': 'error',
	'sonarjs/prefer-object-literal': 'error',
	'sonarjs/no-use-of-empty-return-value': 'error',
	'sonarjs/no-same-line-conditional': 'error',
	'sonarjs/prefer-immediate-return': 'warn',
	'sonarjs/prefer-single-boolean-return': 'warn',
	'sonarjs/no-gratuitous-expressions': 'error',
	'sonarjs/no-collapsible-if': 'error',
	'sonarjs/cognitive-complexity': ['warn', 25],
	'react-native/no-single-element-style-arrays': 'error',
	'react-native/no-inline-styles': 'error',
	'react-native/no-unused-styles': 'error',
	'react-native-a11y/has-valid-accessibility-role': 2,
	'react-native-a11y/has-valid-accessibility-state': 2,
	'react-native-a11y/has-valid-important-for-accessibility': 2,
	'react-native-a11y/has-valid-accessibility-live-region': 2,
};
```

Full config :

```js
const TS_ONLY_RULES = {
	'@typescript-eslint/no-use-before-define': ['error'],
	'no-unused-vars': 'off', // see https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-unused-vars.md
	'@typescript-eslint/no-unused-vars': ['error'],
	'@typescript-eslint/no-shadow': ['error'],
	'@typescript-eslint/no-confusing-non-null-assertion': ['error'],
	'@typescript-eslint/no-extra-non-null-assertion': ['error'],
	'@typescript-eslint/prefer-optional-chain': ['error'],
	'@typescript-eslint/no-extra-non-null-assertion': ['error'],
};

const ALL_RULES = {
	'max-classes-per-file': 0,
	camelcase: 0,
	curly: ['error', 'all'],
	'new-cap': 0,
	'max-len': 0,
	'comma-dangle': 0,
	'no-dupe-keys': 2,
	'no-tabs': 0,
	'spaced-comment': 'off',
	'no-underscore-dangle': 0,
	'no-case-declarations': 0,
	'no-confusing-arrow': 0,
	'no-unused-vars': 'off',
	'no-use-before-define': 'off',
	'no-plusplus': 0,
	'no-shadow': 'off',
	'no-bitwise': 0,
	'no-mixed-operators': 0,
	'no-param-reassign': 0,
	'no-mixed-spaces-and-tabs': 0,
	'no-useless-escape': 0,
	'no-return-assign': 0,
	'no-multi-assign': 1,
	'no-console': ['error', { allow: ['warn', 'error'] }],
	'linebreak-style': 0,
	'object-curly-newline': 'off',
	'function-paren-newline': 'off',
	'id-length': 'warn',
	'consistent-return': 0,
	'default-case': 0,
	'class-methods-use-this': 0,
	'implicit-arrow-linebreak': 0,
	'operator-linebreak': 0,
	'array-callback-return': 0,
	'arrow-parens': 0,
	'arrow-body-style': ['error', 'always'],
	'react/prefer-es6-class': 0,
	'react/jsx-no-duplicate-props': 2,
	'react/no-multi-comp': 0,
	'react/jsx-filename-extension': 0,
	'react/jsx-indent-props': [2, 'tab'],
	'react/destructuring-assignment': 'warn',
	'react/prop-types': 0,
	'react/no-find-dom-node': 1,
	'react/no-deprecated': 2,
	'react/forbid-prop-types': 0,
	'react/jsx-boolean-value': ['error', 'never'],
	'react/prefer-stateless-function': 0,
	'react/jsx-no-bind': 'error',
	'react/self-closing-comp': 'error',
	'react/sort-comp': 0,
	'react/require-default-props': 0,
	'react/no-string-refs': 0,
	'react/jsx-fragments': ['warn', 'syntax'],
	'react/jsx-props-no-spreading': 'warn',
	'react/jsx-key': 'error',
	'react/state-in-constructor': 0,
	'react/static-property-placement': 0,
	'react/react-in-jsx-scope': 'off',
	'react/jsx-uses-react': 'off',
	'jsx-a11y/media-has-caption': 1,
	'jsx-a11y/no-static-element-interactions': 1,
	'jsx-a11y/label-has-for': 'warn',
	'jsx-a11y/label-has-associated-control': 'warn',
	'jsx-a11y/anchor-is-valid': ['warn', { aspects: ['invalidHref'] }],
	'jsx-a11y/click-events-have-key-events': 'warn',
	'jsx-a11y/interactive-supports-focus': 'warn',
	'prefer-destructuring': 0,
	'simple-import-sort/imports': [
		'error',
		{
			groups: [
				// Side effect imports.
				['^\\u0000'],
				// Packages execpt @beedeez ones
				['^(?!@beedeez)'],
				// beedeez imports
				['^@beedeez'],
				// // Relative imports.
				// // Anything that starts with a dot.
				['^\\.'],
			],
		},
	],
	'simple-import-sort/exports': 'error',
	'import/first': 'error',
	'import/newline-after-import': 'error',
	'import/no-duplicates': 'error',
	'import/prefer-default-export': 0,
	'import/no-cycle': 0,
	'import/no-named-as-default': 0,
	'import/no-named-as-default-member': 1,
	'import/extensions': [
		'error',
		'never',
		{
			json: 'always',
			png: 'always',
			jpg: 'always',
			jpeg: 'always',
			gif: 'always',
		},
	],
	'import/no-unresolved': [2, { ignore: ['^shim-components/'] }],
	'import/no-extraneous-dependencies': [
		'error',
		{
			devDependencies: true,
			optionalDependencies: false,
			peerDependencies: true,
		},
	],
	'no-restricted-imports': [
		'error',
		{
			patterns: [
				// server side
				'**/../bdz-common/**/*',
				'**/../db-model/**/*',

				'@beedeez/bdz-common/src/**/*',
				'@beedeez/beedeez-db-model/src/**/*',

				// front side
				'@beedeez/beedeez-mobile-core-js/**/*',
				'@beedeez/common-react-components/**/*',
				'@beedeez/bdz-components-lib/**/*',
				'@beedeez/native-common/**/*',

				'@beedeez/front-lib-core/lib/**/*',
				'@beedeez/front-lib-react-components/lib/**/*',
				'@beedeez/front-lib-app-common/lib/**/*',
				'@beedeez/front-lib-native-shims/lib/**/*',
				'@beedeez/front-lib-components/lib/**/*',

				'**/../core/**/*',
				'**/../front-react-components/**/*',
				'**/../front-react-native-components/**/*',
				'**/../bdz-components-lib/**/*',

				// common
				'**/../lib/**/*',
			],
		},
	],
	'unicorn/prefer-string-starts-ends-with': 'error',
	'unicorn/prefer-math-trunc': 'error',
	'unicorn/prefer-includes': 'error',
	'unicorn/prefer-array-some': 'error',
	'unicorn/prefer-array-flat-map': 'warn',
	'unicorn/prefer-array-find': 'error',
	'unicorn/no-lonely-if': 'warn',
	'unicorn/prefer-string-slice': 'warn',
	'unicorn/no-instanceof-array': 'error',
	'unicorn/require-array-join-separator': 'error',
	'unicorn/consistent-function-scoping': 'warn',
	'unicorn/prefer-string-starts-ends-with': 'error',
	'unicorn/prefer-string-trim-start-end': 'error',
	'unicorn/no-nested-ternary': 'error',
	'unicorn/no-new-buffer': 'error',
	'unicorn/prefer-date-now': 'error',
	'unicorn/no-unreadable-array-destructuring': 'warn',
	'unicorn/no-array-push-push': 'warn',
	'unicorn/better-regex': 'error',
	'unicorn/no-useless-spread': 'error',
	'unicorn/no-useless-fallback-in-spread': 'error',
	'unicorn/no-invalid-remove-event-listener': 'error',
	'unicorn/prefer-set-size': 'error',
	'unicorn/filename-case': ['error', { case: 'kebabCase' }],
	'sonarjs/no-all-duplicated-branches': 'error',
	'sonarjs/no-element-overwrite': 'error',
	'sonarjs/no-extra-arguments': 'error',
	'sonarjs/no-identical-conditions': 'error',
	'sonarjs/no-identical-expressions': 'error',
	'sonarjs/no-duplicated-branches': 'warn',
	'sonarjs/no-identical-functions': 'warn',
	'sonarjs/no-inverted-boolean-check': 'error',
	'sonarjs/no-redundant-boolean': 'error',
	'sonarjs/prefer-object-literal': 'error',
	'sonarjs/no-use-of-empty-return-value': 'error',
	'sonarjs/no-same-line-conditional': 'error',
	'sonarjs/prefer-immediate-return': 'warn',
	'sonarjs/prefer-single-boolean-return': 'warn',
	'sonarjs/no-gratuitous-expressions': 'error',
	'sonarjs/no-collapsible-if': 'error',
	'sonarjs/cognitive-complexity': ['warn', 25],
	'react-native/no-single-element-style-arrays': 'error',
	'react-native/no-inline-styles': 'error',
	'react-native/no-unused-styles': 'error',
	'react-native-a11y/has-valid-accessibility-role': 2,
	'react-native-a11y/has-valid-accessibility-state': 2,
	'react-native-a11y/has-valid-important-for-accessibility': 2,
	'react-native-a11y/has-valid-accessibility-live-region': 2,
};

const ALL_PLUGINS = [
	'simple-import-sort',
	'import',
	'unicorn',
	'sonarjs',
	'prettier',
	'react-native',
];

const ALL_EXTENDS = [
	'airbnb',
	'prettier',
	'plugin:react-hooks/recommended',
	'plugin:react-native-a11y/all',
];

const ENVS = {
	es2021: true,
	'react-native/react-native': true,
	browser: true,
	es6: true,
	node: true,
};

const SETTINGS = {
	'import/parsers': {
		'@typescript-eslint/parser': ['.ts', '.tsx'],
		'@babel/eslint-parser': ['.js', '.jsx'],
	},
	'import/resolver': {
		node: {
			extensions: ['.js', '.jsx', '.ts', '.tsx'],
		},
		typescript: {
			project: 'packages/*/tsconfig.json',
		},
	},
};

module.exports = {
	extends: [...ALL_EXTENDS],
	plugins: [...ALL_PLUGINS],
	globals: {
		JSX: 'readonly',
	},
	parser: '@babel/eslint-parser',
	settings: { ...SETTINGS },
	parserOptions: {
		ecmaFeatures: { jsx: true },
		ecmaVersion: 'latest',
		sourceType: 'module',
		requireConfigFile: false,
		babelOptions: {
			plugins: [
				'@babel/plugin-proposal-class-properties',
				'@babel/plugin-proposal-object-rest-spread',
				'@babel/plugin-proposal-optional-chaining',
				'@babel/plugin-proposal-export-default-from',
			],
			presets: [
				[
					'@babel/preset-env',
					{
						targets: '> 1%, Last 2 versions, ie 11, not op_mini all',
						useBuiltIns: 'entry',
						corejs: 3,
					},
				],
				[
					'@babel/preset-react',
					{
						runtime: 'automatic',
					},
				],
			],
		},
	},
	rules: {
		...ALL_RULES,
	},
	env: {
		...ENVS,
	},
	overrides: [
		{
			files: ['**/*.{ts,tsx}'],
			extends: [...ALL_EXTENDS],
			plugins: ['@typescript-eslint', ...ALL_PLUGINS],
			parser: '@typescript-eslint/parser',
			rules: {
				...ALL_RULES,
				...TS_ONLY_RULES,
			},
			globals: {
				JSX: 'readonly',
			},
			parserOptions: {
				ecmaFeatures: { jsx: true },
			},
			settings: {
				...SETTINGS,
			},
		},
	],
};
```

### What did you expect to happen?

To work

### What actually happened?

It's not working

### Link to Minimal Reproducible Example

don't have

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @billouboq, thanks for the issue!

Can you please provide a repro repo so we could take a look?

I'm guessing you somehow have an older version of the `escape-string-regexp` package installed instead of required `^4.0.0` version. Deleting and installing `node_modules` again would probably solve the issue.

**Comment by billouboq** [comment]
@mdjermanovic That's must be that, had to resolve to a specific version, will remote it, thank you so much !
