### ISSUE TITLE
Bug: eslint with jsdoc plugin crashs after update to 8.45.0

### ISSUE THREAD

**Issue by JoergAtGithub** [eslint/eslint#17374]
### Environment

Local ESLint version: 8.45.0
Operating System: GitHub Ubuntu 20.4

### What parser are you using?

Default (Espree)

### What did you do?

I execute a GitHub CI run by for a JajaScript file which passed the eslint check before. This time pre-commit updated eslint to the new version 8.45.0 and it crashed: https://github.com/mixxxdj/mixxx/actions/runs/5569071865/jobs/10172250150

### What did you expect to happen?

The same as in the run before update to 8.45.0. No crash and Pass as result, because the JS file is unchanged. 

### What actually happened?

```
023-07-16T18:19:19.4099834Z eslint...................................................................[41mFailed[m
2023-07-16T18:19:19.4100517Z [2m- hook id: eslint[m
2023-07-16T18:19:19.4101351Z [2m- exit code: 2[m
2023-07-16T18:19:19.4101536Z 
2023-07-16T18:19:19.4106620Z Oops! Something went wrong! :(
2023-07-16T18:19:19.4107121Z 
2023-07-16T18:19:19.4107255Z ESLint: 8.45.0
2023-07-16T18:19:19.4107427Z 
2023-07-16T18:19:19.4108139Z TypeError: Cannot read properties of undefined (reading 'typeAnnotation')
2023-07-16T18:19:19.4108659Z Occurred while linting /__w/mixxx/mixxx/res/controllers/Traktor-Kontrol-Z2-hid-scripts.js:29
2023-07-16T18:19:19.4109065Z Rule: "jsdoc/check-param-names"
2023-07-16T18:19:19.4109664Z     at getParamName (/github/home/.cache/pre-commit/repoft31l0fp/node_env-default/lib/node_modules/eslint-plugin-jsdoc/dist/jsdocUtils.js:129:26)
2023-07-16T18:19:19.4110315Z     at /github/home/.cache/pre-commit/repoft31l0fp/node_env-default/lib/node_modules/eslint-plugin-jsdoc/dist/jsdocUtils.js:258:12
2023-07-16T18:19:19.4110705Z     at Array.map (<anonymous>)
2023-07-16T18:19:19.4111287Z     at Object.getFunctionParameterNames (/github/home/.cache/pre-commit/repoft31l0fp/node_env-default/lib/node_modules/eslint-plugin-jsdoc/dist/jsdocUtils.js:257:61)
2023-07-16T18:19:19.4112087Z     at utils.getFunctionParameterNames (/github/home/.cache/pre-commit/repoft31l0fp/node_env-default/lib/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:434:32)
2023-07-16T18:19:19.4112862Z     at _default.meta.docs.description (/github/home/.cache/pre-commit/repoft31l0fp/node_env-default/lib/node_modules/eslint-plugin-jsdoc/dist/rules/checkParamNames.js:269:40)
2023-07-16T18:19:19.4113576Z     at iterate (/github/home/.cache/pre-commit/repoft31l0fp/node_env-default/lib/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:825:3)
2023-07-16T18:19:19.4114232Z     at checkJsdoc (/github/home/.cache/pre-commit/repoft31l0fp/node_env-default/lib/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:1127:9)
2023-07-16T18:19:19.4115282Z     at ruleErrorHandler (/github/home/.cache/pre-commit/repoft31l0fp/node_env-default/lib/node_modules/eslint/lib/linter/linter.js:1050:28)
2023-07-16T18:19:19.4115886Z     at /github/home/.cache/pre-commit/repoft31l0fp/node_env-default/lib/node_modules/eslint/lib/linter/safe-emitter.js:45:58
2023-07-16T18:19:19.4116144Z 
```

The JS code where eslint crashed looks as follows:
```
class DeckClass {
    /**
     * Creates an instance of DeckClass.
     *
     * @param {TraktorZ2Class} parent
     * @param {number} deckNumber
     * @param {string} group
     */
    constructor(parent, deckNumber, group) {
        /** @type {TraktorZ2Class} */
        this.parent = parent;
```

https://github.com/mixxxdj/mixxx/blob/29c88aff408cff5218765efec578a46f7d3b85f9/res/controllers/Traktor-Kontrol-Z2-hid-scripts.js#L21-L31

### Link to Minimal Reproducible Example

https://github.com/mixxxdj/mixxx/pull/3038

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Rec0iL99** [comment]
Hi @JoergAtGithub, thanks for the issue. Looks like the error is coming from `eslint-plugin-jsdoc`, a 3rd party plugin that's not maintained by the ESLint team. The best course of action here would be to open the issue there.

Leaving this open for the core team to verify since `v8.45.0` is a new release. 

cc @eslint/eslint-team

**Comment by nzakas** [comment]
@JoergAtGithub we need a minimal reproduction case to verify. Please set up a StackBlitz or small repo that isolates this behavior so we can take a look.

**Comment by nzakas** [comment]
This is not related to the ESLint release. `eslint-plugin-jsdoc` published a release this past weekend, and it appears the problem is in their release. Please  open an issue there:

https://github.com/gajus/eslint-plugin-jsdoc/issues
