### ISSUE TITLE
Flat Config - key rules: key X Could not find plugin X

### ISSUE THREAD

**Issue by ivodolenc** [eslint/eslint#17485]
### Environment

Node version: 18.17.1
npm version: 9.8.1
Local ESLint version: 8.47.0
Global ESLint version: -
Operating System: macos ventura 13.5

### What parser are you using?

@typescript-eslint/parser

### What did you do?

Hi, since this works with a workarounds, I believe it's a potential bug.

I have a shearable eslint (new flat config) configuration which you can see [here](https://github.com/ivodolenc/configshare/tree/main/src/eslint).

Here is a local eslint `config` example:

```js
// cli command (package.json)

{
  "scripts": {
    "lint": "ESLINT_USE_FLAT_CONFIG=true eslint ."
  },
}
```

```js
// eslint.config.js

import { jsConfig, tsConfig, ignoresConfig } from 'configshare/eslint'

export default [
  jsConfig,
  tsConfig,
  ignoresConfig,
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { ignoreRestSiblings: true },
      ],
    },
  },
]
```

All works fine as expected. The code analysis and live rule checking works fine so far and if the manual check is not started, you may not even notice that something is wrong.

But as soon as I run the cli command `npm run lint` I get the below error:

```text
Oops! Something went wrong! :(

ESLint: 8.47.0

TypeError: Key "rules": Key "@typescript-eslint/no-unused-vars": Could not find plugin "@typescript-eslint".
    at throwRuleNotFoundError (.../node_modules/eslint/lib/config/rule-validator.js:65:11)
    at RuleValidator.validate (.../node_modules/eslint/lib/config/rule-validator.js:127:17)
    at [finalizeConfig] (.../node_modules/eslint/lib/config/flat-config-array.js:231:23)
    at FlatConfigArray.getConfig (.../node_modules/@humanwhocodes/config-array/api.js:919:55)
    at FlatConfigArray.isFileIgnored (.../node_modules/@humanwhocodes/config-array/api.js:943:15)
    at .../node_modules/eslint/lib/eslint/eslint-helpers.js:312:49
    at Array.reduce (<anonymous>)
    at entryFilter (.../node_modules/eslint/lib/eslint/eslint-helpers.js:299:28)
    at Object.isAppliedFilter (.../node_modules/@nodelib/fs.walk/out/readers/common.js:12:31)
    at AsyncReader._handleEntry (.../node_modules/@nodelib/fs.walk/out/readers/async.js:86:20)
```

Also, if any rule has a value other than `'off'` the same will not work.

It turns out that if custom rules need additional settings, the cli command throws an error, but only in the case of manual triggering.

### Workaround 1

This example works fine when I run the same command `npm run lint`:

```js
// eslint.config.js

import { jsConfig, tsConfig, ignoresConfig } from 'configshare/eslint'

export default [
  jsConfig,
  tsConfig,
  ignoresConfig,
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
    },
  },
]
```

### Workaround 2

This example also works fine when I run the same command `npm run lint`:

```js
// eslint.config.js

import tsPlugin from '@typescript-eslint/eslint-plugin'
import { jsConfig, tsConfig, ignoresConfig } from 'configshare/eslint'

export default [
  jsConfig,
  tsConfig,
  ignoresConfig,
  {
    plugins: { '@typescript-eslint': tsPlugin }, // this is already defined inside `tsConfig` object so there is no need to add it again
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { ignoreRestSiblings: true },
      ],
    },
  },
]
```

### What did you expect to happen?

No errors.

### What actually happened?

-

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Your `tsConfig` adds `'@typescript-eslint'` plugin for [typescript files only](https://github.com/ivodolenc/configshare/blob/90d24e877c595f9b89fe0e3637e999cd7cef591c/src/eslint/ts-config.js#L7), but in `eslint.config.js` you're enabling typescript-eslint plugin rules for all files, so I'd guess that the error is thrown when calculating config for a javascript file, which would be expected behavior because the configuration does not enable `'@typescript-eslint'` plugin for javascript files.

Can you try this:

```diff
// eslint.config.js

import { jsConfig, tsConfig, ignoresConfig } from 'configshare/eslint'

export default [
  jsConfig,
  tsConfig,
  ignoresConfig,
  {
+   files: ['**/*.{ts,mts,cts}'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { ignoreRestSiblings: true },
      ],
    },
  },
]
```

Otherwise, please provide a link to a minimal reproducible example so we could take a look.

**Comment by ivodolenc** [comment]
@mdjermanovic Tnx for quick reply.

Yep, [this](https://github.com/eslint/eslint/issues/17485#issuecomment-1686051251) works without errors.

I was expecting that once I set the `files`, `ignores` and `globalIgnores`, I'd never have to adjust them again, because that's what shareable configurations are for.

---

Quick question, couldn't this be solved by using IDs or a simpler system?

So, in each object, the user defines a specific `id` and eslint later, during the final config resolving, all the options merges by the ids.

If I set the `id` main options once, every time I want to extend that object I simply add the `id` and the eslint would know what to do with it.

```js
// shareable config

export const tsConfig = {
  id: 'ts-config', // unique object ID
  files: ['**/*.{ts,mts,cts}'],
  languageOptions: {
    parser: tsParser,
    parserOptions: {
      sourceType: 'module',
      ecmaVersion: 'latest',
    },
  },
  plugins: {
    '@typescript-eslint': tsPlugin,
  },
  rules: {
    // ...
  },
}
```

```js
// eslint.config.js

import { tsConfig } from 'shareable-config'

export default [
  tsConfig,
  {
    id: 'ts-config', // this is much simpler than defining all the glob patterns each time
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { ignoreRestSiblings: true },
      ],
    },
  },
]
```
