### ISSUE TITLE
Bug: npm init @eslint/config with "Standard" style generates incorrect setup

### ISSUE THREAD

**Issue by OnkelTem** [eslint/eslint#17480]
### Environment

Node version:  16.17
npm version: 8.15
Local ESLint version: 8.47
Global ESLint version: 
Operating System: Linux Ubuntu 22.04

### What parser are you using?

Default (Espree)

### What did you do?

I'm running the configuration wizard like this:

```
npm init @eslint/config
✔ How would you like to use ESLint? · style
✔ What type of modules does your project use? · esm
✔ Which framework does your project use? · none
✔ Does your project use TypeScript? · No / Yes
✔ Where does your code run? · browser
✔ How would you like to define a style for your project? · guide
✔ Which style guide do you want to follow? · standard-with-typescript
✔ What format do you want your config file to be in? · JavaScript
Checking peerDependencies of eslint-config-standard-with-typescript@latest
Local ESLint installation not found.
The config that you've selected requires the following dependencies:

eslint-config-standard-with-typescript@latest @typescript-eslint/eslint-plugin@^5.52.0 eslint@^8.0.1 eslint-plugin-import@^2.25.2 eslint-plugin-n@^15.0.0 || ^16.0.0  eslint-plugin-promise@^6.0.0 typescript@*
✔ Would you like to install them now? · No / Yes
✔ Which package manager do you want to use? · npm
Installing eslint-config-standard-with-typescript@latest, @typescript-eslint/eslint-plugin@^5.52.0, eslint@^8.0.1, eslint-plugin-import@^2.25.2, eslint-plugin-n@^15.0.0 || ^16.0.0 , eslint-plugin-promise@^6.0.0, typescript@*
```

### What did you expect to happen?

Working linting

### What actually happened?

After it finishes,  running `eslint` results to this error:
```
$ $npx eslint './src/**/*.ts'

Oops! Something went wrong! :(

ESLint: 8.47.0

Error: Error while loading rule '@typescript-eslint/dot-notation': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Occurred while linting /projects/custom/eslint/tts/src/index.ts
    at getParserServices (/projects/custom/eslint/tts/node_modules/@typescript-eslint/utils/dist/eslint-utils/getParserServices.js:22:15)
    at create (/projects/custom/eslint/tts/node_modules/@typescript-eslint/eslint-plugin/dist/rules/dot-notation.js:85:81)
    at Object.create (/projects/custom/eslint/tts/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:41:20)
    at createRuleListeners (/projects/custom/eslint/tts/node_modules/eslint/lib/linter/linter.js:870:21)
    at /projects/custom/eslint/tts/node_modules/eslint/lib/linter/linter.js:1040:110
    at Array.forEach (<anonymous>)
    at runRules (/projects/custom/eslint/tts/node_modules/eslint/lib/linter/linter.js:977:34)
    at Linter._verifyWithoutProcessors (/projects/custom/eslint/tts/node_modules/eslint/lib/linter/linter.js:1330:31)
    at Linter._verifyWithConfigArray (/projects/custom/eslint/tts/node_modules/eslint/lib/linter/linter.js:1706:21)
    at Linter.verify (/projects/custom/eslint/tts/node_modules/eslint/lib/linter/linter.js:1412:65)

```

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by OnkelTem** [comment]
Before creating this ticket, I [created a similar issue](https://github.com/standard/eslint-config-standard-with-typescript/issues/1225) in the **eslint-config-standard-with-typescript** repository, assuming that its maintainers would know better what to do. And in fact, this is how to fix the problem:

![image](https://github.com/eslint/eslint/assets/114060/6845d4d0-4225-488e-b2bd-16757d1f5164)

which is covered in the docs here: https://typescript-eslint.io/linting/typed-linting/

I believe that the rule '@typescript-eslint/dot-notation' makes this error trigger. 

Also, I find it doubtful to not see the proper `parser` value in the user config.
