### ISSUE TITLE
Bug: ESLint Error: Cannot find module 'inquirer'

### ISSUE THREAD

**Issue by erosman** [eslint/eslint#17704]
### Environment

Node version: 
npm version: 9.2.0
Local ESLint version: 6.4.0
Global ESLint version: 
Operating System: Ubuntu 23.10

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

First install, default, nothing configured yet

### What did you expect to happen?

I am trying to install ESLint in VS Code (without React or Prettier) but I get the following error.
VS Code ESLint extension has been installed.

VS Code Terminal/Ubuntu Terminal
```
$ eslint --init

Error: Cannot find module 'inquirer'
Require stack:
- /usr/share/nodejs/eslint/lib/init/config-initializer.js
- /usr/share/nodejs/eslint/bin/eslint.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (/usr/share/nodejs/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/usr/share/nodejs/eslint/lib/init/config-initializer.js:15:16)
    at Module._compile (/usr/share/nodejs/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
```

Tried the following in Ubuntu terminal
```
$ npm install inquirer
```

Also ...
```
$ npm install --save inquirer
```

Ubuntu 23.10  
VS Code 1.84.0  
nodejs 18.13.0  
npm 9.2.0  
eslint 6.4.0  
inquirer 9.2.11  

### What actually happened?

refer to above

### Link to Minimal Reproducible Example

n/a

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Rec0iL99** [comment]
Hi @erosman, thanks for issue. We require a reproducible example for bug reports. Please provide one.

**Comment by erosman** [comment]
It is the initial installation

- Install nodejs
- Instal eslint
- Install VS Code ESLint extension
- terminal: eslint --init

However, I tried the following and it seems to work `npm init @eslint/config`

**Comment by erosman** [comment]
After some testing, the initial [VS Code ESLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) command "ESLint: Create ESLint configuration" causes the above error.
