### ISSUE TITLE
Arrow function expression throws exception

### ISSUE THREAD

**Issue by dmnd** [eslint/eslint#1789]
```
$ eslint -v
v0.14.0


$ eslint test.jsx 

/usr/local/lib/node_modules/eslint/lib/rules/no-extra-strict.js:17
        for (i = 0, l = body.length; i < l; ++i) {
                            ^
TypeError: Cannot read property 'length' of undefined
    at directives (/usr/local/lib/node_modules/eslint/lib/rules/no-extra-strict.js:17:29)
    at checkForUnnecessaryUseStrict (/usr/local/lib/node_modules/eslint/lib/rules/no-extra-strict.js:38:35)
    at EventEmitter.ArrowFunctionExpression (/usr/local/lib/node_modules/eslint/lib/rules/no-extra-strict.js:69:13)
    at EventEmitter.emit (events.js:117:20)
    at Controller.controller.traverse.enter (/usr/local/lib/node_modules/eslint/lib/eslint.js:673:25)
    at Controller.__execute (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/eslint/lib/eslint.js:666:24)
    at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:172:27)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:278:26

$ cat test.jsx 
var fn = x => 1;


$ cat .eslintrc 
env:
  browser: true,
  node: true

ecmaFeatures:
  arrowFunctions: true

```

**Comment by lo1tuma** [comment]
Looks like a bug in [`no-extra-strict`](http://eslint.org/docs/rules/no-extra-strict.html), which is deprecated.
Can you try switching to the [`strict`](http://eslint.org/docs/rules/strict.html) rule, maybe this would solve the problem.

**Comment by dmnd** [comment]
I don't have `no-extra-strict` in my `.eslintrc`. But I just disabled it in my config, and ended up with this:

```
$ eslint test.js 

/usr/local/lib/node_modules/eslint/lib/rules/strict.js:111
            isStrict = isStrictPragma(node.body.body[0]) || isParentStrict;
                                                    ^
TypeError: Cannot read property '0' of undefined
    at EventEmitter.enterScope (/usr/local/lib/node_modules/eslint/lib/rules/strict.js:111:53)
    at EventEmitter.emit (events.js:117:20)
    at Controller.controller.traverse.enter (/usr/local/lib/node_modules/eslint/lib/eslint.js:673:25)
    at Controller.__execute (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/eslint/lib/eslint.js:666:24)
    at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:172:27)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:278:26
    at walk (/usr/local/lib/node_modules/eslint/lib/util/traverse.js:81:9)
    at /usr/local/lib/node_modules/eslint/lib/util/traverse.js:102:9


$ cat test.js 
var fn = x => 1;


$ cat .eslintrc 
env:
  browser: true,
  node: true

ecmaFeatures:
  arrowFunctions: true

rules:
  no-extra-strict: 0
```

**Comment by nzakas** [comment]
Working on this.
