### ISSUE TITLE
Bug: Cannot read properties of undefined (reading 'ignores')

### ISSUE THREAD

**Issue by FirelightFlagboy** [eslint/eslint#18094]
### Environment

Node version: v16.20.2
npm version: v8.19.4
Local ESLint version: v8.56.0 (Currently used)
Global ESLint version: Not found
Operating System: linux 6.7.3-arch1-2

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

`eslint.config.js`:

```js
const typescript_plugin = require('@typescript-eslint/eslint-plugin')
const typescript_parser = require('@typescript-eslint/parser')

module.exports = [
  {
    plugins: {
      typescript_plugin
    },
    languageOptions: {
      parser: typescript_parser
    },
    ignores: [],
    rules: {}
  },
  // extends ...
  typescript_plugin.configs.eslint_recommended
]
```

`package.json`:

```json
{
  "name": "[redacted]",
  "version": "0.0.1",
  "engines": {
    "node": "16.17"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^12.0.2",
    "@angular/cdk": "^12.0.2",
    "@angular/common": "^12.0.2",
    "@angular/compiler": "^12.0.2",
    "@angular/core": "^12.0.2",
    "@angular/forms": "^12.0.2",
    "@angular/material": "^12.0.2",
    "@angular/platform-browser": "^12.0.2",
    "@angular/platform-browser-dynamic": "^12.0.2",
    "@angular/router": "^12.0.2",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@stripe/stripe-js": "^1.15.0",
    "bootstrap": "^4.6.0",
    "core-js": "^3.13.1",
    "express": "^4.17.1",
    "force-ssl-heroku": "^1.0.2",
    "google-libphonenumber": "^3.2.21",
    "latest-version": "^5.1.0",
    "ng-recaptcha": "^8.0.0",
    "ng2-pdf-viewer": "6.4.1",
    "ngx-stripe": "^12.0.1",
    "path": "^0.12.7",
    "rxjs": "^6.6.7",
    "tslib": "^2.2.0",
    "zone.js": "^0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^12.0.2",
    "@angular/cli": "^12.0.2",
    "@angular/compiler-cli": "^12.0.2",
    "@angular/language-service": "^12.0.2",
    "@eslint/eslintrc": "^3.0.0",
    "@types/jasmine": "^3.7.6",
    "@types/jasminewd2": "^2.0.9",
    "@types/node": "^12.20.13",
    "@typescript-eslint/eslint-plugin": "^6.21.0",
    "@typescript-eslint/parser": "^6.21.0",
    "codelyzer": "^6.0.2",
    "eslint": "^8.56.0",
    "jasmine-core": "~3.8.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "^6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.7.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.7.0",
    "typescript": "^4.2.4"
  }
}
```

</details>

No code involved, `eslint` crash at the startup

### What did you expect to happen?

That `eslint` lint the repository without crashing :sweat_smile: 

### What actually happened?

```

Oops! Something went wrong! :(

ESLint: 8.56.0

TypeError: Cannot read properties of undefined (reading 'ignores')
    at FlatConfigArray.get ignores [as ignores] ([redacted]/node_modules/@humanwhocodes/config-array/api.js:648:15)
    at FlatConfigArray.isDirectoryIgnored ([redacted]/node_modules/@humanwhocodes/config-array/api.js:1012:10)
    at FlatConfigArray.getConfig ([redacted]/node_modules/@humanwhocodes/config-array/api.js:806:12)
    at FlatConfigArray.isFileIgnored ([redacted]/node_modules/@humanwhocodes/config-array/api.js:962:15)
    at [redacted]/node_modules/eslint/lib/eslint/eslint-helpers.js:312:49
    at Array.reduce (<anonymous>)
    at entryFilter ([redacted]/node_modules/eslint/lib/eslint/eslint-helpers.js:299:28)
    at Object.isAppliedFilter ([redacted]/node_modules/@nodelib/fs.walk/out/readers/common.js:12:31)
    at AsyncReader._handleEntry ([redacted]/node_modules/@nodelib/fs.walk/out/readers/async.js:86:20)
    at [redacted]/node_modules/@nodelib/fs.walk/out/readers/async.js:65:22
```

### Link to Minimal Reproducible Example

https://github.com/FirelightFlagboy/eslint-cannot-read-property-of-undefined-reading-ignores

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
> ```js
> typescript_plugin.configs.eslint_recommended
> ```

Can you check what the value of `typescript_plugin.configs.eslint_recommended` is? It could be that `@typescript-eslint/eslint-plugin` doesn't export a config named `eslint_recommended`, in which case this would be `undefined`.

**Comment by FirelightFlagboy** [comment]
The value of `typescript_plugin.configs.eslint_recommended` should be:

```js
"use strict";
module.exports = {
    overrides: [
        {
            files: ['*.ts', '*.tsx', '*.mts', '*.cts'],
            rules: {
                'constructor-super': 'off', // ts(2335) & ts(2377)
                'getter-return': 'off', // ts(2378)
                'no-const-assign': 'off', // ts(2588)
                'no-dupe-args': 'off', // ts(2300)
                'no-dupe-class-members': 'off', // ts(2393) & ts(2300)
                'no-dupe-keys': 'off', // ts(1117)
                'no-func-assign': 'off', // ts(2630)
                'no-import-assign': 'off', // ts(2632) & ts(2540)
                'no-new-symbol': 'off', // ts(7009)
                'no-obj-calls': 'off', // ts(2349)
                'no-redeclare': 'off', // ts(2451)
                'no-setter-return': 'off', // ts(2408)
                'no-this-before-super': 'off', // ts(2376) & ts(17009)
                'no-undef': 'off', // ts(2304) & ts(2552)
                'no-unreachable': 'off', // ts(7027)
                'no-unsafe-negation': 'off', // ts(2365) & ts(2322) & ts(2358)
                'no-var': 'error', // ts transpiles let/const to var, so no need for vars any more
                'prefer-const': 'error', // ts provides better types with const
                'prefer-rest-params': 'error', // ts provides better types with rest args over arguments
                'prefer-spread': 'error', // ts transpiles spread to apply, so no need for manual apply
            },
        },
    ],
};
//# sourceMappingURL=eslint-recommended.js.map
```

I've extract the value from `node_modules/@typescript-eslint/eslint-plugin/dist/configs/eslint-recommended.js`

**Comment by snitin315** [comment]
@FirelightFlagboy As per https://github.com/typescript-eslint/typescript-eslint/pull/7935#issue-1994634097, you can't use `'@typescript-eslint/eslint-plugin'` for flat config, there is a different package `typescript-eslint`. [The new usage is mentioned in this doc](https://github.com/typescript-eslint/typescript-eslint/blob/main/docs/packages/TypeScript_ESLint.mdx)


If that still doesn't work for you, can you open an issue in typescript-eslint repo instead?

**Comment by G-Rath** [comment]
> It could be that @typescript-eslint/eslint-plugin doesn't export a config named eslint_recommended, in which case this would be undefined.

I came across this while testing some `eslint-plugin-jest` stuff for our next major, because we removed our `flat/snapshot` config - it took me a few minutes to track down what was happening and seems a bit surprising; I know in flat config ESLint can't say for sure this is the case, but I think it would be nice if there could be an explicit `undefined` check so we get a more helpful "hey you've provided undefined which is never valid; are you maybe trying to use a config that doesn't exist?" type message rather than a generic property access (which is also implementation dependent - right now it happens to be `ignores` but in future ESLint might do something before that section of code, changing the error message).

I'm happy to open an issue and even attempt a PR if people think that would be a good idea.
