### ISSUE TITLE
Bug: "TypeError: context.getScope is not a function" in no-floating-promise

### ISSUE THREAD

**Issue by emaxx-google** [eslint/eslint#18277]
### Environment

Node version: v18.19.1
npm version: 9.2.0
Local ESLint version: 9.0.0
Global ESLint version: 9.0.0
Operating System: Ubuntu

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
env:
  browser: true
  es2020: true
extends: eslint:recommended
plugins:
  - no-floating-promise
rules:
  no-floating-promise/no-floating-promise: error
```
</details>

```js
GSC.AsyncAsserts.assertThrows = async function (func) {
  try {
    await func();
  } catch (e) {
    return e;
  }
  fail('Unexpectedly no exception in function');
  goog.asserts.fail();
};
```

### What did you expect to happen?

Succeed on the same source files on which ESLint 8.x succeeded.

### What actually happened?

```
TypeError: context.getScope is not a function
Occurred while linting /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/common/js/src/async-asserts.js:36
Rule: "no-floating-promise/no-floating-promise"
    at ExpressionStatement > CallExpression (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/node_modules/eslint-plugin-no-floating-promise/lib/rules/no-floating-promise.js:148:58)
    at ruleErrorHandler (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/node_modules/eslint/lib/linter/linter.js:1145:48)
    at /home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/node_modules/eslint/lib/linter/node-event-generator.js:326:[22](https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/actions/runs/8577666631/job/23510543074#step:5:23))
    at NodeEventGenerator.enterNode (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at runRules (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/node_modules/eslint/lib/linter/linter.js:1184:40)
    at Linter._verifyWithoutProcessors (/home/runner/work/chromeos_smart_card_connector/chromeos_smart_card_connector/env/node_modules/eslint/lib/linter/linter.js:1453:31)
```

### Link to Minimal Reproducible Example

https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/actions/runs/8577666631/job/23510543074

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

The problem is in the `no-floating-promise` plugin, still I'm reporting it here as well since backwards-incompatible change in 9.0.0 might be unexpected?..

**Comment by ota-meshi** [comment]
Hi @emaxx-google 
I think you need to contact the author of eslint-plugin-no-floating-promise and have them fix the plugin.

https://eslint.org/docs/latest/use/migrate-to-9.0.0#breaking-changes-for-plugin-developers

**Comment by emaxx-google** [comment]
Thanks, the report already filed there: https://github.com/SebastienGllmt/eslint-plugin-no-floating-promise/issues/16 (although it's unclear whether the plugin is still maintained for any major changes). Thank you for providing the link - I've copied it there.

**Comment by fasttime** [comment]
Thanks for the report @emaxx-google. `context.getScope` has been removed in ESLint v9, you can read more about the background of this change in [this blog post](https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/#from-context-to-sourcecode).
