### ISSUE TITLE
Bug: Error in npx eslint . command in latest version 9.0.0

### ISSUE THREAD

**Issue by DSY4444** [eslint/eslint#18308]
### Environment

Node version: 9.0.0
npm version: 
Local ESLint version: 
Global ESLint version: 
Operating System: 

### What parser are you using?

Default (Espree)

### What did you do?

npx eslint .

### What did you expect to happen?

It should work like previous versions 

### What actually happened?

when i am doing npx eslint . in latest version 9.0.0 , it gives error

Oops! Something went wrong! :(

ESLint: 9.0.0

Error: Could not find config file.
    at locateConfigFileToUse (/Users/ds/Project/yarkensol/server-api/node_modules/eslint/lib/eslint/eslint.js:349:21)
    at async calculateConfigArray (/Users/ds/Project/yarkensol/server-api/node_modules/eslint/lib/eslint/eslint.js:384:49)
    at async ESLint.lintFiles (/Users/ds/Project/yarkensol/server-api/node_modules/eslint/lib/eslint/eslint.js:814:25)
    at async Object.execute (/Users/ds/Project/yarkensol/server-api/node_modules/eslint/lib/cli.js:461:23)
    at async main (/Users/ds/Project/yarkensol/server-api/node_modules/eslint/bin/eslint.js:165:22)

### Link to Minimal Reproducible Example

npx eslint .

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aladdin-add** [comment]
flat configs were enabled by default since eslint v9.

please read our migration guide: https://eslint.org/docs/latest/use/migrate-to-9.0.0#flat-config
