### ISSUE TITLE
ESLint crashes on non-existing file

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#1831]
When passing non-existing file to ESLint, you get a crash with a stack dump. I know that was changed in #1400 But the code hasn't been cleaned up correctly. CLIEngine has an else statement that kicks in when file doesn't exist, which is never hit. Either that else statement has to be removed or #1400 should be reverted and original code should be fixed (in original code, catch was just returning, when it really should call callback function and let CLIEngine handle error message).

**Comment by nzakas** [comment]
Can you paste in the console output when this happens?

**Comment by ilyavolodin** [comment]
```
$ eslint -v
v0.14.1

$ eslint blah.js

fs.js:695
  return binding.stat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'c:\Users\Ilya\Documents\github\eslint\blah.js'
    at Object.fs.statSync (fs.js:695:18)
    at walk (c:\Users\Ilya\AppData\Roaming\npm\node_modules\eslint\lib\util\traverse.js:36:15)
    at c:\Users\Ilya\AppData\Roaming\npm\node_modules\eslint\lib\util\traverse.js:102:9
    at Array.forEach (native)
    at traverse (c:\Users\Ilya\AppData\Roaming\npm\node_modules\eslint\lib\util\traverse.js:101:11)
    at CLIEngine.executeOnFiles (c:\Users\Ilya\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine.js:269:9)
    at Object.cli.execute (c:\Users\Ilya\AppData\Roaming\npm\node_modules\eslint\lib\cli.js:178:65)
    at Object.<anonymous> (c:\Users\Ilya\AppData\Roaming\npm\node_modules\eslint\bin\eslint.js:13:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by lo1tuma** [comment]
This is the expected behavior. In #1296 we discussed this and agreed that it should throw before linting.

**Comment by nzakas** [comment]
Let's just remove the `else` then and maybe add a comment to say an error will be thrown when a for doesn't exist?

**Comment by nzakas** [comment]
Working on this.
