### ISSUE TITLE
Bug: Key "plugins": Cannot redefine plugin "@typescript-eslint"

### ISSUE THREAD

**Issue by daniele-zurico** [eslint/eslint#18345]
### Environment

Node version: v20.11.1
npm version: 10.2.4
Local ESLint version: 8.57.0
Global ESLint version: -
Operating System: OS 14.4.1 

### What parser are you using?

Default (Espree)

### What did you do?

I followed the getting started configuration: https://eslint.org/docs/latest/use/getting-started and after it finishes the packages of my library are:
```js
"@babel/core": "7.24.3",
    "@babel/preset-env": "7.24.3",
    "@babel/preset-react": "7.24.1",
    "@babel/preset-typescript": "7.24.1",
    "@commitlint/config-conventional": "17.7.0",
    "@eslint/eslintrc": "^3.0.2",
    "@eslint/js": "^9.0.0",
    "@storybook/addon-a11y": "^8.0.5",
    "@storybook/addon-actions": "^8.0.5",
    "@storybook/addon-controls": "^8.0.5",
    "@storybook/addon-docs": "^8.0.5",
    "@storybook/addon-essentials": "^8.0.5",
    "@storybook/addon-links": "^8.0.5",
    "@storybook/addon-mdx-gfm": "^8.0.5",
    "@storybook/addon-webpack5-compiler-babel": "3.0.3",
    "@storybook/blocks": "^8.0.5",
    "@storybook/manager-api": "^8.0.5",
    "@storybook/preview-api": "^8.0.5",
    "@storybook/react": "^8.0.5",
    "@storybook/react-webpack5": "^8.0.5",
    "@storybook/theming": "^8.0.5",
    "@testing-library/jest-dom": "6.1.2",
    "@testing-library/react": "14.0.0",
    "@testing-library/user-event": "14.4.3",
    "@types/jest": "^29.5.4",
    "@types/mock-fs": "4.13.1",
    "@types/react": "18.2.21",
    "@types/react-dom": "18.2.7",
    "@typescript-eslint/eslint-plugin": "^6.4.0",
    "babel-loader": "9.1.3",
    "chromatic": "6.24.1",
    "codecov": "3.8.3",
    "commitlint": "17.7.1",
    "cssnano": "6.0.1",
    "cssnano-preset-default": "6.0.1",
    "eslint": "^8.0.1",
    "eslint-config-standard-with-typescript": "^43.0.1",
    "eslint-plugin-import": "^2.25.2",
    "eslint-plugin-n": "^15.0.0 || ^16.0.0 ",
    "eslint-plugin-promise": "^6.0.0",
    "eslint-plugin-react": "^7.34.1",
    "globals": "^15.0.0",
    "husky": "8.0.3",
    "identity-obj-proxy": "3.0.0",
    "jest": "29.6.4",
    "jest-environment-jsdom": "29.6.4",
    "lint": "0.8.19",
    "microbundle": "0.15.1",
    "mock-fs": "5.2.0",
    "postcss-functions": "4.0.2",
    "postcss-import": "15.1.0",
    "postcss-nesting": "12.0.1",
    "raw-loader": "4.0.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-is": "18.2.0",
    "react-live": "4.1.3",
    "resolve-url-loader": "5.0.0",
    "rollup": "3.28.1",
    "rollup-plugin-postcss": "4.0.2",
    "sass": "1.66.1",
    "sourcemap-codec": "^1.4.8",
    "storybook": "^8.0.5",
    "storybook-css-modules-preset": "1.1.1",
    "storybook-design-token": "^3.1.0",
    "ts-jest": "29.1.1",
    "ts-node": "10.9.1",
    "typescript": "*",
    "typescript-eslint": "^7.6.0"
```

### What did you expect to happen?

to does the lint

### What actually happened?

but it's throwing an error:
```bash
danielezurico@LIN66006905 dcx-react-library % yarn lint
yarn run v1.22.22
$ eslint src

Oops! Something went wrong! :(

ESLint: 8.57.0

Error: Key "plugins": Cannot redefine plugin "@typescript-eslint".
    at /Users/danielezurico/Documents/Projects/dcx-react-library/node_modules/@humanwhocodes/object-schema/src/object-schema.js:250:27
    at Array.reduce (<anonymous>)
    at ObjectSchema.merge (/Users/danielezurico/Documents/Projects/dcx-react-library/node_modules/@humanwhocodes/object-schema/src/object-schema.js:237:24)
    at /Users/danielezurico/Documents/Projects/dcx-react-library/node_modules/@humanwhocodes/config-array/api.js:935:42
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfig (/Users/danielezurico/Documents/Projects/dcx-react-library/node_modules/@humanwhocodes/config-array/api.js:934:39)
    at FlatConfigArray.isFileIgnored (/Users/danielezurico/Documents/Projects/dcx-react-library/node_modules/@humanwhocodes/config-array/api.js:962:15)
    at /Users/danielezurico/Documents/Projects/dcx-react-library/node_modules/eslint/lib/eslint/eslint-helpers.js:312:49
    at Array.reduce (<anonymous>)
    at entryFilter (/Users/danielezurico/Documents/Projects/dcx-react-library/node_modules/eslint/lib/eslint/eslint-helpers.js:299:28)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Link to Minimal Reproducible Example

https://github.com/Capgemini/dcx-react-library/tree/feat/eslint-2

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aladdin-add** [comment]
you can remove tseslint - it has been included in `eslint-config-standard-with-typescript`.
