### ISSUE TITLE
Bug: (Config (unnamed): Unexpected key "baseDirectory" found.)

### ISSUE THREAD

**Issue by zN3utr4l** [eslint/eslint#18389]
### Environment

Node version: v20.12.2
npm version: v10.5.2
yarn version: 4.1.1
Local ESLint version: v9.1.1 (Currently used)
Global ESLint version: Not found
Operating System: win32 10.0.22631

```
"devDependencies": {
    "@eslint/eslintrc": "^3.0.2",
    "@eslint/js": "^9.1.1",
    "@typescript-eslint/eslint-plugin": "^7.7.1",
    "eslint": "^9.1.1",
    "eslint-config-prettier": "^9.1.0",
    "eslint-config-standard-with-typescript": "^43.0.1",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-n": "^17.3.0",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-vue": "^9.25.0",
    "globals": "^15.0.0",
    "prettier": "^3.2.5",
    "typescript": "^5.4.5",
  }
```

### What parser are you using?

vue-eslint-parser

### What did you do?

<details>
<summary>Configuration</summary>

```
import pluginVue from 'eslint-plugin-vue'
import globals from 'globals'

import { FlatCompat } from '@eslint/eslintrc'
import pluginJs from '@eslint/js'
import tseslint from '@typescript-eslint/eslint-plugin'
import standardWithTypescript from 'eslint-config-standard-with-typescript'

import path from 'path'
import { fileURLToPath } from 'url'

// mimic CommonJS variables -- not needed if using CommonJS
const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const compat = new FlatCompat({ baseDirectory: __dirname, recommendedConfig: pluginJs.configs.recommended, allConfig: pluginJs.configs.all })

export default [
  {
    languageOptions: {
      globals: {
        __statics: 'readonly',
        __QUASAR_SSR__: 'readonly',
        __QUASAR_SSR_SERVER__: 'readonly',
        __QUASAR_SSR_CLIENT__: 'readonly',
        __QUASAR_SSR_PWA__: 'readonly',
        ...globals.browser
      }
    },
    ignores: [
      "/dist",
      "/src-capacitor",
      "/src-cordova",
      "/.quasar",
      "/node_modules",
      ".eslintrc.cjs",
      "/quasar.config.*.temporary.compiled*"
    ]
  },
  compat,
  standardWithTypescript,
  ...pluginVue.configs['flat/essential'],
  tseslint.configs['recommended-type-checked']
]

```
</details>

```bash
yarn eslint --debug .
```

### What did you expect to happen?

no error

### What actually happened?

PS G:\Test\Test.Hmi\Test.Hmi\test.hmi.client> yarn eslint --debug .
  eslint:cli CLI args: [ '--debug', '.' ] +0ms
  eslint:cli Using flat config? true +3ms
  eslint:cli Running on files +5ms
  eslint:eslint Using file patterns: . +0ms
  eslint:eslint Searching for eslint.config.js +0ms
  eslint:eslint Loading config from G:\Test\Test.Hmi\Test.Hmi\test.hmi.client\eslint.config.js +4ms
  eslint:eslint Config file URL is file:///G:/Test/Test.Hmi/Test.Hmi/test.hmi.client/eslint.config.js +0ms
  eslint:rules Loading rule 'array-bracket-newline' (remaining=289) +0ms
  eslint:rules Loading rule 'array-bracket-spacing' (remaining=288) +10ms
  eslint:rules Loading rule 'array-element-newline' (remaining=287) +4ms
  eslint:rules Loading rule 'arrow-spacing' (remaining=286) +3ms
  eslint:rules Loading rule 'block-spacing' (remaining=285) +33ms
  eslint:rules Loading rule 'brace-style' (remaining=284) +4ms
  eslint:rules Loading rule 'camelcase' (remaining=283) +4ms
  eslint:rules Loading rule 'comma-dangle' (remaining=282) +3ms
  eslint:rules Loading rule 'comma-spacing' (remaining=281) +5ms
  eslint:rules Loading rule 'comma-style' (remaining=280) +4ms
  eslint:rules Loading rule 'dot-location' (remaining=279) +10ms
  eslint:rules Loading rule 'dot-notation' (remaining=278) +3ms
  eslint:rules Loading rule 'eqeqeq' (remaining=277) +4ms
  eslint:rules Loading rule 'func-call-spacing' (remaining=276) +3ms
  eslint:rules Loading rule 'key-spacing' (remaining=275) +13ms
  eslint:rules Loading rule 'keyword-spacing' (remaining=274) +5ms
  eslint:rules Loading rule 'multiline-ternary' (remaining=273) +9ms
  eslint:rules Loading rule 'no-console' (remaining=272) +7ms
  eslint:rules Loading rule 'no-constant-condition' (remaining=271) +2ms
  eslint:rules Loading rule 'no-empty-pattern' (remaining=270) +16ms
  eslint:rules Loading rule 'no-extra-parens' (remaining=269) +4ms
  eslint:rules Loading rule 'no-loss-of-precision' (remaining=268) +6ms
  eslint:rules Loading rule 'no-restricted-syntax' (remaining=267) +20ms
  eslint:rules Loading rule 'no-sparse-arrays' (remaining=266) +6ms
  eslint:rules Loading rule 'no-useless-concat' (remaining=265) +20ms
  eslint:rules Loading rule 'object-curly-newline' (remaining=264) +7ms
  eslint:rules Loading rule 'object-curly-spacing' (remaining=263) +4ms
  eslint:rules Loading rule 'object-property-newline' (remaining=262) +4ms
  eslint:rules Loading rule 'object-shorthand' (remaining=261) +2ms
  eslint:rules Loading rule 'operator-linebreak' (remaining=260) +3ms
  eslint:rules Loading rule 'prefer-template' (remaining=259) +8ms
  eslint:rules Loading rule 'quote-props' (remaining=258) +3ms
  eslint:rules Loading rule 'space-in-parens' (remaining=257) +17ms
  eslint:rules Loading rule 'space-infix-ops' (remaining=256) +3ms
  eslint:rules Loading rule 'space-unary-ops' (remaining=255) +4ms
  eslint:rules Loading rule 'template-curly-spacing' (remaining=254) +5ms
  eslint:rules Loading rule 'consistent-return' (remaining=253) +589ms
  eslint:rules Loading rule 'indent' (remaining=252) +13ms
  eslint:rules Loading rule 'init-declarations' (remaining=251) +3ms
  eslint:rules Loading rule 'lines-around-comment' (remaining=250) +3ms
  eslint:rules Loading rule 'lines-between-class-members' (remaining=249) +1ms
  eslint:rules Loading rule 'max-params' (remaining=248) +2ms
  eslint:rules Loading rule 'no-dupe-class-members' (remaining=247) +19ms
  eslint:rules Loading rule 'no-empty-function' (remaining=246) +4ms
  eslint:rules Loading rule 'no-extra-semi' (remaining=245) +3ms
  eslint:rules Loading rule 'no-invalid-this' (remaining=244) +17ms
  eslint:rules Loading rule 'no-loop-func' (remaining=243) +2ms
  eslint:rules Loading rule 'no-magic-numbers' (remaining=242) +1ms
  eslint:rules Loading rule 'no-restricted-imports' (remaining=241) +17ms
  eslint:rules Loading rule 'no-unused-expressions' (remaining=240) +40ms
  eslint:rules Loading rule 'no-useless-constructor' (remaining=239) +3ms
  eslint:rules Loading rule 'prefer-destructuring' (remaining=238) +13ms
  eslint:rules Loading rule 'quotes' (remaining=237) +42ms
  eslint:rules Loading rule 'semi' (remaining=236) +8ms
  eslint:rules Loading rule 'space-before-blocks' (remaining=235) +3ms
  eslint:eslint Deleting cache file at G:\Test\Test.Hmi\Test.Hmi\test.hmi.client\.eslintcache +1s

Oops! Something went wrong! :(

ESLint: 9.1.1

ConfigError: Config (unnamed): Unexpected key "baseDirectory" found.
    at rethrowConfigError (G:\Test\Test.Hmi\Test.Hmi\test.hmi.client\node_modules\@humanwhocodes\config-array\api.js:230:8)
    at G:\Test\Test.Hmi\Test.Hmi\test.hmi.client\node_modules\@humanwhocodes\config-array\api.js:1032:5
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfig (G:\Test\Test.Hmi\Test.Hmi\test.hmi.client\node_modules\@humanwhocodes\config-array\api.js:1028:39)
    at FlatConfigArray.isFileIgnored (G:\Test\Test.Hmi\Test.Hmi\test.hmi.client\node_modules\@humanwhocodes\config-array\api.js:1060:15)
    at G:\Test\Test.Hmi\Test.Hmi\test.hmi.client\node_modules\eslint\lib\eslint\eslint-helpers.js:346:57
    at Array.reduce (<anonymous>)
    at G:\Test\Test.Hmi\Test.Hmi\test.hmi.client\node_modules\eslint\lib\eslint\eslint-helpers.js:333:36
    at G:\Test\Test.Hmi\Test.Hmi\test.hmi.client\node_modules\eslint\lib\eslint\eslint-helpers.js:296:32
    at Object.isAppliedFilter (G:\Test\Test.Hmi\Test.Hmi\test.hmi.client\node_modules\@nodelib\fs.walk\out\readers\common.js:12:29)

### Link to Minimal Reproducible Example

??

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

This was my `eslintrc.cjs`, I wanted to bring everything to eslint 9, I ran `yarn run eslint --init --config @typescript-eslint/eslint-plugin` but it installed eslint 8 so I was trying to update it manually.

```
module.exports = {

  // https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy
  // This option interrupts the configuration hierarchy at this file
  // Remove this if you have an higher level ESLint config file (it usually happens into a monorepos)
  root: true,

  // https://eslint.vuejs.org/user-guide/#how-to-use-a-custom-parser
  // Must use parserOptions instead of "parser" to allow vue-eslint-parser to keep working
  // `parser: 'vue-eslint-parser'` is already included with any 'plugin:vue/**' config and should be omitted
  parserOptions: {
    parser: require.resolve('@typescript-eslint/parser'),
    extraFileExtensions: ['.vue'],
    ecmaVersion: 'latest'
  },

  env: {
    browser: true,
    es2022: true,
    node: true
  },

  // Rules order is important, please avoid shuffling them
  extends: [

    // Base ESLint recommended rules
    // 'eslint:recommended',

    // https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#usage
    // ESLint typescript rules
    'plugin:@typescript-eslint/recommended',

    // Uncomment any of the lines below to choose desired strictness,
    // but leave only one uncommented!
    // See https://eslint.vuejs.org/rules/#available-rules
    'plugin:vue/vue3-essential', // Priority A: Essential (Error Prevention)

    // 'plugin:vue/vue3-strongly-recommended', // Priority B: Strongly Recommended (Improving Readability)
    // 'plugin:vue/vue3-recommended', // Priority C: Recommended (Minimizing Arbitrary Choices and Cognitive Overhead)

    // https://github.com/prettier/eslint-config-prettier#installation
    // usage with Prettier, provided by 'eslint-config-prettier'.
    'prettier'
  ],

  plugins: [

    // required to apply rules which need type information
    '@typescript-eslint',

    // https://eslint.vuejs.org/user-guide/#why-doesn-t-it-work-on-vue-files
    // required to lint *.vue files
    'vue'

    // https://github.com/typescript-eslint/typescript-eslint/issues/389#issuecomment-509292674
    // Prettier has not been included as plugin to avoid performance impact
    // add it as an extension for your IDE

  ],

  globals: {
    ga: 'readonly', // Google Analytics
    cordova: 'readonly',
    __statics: 'readonly',
    __QUASAR_SSR__: 'readonly',
    __QUASAR_SSR_SERVER__: 'readonly',
    __QUASAR_SSR_CLIENT__: 'readonly',
    __QUASAR_SSR_PWA__: 'readonly',
    process: 'readonly',
    Capacitor: 'readonly',
    chrome: 'readonly'
  },

  // add your custom rules here
  rules: {
    'prefer-promise-reject-errors': 'off',

    quotes: ['warn', 'single', { avoidEscape: true }],

    // this rule, if on, would require explicit return type on the `render` function
    '@typescript-eslint/explicit-function-return-type': 'off',

    // in plain CommonJS modules, you can't use `import foo = require('foo')` to pass this rule, so it has to be disabled
    '@typescript-eslint/no-var-requires': 'off',

    '@typescript-eslint/no-explicit-any': 'off',

    '@typescript-eslint/no-unused-vars': 'off',

    // The core 'no-unused-vars' rules (in the eslint:recommended ruleset)
    // does not work with type definitions
    'no-unused-vars': 'off',

    // allow debugger during development only
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off'
  }
}
```

**Comment by zN3utr4l** [comment]
```
import pluginVue from 'eslint-plugin-vue'
import globals from 'globals'

import { FlatCompat } from '@eslint/eslintrc'
import pluginJs from '@eslint/js'
import tseslint from 'typescript-eslint'

import path from 'path'
import { fileURLToPath } from 'url'

// mimic CommonJS variables -- not needed if using CommonJS
const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const compat = new FlatCompat({ baseDirectory: __dirname, recommendedConfig: pluginJs.configs.recommended, allConfig: pluginJs.configs.all })

export default [
  {
    languageOptions: {
      globals: {
        __statics: 'readonly',
        __QUASAR_SSR__: 'readonly',
        __QUASAR_SSR_SERVER__: 'readonly',
        __QUASAR_SSR_CLIENT__: 'readonly',
        __QUASAR_SSR_PWA__: 'readonly',
        ...globals.browser
      },
      parserOptions: {
        extraFileExtensions: ['.vue']
      }
    },
    ignores: [
      '/dist',
      '/src-capacitor',
      '/src-cordova',
      '/.quasar',
      '/node_modules',
      '/quasar.config.*.temporary.compiled*'
    ]
  },
  ...compat.extends('prettier', 'standard-with-typescript'),
  ...pluginVue.configs['flat/recommended'],
  ...tseslint.configs.recommended
]
```


Fixed with this config
