### ISSUE TITLE
Question: Unexpected key "typescript" found

### ISSUE THREAD

**Issue by rr210** [eslint/eslint#18523]
### Environment

Environment Info:

Node version: v18.17.0
npm version: v9.6.7
Local ESLint version: v9.3.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 23.1.0

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>
nuxt.config.ts
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: [
    '@pinia/nuxt',
    '@nuxt/ui',
    '@nuxtjs/i18n',
    '@vueuse/nuxt',
    '@pinia-plugin-persistedstate/nuxt',
    '@nuxt/eslint',
  ],
  eslint: {
    // options here
    config: {
      autoInit: false // <--- disable auto-init
    }
  },
})
```
</details>

eslint.config.mjs
```js
import withNuxt from './.nuxt/eslint.config.mjs'
import antfu from '@antfu/eslint-config'

export default withNuxt(
  // your custom flat configs go here, for example:
  {
    typescript: true,
    formatters: true,
    rules: {
      'node/prefer-global/process': 'off',
      'n/prefer-global/buffer': 'off',
    },
  },
)
```

### What did you expect to happen?

<img width="941" alt="image" src="https://github.com/eslint/eslint/assets/66169324/5158dfd8-3574-40a7-9120-a32da61157ca">

### What actually happened?

```
harry@B-10XSQ05P-0100:github/own-cover-main $ pnpm run lint

> nuxt-app@ lint /Users/harry/envcode/github/own-cover-main
> eslint .


Oops! Something went wrong! :(

ESLint: 9.3.0

ConfigError: Config (unnamed): Unexpected key "typescript" found.
    at rethrowConfigError (/Users/harry/envcode/github/own-cover-main/node_modules/.pnpm/@humanwhocodes+config-array@0.13.0/node_modules/@humanwhocodes/config-array/api.js:230:8)
    at /Users/harry/envcode/github/own-cover-main/node_modules/.pnpm/@humanwhocodes+config-array@0.13.0/node_modules/@humanwhocodes/config-array/api.js:1032:5
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfig (/Users/harry/envcode/github/own-cover-main/node_modules/.pnpm/@humanwhocodes+config-array@0.13.0/node_modules/@humanwhocodes/config-array/api.js:1028:39)
    at FlatConfigArray.isFileIgnored (/Users/harry/envcode/github/own-cover-main/node_modules/.pnpm/@humanwhocodes+config-array@0.13.0/node_modules/@humanwhocodes/config-array/api.js:1060:15)
    at /Users/harry/envcode/github/own-cover-main/node_modules/.pnpm/eslint@9.3.0/node_modules/eslint/lib/eslint/eslint-helpers.js:346:57
    at Array.reduce (<anonymous>)
    at /Users/harry/envcode/github/own-cover-main/node_modules/.pnpm/eslint@9.3.0/node_modules/eslint/lib/eslint/eslint-helpers.js:333:36
    at /Users/harry/envcode/github/own-cover-main/node_modules/.pnpm/eslint@9.3.0/node_modules/eslint/lib/eslint/eslint-helpers.js:296:32
    at Object.isAppliedFilter (/Users/harry/envcode/github/own-cover-main/node_modules/.pnpm/@nodelib+fs.walk@1.2.8/node_modules/@nodelib/fs.walk/out/readers/common.js:12:31)
```

### Link to Minimal Reproducible Example

wu

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
You're using a function provided by your Nuxt project. You'll need to contact the Nuxt team for help with this.
