### ISSUE TITLE
eslint throwing on type error on global returns

### ISSUE THREAD

**Issue by sam-github** [eslint/eslint#1868]
On repo/branch: https://github.com/strongloop/strong-supervisor/tree/try-linters (edit: you don't have to be on branch, throws on master as well)

@kraman, you reproduced this on OS X with 0.15, and node 0.11.3, right?

```
sam@samtu:~/w/sn/strong-supervisor (master u=) % ./node_modules/.bin/eslint lib
/home/sam/w/sn/strong-supervisor/node_modules/eslint/lib/rules/consistent-return.js:55
                returnTypeDefined = "type" in returnInfo;
                                              ^
TypeError: Cannot use 'in' operator to search for 'type' in undefined
    at EventEmitter.ReturnStatement (/home/sam/w/sn/strong-supervisor/node_modules/eslint/lib/rules/consistent-return.js:55:47)
    at EventEmitter.emit (events.js:117:20)
    at Controller.controller.traverse.enter (/home/sam/w/sn/strong-supervisor/node_modules/eslint/lib/eslint.js:683:25)
    at Controller.__execute (/home/sam/w/sn/strong-supervisor/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/home/sam/w/sn/strong-supervisor/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/home/sam/w/sn/strong-supervisor/node_modules/eslint/lib/eslint.js:676:24)
    at processFile (/home/sam/w/sn/strong-supervisor/node_modules/eslint/lib/cli-engine.js:172:23)
    at /home/sam/w/sn/strong-supervisor/node_modules/eslint/lib/cli-engine.js:271:26
    at /home/sam/w/sn/strong-supervisor/node_modules/eslint/lib/util/traverse.js:61:17
    at Array.forEach (native)
```

system info:

```
sam@samtu:~/w/sn/strong-supervisor (master u=) % uname -a
Linux samtu 3.16.0-29-generic #39-Ubuntu SMP Mon Dec 15 22:27:29 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
sam@samtu:~/w/sn/strong-supervisor (master u=) % node -v
v0.10.36
sam@samtu:~/w/sn/strong-supervisor (master u=) % ./node_modules/.bin/eslint -v
v0.15.0
```

**Comment by nzakas** [comment]
Can you use some debug flags to narrow down where the problem is occurring? (Ideally with some sample code.)

You can use debug flags like this:

```js
$ DEBUG=eslint:* eslint .
```

Where `eslint .` is your command for running ESLint. You should be able to see which file the error occurred in and then be able to narrow down to which `return` statement is causing the problem.

**Comment by sam-github** [comment]
`globalReturn` seems broken.

I can repro on this file:

```
#!/usr/bin/env node

if(true) {
  return 1;
}
```

**Comment by nzakas** [comment]
Ah okay! That makes sense, the rule is confused that `return` is outside a function. Definitely a bug.

**Comment by btmills** [comment]
Working on this.

**Comment by sam-github** [comment]
Worked for me, thanks!
