### ISSUE TITLE
Bug: Unexpected key "emcaVersion" and fetch is not defined

### ISSUE THREAD

**Issue by bliu13** [eslint/eslint#19088]
### Environment

Node version: v22.10.0
npm version: 10.9.0
Local ESLint version: 9.13.0
Global ESLint version: N/A
Operating System: macOS 15.1

### What parser are you using?

@babel/eslint-parser

### What did you do?

<details>
<summary>Configuration</summary>

```js
import babelParser from "@babel/eslint-parser";
import eslintDefault from "@eslint/js";

export default [
  {
    files: ["**/*.js", "**/*.cjs", "**/*.mjs"],
    languageOptions: {
      parser: babelParser,
      emcaVersion: 2024, // "latest" doesn't work either
      parserOptions: {
        requireConfigFile: false
      }
    },
    rules: {
      ...eslintDefault.configs.recommended.rules,
    }
  }
]
```
</details>

```js
import fetch from 'fetch'

export default async getData() {
  return fetch('http://google.com')
}
```

### What did you expect to happen?

I am expecting the linter to [support ecmaVersion](https://eslint.org/docs/latest/use/configure/language-options#specifying-javascript-options), but the key is unexpected. I am trying to set the ecmaVersion because eslint is because of the error I am seeing related to the Fetch API:
```sh
'fetch' is not defined                        no-undef
```

### What actually happened?

When I run `eslint --cache --fix .`, I am getting the following error:
```sh
Oops! Something went wrong! :(

ESLint: 9.13.0

TypeError: Key "languageOptions": Unexpected key "emcaVersion" found.
    at new Config (/some-path/node_modules/eslint/lib/config/config.js:215:19)
    at [finalizeConfig] (/some-path/node_modules/eslint/lib/config/flat-config-array.js:216:16)
    at FlatConfigArray.getConfigWithStatus (/some-path/node_modules/@eslint/config-array/dist/cjs/index.cjs:1102:55)
    at FlatConfigArray.getConfig (/some-path/node_modules/@eslint/config-array/dist/cjs/index.cjs:1120:15)
    at entryFilter (/some-path/node_modules/eslint/lib/eslint/eslint-helpers.js:286:40)
    at async NodeHfs.<anonymous> (file:///some-path/node_modules/@humanfs/core/src/hfs.js:574:24)
    at async NodeHfs.walk (file:///some-path/node_modules/@humanfs/core/src/hfs.js:614:3)
    at async globSearch (/some-path/node_modules/eslint/lib/eslint/eslint-helpers.js:327:26)
    at async Promise.allSettled (index 0)
    at async globMultiSearch (/some-path/node_modules/eslint/lib/eslint/eslint-helpers.js:412:21)
```

### Link to Minimal Reproducible Example

https://eslint.org/play/#eyJ0ZXh0IjoiZmV0Y2goXCJodHRwOi8vZ29vZ2xlLmNvbVwiKTtcbiIsIm9wdGlvbnMiOnsicnVsZXMiOnsibm8tdW5kZWYiOlsiZXJyb3IiXX0sImxhbmd1YWdlT3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e319LCJlY21hVmVyc2lvbiI6MjAyNCwic291cmNlVHlwZSI6Im1vZHVsZSJ9fX0=

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @bliu13, thanks for the issue!

The configuration error you're getting is due to a typo (emcaVersion -> ecmaVersion).

As for the `fetch` global variable, it's not part of the ECMAScript Specification so it is not automatically enabled by any ecmaVersion. You can enable it using [`languageOptions.globals`](https://eslint.org/docs/latest/use/configure/language-options#using-configuration-files).

```js
languageOptions: {
    globals: {
        fetch: "readonly"
    }
}
```
