### ISSUE TITLE
Bug: (fill in)

### ISSUE THREAD

**Issue by glass-ships** [eslint/eslint#19134]
### Environment

Node version: 23.1.0
npm version: using bun, 1.1.34
Local ESLint version: 9.15.0
Global ESLint version:
Operating System: Ubuntu 24.04

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```javascript
import { FlatCompat } from "@eslint/eslintrc";
import js from "@eslint/js";
import prettierConfig from "@vue/eslint-config-prettier";
import vueTsEslintConfig from "@vue/eslint-config-typescript";
import eslintPluginPrettierRecommended from "eslint-plugin-prettier/recommended";
import pluginVue from "eslint-plugin-vue";
import url from "url";

const __dirname = url.fileURLToPath(new URL(".", import.meta.url));
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  // allConfig: js.configs.all,
});

export default [
  /** Extend recommended configs */
  ...compat.extends("plugin:vue/vue3-recommended", "plugin:vuejs-accessibility/recommended", "prettier"),
  ...pluginVue.configs["flat/recommended"],
  ...vueTsEslintConfig(),
  eslintPluginPrettierRecommended,
  prettierConfig,
  /** Configuration */
  {
    languageOptions: {
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "script",
      },
    },
    files: ["src/**/*.js", "src/**/*.mjs", "src/**/*.ts", "src/**/*.tsx", "src/**/*.vue"],
    /** Override rules */
    rules: {
      "max-len": ["error", { code: 120 }],
      "prefer-const": 0,
      "@typescript-eslint/ban-ts-comment": ["error", { "ts-ignore": "allow-with-description" }],
      "@typescript-eslint/no-explicit-any": "off",
      "prettier/prettier": [
        "warn",
        {},
        {
          usePrettierrc: true,
        },
      ],
      "vuejs-accessibility/label-has-for": [
        "error",
        {
          required: {
            some: ["nesting", "id"],
          },
        },
      ],
    },
  },
];

```
</details>

Configured as above, then ran:
```js
eslint src
```

### What did you expect to happen?

Expected linting to run

### What actually happened?

```
$ eslint src

Oops! Something went wrong! :(

ESLint: 9.15.0

TypeError: Error while loading rule '@typescript-eslint/no-unused-expressions': Cannot read properties of undefined (reading 'allowShortCircuit')
```

### Link to Minimal Reproducible Example

https://github.com/reflectometry/refl1d/tree/lint-frontend/refl1d/webview/client

### Participation

- [x] I am willing to submit a pull request for this issue.

### Additional comments

This was working fine last week, and I've since created a new branch in the source repo to introduce the same changes based on a different branch, so it's possible I've missed something in re-setting this up, but I can't seem to nail down what's wrong here...
Noticed a new release as of 4 days ago, is it possible something has changed since then?

**Comment by mdjermanovic** [comment]
I can reproduce this. I believe this is due to `@typescript-eslint/no-unused-expressions` rule passing an empty array of options to the core `no-unused-expression` rule, which in v9.15.0 expects an array with an object element because it has it specified in `meta.defaultOptions`.

@JoshuaKGoldberg @bradzacher looks like this should be fixed in `typescript-eslint`?

**Comment by mdjermanovic** [comment]
Here's the stack trace I'm getting:

```
Oops! Something went wrong! :(

ESLint: 9.15.0

TypeError: Error while loading rule '@typescript-eslint/no-unused-expressions': Cannot read properties of undefined (reading 'allowShortCircuit')
Occurred while linting C:\projects\tmp\refl1d\refl1d\webview\client\src\app_state.ts
    at Object.create (C:\projects\tmp\refl1d\refl1d\webview\client\node_modules\eslint\lib\rules\no-unused-expressions.js:75:13)
    at create (C:\projects\tmp\refl1d\refl1d\webview\client\node_modules\@typescript-eslint\eslint-plugin\dist\rules\no-unused-expressions.js:28:32)
    at Object.create (C:\projects\tmp\refl1d\refl1d\webview\client\node_modules\@typescript-eslint\utils\dist\eslint-utils\RuleCreator.js:31:20)
    at createRuleListeners (C:\projects\tmp\refl1d\refl1d\webview\client\node_modules\eslint\lib\linter\linter.js:944:21)
    at C:\projects\tmp\refl1d\refl1d\webview\client\node_modules\eslint\lib\linter\linter.js:1082:84
    at Array.forEach (<anonymous>)
    at runRules (C:\projects\tmp\refl1d\refl1d\webview\client\node_modules\eslint\lib\linter\linter.js:1013:34)
    at #flatVerifyWithoutProcessors (C:\projects\tmp\refl1d\refl1d\webview\client\node_modules\eslint\lib\linter\linter.js:1911:31)
    at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (C:\projects\tmp\refl1d\refl1d\webview\client\node_modules\eslint\lib\linter\linter.js:1993:49)
    at Linter._verifyWithFlatConfigArray (C:\projects\tmp\refl1d\refl1d\webview\client\node_modules\eslint\lib\linter\linter.js:2082:21)
```

**Comment by idimetrix** [comment]
Have the same issue!

**Comment by fasttime** [comment]
Related `typescript-eslint` issue: typescript-eslint/typescript-eslint#10338.

**Comment by Tkkg1994** [comment]
Just wanted to report the exact same thing, thanks for posting. If somebody needs anymore logs, let me know!

**Comment by mdjermanovic** [comment]
As explained in https://github.com/typescript-eslint/typescript-eslint/issues/10338#issuecomment-2480033066, this is not a bug in ESLint, but typescript-eslint plugin rules need to be updated.

We'll keep this issue open for visibility until the problem is resolved in typescript-eslint.

**Comment by bhalperin** [comment]
Same here:
```
 Error while loading rule '@typescript-eslint/no-empty-function': Cannot read properties of undefined (reading 'allow')
```
Stack trace:
```
at Object.create (C:\data\projects\nx\github\node_modules\eslint\lib\rules\no-empty-function.js:125:18)
```
The failing line of code:
```
const [{ allow }] = context.options;
```

**Comment by rishi23root** [comment]
for me, I had to update the rules 
```
"@typescript-eslint/no-unused-expressions": [
        "error",
        {
          allowShortCircuit: true,
          allowTernary: true,
        },
      ],
"@typescript-eslint/dot-notation": ["error", { allowKeywords: true }],
"@typescript-eslint/no-empty-function": ["error", { allow: ["arrowFunctions"] }],
```

**Comment by mdjermanovic** [comment]
Rule implementations are not public API so there was no breaking change in a minor release.

**Comment by glass-ships** [comment]
I would definitely agree that a breaking change like this belongs in a major release, not a minor or patch.  

And I would disagree that there was no breaking change in a minor release, considering updating from 9.14 to 9.15 _of eslint_ is what broke functionality for several users using another plugin which extends eslint and themselves made no changes. 

Ideally this would get reverted and reserved for a major release, giving `typescript-eslint` and others time to modify their code without users having to pin their `eslint` version to 9.14.0, or modify their rules to manually list out every option expected by every rule as in comment https://github.com/eslint/eslint/issues/19134#issuecomment-2480588649

At the very least, barring a reversion, documentation should be updated to accurately reflect expectations for plugin creators.  
For example, current documentation reads "Rules may specify a meta.defaultOptions array of default values for any options.",  
where "may" implies that `meta.defaultOptions` is optional, when in reality it does not appear to be optional (from my understanding of the conversation in https://github.com/eslint/eslint/issues/19134)

**Comment by Jason3S** [comment]
The issue is not limited to `@typescript-eslint`, `unicorn` also has issues.

```
TypeError: Error while loading rule 'unicorn/expiring-todo-comments': Cannot read properties of undefined (reading 'decoration')
```

Is the problem an issue with `defaultOptions` not getting correctly propagated or with code that cannot handle undefined options:

https://github.com/eslint/eslint/pull/17656/files#diff-295e5aae69e9308d6777e4522ca3337e15b8eaa604beaf30c679b45dd33cd20eR73-R79

The following will give a `TypeError: Cannot read properties of undefined ...`
if `context.options[0] === undefined`.
```js
const [{
            allow,
            ignoreDestructuring,
            ignoreGlobals,
            ignoreImports,
            properties
        }] = context.options;
```

A fix would be:

```js
        const [{
            allowShortCircuit,
            allowTernary,
            allowTaggedTemplates,
            enforceForJSX
        } = this.meta.defaultOptions[0]] = context.options;
```

or

```js
        const [{
            allowShortCircuit,
            allowTernary,
            allowTaggedTemplates,
            enforceForJSX
        } = {}] = context.options;
```

**Comment by mdjermanovic** [comment]
Again, rule implementations are not [public API](https://github.com/eslint/eslint/blob/main/lib/api.js). Otherwise, we wouldn't be able to make any changes to rules in non-major versions. We do not recommend extending core rules because that can break with a new minor or patch version of ESLint, and thus they're exported under [`use-at-your-own-risk`](https://github.com/eslint/eslint/blob/6f37b0747a14dfa9a9e3bdebc5caed1f39b6b0e2/package.json#L18-L21) entry point. Please see https://github.com/eslint/rfcs/pull/80 for more details.

> At the very least, barring a reversion, documentation should be updated to accurately reflect expectations for plugin creators.
> For example, current documentation reads "Rules may specify a meta.defaultOptions array of default values for any options.",
> where "may" implies that `meta.defaultOptions` is optional, when in reality it does not appear to be optional (from my understanding of the conversation in [typescript-eslint/typescript-eslint#10338](https://github.com/typescript-eslint/typescript-eslint/issues/10338))

`meta.defaultOptions` is an optional property. Rules may or may not specify this property. Most of the core rules still don't have this property specified.

**Comment by Jason3S** [comment]
This is the patch I used to get it working. Note: I don't use all the rules from TypeScript ESLint or Unicorn.

```diff
diff --git a/lib/rules/no-unused-expressions.js b/lib/rules/no-unused-expressions.js
index fd1437c1606a56cbce147d040d601d0acef3d24a..1ac2d6e45fbb04f93d9cccdc5265bb38c3701aca 100644
--- a/lib/rules/no-unused-expressions.js
+++ b/lib/rules/no-unused-expressions.js
@@ -76,7 +76,7 @@ module.exports = {
             allowTernary,
             allowTaggedTemplates,
             enforceForJSX
-        }] = context.options;
+        } = {}] = context.options;
 
         /**
          * Has AST suggesting a directive.
diff --git a/lib/rules/no-warning-comments.js b/lib/rules/no-warning-comments.js
index 628f5a2ac513303cc3fe2cc9adcbf1ae54128747..a42e8318e028c6a3717afceef3c949bf8eab5827 100644
--- a/lib/rules/no-warning-comments.js
+++ b/lib/rules/no-warning-comments.js
@@ -64,7 +64,7 @@ module.exports = {
 
     create(context) {
         const sourceCode = context.sourceCode;
-        const [{ decoration, location, terms: warningTerms }] = context.options;
+        const [{ decoration, location, terms: warningTerms } = this.meta.defaultOptions[0]] = context.options;
         const escapedDecoration = escapeRegExp(decoration ? decoration.join("") : "");
         const selfConfigRegEx = /\bno-warning-comments\b/u;
```

**Comment by azat-io** [comment]
Looks like this is the same problem #19140.

**Comment by Yvad60** [comment]
Same issue heere

**Comment by kirkwaiblinger** [comment]
typescript-eslint team member here 👋 

I want to affirm what @mdjermanovic has said in https://github.com/eslint/eslint/issues/19134#issuecomment-2480636471. ESLint giving rule authors the ability to define default options, and then using it internally, ***is not a breaking change***. It's a welcome feature, that was even proposed (#17448), defended (https://github.com/eslint/rfcs/pull/113), and implemented (#17656) primarily by typescript-eslint's own @JoshuaKGoldberg. This design was inspired by [typescript-eslint's own default options utility](https://typescript-eslint.io/developers/custom-rules/#handling-rule-options), which has existed for a long time to fill that feature gap, but the ESLint design diverged in order to meet their needs.

The only breakages in the ecosystem appear to be due to brittle rule composition methods where a plugin attempts to reuse logic from a eslint core rule, see https://github.com/typescript-eslint/typescript-eslint/issues/10338 and https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2496, which is, as ESLint team members have noted, an explicitly discouraged practice, and absolutely not ensured by semver.

[typescript-eslint](https://typescript-eslint.io/) is a _separate_ project from ESLint. For some of our "extension" rules, we make a _best effort_ to hack some ESLint core rules, which (with few, minor exceptions) are currently written for JS _only_, to run on TypeScript code. This strategy is known to be brittle (#6456) and is only still used in a subset of (simple) ESLint rules, because of its known potential to break on _any_ ESLint change, rather than only on major version changes.

There is always potential for improvement in the ecosystem going forward. Potentially ESLint may support TS in its core rules (https://github.com/eslint/eslint/discussions/18830), and it would be really lovely to check for these sort of downstream ecosystem clashes before releasing (#19139). However, the bottom line is, again, ***this is not a breaking change*** and, please, let's not pile on ESLint as if it were one. For our part, a fix is already well underway at typescript-eslint.

**Comment by glass-ships** [comment]
Thanks Kirk, and Milos as well as everyone else who's helped investigate this. Apologies if I came off as confrontational, I just get curious/invested and the discussions have been very informative!

**Comment by mrlika** [comment]
I had the same issue while updating my PNPM monorepo to the `typescript-eslint` flat config. Linting works as expected on 9.14 but fails with the error in the topic on 9.15

**Comment by sohamnandi77** [comment]
facing the same issue.

**Comment by glass-ships** [comment]
According to the ts-eslint team, a fix has been pushed to their canary release.
Refer to this issue https://github.com/typescript-eslint/typescript-eslint/issues/10338#issuecomment-2480917240

**Comment by aliofye** [comment]
First time I encounter a live bug that's being fixed as we speak, I too am facing the same issue!

**Comment by reggi** [comment]
workaround 

```ts
import globals from "globals";
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";
import eslintPluginImport from "eslint-plugin-import";

/** @type {import('eslint').Linter.Config[]} */
export default [
  {files: ["**/*.{js,mjs,cjs,ts}"]},
  {languageOptions: { globals: globals.browser }},
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      "@typescript-eslint/no-unused-expressions": "off"
    }
  }
];
```

**Comment by whatwg6** [comment]
+

**Comment by whatwg6** [comment]
`+1`

**Comment by Truimo** [comment]
I am also facing the same error problem.

eslint ^9.15.0

**Comment by absidue** [comment]
Please do not spam issues with "me too" comments, just leave a thumbs up on the top post. Leaving comments like that not only spams people's email inboxes but also makes it a lot harder to find the comments with the important information.

**Comment by muuvmuuv** [comment]
Canary release works on my side: `pnpm update typescript-eslint@canary`

**Comment by anishkumar127** [comment]
Same error. after updating eslint version.

Error
Oops! Something went wrong! :(

ESLint: 9.15.0

TypeError: Error while loading rule '@typescript-eslint/no-unused-expressions': Cannot read properties of undefined (reading 'allowShortCircuit')
Occurred while linting C:\Users\AnishKumar\Videos\FFastify\src\api\assets\assets-mapping\delete\delete-assets-mapping.handlers.ts
    at Object.create (C:\Users\AnishKumar\Videos\FFastify\node_modules\.pnpm\eslint@9.15.0_jiti@1.21.6\node_modules\eslint\lib\rules\no-unused-expressions.js:75:13)

**Comment by kirkwaiblinger** [comment]
Update on the typescript-eslint side, our fix has been released; see https://github.com/typescript-eslint/typescript-eslint/issues/10338#issuecomment-2483750053.

PSA - Be sure to report any issues you encounter _to typescript-eslint_, not here. And please follow the directions in https://github.com/typescript-eslint/typescript-eslint/issues/10338#issuecomment-2483750053 before doing so. Thanks!

**Comment by 238SAMIxD** [comment]
9.23.0: error is still here

**Comment by ClementValot** [comment]
It shouldn't :D
Have you upgraded your `@typescript-eslint` dependencies to latest?

**Comment by Zeryther** [comment]
> It shouldn't :D Have you upgraded your `@typescript-eslint` dependencies to latest?

Still happening on latest version for me

**Comment by softmarshmallow** [comment]
Getting this error on `9.27.0`
Caused by `next/typescript`
