### ISSUE TITLE
Change Request: Improve error message when a plugin's rules are enabled without the plugin

### ISSUE THREAD

**Issue by bradgarropy** [eslint/eslint#19254]
### ESLint version

v9.17.0

### What problem do you want to solve?

In my example, I was using defining rules for `simple-import-sort` on a file set where the `simple-import-sort` plugin was not included.

```javascript
import simpleImportSort from 'eslint-plugin-simple-import-sort';

const config = [
  {
    files: ['**/*.ts'],
    plugins: {
      'simple-import-sort': simpleImportSort,
    },
  },
  {
    rules: {
      'simple-import-sort/imports': ['error'],
    },
  },
];

export default config;
```

This results in a confusing error message:

```text
Oops! Something went wrong! :(

ESLint: 9.17.0

TypeError: Key "rules": Key "simple-import-sort/imports": Could not find plugin "simple-import-sort".
    at throwRuleNotFoundError (file:///home/projects/no-irregular-whitespace-rvqwyakg/node_modules/eslint/lib/config/rule-validator.js#cjs:66:11)
    at RuleValidator.validate (file:///home/projects/no-irregular-whitespace-rvqwyakg/node_modules/eslint/lib/config/rule-validator.js#cjs:147:17)
    at new Config (file:///home/projects/no-irregular-whitespace-rvqwyakg/node_modules/eslint/lib/config/config.js#cjs:228:27)
    at [finalizeConfig] (file:///home/projects/no-irregular-whitespace-rvqwyakg/node_modules/eslint/lib/config/flat-config-array.js#cjs:216:16)
    at FlatConfigArray.getConfigWithStatus (file:///home/projects/no-irregular-whitespace-rvqwyakg/node_modules/@eslint/config-array/dist/cjs/index.cjs#cjs:1178:55)
    at FlatConfigArray.getConfig (file:///home/projects/no-irregular-whitespace-rvqwyakg/node_modules/@eslint/config-array/dist/cjs/index.cjs#cjs:1196:15)
    at entryFilter (file:///home/projects/no-irregular-whitespace-rvqwyakg/node_modules/eslint/lib/eslint/eslint-helpers.js#cjs:282:40)
    at async NodeHfs.eval (file:///home/projects/no-irregular-whitespace-rvqwyakg/node_modules/@humanfs/core/src/hfs.js:591:24)
    at async NodeHfs.walk (file:///home/projects/no-irregular-whitespace-rvqwyakg/node_modules/@humanfs/core/src/hfs.js:631:3)
    at async globSearch (file:///home/projects/no-irregular-whitespace-rvqwyakg/node_modules/eslint/lib/eslint/eslint-helpers.js#cjs:323:26)
```

#### Minimal Reproduction
https://stackblitz.com/edit/no-irregular-whitespace-rvqwyakg

### What do you think is the correct solution?

It would help to have a more descriptive error message stating that the `plugin` I was trying to write rules for is defined in another configuration object. Even better if it could reference the line where it was included.

For example:

```text
Oops! Something went wrong! :(

ESLint: 9.17.0

TypeError: Key "rules": Key "simple-import-sort/imports": The plugin you are referencing ("simple-import-sort") is defined in a different configuration object.

eslint.config.ts:6-8

    plugins: {
      'simple-import-sort': simpleImportSort,
    },
```

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

/cc @JoshuaKGoldberg

**Comment by aladdin-add** [comment]
> In my example, I was using defining rules for simple-import-sort on a file set where the simple-import-sort plugin was not included.

the root of the problem here is that the 2nd config object doesn't specify files, so it defaults to `**/*.{js,mjs,cjs}`, which is not applied to ts files.

If you add it in the 2nd object, it will work as expected: 
```js
import simpleImportSort from 'eslint-plugin-simple-import-sort';

const config = [
  {
    files: ['**/*.ts'],
    plugins: {
      'simple-import-sort': simpleImportSort,
    },
  },
  {
    files: ['**/*.ts'],
    rules: {
      'simple-import-sort/imports': ['error'],
    },
  },
];

export default config;
```

**Comment by JoshuaKGoldberg** [comment]
I think the problem being reported is that the error message isn't helpful, not that the config should work differently than how it is.

I'm in support of this suggestion. IME it's pretty common that folks new to flat config accidentally enable a plugin rule separately from where the plugin is defined. I've done this myself on occasion too.

(context/disclaimer: Brad and I paired on migrating Brad's personal ESLint config to flat config and trying out `@eslint/css`)

**Comment by nzakas** [comment]
I'm fine with updating the message to something that is more helpful. I'm just not sure if the suggested message is actually possible given the scope of information we have at the time the error is thrown. The error occurs during the validation phase after the final configuration object is calculated for a file. So, we definitely have no idea where in the config file any changes should be made and may not be able to access other config objects in the array to say where else it is defined.

It may end up just being simpler to do something like this:

```
Oops! Something went wrong! :(

ESLint: 9.17.0

TypeError: Key "rules": Key "simple-import-sort/imports": Could not find plugin "simple-import-sort" in the configuration for file /path/to/file.js.

Common causes of this problem include:

1. The "simple-import-sort" plugin is not defined in your configuration file. 
2. "simple-import-sort" is defined in a configuration object that that doesn't match /path/to/file.js.

Use the Config Inspector (--inspect-config) to check your configuration file and which parts match path/to/file.js.
```

We should be careful not to create a message that is too long, though, as people won't read it.
