### ISSUE TITLE
escope throws error when import is used

### ISSUE THREAD

**Issue by fczuardi** [eslint/eslint#1963]
Maybe this is a duplicate of https://github.com/eslint/espree/issues/10 if that is the case, please feel free to close this issue :)

Here is a simple js file:

```es6
import foo from 'foo';
```

When I run eslint (0.16.0 or master) with the default parser and this .eslintrc config:

```
{
    "rules": {
        "quotes": [1, "single"],
        "no-unused-vars": 1
    },
    "ecmaFeatures": {
        "modules": true,
    },
}
```

I get the following error:

```
 
/home/fabricio/bug/node_modules/eslint/node_modules/escope/escope.js:73
            throw new Error(text);
                  ^
Error
    at assert (/home/fabricio/bug/node_modules/eslint/node_modules/escope/escope.js:73:19)
    at Referencer.extend.ImportDeclaration (/home/fabricio/bug/node_modules/eslint/node_modules/escope/escope.js:1383:13)
    at Referencer.Visitor.visit (/home/fabricio/bug/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
    at Referencer.Visitor.visitChildren (/home/fabricio/bug/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:88:38)
    at Referencer.extend.Program (/home/fabricio/bug/node_modules/eslint/node_modules/escope/escope.js:1236:18)
    at Referencer.Visitor.visit (/home/fabricio/bug/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
    at Object.analyze (/home/fabricio/bug/node_modules/eslint/node_modules/escope/escope.js:1430:20)
    at EventEmitter.module.exports.api.verify (/home/fabricio/bug/node_modules/eslint/lib/eslint.js:651:35)
    at processFile (/home/fabricio/bug/node_modules/eslint/lib/cli-engine.js:193:27)
    at /home/fabricio/bug/node_modules/eslint/lib/cli-engine.js:293:26

```

The same happens if the .eslintrc is:

```
{
    "rules": {
        "quotes": [1, "single"],
        "no-unused-vars": 1
    },
    "env":{
        "es6": true
    },
    "ecmaFeatures": {
        "modules": true
    }
}
```

**Comment by nzakas** [comment]
Looks like we need to specify `ecmaVersion: 6` in addition to `sourceType: "module" ` in order for that to work. 

Workaround for now: either enable `ecmaFeatures.blockBindings` or the `es6` environment.

**Comment by fczuardi** [comment]
the second .eslintrc example above is using the ```es6``` environment and still failing, right?

**Comment by nzakas** [comment]
Sorry, I missed that. The key thing is `blockBindings` , so can you try just using that with `modules` and see what happens?

Was an error message output above what you pasted? Looks like you may have copied just under the actual message.

I'm mobile for the rest of the day, so sorry I can't do much debugging myself.

**Comment by fczuardi** [comment]
No luck, tried 2 variations:

```
{
    "rules": {
        "quotes": [1, "single"],
        "no-unused-vars": 1
    },
    "ecmaFeatures": {
        "modules": true,
        "blockBindings": true
    }
}
```

and

```
{
    "rules": {
        "quotes": [1, "single"],
        "no-unused-vars": 1
    },
    "env":{
        "es6": true
    },
    "ecmaFeatures": {
        "modules": true,
        "blockBindings": true
    }
}
```

**Comment by fczuardi** [comment]
ok, found the issue... the code is checking for an attribute called ```module``` (singular) and I am using ```modules``` (plural) on my .eslintrc

**Comment by extesy** [comment]
Similar thing happens with exports:

```
D:\Projects\Web\eBookTracker\node_modules\eslint\node_modules\estraverse\estraverse.js:517
                        throw new Error('Unknown node type ' + nodeType + '.')
                              ^
Error: Unknown node type ExportDefaultDeclaration.
    at Controller.traverse (D:\Projects\Web\eBookTracker\node_modules\eslint\node_modules\estraverse\estraverse.js:517:31)
    at EventEmitter.module.exports.api.verify (D:\Projects\Web\eBookTracker\node_modules\eslint\lib\eslint.js:706:24)
    at processFile (D:\Projects\Web\eBookTracker\node_modules\eslint\lib\cli-engine.js:193:27)
    at D:\Projects\Web\eBookTracker\node_modules\eslint\lib\cli-engine.js:293:26
    at walk (D:\Projects\Web\eBookTracker\node_modules\eslint\lib\util\traverse.js:81:9)
    at D:\Projects\Web\eBookTracker\node_modules\eslint\lib\util\traverse.js:102:9
    at Array.forEach (native)
    at traverse (D:\Projects\Web\eBookTracker\node_modules\eslint\lib\util\traverse.js:101:11)
    at CLIEngine.executeOnFiles (D:\Projects\Web\eBookTracker\node_modules\eslint\lib\cli-engine.js:284:9)
    at Object.cli.execute (D:\Projects\Web\eBookTracker\node_modules\eslint\lib\cli.js:178:65)
```

If I remove "modules" from ecmaFeatures then there's no exception.

**Comment by fczuardi** [comment]
using ```ecmaFeatures.module``` I no longer get the throw, and the output is:

```
test.js
  1:1  error  Illegal import declaration

✖ 1 problem (1 error, 0 warnings)
```

is that the expected output for the javascript code of the original report?

**Comment by extesy** [comment]
@fczuardi using `ecmaFeatures.module` is the same as using `ecmaFeatures.qwersdfasfe`. Here's the source code from espree.js:

```
    var allowClasses = extra.ecmaFeatures.classes,
        allowModules = extra.ecmaFeatures.modules,
        allowBlockBindings = extra.ecmaFeatures.blockBindings;
```

It looks for `modules` here, not `module`.

**Comment by fczuardi** [comment]
@extesy here is the check:

https://github.com/eslint/eslint/blob/master/lib/eslint.js#L655

maybe your bug is unrelated, but ```ecmaFeatures.qwersdfasfe``` is definitely not the same as ```ecmaFeatures.module``` :)

**Comment by fczuardi** [comment]
I was originally using ```modules``` based on this recommendation https://github.com/eslint/eslint/issues/1944#issuecomment-77707309

**Comment by fczuardi** [comment]
workaround: use both module and modules ;)

I can send a PR to fix the check and expect only modules in the plural

**Comment by extesy** [comment]
Actually, you are right: using both module and modules fixes import exception in one file, but it doesn't fix export exception from my report above.

**Comment by fczuardi** [comment]
here is the pull request https://github.com/eslint/eslint/pull/1964

**Comment by nzakas** [comment]
@extesy please for a separate issue for that.
