### ISSUE TITLE
Exception with es6 module default exports

### ISSUE THREAD

**Issue by extesy** [eslint/eslint#1965]
When using configuration file like this:

```
{
  "env": {
    "browser": true,
    "amd": true,
    "jquery": true,
    "es6": true
  },
  "ecmaFeatures": {
    "module": true,
    "modules": true,
    "jsx": true
  }
}
```

and module with default exports (like `export default function initialize()`), I get this exception:

```
D:\Projects\Web\eBookTracker\node_modules\eslint\node_modules\estraverse\estraverse.js:517
                        throw new Error('Unknown node type ' + nodeType + '.')
                              ^
Error: Unknown node type ExportDefaultDeclaration.
    at Controller.traverse (D:\Projects\Web\eBookTracker\node_modules\eslint\node_modules\estraverse\estraverse.js:517:31)
    at EventEmitter.module.exports.api.verify (D:\Projects\Web\eBookTracker\node_modules\eslint\lib\eslint.js:706:24)
    at processFile (D:\Projects\Web\eBookTracker\node_modules\eslint\lib\cli-engine.js:193:27)
    at D:\Projects\Web\eBookTracker\node_modules\eslint\lib\cli-engine.js:293:26
    at walk (D:\Projects\Web\eBookTracker\node_modules\eslint\lib\util\traverse.js:81:9)
    at D:\Projects\Web\eBookTracker\node_modules\eslint\lib\util\traverse.js:102:9
    at Array.forEach (native)
    at traverse (D:\Projects\Web\eBookTracker\node_modules\eslint\lib\util\traverse.js:101:11)
    at CLIEngine.executeOnFiles (D:\Projects\Web\eBookTracker\node_modules\eslint\lib\cli-engine.js:284:9)
    at Object.cli.execute (D:\Projects\Web\eBookTracker\node_modules\eslint\lib\cli.js:178:65)
```

If I remove "modules" from ecmaFeatures then there's no exception but it doesn't recognize export statement anymore.

**Comment by nzakas** [comment]
Looks like estraverse doesn't understand this node type. For
Filed https://github.com/estools/estraverse/issues/46
