### ISSUE TITLE
Clash on ImportDeclaration

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#1970]
I'm excited the good news about ESLint 0.16.0!

But I tried to lint this single line code, then occured an error.

```js
import test from "test";
```

```
> eslint .\src\test.js
***\nodist\bin\node_modules\eslint\node_modules\escope\escope.js:73
            throw new Error(text);
                  ^
Error
    at assert (***\nodist\bin\node_modules\eslint\node_modules\escope\escope.js:73:19)
    at Referencer.extend.ImportDeclaration (***\nodist\bin\node_modules\eslint\node_modules\escope\escope.js:1383:13)
    at Referencer.Visitor.visit (***\nodist\bin\node_modules\eslint\node_modules\escope\node_modules\esrecurse\esrecurse.js:109:34)
    at Referencer.Visitor.visitChildren (***\nodist\bin\node_modules\eslint\node_modules\escope\node_modules\esrecurse\esrecurse.js:88:38)
    at Referencer.extend.Program (***\nodist\bin\node_modules\eslint\node_modules\escope\escope.js:1236:18)
    at Referencer.Visitor.visit (***\nodist\bin\node_modules\eslint\node_modules\escope\node_modules\esrecurse\esrecurse.js:109:34)
    at Object.analyze (***\nodist\bin\node_modules\eslint\node_modules\escope\escope.js:1430:20)
    at EventEmitter.module.exports.api.verify (***\nodist\bin\node_modules\eslint\lib\eslint.js:651:35)
    at processFile (***\nodist\bin\node_modules\eslint\lib\cli-engine.js:193:27)
    at ***\nodist\bin\node_modules\eslint\lib\cli-engine.js:293:26
```

I guess this assertion error: `assert(this.scopeManager.__isES6() && this.scopeManager.isModule());`.
I use Node.js v0.12.0, and set `true` to all ecmaFeatures and env.es6.

and when I removed `ecmaFeatures.modules`, eslint didn't throw the error.

Umm...
I guess the entry point of this error is here: https://github.com/eslint/eslint/blob/master/lib/eslint.js#L651
the code refers `currentConfig.ecmaFeatures.module`, but document says `modules`.

Ah, I set `true` to both `modules` and `module`, then eslint didn't throw the error.

I'm sorry my poor English. I'm not native...

**Comment by mysticatea** [comment]
Oh, I'm sorry, had fixed already...

**Comment by michaelficarra** [comment]
Yep, duplicate of #1963.
