### ISSUE TITLE
Module feature still broken (needs estraverse 2.0.0)

### ISSUE THREAD

**Issue by steadicat** [eslint/eslint#1979]
There's a [bug](https://github.com/estools/estraverse/issues/46) in the `1.9` version of `estraverse` that causes the following error when using ES6 modules. It's fixed in 2.0. Can you bump the version?

```
/Users/stefano/Work/storehouse-api/node_modules/eslint/node_modules/estraverse/estraverse.js:517
                        throw new Error('Unknown node type ' + nodeType + '.')
                              ^
Error: Unknown node type ExportDefaultDeclaration.
    at Controller.traverse (/Users/stefano/Work/storehouse-api/node_modules/eslint/node_modules/estraverse/estraverse.js:517:31)
    at EventEmitter.module.exports.api.verify (/Users/stefano/Work/storehouse-api/node_modules/eslint/lib/eslint.js:706:24)
    at processFile (/Users/stefano/Work/storehouse-api/node_modules/eslint/lib/cli-engine.js:193:27)
    at /Users/stefano/Work/storehouse-api/node_modules/eslint/lib/cli-engine.js:293:26
    at /Users/stefano/Work/storehouse-api/node_modules/eslint/lib/util/traverse.js:61:17
    at Array.forEach (native)
    at traverse (/Users/stefano/Work/storehouse-api/node_modules/eslint/lib/util/traverse.js:41:54)
    at /Users/stefano/Work/storehouse-api/node_modules/eslint/lib/util/traverse.js:63:17
    at Array.forEach (native)
    at traverse (/Users/stefano/Work/storehouse-api/node_modules/eslint/lib/util/traverse.js:41:54)
make: *** [lint] Error 1

```

**Comment by steadicat** [comment]
Never mind, looks like it's fixed in `0.16.1`.
