### ISSUE TITLE
Throws an error in no-shadow-restricted-names when enabled modules

### ISSUE THREAD

**Issue by okuryu** [eslint/eslint#1985]
I bumped a following error with enabled modules option.

```sh
$ cat module.js
export default function () {
}
```

```sh
$ cat .eslintrc
{
  "ecmaFeatures": {
    "modules": true
  }
}
```

```sh
$ ./node_modules/.bin/eslint module.js

/Users/okuryu/work/test-eslint/node_modules/eslint/lib/rules/no-shadow-restricted-names.js:17
        if (RESTRICTED.indexOf(id.name) > -1) {
                                 ^
TypeError: Cannot read property 'name' of null
    at checkForViolation (/Users/okuryu/work/test-eslint/node_modules/eslint/lib/rules/no-shadow-restricted-names.js:17:34)
    at EventEmitter.FunctionDeclaration (/Users/okuryu/work/test-eslint/node_modules/eslint/lib/rules/no-shadow-restricted-names.js:39:13)
    at EventEmitter.emit (events.js:117:20)
    at Controller.controller.traverse.enter (/Users/okuryu/work/test-eslint/node_modules/eslint/lib/eslint.js:726:25)
    at Controller.__execute (/Users/okuryu/work/test-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:399:31)
    at Controller.traverse (/Users/okuryu/work/test-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:497:28)
    at EventEmitter.module.exports.api.verify (/Users/okuryu/work/test-eslint/node_modules/eslint/lib/eslint.js:719:24)
    at processFile (/Users/okuryu/work/test-eslint/node_modules/eslint/lib/cli-engine.js:193:27)
    at /Users/okuryu/work/test-eslint/node_modules/eslint/lib/cli-engine.js:293:26
    at walk (/Users/okuryu/work/test-eslint/node_modules/eslint/lib/util/traverse.js:81:9)
```

```sh
$ ./node_modules/.bin/eslint -v
v0.16.1
```

**Comment by nzakas** [comment]
Definitely looks like a bug. Will look into it.

**Comment by steadicat** [comment]
`no-underscore-dangle` has the same issue.

**Comment by nzakas** [comment]
Working on this.

**Comment by kentcdodds** [comment]
Nice. I ran into this last night and it was killing me. Saw this fix this morning and npm installed master and it totally fixed the problem. Looking forward to the next release.

As a side note, I just switched my entire 26,000 Lines of code application for jshint to eslint. Woot woot :-)
