### ISSUE TITLE
Destructuring Defaults throws Unknown node type Error

### ISSUE THREAD

**Issue by kentor** [eslint/eslint#1986]
package.json:
```json
{
  "devDependencies": {
    "eslint": "^0.16.1"
  }
}
```

index.js:
```js
var { a='a' } = {};
```

.eslintrc:
```yaml
---
env:
  es6: true
```

```
$ ./node_modules/.bin/eslint index.js

/Users/kenneth/stuff/eslint-test/node_modules/eslint/node_modules/estraverse/estraverse.js:517
                        throw new Error('Unknown node type ' + nodeType + '.')
                              ^
Error: Unknown node type AssignmentPattern.
    at Controller.traverse (/Users/kenneth/stuff/eslint-test/node_modules/eslint/node_modules/estraverse/estraverse.js:517:31)
    at Object.traverse (/Users/kenneth/stuff/eslint-test/node_modules/eslint/node_modules/estraverse/estraverse.js:709:27)
    at traverseIdentifierInPattern (/Users/kenneth/stuff/eslint-test/node_modules/eslint/node_modules/escope/escope.js:879:20)
    at Referencer.extend.visitPattern (/Users/kenneth/stuff/eslint-test/node_modules/eslint/node_modules/escope/escope.js:1024:13)
    at Referencer.extend.visitVariableDeclaration (/Users/kenneth/stuff/eslint-test/node_modules/eslint/node_modules/escope/escope.js:1168:18)
    at Referencer.extend.VariableDeclaration (/Users/kenneth/stuff/eslint-test/node_modules/eslint/node_modules/escope/escope.js:1336:22)
    at Referencer.Visitor.visit (/Users/kenneth/stuff/eslint-test/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
    at Referencer.Visitor.visitChildren (/Users/kenneth/stuff/eslint-test/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:88:38)
    at Referencer.extend.Program (/Users/kenneth/stuff/eslint-test/node_modules/eslint/node_modules/escope/escope.js:1236:18)
    at Referencer.Visitor.visit (/Users/kenneth/stuff/eslint-test/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)

**Comment by nzakas** [comment]
This is an issue with estraverse not understanding what it's seeing. A new version was just released, so I'll try to plug it in today.
