### ISSUE TITLE
TypeError: Cannot set property 'check' of undefined

### ISSUE THREAD

**Issue by dmfilipenko** [eslint/eslint#2005]
With new version of ESLint got this issue, when **indent** set to **[2,2]** in .eslintrc
```
/usr/local/lib/node_modules/eslint/lib/rules/indent.js:95
        linesToCheck[line].check = true;
                                 ^
TypeError: Cannot set property 'check' of undefined
    at markCheckLine (/usr/local/lib/node_modules/eslint/lib/rules/indent.js:95:34)
    at markCheck (/usr/local/lib/node_modules/eslint/lib/rules/indent.js:104:9)
    at /usr/local/lib/node_modules/eslint/lib/rules/indent.js:180:17
    at Array.forEach (native)
    at markChildren (/usr/local/lib/node_modules/eslint/lib/rules/indent.js:178:27)
    at EventEmitter.Program (/usr/local/lib/node_modules/eslint/lib/rules/indent.js:388:13)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (/usr/local/lib/node_modules/eslint/lib/eslint.js:735:25)
    at Controller.__execute (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
```
When I set **indent** to **0** everything okay

**Comment by nzakas** [comment]
Just to confirm, you're using 0.16.2? Can you share the code you were linting?

**Comment by dmfilipenko** [comment]
Yep, version is ```v0.16.2```
code is
````import {addons} from 'react/addons'^Mimport React from 'react'```

**Comment by nzakas** [comment]
Working on this.

**Comment by nzakas** [comment]
So it looks like you're using `\r` as a line break instead of `\n`, so the line breaking is getting confused.

Out of curiosity, why are you using `\r`?

**Comment by nzakas** [comment]
It's not the actual rule, but rather `getSourceLines()` that is returning the wrong results due to the unexpected line break. According to ECMA-262, `\r` is a valid line break by itself, but we're not treating it as such.
