### ISSUE TITLE
Computed properties failing

### ISSUE THREAD

**Issue by sscotth** [eslint/eslint#2120]
```js
// ecmaFeatures:
//   objectLiteralComputedProperties:  true  # enable computed object literal property names
var suffix = " name";

var person = {
    ["first" + suffix]: "Nicholas",
    ["last" + suffix]: "Zakas"
};

console.log(person["first name"]);      // "Nicholas"
console.log(person["last name"]);       // "Zakas"
```

```
/Users/scott/.nvm/versions/io.js/v1.6.1/lib/node_modules/eslint/lib/rules/key-spacing.js:38
    return (key.type === "Identifier" ? key.name : key.raw).length;
                                                           ^
TypeError: Cannot read property 'length' of undefined
    at getKeyWidth (/Users/scott/.nvm/versions/io.js/v1.6.1/lib/node_modules/eslint/lib/rules/key-spacing.js:38:60)
    at Array.map (native)
    at verifyAlignment (/Users/scott/.nvm/versions/io.js/v1.6.1/lib/node_modules/eslint/lib/rules/key-spacing.js:158:33)
    at /Users/scott/.nvm/versions/io.js/v1.6.1/lib/node_modules/eslint/lib/rules/key-spacing.js:201:21
    at Array.forEach (native)
    at EventEmitter.ObjectExpression (/Users/scott/.nvm/versions/io.js/v1.6.1/lib/node_modules/eslint/lib/rules/key-spacing.js:200:26)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:166:7)
    at Controller.controller.traverse.enter (/Users/scott/.nvm/versions/io.js/v1.6.1/lib/node_modules/eslint/lib/eslint.js:735:25)
    at Controller.__execute (/Users/scott/.nvm/versions/io.js/v1.6.1/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
```

**Comment by michaelficarra** [comment]
This is in the key-spacing rule. As a workaround, you should disable that rule.

**Comment by nzakas** [comment]
We will get this fixed soon.

**Comment by gyandeeps** [comment]
I thik it gives this error on `iojs`.
On `node 0.12.0`, it doesnt throw any error but I think this rule doesnt work for `objectLiteralComputedProperties` property of `ecmaFeatures`.

.eslintrc

```.json
{
    "env": {
        "node": true
    },
    "ecmaFeatures": {
        "objectLiteralComputedProperties": true
    },
    "rules": {
        "key-spacing": [2, {
            "beforeColon": false,
            "afterColon": true
        }]
    }
}
```

app.js

```.js
var suffix = " name";

var person = {
    ["first" + suffix] : "Nicholas",
    ["last" + suffix]: "Zakas"
};

console.log(person["first name"]);      // "Nicholas"
console.log(person["last name"]);       // "Zakas"
```

**Comment by nzakas** [comment]
@gyandeeps what makes you think this is related to Node version? The problem is that we're expecting an identifier or string.

**Comment by gyandeeps** [comment]
Yup, it throws error regardless of the node version. I did update my comment.
I think we have 2 potential problem (take the code in this issue as example):
- When we use the rule with `"align": "colon"` option then it throws the error as mentioned in this issue.
- Use this rule but without the option `"align": "colon"` and then i would expect 1 error. For this use the setup as described below.

.eslintrc

```.json
{
    "env": {
        "node": true
    },
    "ecmaFeatures": {
        "objectLiteralComputedProperties": true
    },
    "rules": {
        "key-spacing": [2, {
            "beforeColon": false,
            "afterColon": true
        }]
    }
}
```

app.js

```.js
var suffix = " name";

var person = {
    ["first" + suffix] : "Nicholas",
    ["last" + suffix]: "Zakas"
};

console.log(person["first name"]);      // "Nicholas"
console.log(person["last name"]);       // "Zakas"
```

I would expect 1 error under this scenario.

**Comment by nzakas** [comment]
Yeah, we're just not handling computed properties at all, so everything is haywire.

**Comment by btmills** [comment]
Working on this.
