### ISSUE TITLE
Rule: indent fails with SwitchStatement with no SwitchCases

### ISSUE THREAD

**Issue by message** [eslint/eslint#2144]
```
/Users/message/www/java-frontend-webapp/node_modules/gulp-eslint/node_modules/eslint/lib/rules/indent.js:422
            if (node.loc.start.column === children[0].loc.start.column) {
                                                     ^
TypeError: Cannot read property 'loc' of undefined
  at EventEmitter.SwitchStatement (/Users/message/www/java-frontend-webapp/node_modules/gulp-eslint/node_modules/eslint/lib/rules/indent.js:422:54)
  at EventEmitter.emit (events.js:117:20)
  at Controller.controller.traverse.enter (/Users/message/www/java-frontend-webapp/node_modules/gulp-eslint/node_modules/eslint/lib/eslint.js:735:25)
  at Controller.__execute (/Users/message/www/java-frontend-webapp/node_modules/gulp-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
  at Controller.traverse (/Users/message/www/java-frontend-webapp/node_modules/gulp-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
  at EventEmitter.module.exports.api.verify (/Users/message/www/java-frontend-webapp/node_modules/gulp-eslint/node_modules/eslint/lib/eslint.js:728:24)
  at verify (/Users/message/www/java-frontend-webapp/node_modules/gulp-eslint/index.js:21:25)
  at DestroyableTransform._transform (/Users/message/www/java-frontend-webapp/node_modules/gulp-eslint/index.js:44:18)
  at DestroyableTransform.Transform._read (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at write (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:92:17)
  at emitReadable_ (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at DestroyableTransform.noop [as _transform] (/Users/message/www/java-frontend-webapp/node_modules/through2/through2.js:26:3)
  at DestroyableTransform.Transform._read (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at write (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:92:17)
  at emitReadable_ (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/Users/message/www/java-frontend-webapp/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at /Users/message/www/java-frontend-webapp/node_modules/gulp/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:12:5
  at evalmachine.<anonymous>:271:14
  at /Users/message/www/java-frontend-webapp/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs/graceful-fs.js:102:5
  at Object.oncomplete (evalmachine.<anonymous>:107:15)
```
Indent rule is stil in beta?

**Comment by ilyavolodin** [comment]
Everything is still in beta (we have not reached version 1.0.0 yet). Can you please provide the code that this is failing on?

**Comment by michaelficarra** [comment]
Looks like the intent rule doesn't like a SwitchStatement with no SwitchCases: https://github.com/eslint/eslint/blob/06927eeacba776c29a40bc0a191f9d9fc9575ba6/lib/rules/indent.js#L422. This should probably trigger it:

```js
switch(0) { }
```

**Comment by message** [comment]
Yeap @michaelficarra. /cc @ilyavolodin 
```
switch (true) {
}
```

**Comment by btmills** [comment]
Working on this.
