### ISSUE TITLE
package.json says espree ^1.12.0, but running tests with .0 or .1 fails

### ISSUE THREAD

**Issue by DavidAnson** [eslint/eslint#2195]
Running "npm test" with espree 1.12.0 or 1.12.1 installed leads to the below test failure. There is no such failure with espree 1.12.2 or 1.12.3 installed.

```
  1) no-ex-assign try { } catch ({e}) { this.something = 2; }:
     AssertionError: Should have no errors but had 1: [ { fatal: true,
    severity: 2,
    message: 'Unexpected token {',
    line: 1,
    column: 16 } ]: expected 1 to equal 0
      at testValidTemplate (C:\T\eslint\node_modules\eslint-tester\lib\eslint-tester.js:117:20)
      at Context.<anonymous> (C:\T\eslint\node_modules\eslint-tester\lib\eslint-tester.js:164:25)
      at callFn (C:\T\eslint\node_modules\mocha\lib\runnable.js:266:21)
      at Test.Runnable.run (C:\T\eslint\node_modules\mocha\lib\runnable.js:259:7)
      at Runner.runTest (C:\T\eslint\node_modules\mocha\lib\runner.js:387:10)
      at C:\T\eslint\node_modules\mocha\lib\runner.js:470:12
      at next (C:\T\eslint\node_modules\mocha\lib\runner.js:312:14)
      at C:\T\eslint\node_modules\mocha\lib\runner.js:322:7
      at next (C:\T\eslint\node_modules\mocha\lib\runner.js:257:23)
      at Immediate._onImmediate (C:\T\eslint\node_modules\mocha\lib\runner.js:289:5)
      at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by nzakas** [comment]
Thanks, we should get that updated.
