### ISSUE TITLE
Reference error with no-unused-vars and JSX

### ISSUE THREAD

**Issue by sebmck** [eslint/eslint#2304]
The following error is thrown when attempting to lint `import App from './App'; export default (<App />);` with the rule `no-unused-vars`.

```
TypeError: Cannot read property 'type' of undefined
    at isExported (/Users/sebmck/Projects/babel/eslint/node_modules/eslint/lib/rules/no-unused-vars.js:43:27)
    at EventEmitter.Program:exit (/Users/sebmck/Projects/babel/eslint/node_modules/eslint/lib/rules/no-unused-vars.js:158:70)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:166:7)
    at Controller.controller.traverse.leave (/Users/sebmck/Projects/babel/eslint/node_modules/eslint/lib/eslint.js:743:25)
    at Controller.__execute (/Users/sebmck/Projects/babel/eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (/Users/sebmck/Projects/babel/eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:481:28)
    at EventEmitter.module.exports.api.verify (/Users/sebmck/Projects/babel/eslint/node_modules/eslint/lib/eslint.js:728:24)
    at repl:1:26
    at REPLServer.defaultEval (repl.js:124:27)
```

```javascript
require("eslint").linter.verify("import App from './App'; export default (<App />);", {
  ecmaFeatures: { modules: true, jsx: true },
  rules: { "no-unused-vars": 1, "no-undef": 1 }
});
```

**Comment by nzakas** [comment]
Thanks, will take a look.

**Comment by btmills** [comment]
@sebmck which version of ESLint are you using? I can reproduce this in `v0.18.0` but not `v0.19.0`.

**Comment by sebmck** [comment]
Yep that was it. Apologies for not checking if I was on the latest. Thanks @btmills!
