### ISSUE TITLE
"key-spacing" rule issue

### ISSUE THREAD

**Issue by ALF-er** [eslint/eslint#2311]
Hello, I'm using eslint v0.19.0 and receive error
```
C:\Users\Illia\AppData\Roaming\npm\node_modules\eslint\lib\rules\key-spacing.js:217
            widths = properties.map(getKeyWidth), // Width of keys, including
                                ^
TypeError: undefined is not a function
    at verifyGroupAlignment (C:\Users\Illia\AppData\Roaming\npm\node_modules\eslint\lib\rules\key-spacing.js:217:33)
    at C:\Users\Illia\AppData\Roaming\npm\node_modules\eslint\lib\rules\key-spacing.js:251:13
    at Array.forEach (native)
    at verifyAlignment (C:\Users\Illia\AppData\Roaming\npm\node_modules\eslint\lib\rules\key-spacing.js:250:28)
    at EventEmitter.ObjectExpression (C:\Users\Illia\AppData\Roaming\npm\node_modules\eslint\lib\rules\key-spacing.js:292:21)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:166:7)
    at Controller.controller.traverse.enter (C:\Users\Illia\AppData\Roaming\npm\node_modules\eslint\lib\eslint.js:726:25)
    at Controller.__execute (C:\Users\Illia\AppData\Roaming\npm\node_modules\eslint\node_modules\estraverse\estraverse.js:393:31)
    at Controller.traverse (C:\Users\Illia\AppData\Roaming\npm\node_modules\eslint\node_modules\estraverse\estraverse.js:491:28)
```

on file
```
/*eslint key-spacing: [2, { "align": "value" }]*/
 
(
	{
		user: 2
	}
)
```

It's bug, or I miss something?

**Comment by btmills** [comment]
#2238 broke `key-spacing` on single-property object literals. Working on this.

**Comment by IanVS** [comment]
My apologies for introducing this regression, and thanks for fixing @btmills.
