### ISSUE TITLE
space-in-brackets: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by deepsweet** [eslint/eslint#2378]
```
$ eslint -v
v0.20.0
```

```
$ npm ls babel-eslint
...
└── babel-eslint@3.0.1
```

```
test/node_modules/eslint/lib/rules/space-in-brackets.js:233
            if (firstSpecifier.type === "ImportSpecifier" && lastSpecifier.typ
                              ^
TypeError: Cannot read property 'type' of undefined
    at EventEmitter.ImportDeclaration (test/node_modules/eslint/lib/rules/space-in-brackets.js:233:31)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:166:7)
    at Controller.controller.traverse.enter (test/node_modules/eslint/lib/eslint.js:726:25)
    at Controller.__execute (test/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (test/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (test/node_modules/eslint/lib/eslint.js:719:24)
    at processFile (test/node_modules/eslint/lib/cli-engine.js:197:27)
    at test/node_modules/eslint/lib/cli-engine.js:299:26
    at test/node_modules/eslint/lib/util/traverse.js:61:17
```

**Comment by gyandeeps** [comment]
Can you share the code?

**Comment by deepsweet** [comment]
I figured it out, the problem is in short-hand imports w/o assignments like this:

```js
import './foo';
```

**Comment by nzakas** [comment]
AFAIK, that's invalid syntax.

**Comment by michaelficarra** [comment]
No, it's valid.

```
ImportDeclaration :
  import ImportClause FromClause ;
  import ModuleSpecifier ;
```

**Comment by nzakas** [comment]
Huh, I had no idea.

**Comment by yamalight** [comment]
any ETA on release of fixed version?

**Comment by nzakas** [comment]
Possibly this weekend; next weekend if not.

**Comment by yamalight** [comment]
@nzakas great, thanks!
