### ISSUE TITLE
space-in-brackets: Cannot read property 'range' of undefined

### ISSUE THREAD

**Issue by Ambroos** [eslint/eslint#2392]
ESLint v0.20.0 crashes with this error when trying to validate each of the files below (and variations) using the .eslintrc below. This error did not occur with ESLint v0.19.

## Error
```
TypeError: Cannot read property 'range' of undefined
    at EventEmitter.api.getTokenBefore (/Users/Ambroos/.node/lib/node_modules/eslint/lib/token-store.js:90:34)
    at RuleContext.(anonymous function) [as getTokenBefore] (/Users/Ambroos/.node/lib/node_modules/eslint/lib/rule-context.js:84:33)
    at EventEmitter.ExportNamedDeclaration (/Users/Ambroos/.node/lib/node_modules/eslint/lib/rules/space-in-brackets.js:248:33)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (/Users/Ambroos/.node/lib/node_modules/eslint/lib/eslint.js:726:25)
    at Controller.__execute (/Users/Ambroos/.node/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (/Users/Ambroos/.node/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (/Users/Ambroos/.node/lib/node_modules/eslint/lib/eslint.js:719:24)
    at processText (/Users/Ambroos/.node/lib/node_modules/eslint/lib/cli-engine.js:231:23)
    at CLIEngine.executeOnText (/Users/Ambroos/.node/lib/node_modules/eslint/lib/cli-engine.js:343:22) 
```

## .eslintrc
```json
{
  "ecmaFeatures": {
    "blockBindings": true,
    "modules": true
  },
  "rules": {
    "space-in-brackets": 2
  }
}
```

## test1.js
```javascript
export const thing = {
    value: 1
};
```

## test2.js
```javascript
export const thing = {};
```

## test3.js
```javascript
export var thing = {};
```

## test4.js
```javascript
export let thing = {};
```

**Comment by daliwali** [comment]
+1, also getting this error.

**Comment by nzakas** [comment]
Thanks. Are you using the default parser or babel-eslint?

**Comment by Ambroos** [comment]
The error occurs with both, so I assume it's an ESLint issue.

**Comment by nzakas** [comment]
Thanks, will take a look.
