### ISSUE TITLE
space-in-brackets breaks with es6 exported class

### ISSUE THREAD

**Issue by Jxck** [eslint/eslint#2401]
Hi, I tried eslint@0.20.0 with es6
and found buggy behave in spece-in-brackets rule in es6 code.

```js
// index.js
export class MyClass {
}
```

```
# .eslintrc
env:
  es6     : true

ecmaFeatures:
 arrowFunctions: true,
 binaryLiterals: true,
 blockBindings: true,
 classes: true,
 defaultParams: true,
 destructuring: true,
 forOf: true,
 generators: true,
 modules: true,
 objectLiteralComputedProperties: true,
 objectLiteralDuplicateProperties: true,
 objectLiteralShorthandMethods: true,
 objectLiteralShorthandProperties: true,
 octalLiterals: true,
 regexUFlag: true,
 regexYFlag: true,
 superInFunctions: true,
 templateStrings: true,
 unicodeCodePointEscapes: true,
 globalReturn: true

rules:
  space-in-brackets      : [2, 'always']
```

```sh
$ eslint -c .eslint index.js
.../node_modules/eslint/lib/token-store.js:90
        return tokens[starts[node.range[0]] - (skip || 0) - 1];
                                 ^
TypeError: Cannot read property 'range' of undefined
    at EventEmitter.api.getTokenBefore (.../node_modules/g/eslint/lib/token-store.js:90:34)
    at RuleContext.(anonymous function) [as getTokenBefore] (.../node_modules/g/eslint/lib/rule-context.js:84:33)
    at EventEmitter.ExportNamedDeclaration (.../node_modules/g/eslint/lib/rules/space-in-brackets.js:247:33)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (.../node_modules/g/eslint/lib/eslint.js:726:25)
    at Controller.__execute (.../node_modules/g/estraverse/estraverse.js:393:31)
    at Controller.traverse (.../node_modules/g/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (.../node_modules/g/eslint/lib/eslint.js:719:24)
    at processFile (.../node_modules/g/eslint/lib/cli-engine.js:197:27)
    at .../node_modules/g/eslint/lib/cli-engine.js:299:26
```

thanks

**Comment by nzakas** [comment]
Thanks, we will take a look.

**Comment by jrvidal** [comment]
Looks like #2396 already fixed this.

**Comment by nzakas** [comment]
Oh cool, thanks!
