### ISSUE TITLE
`no-multiple-empty-lines` fails on {max: 0}

### ISSUE THREAD

**Issue by kdex** [eslint/eslint#2423]
I personally use comments as separators to force myself to comment all the code I write instead of just leaving blank lines around. Since nearly all editors have some decent syntax highlighting today, this results in pretty clear and re-usable code for me.

Setting `max: 0` should forbid:

```js
let req = new XMLHttpRequest();

req.open("get", "api/u/online.json", true);
```

but allow this:

```js
let req = new XMLHttpRequest();
/* Retrieve list of online users */
req.open("GET", "api/u/online.json", true);
```

But instead, this happens:

```js
0 ✓ kdex@punchy ~/dev/p $ grunt dev
Running "eslint:lint" (eslint) task
Warning: Cannot read property 'length' of undefined Use --force to continue.

Aborted due to warnings.

```

 Could you make `max: 0` behave the way one would expect it to?

**Comment by nzakas** [comment]
What is ESLint outputting exactly? All you're showing is what grunt is outputting, which doesn't tell us anything.

**Comment by kdex** [comment]
One stack trace coming up, hot and greasy:

```js
0 ✓ kdex@punchy ~/dev/p $ node_modules/grunt-eslint/node_modules/eslint/bin/eslint.js --config conf/standard-js.json src/client/js/app.js 
/srv/http/bp/node_modules/grunt-eslint/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:48
                            column: lines[lastLocation].length
                                                       ^
TypeError: Cannot read property 'length' of undefined
    at EventEmitter.checkBlankLines (/srv/http/bp/node_modules/grunt-eslint/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:48:56)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (/srv/http/bp/node_modules/grunt-eslint/node_modules/eslint/lib/eslint.js:726:25)
    at Controller.__execute (/srv/http/bp/node_modules/grunt-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (/srv/http/bp/node_modules/grunt-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (/srv/http/bp/node_modules/grunt-eslint/node_modules/eslint/lib/eslint.js:719:24)
    at processFile (/srv/http/bp/node_modules/grunt-eslint/node_modules/eslint/lib/cli-engine.js:197:27)
    at /srv/http/bp/node_modules/grunt-eslint/node_modules/eslint/lib/cli-engine.js:299:26
    at walk (/srv/http/bp/node_modules/grunt-eslint/node_modules/eslint/lib/util/traverse.js:81:9)
    at /srv/http/bp/node_modules/grunt-eslint/node_modules/eslint/lib/util/traverse.js:102:9
1 ✗ kdex@punchy ~/dev/p $ 
```

Also:

```js
1 ✗ kdex@punchy ~/dev/bp $ node_modules/grunt-eslint/node_modules/eslint/bin/eslint.js --config conf/standard-js.json src/client/js/app.js --version
v0.20.0
```

**Comment by gyandeeps** [comment]
I tried it too. It doesnt handle value 0.
But I think it should support it.

**Comment by nzakas** [comment]
It definitely should not throw an error, but what should `max:0` do? Just disallow all empty lines?

**Comment by kdex** [comment]
It should disallow "empty" lines, with "empty" meaning whitespace-only. Assuming that "·" is a whitespace character and "↲" is a EOL character in the following snippets, it should **forbid** the following cases:

```js
let·req·=·new·XMLHttpRequest();↲
↲
req.open("get",·"api/u/online.json",·true);
```

```js
let·req·=·new·XMLHttpRequest();↲
·↲
req.open("get",·"api/u/online.json",·true);
```

```js
let·req·=·new·XMLHttpRequest();↲
······↲
req.open("get",·"api/u/online.json",·true);
```

```js
let·req·=·new·XMLHttpRequest();↲
↲
······↲
req.open("get",·"api/u/online.json",·true);
```


Whereas these cases should be allowed:

```js
let·req·=·new·XMLHttpRequest();↲
/*·Retrieve·list·of·online·users·*/↲
req.open("get",·"api/u/online.json",·true);
```

```js
let·req·=·new·XMLHttpRequest();↲
/*·Retrieve·list·of·online·users·*/↲
"I·am·a·useless·string,·but·I·serve·more·information·than·a·blank·line";↲
req.open("get",·"api/u/online.json",·true);
```

The last line of the file should be ignored, as this case is already covered by `eol-last`. This means that this should pass, given that `eol-last` is enabled and fail if `eol-last` is disabled.

```js
let·req·=·new·XMLHttpRequest();↲
/*·Retrieve·list·of·online·users·*/↲
req.open("get",·"api/u/online.json",·true);↲
```

**Comment by gcochard** [comment]
Wow, can't believe I missed this edge case when authoring the rule. Looking at this tonight.

**Comment by gcochard** [comment]
To clarify, we can't detect if other rules are active or not, so you'll want to use `eol-last` to detect your last case.

**Comment by gcochard** [comment]
Shoot, missed the last line exception. I'll create another pull request. @nzakas should I create another issue as well?

**Comment by nzakas** [comment]
No, just use "refs #2423" in your commit.
