### ISSUE TITLE
Simple import statement causes an error deep inside ESLint

### ISSUE THREAD

**Issue by mzgol** [eslint/eslint#2434]
ESLint 0.20.0, JS:
```js
import './polyfill';
```
Config:
```json
{
    "ecmaFeatures": {
        "modules": true
    },

    "env": {
        "es6": true,
        "node": true
    },

    "rules": {
        "comma-dangle": 0,
        "no-console": 0,

        "block-scoped-var": 2,
        "complexity": [2, 10],
        "eqeqeq": [2, "smart"],
        "no-else-return": 2,
        "no-floating-decimal": 2,
        "no-lone-blocks": 0,
        "no-self-compare": 2,
        "wrap-iife": [2, "inside"],

        "no-use-before-define": 0,
        "no-shadow": 0,

        "no-mixed-requires": 0,

        "brace-style": 2,
        "camelcase": 0,
        "new-cap": 0,
        "no-lonely-if": 2,
        "no-underscore-dangle": 0,
        "space-after-keywords": 2,
        "space-in-brackets": [2, "never"],
        "space-infix-ops": 2,
        "quotes": [2, "single"],

        "no-bitwise": 2
    }
}

```
Output:
```
/Users/mgol/Documents/projects/wiekxix/git/node_modules/grunt-eslint/node_modules/eslint/lib/rules/space-in-brackets.js:233
            if (firstSpecifier.type === "ImportSpecifier" && lastSpecifier.typ
                              ^
TypeError: Cannot read property 'type' of undefined
    at EventEmitter.ImportDeclaration (/Users/mgol/Documents/projects/wiekxix/git/node_modules/grunt-eslint/node_modules/eslint/lib/rules/space-in-brackets.js:233:31)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:166:7)
    at Controller.controller.traverse.enter (/Users/mgol/Documents/projects/wiekxix/git/node_modules/grunt-eslint/node_modules/eslint/lib/eslint.js:726:25)
    at Controller.__execute (/Users/mgol/Documents/projects/wiekxix/git/node_modules/grunt-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (/Users/mgol/Documents/projects/wiekxix/git/node_modules/grunt-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (/Users/mgol/Documents/projects/wiekxix/git/node_modules/grunt-eslint/node_modules/eslint/lib/eslint.js:719:24)
    at processFile (/Users/mgol/Documents/projects/wiekxix/git/node_modules/grunt-eslint/node_modules/eslint/lib/cli-engine.js:197:27)
    at /Users/mgol/Documents/projects/wiekxix/git/node_modules/grunt-eslint/node_modules/eslint/lib/cli-engine.js:299:26
    at /Users/mgol/Documents/projects/wiekxix/git/node_modules/grunt-eslint/node_modules/eslint/lib/util/traverse.js:61:17
```

**Comment by gyandeeps** [comment]
Same as https://github.com/eslint/eslint/issues/2378
It has been fixed but not yet released.
