### ISSUE TITLE
Named export breaks ESLint

### ISSUE THREAD

**Issue by mzgol** [eslint/eslint#2435]
ESLint 0.20.0, JS:
```js
export function f(){}
```
Config:
```json
{
    "ecmaFeatures": {
        "modules": true
    },

    "env": {
        "es6": true,
        "node": true
    },

    "rules": {
        "comma-dangle": 0,
        "no-console": 0,

        "block-scoped-var": 2,
        "complexity": [2, 10],
        "eqeqeq": [2, "smart"],
        "no-else-return": 2,
        "no-floating-decimal": 2,
        "no-lone-blocks": 0,
        "no-self-compare": 2,
        "wrap-iife": [2, "inside"],

        "no-use-before-define": 0,
        "no-shadow": 0,

        "no-mixed-requires": 0,

        "brace-style": 2,
        "camelcase": 0,
        "new-cap": 0,
        "no-lonely-if": 2,
        "no-underscore-dangle": 0,
        "space-after-keywords": 2,
        "space-in-brackets": [2, "never"],
        "space-infix-ops": 2,
        "quotes": [2, "single"],

        "no-bitwise": 2
    }
}

```
Output:
```
/Users/mgol/Documents/projects/wiekxix/git/node_modules/grunt-eslint/node_modules/eslint/lib/token-store.js:90
        return tokens[starts[node.range[0]] - (skip || 0) - 1];
                                 ^
TypeError: Cannot read property 'range' of undefined
    at EventEmitter.api.getTokenBefore (/Users/mgol/Documents/projects/wiekxix/git/node_modules/grunt-eslint/node_modules/eslint/lib/token-store.js:90:34)
    at RuleContext.(anonymous function) [as getTokenBefore] (/Users/mgol/Documents/projects/wiekxix/git/node_modules/grunt-eslint/node_modules/eslint/lib/rule-context.js:84:33)
    at EventEmitter.ExportNamedDeclaration (/Users/mgol/Documents/projects/wiekxix/git/node_modules/grunt-eslint/node_modules/eslint/lib/rules/space-in-brackets.js:248:33)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:166:7)
    at Controller.controller.traverse.enter (/Users/mgol/Documents/projects/wiekxix/git/node_modules/grunt-eslint/node_modules/eslint/lib/eslint.js:726:25)
    at Controller.__execute (/Users/mgol/Documents/projects/wiekxix/git/node_modules/grunt-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (/Users/mgol/Documents/projects/wiekxix/git/node_modules/grunt-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (/Users/mgol/Documents/projects/wiekxix/git/node_modules/grunt-eslint/node_modules/eslint/lib/eslint.js:719:24)
    at processFile (/Users/mgol/Documents/projects/wiekxix/git/node_modules/grunt-eslint/node_modules/eslint/lib/cli-engine.js:197:27)
```

**Comment by gyandeeps** [comment]
I think this issue got resolved in https://github.com/eslint/eslint/pull/2396
I have to double check. But that fix has not been released yet.

**Comment by gyandeeps** [comment]
Yes it did.
