### ISSUE TITLE
`space-in-brackets` error with export

### ISSUE THREAD

**Issue by hzoo** [eslint/eslint#2471]
Originally reported in https://github.com/babel/babel-eslint/issues/87, but I was able to reproduce the error with the default parser so maybe someone else can confirm?

`.eslintrc`

```yaml
ecmaFeatures:
  modules: true
  blockBindings: true

# 0: off, 1: warning, 2: error
rules:

  # consistent whitespace in brackets
  space-in-brackets: [2, "always"]
```

`test.js`
```js
export const bar = "foo"
```

with eslint `0.20.0`

Error:

```js
d:\node\www\stylelint\node_modules\eslint\lib\token-store.js:90
        return tokens[starts[node.range[0]] - (skip || 0) - 1];
                                 ^
TypeError: Cannot read property 'range' of undefined
    at EventEmitter.api.getTokenBefore (d:\node\www\stylelint\node_modules\eslint\lib\token-store.js:90:34)
    at RuleContext.(anonymous function) [as getTokenBefore] (d:\node\www\stylelint\node_modules\eslint\lib\rule-context.js:84:33)
    at EventEmitter.ExportNamedDeclaration (d:\node\www\stylelint\node_modules\eslint\lib\rules\space-in-brackets.js:248:33)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (d:\node\www\stylelint\node_modules\eslint\lib\eslint.js:726:25)
    at Controller.__execute (d:\node\www\stylelint\node_modules\eslint\node_modules\estraverse\estraverse.js:393:31)
    at Controller.traverse (d:\node\www\stylelint\node_modules\eslint\node_modules\estraverse\estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (d:\node\www\stylelint\node_modules\eslint\lib\eslint.js:719:24)
    at processFile (d:\node\www\stylelint\node_modules\eslint\lib\cli-engine.js:197:27)
    at d:\node\www\stylelint\node_modules\eslint\lib\cli-engine.js:299:26
```

**Comment by hzoo** [comment]
Ok checking the history it looks like this would be a duplicate of #2392 which was fixed in master?
