### ISSUE TITLE
Unnecessary 'undefined' in config error output

### ISSUE THREAD

**Issue by roadhump** [eslint/eslint#2474]
`undefined` is appended to config error output when using `--stdin` option and error output seems slightly inconsistent. I suppose part with `eslint/lib/config.js` can be omitted, but `YAMLException:` must be in both cases.

```
$ cat 1.js | eslint --stdin

Cannot read config file: /Users/roadhump/Projects/tx/.eslintrc
Error: JS-YAML: unexpected end of the stream within a double quoted scalar at line 6, column 1:
    
    ^
undefined
```

It is ok without stdin

```
$ eslint 1.js


/Users/roadhump/Projects/eslint/lib/config.js:61
            throw e;
                  ^
YAMLException: Cannot read config file: /Users/roadhump/Projects/tx/.eslintrc
Error: JS-YAML: unexpected end of the stream within a double quoted scalar at line 6, column 1:
    
    ^
```

**Comment by gyandeeps** [comment]
@roadhump Is this still an issue?

**Comment by roadhump** [comment]
@gyandeeps I see in version 1.2.0 that error is more correct, without strange `undefined`, but errors are still differ for `eslint file.js` and `eslint --stdin`.

**Comment by gyandeeps** [comment]
Can you please update the issue with the correct information as per `1.2.0`

**Comment by roadhump** [comment]
For ESLint 1.2.0
I use incorrect `.eslintrc` file and get slightly different errors when run as `eslint file.js` and `eslint --stdin`. I suppose errors should be the same in the name of consistency.

e.g.
`eslint src/App.js`
```

/Users/roadhump/Projects/xx/node_modules/eslint/lib/config.js:87
            throw e;
            ^
YAMLException: Cannot read config file: /Users/roadhump/Projects/xx/.eslintrc
Error: missed comma between flow collection entries at line 2, column 13:
        "parser"s: "babel-eslint",
                ^
    at generateError (/Users/roadhump/Projects/xx/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:160:10)
    at throwError (/Users/roadhump/Projects/xx/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:166:9)
    at readFlowCollection (/Users/roadhump/Projects/xx/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:675:7)
    at composeNode (/Users/roadhump/Projects/xx/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1316:11)
    at readBlockMapping (/Users/roadhump/Projects/xx/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:990:16)
    at composeNode (/Users/roadhump/Projects/xx/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1315:12)
    at readDocument (/Users/roadhump/Projects/xx/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1478:3)
    at loadDocuments (/Users/roadhump/Projects/xx/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1538:5)
    at load (/Users/roadhump/Projects/xx/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1555:19)
    at Object.safeLoad (/Users/roadhump/Projects/xx/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1573:10)
```

`cat src/App.js | eslint --stdin`
```
Cannot read config file: /Users/roadhump/Projects/xx/.eslintrc
Error: missed comma between flow collection entries at line 2, column 13:
        "parser"s: "babel-eslint",
                ^
YAMLException: Cannot read config file: /Users/roadhump/Projects/xx/.eslintrc
Error: missed comma between flow collection entries at line 2, column 13:
        "parser"s: "babel-eslint",
                ^
    at generateError (/Users/roadhump/Projects/xx/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:160:10)
    at throwError (/Users/roadhump/Projects/xx/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:166:9)
    at readFlowCollection (/Users/roadhump/Projects/xx/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:675:7)
    at composeNode (/Users/roadhump/Projects/xx/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1316:11)
    at readBlockMapping (/Users/roadhump/Projects/xx/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:990:16)
    at composeNode (/Users/roadhump/Projects/xx/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1315:12)
    at readDocument (/Users/roadhump/Projects/xx/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1478:3)
    at loadDocuments (/Users/roadhump/Projects/xx/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1538:5)
    at load (/Users/roadhump/Projects/xx/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1555:19)
    at Object.safeLoad (/Users/roadhump/Projects/xx/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1573:10)

```

**Comment by nzakas** [comment]
@roadhump what are you reporting now? It looks like you're not seeing `undefined` anymore.

**Comment by roadhump** [comment]
@nzakas Yes, I agree, it seems my bug is closed, I should create separate for my comment.
