### ISSUE TITLE
eslint installed globally and SublimLinter + SublimeLinter-Eslint but wont work

### ISSUE THREAD

**Issue by AlexKvazos** [eslint/eslint#2482]
I am getting this stack trace in the console

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 256, in on_post_save
    callback.on_post_save(v)
  File "/Users/alexkvazos/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 445, in on_post_save
    self.file_was_saved(view)
  File "/Users/alexkvazos/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 449, in file_was_saved
    syntax_changed = self.check_syntax(view)
  File "/Users/alexkvazos/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 209, in check_syntax
    Linter.assign(view, reset=True)
  File "/Users/alexkvazos/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 724, in assign
    if not linter_class.disabled and linter_class.can_lint(syntax):
  File "./functools.py", line 251, in wrapper
  File "/Users/alexkvazos/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1582, in can_lint
    status = 'WARNING: {} deactivated, cannot locate \'{}\''.format(cls.name, executable)
UnboundLocalError: local variable 'executable' referenced before assignment
Assigning js to syntax Packages/JavaScriptNext - ES6 Syntax/JavaScriptNext.tmLanguage
reloading Packages/User/JavaScriptNext.sublime-settings
```

**Comment by ilyavolodin** [comment]
That looks like a stacktrace from SublimeLinter. We do not support IDE integrations, you are probably better off filing an issue here: https://github.com/roadhump/SublimeLinter-eslint

**Comment by AlexKvazos** [comment]
Yeah sorry guys, it was because I didn't setup eslint correctly with nvm + zsh. I was loading it in zshrc instead of zprofile.
