### ISSUE TITLE
Unknown node type ExportDeclaration on ES6 files

### ISSUE THREAD

**Issue by otakustay** [eslint/eslint#2492]
It may be a bug of [estraverse](https://github.com/estools/estraverse) but I did not find any issue there:

```bash
~/Dev/emc(branch:1.0/feature/es6*) » eslint -v                                                                                   
v0.11.0-alpha.0
------------------------------------------------------------
~/Dev/emc(branch:1.0/feature/es6*) » cat test.js                                                                                 
var a = 3;
export default a;
------------------------------------------------------------
~/Dev/emc(branch:1.0/feature/es6*) » cat .eslintrc                                                                               
{
    "settings": {
        "ecmascript": 6
    },
    "rules": {
        "strict": false,
        "quotes": [2, "single"]
    },
    "globals": {
        "Symbol": true
    }
}
------------------------------------------------------------
~/Dev/emc(branch:1.0/feature/es6*) » eslint test.js -c .eslintrc                                                                 
/usr/local/lib/node_modules/eslint/node_modules/escope/node_modules/estraverse/estraverse.js:511
                        throw new Error('Unknown node type ' + nodeType + '.')
                              ^
Error: Unknown node type ExportDeclaration.
    at Controller.traverse (/usr/local/lib/node_modules/eslint/node_modules/escope/node_modules/estraverse/estraverse.js:511:31)
    at Object.traverse (/usr/local/lib/node_modules/eslint/node_modules/escope/node_modules/estraverse/estraverse.js:703:27)
    at Object.analyze (/usr/local/lib/node_modules/eslint/node_modules/escope/escope.js:855:20)
    at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/eslint/lib/eslint.js:601:36)
    at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:134:27)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:230:26
    at walk (/usr/local/lib/node_modules/eslint/lib/util/traverse.js:81:9)
    at /usr/local/lib/node_modules/eslint/lib/util/traverse.js:102:9
    at Array.forEach (native)
    at traverse (/usr/local/lib/node_modules/eslint/lib/util/traverse.js:101:11)
```

**Comment by gyandeeps** [comment]
Your settings block inside your `.eslintrc` file is wrong.

It should say:

```js
{
     "ecmaFeatures": {
        "modules": true
    }
}
```

Here is docs for configuring eslint: http://eslint.org/docs/user-guide/configuring

**Comment by otakustay** [comment]
Thanks, it seems my knowledge from [the blog](http://eslint.org/blog/2014/11/es6-jsx-support/) is deprecated, my fault not reading document carefully
