### ISSUE TITLE
Cannot read property 'ecmaFeatures' of undefined

### ISSUE THREAD

**Issue by adriano-di-giovanni** [eslint/eslint#2554]
SublimeLinter eslint plugin by @roadhump issues this command

```
eslint --format compact --stdin --stdin-filename __RELATIVE_TO_FOLDER
```

and I can read this error in Sublime Text's console. I tried to run the same command from terminal and I get the same error.

Eslint version is 0.21.1. Same behavior down to 0.20.0

```
Cannot read property 'ecmaFeatures' of undefined
TypeError: Cannot read property 'ecmaFeatures' of undefined
    at /Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/eslint.js:369:53
    at Array.forEach (native)
    at prepareConfig (/Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/eslint.js:368:33)
    at EventEmitter.module.exports.api.verify (/Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/eslint.js:602:18)
    at processText (/Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/cli-engine.js:231:23)
    at CLIEngine.executeOnText (/Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/cli-engine.js:371:26)
    at Object.cli.execute (/Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/cli.js:178:36)
    at configInit.initializeConfig.exitCode (/Users/me/.nvm/v0.10.35/lib/node_modules/eslint/bin/eslint.js:13:28)
    at ConcatStream.<anonymous> (/Users/me/.nvm/v0.10.35/lib/node_modules/eslint/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:117:20)
```

**Comment by ilyavolodin** [comment]
Can you paste your `.eslintrc` file here please? Also, could you try running eslint on the same file from the command line and without --stdin? Just `eslint filename` and see if the same error occurs.

**Comment by adriano-di-giovanni** [comment]
I tried running just `eslint filename`:

```
/Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/eslint.js:369
            if (config.env[env] && environments[env].ecmaFeatures) {
                                                    ^
TypeError: Cannot read property 'ecmaFeatures' of undefined
    at /Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/eslint.js:369:53
    at Array.forEach (native)
    at prepareConfig (/Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/eslint.js:368:33)
    at EventEmitter.module.exports.api.verify (/Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/eslint.js:602:18)
    at processFile (/Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/cli-engine.js:197:27)
    at /Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/cli-engine.js:332:26
    at walk (/Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/util/traverse.js:81:9)
    at /Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/util/traverse.js:102:9
    at Array.forEach (native)
    at traverse (/Users/me/.nvm/v0.10.35/lib/node_modules/eslint/lib/util/traverse.js:101:11)
```

Please, find my `.eslintrc` below

```
{
    "env": {
        "node": true,
        "mocha": true,
        "chai": true
    },
    "rules": {

        // possible errors
        "no-empty": 2,

        // best practices
        "default-case": 2,

        // strict mode
        "strict": [ 2, "global" ],

        // stylistic issues
        "no-underscore-dangle": true,
        "quotes": [ 2, "single" ],
        "spaced-line-comment": [ 2, "always" ],
        "space-unary-ops": 0,
        "space-infix-ops": 0
    }
}
```

Thanks in advance,
Adriano

**Comment by gyandeeps** [comment]
Looks like you set `chai` environment in your `.eslintrc` file.
We don't have builtins for `chai`.

**Comment by adriano-di-giovanni** [comment]
Uh. Simple as that? Sorry for taking your time.

Inviato da iPhone
