### ISSUE TITLE
Crash on file ending in switch statement without close

### ISSUE THREAD

**Issue by DelvarWorld** [eslint/eslint#2619]
crash.js:

    hello = call( function( payload ) {

        switch( payload ) {

            case 'case':
                break;

This file will make eslint die forever

    $ eslint crash.js
    FATAL ERROR: JS Allocation failed - process out of memory
    Abort trap: 6

**Comment by gyandeeps** [comment]
Can you share more stack trace for this error?
or this is it?

**Comment by hzoo** [comment]
Providing the ESLint version and config might be helpful too?

**Comment by ilyavolodin** [comment]
It looks like online demo is crashing on this code as well, and taking browser with it.

**Comment by xjamundx** [comment]
That's exceptionally cool

**Comment by xjamundx** [comment]
FYI espree handles this fine:
```
> require('espree').parse("hello = call( function( payload ) {  switch( payload ) {  case 'case':  break;")
Error: Line 1: Unexpected end of input
    at throwError (/Users/jamuferguson/dev/eslint/node_modules/espree/espree.js:2069:17)
    at throwUnexpected (/Users/jamuferguson/dev/eslint/node_modules/espree/espree.js:2102:9)
    at expect (/Users/jamuferguson/dev/eslint/node_modules/espree/espree.js:2141:9)
    at parseSwitchStatement (/Users/jamuferguson/dev/eslint/node_modules/espree/espree.js:4111:5)
    at parseStatement (/Users/jamuferguson/dev/eslint/node_modules/espree/espree.js:4263:44)
    at parseSourceElement (/Users/jamuferguson/dev/eslint/node_modules/espree/espree.js:5116:24)
    at parseFunctionSourceElements (/Users/jamuferguson/dev/eslint/node_modules/espree/espree.js:4360:25)
    at parseFunctionExpression (/Users/jamuferguson/dev/eslint/node_modules/espree/espree.js:4608:12)
    at parsePrimaryExpression (/Users/jamuferguson/dev/eslint/node_modules/espree/espree.js:2849:20)
    at parseLeftHandSideExpressionAllowCall (/Users/jamuferguson/dev/eslint/node_modules/espree/espree.js:2974:57)
```

But if I put the same code in `test.js` and run eslint, it appears to hang.
```js
hello = call( function( payload ) {  switch( payload ) {  case 'case':  break;
```

**Comment by ilyavolodin** [comment]
Must be one of the rules.

**Comment by gcochard** [comment]
I get `1:79 - Unexpected end of input` in the online demo. No crash.

**Comment by ilyavolodin** [comment]
If you add an extra line break at the end, it crashes chrome for me. Just copy & paste didn't do it for me either.

**Comment by btmills** [comment]
Looks like the newline at the end is important. Adding it to @xjamundx's example will crash espree:

```sh
$ node
> require('espree').parse("hello = call( function( payload ) {  switch( payload ) {  case 'case':  break;\n")
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
[1]    63533 abort      node
```

**Comment by xjamundx** [comment]
Will file this for espree and we can close here...

**Comment by xjamundx** [comment]
https://github.com/eslint/espree/issues/146
