### ISSUE TITLE
Property 'propertyIsEnumerable' of object object is not a function

### ISSUE THREAD

**Issue by pnuzhdin** [eslint/eslint#2688]
Using fresh installed eslint 0.21.2 which install object_assign 2.1.0:

myproject/node_modules/eslint/node_modules/object-assign/index.js:19
		return obj.propertyIsEnumerable(key);
		           ^
TypeError: Property 'propertyIsEnumerable' of object object is not a function
    at myproject/node_modules/eslint/node_modules/object-assign/index.js:19:14
    at Array.filter (native)
    at ownEnumerableKeys (myproject/node_modules/eslint/node_modules/object-assign/index.js:18:14)
    at module.exports (myproject/node_modules/eslint/node_modules/object-assign/index.js:30:10)
    at addDeclaredGlobals (myproject/node_modules/eslint/lib/eslint.js:139:5)
    at EventEmitter.module.exports.api.verify (myproject/node_modules/eslint/lib/eslint.js:702:13)
    at processFile (myproject/node_modules/eslint/lib/cli-engine.js:197:27)
    at myproject/node_modules/eslint/lib/cli-engine.js:332:26
    at myproject/node_modules/eslint/lib/util/traverse.js:61:17
    at Array.forEach (native)

**Comment by ubenzer** [comment]
This started happening ~10 mins ago. One of dependencies' interface might have been changed.

**Comment by lukewaite** [comment]
Yes - it comes from the most recent release of object-assign https://github.com/sindresorhus/object-assign/releases/tag/2.1.0 which was released sometime around 9AM EST.

There's a ticket open for it at https://github.com/sindresorhus/object-assign/issues/15 and the @sindresorhus has pulled version 2.1.0 from npm's registry.

**Comment by pnuzhdin** [comment]
Why you guys using ^ for the component versions? That's make your components potentially unstable

**Comment by sindresorhus** [comment]
This was fixed right away. Can be closed.

**Comment by ilyavolodin** [comment]
Closing. Using ^ dependency versions is intentional.
