### ISSUE TITLE
Config validator reports incorrect config path

### ISSUE THREAD

**Issue by ownagedj** [eslint/eslint#2768]
No matter if I set the rule or I use the default options. Both results in the stack trace below
## Stack trace 
```js
awesomemodule/node_modules/eslint/lib/config-validator.js:88
        throw new Error(message.join(""));
              ^
Error: awesomemodule/.eslintrc:
        Configuration for rule "dot-notation" is invalid:
        Value "allowKeywords" is the wrong type.

    at validateRuleOptions (awesomemodule/node_modules/eslint/lib/config-validator.js
:88:15)
    at awesomemodule/node_modules/eslint/lib/config-validator.js:101:13
    at Array.forEach (native)
    at Object.validate (awesomemodule/node_modules/eslint/lib/config-validator.js:100
:35)
    at loadConfig (awesomemodule/node_modules/eslint/lib/config.js:99:19)
    at getLocalConfig (awesomemodule/node_modules/eslint/lib/config.js:225:23)
    at Config.getConfig (awesomemodule/node_modules/eslint/lib/config.js:363:22)
    at processText (awesomemodule/node_modules/eslint/lib/cli-engine.js:183:27)
    at processFile (awesomemodule/node_modules/eslint/lib/cli-engine.js:226:12)
    at awesomemodule/node_modules/eslint/lib/cli-engine.js:322:26
```

## My rules
```js

{
  "rules": {
    "no-cond-assign": 2,
    "no-delete-var": 2,
    "no-dupe-args": 2,
    "no-dupe-keys": 2,
    "no-duplicate-case": 2,
    "no-empty": 1,
    "no-empty-class": 2,
    "no-extra-bind": 2,
    "no-extra-semi": 2,
    "no-extra-parens": 1,
    "no-fallthrough": 2,
    "no-func-assign": 2,
    "no-invalid-regexp": 2,
    "no-irregular-whitespace": 2,
    "no-multi-spaces": 2,
    "no-new-func": 2,
    "no-new-object": 2,
    "no-process-exit": 2,
    "no-redeclare": 2,
    "no-shadow": 1,
    "no-spaced-func": 2,
    "no-trailing-spaces": 2,
    "no-undef": 2,
    "no-unused-vars": [1, {"vars": "local", "args": "after-used"}],
    "no-underscore-dangle": 0,
    "no-use-before-define": [2, "nofunc"],
    "brace-style": [2, "1tbs", { "allowSingleLine": true }],
    "camelcase": 0,
    "comma-spacing": [2, {"before": false, "after": true}],
    "comma-dangle": [2, "never"],
    "consistent-return": 0,
    "consistent-this": [2, "self"],
    "curly": [2, "all"],
    "dot-notation": [2, {"allowKeywords": true, "allowPattern": ""}],
    "eol-last": 2,
    "eqeqeq": [2, "smart"],
    "indent": [2, 2],
    "key-spacing": [2, {"beforeColon": false, "afterColon": true}],
    "new-parens": 2,
    "operator-linebreak": [2, "after"],
    "quotes": [2, "single"],
    "semi": [2, "always"],
    "space-after-keywords": [2, "always"],
    "space-before-blocks": [2, "always"],
    "space-before-function-parentheses": [2, "never"],
    "space-in-brackets": [2, "never"],
    "space-infix-ops": 2,
    "space-unary-ops": [2, {"words": true, "nonwords": false}],
    "space-return-throw-case": 2,
    "spaced-line-comment": [2, "always"],
    "strict": [2, "global"],
    "valid-typeof": 2,
    "yoda": [2, "never"],
    "valid-jsdoc": [1, {
      "requireReturn": false,
      "requireReturnDescription": false,
      "prefer": {
        "returns": "return"
      }
    }]
  },
  "env": {
    "node": true
  }
}
```

**Comment by btmills** [comment]
@ownagedj what are the contents of `awesomemodule/.eslintrc`? Using the configuration you posted above I can't reproduce the error.

**Comment by ownagedj** [comment]
Yes I use this configuration, as I am encountering the problem.

Maybe this helps?

`node` version `v0.10.38`
`eslint` version `0.23.0`

**Comment by sethen** [comment]
I am getting the same thing but for `comma-dangle` using `eslint 0.23.0`.  My rules were working fine in `0.21.0`.

**Comment by btmills** [comment]
@ownagedj I still can't reproduce this. To help debug, can you edit `node_modules/eslint/lib/config-validator.js` and insert `console.log(options);` at line 78 just inside the `if`, then let me know what the new output is?

**Comment by btmills** [comment]
@sethen Please file a separate issue for that so we can debug them separately.

**Comment by ownagedj** [comment]
`rules` itself are `ok`.
The problem is that eslint is looking for `.eslintrc` in the above folder and finds it.

e.g.

```bash
project/.eslintrc
project/awesomemodule/.eslintrc
```

I added a `console.log` to `eslint/config.js` at line `99` to see that the `filePath` is

and the output is

```bash
project/awesomemodule/.eslintrc
project/awesomemodule/package.json
project/.eslintrc
```

So it takes the outdated `.eslintrc` from `project/.eslint`

Also saw `eslint` looking up the whole file tree. I am not sure if that is supposed to be

**Comment by btmills** [comment]
If the directory traversal is the issue, can this be closed in favor of #2736?

**Comment by gyandeeps** [comment]
@ownagedj The config lookup is being discussed here. https://github.com/eslint/eslint/issues/2736

**Comment by ownagedj** [comment]
Yes. Thanks for the fast help :+1:

**Comment by btmills** [comment]
Closing in favor of discussion in #2736.

**Comment by nzakas** [comment]
@btmills doesn't this mean the validator is outputting the wrong config filename in the error message? Isn't this a bug?

**Comment by btmills** [comment]
Possibly - I'm not sure from this conversation which file the error was in. @ownagedj can you paste the contents of both `project/.eslintrc` and `project/awesomemodule/.eslintrc`?

**Comment by ownagedj** [comment]
Here are the files. As you can see the `project/.eslintrc` has the old rule format, causing the error.

`project/awesomemodule/.eslintrc`
```js
{
  "rules": {
    "no-cond-assign": 2,
    "no-delete-var": 2,
    "no-dupe-args": 2,
    "no-dupe-keys": 2,
    "no-duplicate-case": 2,
    "no-empty": 1,
    "no-empty-class": 2,
    "no-extra-bind": 2,
    "no-extra-semi": 2,
    "no-extra-parens": 1,
    "no-fallthrough": 2,
    "no-func-assign": 2,
    "no-invalid-regexp": 2,
    "no-irregular-whitespace": 2,
    "no-multi-spaces": 2,
    "no-new-func": 2,
    "no-new-object": 2,
    "no-process-exit": 2,
    "no-redeclare": 2,
    "no-shadow": 1,
    "no-spaced-func": 2,
    "no-trailing-spaces": 2,
    "no-undef": 2,
    "no-unused-vars": [1, {"vars": "local", "args": "after-used"}],
    "no-underscore-dangle": 0,
    "no-use-before-define": [2, "nofunc"],
    "brace-style": [2, "1tbs", { "allowSingleLine": true }],
    "camelcase": 0,
    "comma-spacing": [2, {"before": false, "after": true}],
    "comma-dangle": [2, "never"],
    "consistent-return": 0,
    "consistent-this": [2, "self"],
    "curly": [2, "all"],
    "dot-notation": [2, {"allowKeywords": true, "allowPattern": ""}],
    "eol-last": 2,
    "eqeqeq": [2, "smart"],
    "indent": [2, 2],
    "key-spacing": [2, {"beforeColon": false, "afterColon": true}],
    "new-parens": 2,
    "operator-linebreak": [2, "after"],
    "quotes": [2, "single"],
    "semi": [2, "always"],
    "space-after-keywords": [2, "always"],
    "space-before-blocks": [2, "always"],
    "space-before-function-parentheses": [2, "never"],
    "space-in-brackets": [2, "never"],
    "space-infix-ops": 2,
    "space-unary-ops": [2, {"words": true, "nonwords": false}],
    "space-return-throw-case": 2,
    "spaced-line-comment": [2, "always"],
    "strict": [2, "global"],
    "valid-typeof": 2,
    "yoda": [2, "never"],
    "valid-jsdoc": [1, {
      "requireReturn": false,
      "requireReturnDescription": false,
      "prefer": {
        "returns": "return"
      }
    }]
  },
  "env": {
    "node": true
  }
}
```

`project/.eslintrc`
```js
{
  "rules": {
    "no-cond-assign": 2,
    "no-delete-var": 2,
    "no-dupe-args": 2,
    "no-dupe-keys": 2,
    "no-duplicate-case": 2,
    "no-empty": 1,
    "no-empty-class": 2,
    "no-extra-bind": 2,
    "no-extra-semi": 2,
    "no-extra-parens": 1,
    "no-fallthrough": 2,
    "no-func-assign": 2,
    "no-invalid-regexp": 2,
    "no-irregular-whitespace": 2,
    "no-multi-spaces": 2,
    "no-new-func": 2,
    "no-new-object": 2,
    "no-process-exit": 2,
    "no-redeclare": 2,
    "no-shadow": 1,
    "no-spaced-func": 2,
    "no-trailing-spaces": 2,
    "no-undef": 2,
    "no-unused-vars": [1, {"vars": "local", "args": "after-used"}],
    "no-underscore-dangle": 0,
    "no-use-before-define": [2, "nofunc"],
    "brace-style": [2, "1tbs", { "allowSingleLine": true }],
    "camelcase": 0,
    "comma-spacing": [2, {"before": false, "after": true}],
    "comma-dangle": [2, "never"],
    "consistent-return": 0,
    "consistent-this": [2, "self"],
    "curly": [2, "all"],
    "dot-notation": [2, "allowKeywords"],
    "eol-last": 2,
    "eqeqeq": [2, "smart"],
    "indent": [2, 2],
    "key-spacing": [2, {"beforeColon": false, "afterColon": true}],
    "new-parens": 2,
    "operator-linebreak": [2, "after"],
    "quotes": [2, "single"],
    "semi": [2, "always"],
    "space-after-keywords": [2, "always"],
    "space-before-blocks": [2, "always"],
    "space-before-function-parentheses": [2, "never"],
    "space-in-brackets": [2, "never"],
    "space-infix-ops": 2,
    "space-unary-ops": [2, {"words": true, "nonwords": false}],
    "space-return-throw-case": 2,
    "spaced-line-comment": [2, "always"],
    "strict": [2, "global"],
    "valid-typeof": 2,
    "yoda": [2, "never"],
    "valid-jsdoc": [1, {
      "requireReturn": false,
      "requireReturnDescription": false,
      "prefer": {
        "returns": "return"
      }
    }]
  },
  "env": {
    "node": true
  }
}
```

**Comment by btmills** [comment]
Thanks @ownagedj, reopening.

**Comment by btmills** [comment]
@ownagedj I'm trying, but I can't reproduce this. I have two `.eslintrc`s, error in the upper one, and it's reporting the correct path. Any help on a repro?

**Comment by ownagedj** [comment]
The problem was that I had `eslint@0.19.0` installed with `sudo npm i eslint -g`
I removed it `eslint` globally and updated `.eslintrc`  to the latest supported and it worked like a charm.

**Comment by btmills** [comment]
Good to hear! Closing.
