### ISSUE TITLE
Error: EISDIR, illegal operation on a directory if directory called "package.json" exists

### ISSUE THREAD

**Issue by vladikoff** [eslint/eslint#2790]
## STR (OS X)

1. Install latest eslint command line
2. `cd ~`, `mkdir package.json`
3. go to some JavaScript and run `eslint .`

## Actual
```
➜  electron-hello-world git:(master) eslint .

/usr/local/lib/node_modules/eslint/lib/config.js:76
                throw e;
                      ^
Error: Cannot read config file: /Users/vladikoff/package.json
Error: EISDIR, illegal operation on a directory
    at Object.fs.readSync (fs.js:488:19)
    at Object.fs.readFileSync (fs.js:322:28)
    at loadConfig (/usr/local/lib/node_modules/eslint/lib/config.js:72:57)
    at getLocalConfig (/usr/local/lib/node_modules/eslint/lib/config.js:209:23)
    at Config.getConfig (/usr/local/lib/node_modules/eslint/lib/config.js:351:22)
    at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:178:27)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:332:26
    at /usr/local/lib/node_modules/eslint/lib/util/traverse.js:61:17
    at Array.forEach (native)
    at traverse (/usr/local/lib/node_modules/eslint/lib/util/traverse.js:41:54)
```

## Expected

Should lint the project

**Comment by nzakas** [comment]
Do you have a syntax error in your package.json file?

**Comment by vladikoff** [comment]
Hey, thanks for the response. No there are no errors in the package.json FILE.
Keep in mind that I am using `mkdir package.json`. I am creating a DIRECTORY called `package.json` in my $HOME directory. If you are having trouble reproducing this let me know because it should be easily reproducible.

**Comment by nzakas** [comment]
Ooh I see, so I guess we need to ensure package.json is a file before reading it.
