### ISSUE TITLE
Cannot find module './dist/rx'

### ISSUE THREAD

**Issue by carlosvillu** [eslint/eslint#2798]
I have an recurrent error when I try to run eslint from a NPM task.

Always I have this error:

```
Error: Cannot find module './dist/rx'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/carlos.villuendas/Developer/molecules/sui-card/node_modules/eslint/node_modules/inquirer/node_modules/rx/index.js:1:72)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```
I if I install again eslint in the project with `npm i eslint` the error will be fix.

My npm task is:

```
    "lint": "npm run lint:jscs && npm run lint:eslint && npm run lint:css",
    "lint:jscs": "cat ./{src,test}/**/*.{js,jsx} | jscs",
    "lint:eslint": "eslint --ext=\".js\" --ext=\".jsx\" src/",
    "lint:css": "node-sass src -o .tmp; rm .tmp/index.css; csslint .tmp",
    "postlint": "npm run clean:tmp",
```

My eslint versins are:

```
"eslint": "^0.23.0",
"eslint-plugin-react": "~2.5.0",
```

And the .eslintrc is:

```
{
  "parser": "babel-eslint",
	"env": {
		"browser": true,
		"node": true,
		"amd": true,
		"jasmine": true
	},
	"globals": {
		"jest": true,
    "pit": true,
		"__DEV__": true
	},
  "plugins": [
    "react"
  ],
	"ecmaFeatures": {
		"arrowFunctions": true,
		"blockBindings": true,
    "templateStrings": true,
    "generators": true,
    "classes": true,
    "modules": true,
		"forOf": true,
		"jsx": true,
    "objectLiteralComputedProperties": true
	},
	"rules": {
		"no-alert": 2,
		"no-array-constructor": 2,
		"no-caller": 2,
		"no-bitwise": 0,
		"no-catch-shadow": 2,
		"no-console": 2,
		"no-control-regex": 2,
		"no-debugger": 2,
		"no-div-regex": 2,
		"no-dupe-keys": 2,
		"no-else-return": 2,
		"no-empty": 2,
		"no-empty-class": 2,
		"no-eq-null": 2,
		"no-eval": 2,
		"no-ex-assign": 2,
		"no-func-assign": 0,
		"no-floating-decimal": 2,
		"no-implied-eval": 2,
		"no-with": 2,
		"no-fallthrough": 2,
		"no-unreachable": 2,
		"no-undef": 2,
		"no-undef-init": 2,
		"no-unused-expressions": 2,
		"no-octal": 2,
		"no-octal-escape": 2,
		"no-multi-str": 0,
		"no-new-wrappers": 2,
		"no-new-object": 2,
		"no-unused-vars": 1,
		"no-script-url": 2,
		"no-proto": 2,
		"no-redeclare": 2,
		"no-regex-spaces": 2,

		"break-style": 0,
		"block-scoped-var": 0,
		"camelcase": 2,
		"curly": 2,
		"dot-notation": 2,
		"eqeqeq": 2,
		"guard-for-in": 0,
		"max-depth": [0, 4],
		"new-cap": 2,
		"new-parens": 2,
		"quotes": [2, "single"],
		"quote-props": 0,
		"radix": 2,
		"strict": 0,
		"use-isnan": 2,
		"valid-typeof": 1,
		"wrap-iife": 2,
		"wrap-regex": 0,

    "react/display-name": 0,
    "react/jsx-quotes": [2, "single", "avoid-escape"],
    "react/jsx-no-undef": 1,
    "react/jsx-uses-react": 1,
    "react/jsx-uses-vars": 1,
    "react/no-did-mount-set-state": 1,
    "react/no-did-update-set-state": 1,
    "react/no-multi-comp": 1,
    "react/prop-types": 1,
    "react/react-in-jsx-scope": 1,
    "react/self-closing-comp": 1,
    "react/wrap-multilines": 1
	}
}
```

Can you help me ?!

**Comment by nzakas** [comment]
I'm not sure if this is an ESLint error or not. What happens if you just run "npm run eslint"? Please paste the complete console output into this issue.

**Comment by carlosvillu** [comment]
Hi,
Thx for your response. Like you ask me I launch the eslint in isolate mode:

`npm run lint:eslint`

and that is the complete output:

```
(master) λ npm run lint:eslint

> sui-autocompleted@0.0.0 lint:eslint /Users/carlos.villuendas/Developer/atoms/sui-autocompleted
> eslint --ext=".js" --ext=".jsx" src/

module.js:338
    throw err;
          ^
Error: Cannot find module './dist/rx'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/carlos.villuendas/Developer/atoms/sui-autocompleted/node_modules/eslint/node_modules/inquirer/node_modules/rx/index.js:1:72)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/carlos.villuendas/.nvm/versions/node/v0.12.4/bin/node" "/Users/carlos.villuendas/.nvm/versions/node/v0.12.4/bin/npm" "run" "lint:eslint"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! sui-autocompleted@0.0.0 lint:eslint: `eslint --ext=".js" --ext=".jsx" src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sui-autocompleted@0.0.0 lint:eslint script 'eslint --ext=".js" --ext=".jsx" src/'.
npm ERR! This is most likely a problem with the sui-autocompleted package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint --ext=".js" --ext=".jsx" src/
npm ERR! You can get their info via:
npm ERR!     npm owner ls sui-autocompleted
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/carlos.villuendas/Developer/atoms/sui-autocompleted/npm-debug.log
```

The point is that I run `npm i eslint` and later run the same command again `npm run lint:eslint`. All will work perfectly fine again.

```
(master) λ npm run lint:eslint

> sui-autocompleted@0.0.0 lint:eslint /Users/carlos.villuendas/Developer/atoms/sui-autocompleted
> eslint --ext=".js" --ext=".jsx" src/


src/storages/index.jsx
  1:8  warning  EventEmitter is defined but never used  no-unused-vars

src/sui-autocompleted/list-item.jsx
  12:28  warning  'handleSelect' is missing in props validation for ListItem  react/prop-types

✖ 2 problems (0 errors, 2 warnings)

```

**Comment by nzakas** [comment]
I think this has to do with your task setup, is it possible you are deleting files after linting?

**Comment by danderu** [comment]
Hi @nzakas ! I'm working with @carlosvillu 

Yo were absolutely right! We had this prebuild step in our package.json:
```
rimraf **/dist/*
```
This was causing eslint crash after an `npm install`. We've fixed it replacing the prebuild step with:
```
rimraf ./dist/*
```
Thanks! :+1:
