### ISSUE TITLE
Specifying File Extension

### ISSUE THREAD

**Issue by codeuniquely** [eslint/eslint#2816]
There are two sorts of files in React projects

    .js    - JavaScript libraries and various mixins, support classes and so on
    .jsx  - React Components.which contain JSX mark-up as well as JavaScript code.

Using the --ext option at the command line for file extensions seems not to allow this. 

in the module options.js says:
    "--ext [String]             Specify JavaScript file extensions. - default: .js"

and

    eslint --ext .jsx srcdir        only does the jsx files
    eslint  srcdir                       only does the js files

but

    eslint --ext .jsx .js srcdir    only does the jsx files   throws an error

fs.js:696
  return binding.stat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'F:\Projects\ReactUpload\.js'
    at Object.fs.statSync (fs.js:696:18)
    at walk (F:\Projects\ReactUpload\node_modules\eslint\lib\util\traverse.js:36:15)
    at F:\Projects\ReactUpload\node_modules\eslint\lib\util\traverse.js:102:9
    at Array.forEach (native)
    at traverse (F:\Projects\ReactUpload\node_modules\eslint\lib\util\traverse.js:101:11)
    at CLIEngine.executeOnFiles (F:\Projects\ReactUpload\node_modules\eslint\lib\cli-engine.js:313:9)
    at Object.cli.execute (F:\Projects\ReactUpload\node_modules\eslint\lib\cli.js:179:95)
    at Object.<anonymous> (F:\Projects\ReactUpload\node_modules\eslint\bin\eslint.js:32:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

and variants like
   
    eslint --ext .jsx, .js  srcdir
    eslint --ext [.jsx, .js]  srcdir
    eslint --ext ".jsx, .js"  srcdir
    eslint --ext:{ .jsx, .js } srcdir

either throw the same error, so error about it being an invalid option or  just don't work 

How do you actually get ESLint to run over a React Project in a single pass

**Comment by gyandeeps** [comment]
Have you tried this:

```sh
eslint --ext .jsx  --ext .js srcdir
```

**Comment by codeuniquely** [comment]
probably the one combination that I had not tried...
that works, 

You might want to add an example of this on the docs - as others way find it useful.

Thank you

**Comment by nzakas** [comment]
This is already in the docs: http://eslint.org/docs/user-guide/command-line-interface#ext
