### ISSUE TITLE
"indent" rule throws "TypeError: Cannot read property 'start' of undefined"

### ISSUE THREAD

**Issue by feross** [eslint/eslint#2999]
Using the code on `master` (as of https://github.com/eslint/eslint/commit/1c70834295b064021e6aa6698473375063bffbae), I get this crash with the `indent` rule enabled:

```
TypeError: Cannot read property 'start' of undefined
    at getNodeIndent (/Users/feross/pr/standard/node_modules/eslint/lib/rules/indent.js:72:51)
    at /Users/feross/pr/standard/node_modules/eslint/lib/rules/indent.js:102:30
    at Array.forEach (native)
    at checkNodesIndent (/Users/feross/pr/standard/node_modules/eslint/lib/rules/indent.js:101:15)
    at EventEmitter.blockIndentationCheck (/Users/feross/pr/standard/node_modules/eslint/lib/rules/indent.js:254:9)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (/Users/feross/pr/standard/node_modules/eslint/lib/eslint.js:783:25)
    at Controller.__execute (/Users/feross/pr/standard/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/feross/pr/standard/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/Users/feross/pr/standard/node_modules/eslint/lib/eslint.js:776:24)
```

You can trigger the error with the code:

```js
if (true) {
  // This is a comment
}
```

and the rule:

```
"indent": [2, 2]
```

**Comment by feross** [comment]
Found it.

You can trigger the error with the code:

```js
if (true) {
  // This is a comment
}
```

and the rule:

```
"indent": [2, 2]
```
