### ISSUE TITLE
Missing dependency when using npm v3

### ISSUE THREAD

**Issue by lo1tuma** [eslint/eslint#3026]
In #3022 the phantomjs dependency was removed, which still works with npm v2 because npm automatically installs missing peer dependencies. This behavior changed with npm v3, where peer dependencies won’t be automatically installed.

```
$ npm -v
3.1.1
$ npm install
npm WARN EPEERINVALID mocha-phantomjs@3.5.4 requires a peer of phantomjs@1.9.1 - 1.9.7-15 but none was installed.
```

So if you install the eslint dependencies with npm v3 `npm test` won’t work anymore:

```
$ npm test
module.js:334
    throw err;
          ^
Error: Cannot find module 'phantomjs'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/mschreck/workspace/eslint/node_modules/mocha-phantomjs/bin/mocha-phantomjs:140:17)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Function.Module.runMain (module.js:467:10)
npm ERR! Test failed.  See above for more details.
```

**Comment by gyandeeps** [comment]
I think to prepare for `npm` 3 each module has to take care of that. So basically we are covering for them. Shouldn't we report that as an issue on their repo.

**Comment by IanVS** [comment]
Essentially `mocha-phantomjs` is making it difficult for consuming projects by locking down their version of `phantomjs`.  But, as I understand it, it is still the responsibility of consuming projects to install a compatible version of the peer dependencies.

**Comment by lo1tuma** [comment]
@gyandeeps That’s not correct, see the following quote from the [npm v3 release notes](https://github.com/npm/npm/releases/tag/v3.0.0):
> [...] it's up to the consumer of the module (i.e. you) to ensure the peers get installed / are included in
