### ISSUE TITLE
Rules from shareable configs don’t override inherited rules config

### ISSUE THREAD

**Issue by lo1tuma** [eslint/eslint#3261]
I have two `.eslintrc` files, one in my project root and one in the folder `test/e2e`.

Each config files extends from a shareable config:
* `.eslintrc` extends `my-shareable-config/es2015` (this enables e.g. the `no-var` rule)
* `test/e2e/.eslintrc` extends `my-shareable-config` (this explicitly disables the `no-var` rule)

If I lint files in the `test/e2e` folder I still get errors from the `no-var` rule. I would expect no error because the shareable config explicitly disabled this rule.

Same problem exists for `env` and `ecmaFeatures`.

I use ESLint version 1.0.0.

**Comment by gyandeeps** [comment]
I am not able to reproduce the issue. I created the similar scenario as described by you.
Can you try running eslint with DEBUG and share the output.

**Comment by lo1tuma** [comment]
Interesting, if I run `./node_modules/.bin/eslint test/e2e` I get no error.

Here is the output with `DEBUG` enabled:

```
$ DEBUG=eslint:* ./node_modules/.bin/eslint test/
eslint:cli Running on files +0ms
eslint:cli-engine Processing test/a.js +8ms
eslint:cli-engine Linting test/a.js +2ms
eslint:config Constructing config for /Users/mat/workspace/my-project/test/a.js +0ms
eslint:config Using .eslintrc and package.json files +1ms
eslint:config Loading /Users/mat/workspace/my-project/test/.eslintrc +1ms
eslint:config Using /Users/mat/workspace/my-project/test/.eslintrc +18ms
eslint:config Loading /Users/mat/workspace/my-project/.eslintrc +0ms
eslint:config Using /Users/mat/workspace/my-project/.eslintrc +77ms
eslint:config Loading /Users/mat/workspace/my-project/package.json +0ms
eslint:config Merging command line environment settings +6ms
eslint:cli-engine Load plugin react +18ms
eslint:cli-engine Load plugin mocha +1ms
eslint:cli-engine Processing test/e2e/b.js +1ms
eslint:cli-engine Linting test/e2e/b.js +0ms
eslint:config Constructing config for /Users/mat/workspace/my-project/test/e2e/b.js +0ms
eslint:config Using .eslintrc and package.json files +0ms
eslint:config Loading /Users/mat/workspace/my-project/test/e2e/.eslintrc +0ms
eslint:config Using /Users/mat/workspace/my-project/test/e2e/.eslintrc +5ms
eslint:config Loading /Users/mat/workspace/my-project/test/.eslintrc +0ms
eslint:config Using /Users/mat/workspace/my-project/test/.eslintrc +0ms
eslint:config Loading /Users/mat/workspace/my-project/.eslintrc +1ms
eslint:config Using /Users/mat/workspace/my-project/.eslintrc +2ms
eslint:config Loading /Users/mat/workspace/my-project/package.json +1ms
eslint:config Merging command line environment settings +3ms

test/e2e/b.js
3:1  error  Unexpected var, use let or const instead  no-var

    ✖ 1 problem (1 error, 0 warnings)
```

Only the `test/e2e` folder (exits without error):

```
$ DEBUG=eslint:* ./node_modules/.bin/eslint test/e2e
eslint:cli Running on files +0ms
eslint:cli-engine Processing test/e2e/b.js +8ms
eslint:cli-engine Linting test/e2e/b.js +2ms
eslint:config Constructing config for /Users/mat/workspace/my-project/test/e2e/b.js +0ms
eslint:config Using .eslintrc and package.json files +0ms
eslint:config Loading /Users/mat/workspace/my-project/test/e2e/.eslintrc +2ms
eslint:config Using /Users/mat/workspace/my-project/test/e2e/.eslintrc +90ms
eslint:config Loading /Users/mat/workspace/my-project/test/.eslintrc +0ms
eslint:config Using /Users/mat/workspace/my-project/test/.eslintrc +2ms
eslint:config Loading /Users/mat/workspace/my-project/.eslintrc +1ms
eslint:config Using /Users/mat/workspace/my-project/.eslintrc +9ms
eslint:config Loading /Users/mat/workspace/my-project/package.json +1ms
eslint:config Merging command line environment settings +6ms
eslint:cli-engine Load plugin react +22ms
eslint:cli-engine Load plugin mocha +1ms
```

I have also tried to deep freeze the exported config of my shareable config, which works fine if I lint the `test` folder (still with the unexpected `no-var` error), but crashes for the `test/e2e` folder:

```
$ DEBUG=eslint:* ./node_modules/.bin/eslint test/e2e
eslint:cli Running on files +0ms
eslint:cli-engine Processing test/e2e/b.js +8ms
eslint:cli-engine Linting test/e2e/b.js +2ms
eslint:config Constructing config for /Users/mat/workspace/my-project/test/e2e/b.js +1ms
eslint:config Using .eslintrc and package.json files +0ms
eslint:config Loading /Users/mat/workspace/my-project/test/e2e/.eslintrc +1ms
eslint:config Using /Users/mat/workspace/my-project/test/e2e/.eslintrc +87ms
eslint:config Loading /Users/mat/workspace/my-project/test/.eslintrc +1ms
eslint:config Using /Users/mat/workspace/my-project/test/.eslintrc +1ms
eslint:config Loading /Users/mat/workspace/my-project/.eslintrc +1ms
/Users/mat/workspace/my-project/node_modules/eslint/lib/config.js:141
throw e;
^
TypeError: Cannot assign to read only property 'es6' of #<Object>
Referenced from: /Users/mat/workspace/my-project/.eslintrc
at Object.<anonymous> (/Users/mat/workspace/my-project/node_modules/my-shareable-config/es2015/es2015BaseConfig.js:6:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mat/workspace/my-project/node_modules/my-shareable-config/es2015/shared.js:3:14)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
```

**Comment by lo1tuma** [comment]
I figured it out, the problem was on my side.
My shareable config looks like this:

```
.
├── baseConfig.json
├── browser.js
├── es2015
│   ├── es2015BaseConfig.js
│   ├── index.js
│   └── shared.js
├── index.js
├── package.json
├── shared.js
```

Each config flavor requires `baseConfig.json` and modifies it a little bit, due to the require cache they are all mutating the same object. So if you use multiple config flavors in the same eslint run it will cause problems.
