### ISSUE TITLE
valid-jsdoc crash

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#3588]
Rule valid-jsdoc seems to crash on the following construct:
```js
/**
 * @param data [Array]
 * @return {null}
 */
var test = function (data) {
};
```

Expected output:
No error

Actual:
```sh
c:\Program Files\nodejs\node_modules\eslint\lib\rules\valid-jsdoc.js:123
                        } else if (tag.name.indexOf(".") === -1) {
                                            ^
TypeError: Cannot call method 'indexOf' of undefined
    at c:\Program Files\nodejs\node_modules\eslint\lib\rules\valid-jsdoc.js:123:45
    at Array.forEach (native)
    at EventEmitter.checkJSDoc (c:\Program Files\nodejs\node_modules\eslint\lib\rules\valid-jsdoc.js:106:24)
    at EventEmitter.emit (events.js:117:20)
    at Controller.controller.traverse.leave (c:\Program Files\nodejs\node_modules\eslint\lib\eslint.js:823:25)
    at Controller.__execute (c:\Program Files\nodejs\node_modules\eslint\node_modules\estraverse\estraverse.js:397:31)
    at Controller.traverse (c:\Program Files\nodejs\node_modules\eslint\node_modules\estraverse\estraverse.js:485:28)
    at EventEmitter.module.exports.api.verify (c:\Program Files\nodejs\node_modules\eslint\lib\eslint.js:808:24)
    at processText (c:\Program Files\nodejs\node_modules\eslint\lib\cli-engine.js:199:27)
    at processFile (c:\Program Files\nodejs\node_modules\eslint\lib\cli-engine.js:224:12)
```

ESLint version 1.3.1 reproducible in online demo.

Looks like argument named `data` is screwing things up. Might be an issue with doctrine, but the rule shouldn't crash in any case.

**Comment by gyandeeps** [comment]
Duplicate https://github.com/eslint/eslint/issues/2270 ?

**Comment by ilyavolodin** [comment]
Yes, looks like it. Original issue was using name "fields" I'm using "data" but in the end the result is the same. Closing in favor of #2270
