### ISSUE TITLE
no-unused-vars crashes on global comments

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#3714]
Found this issue with the latest code added 5 days and not released yet). The following code:
```js
/* global angular: true,
  $LocalProvider,
  $SomeOtherCrap
*/

var a = $LocalProvider;
```
will crash `no-unused-vars` with the following message:
```sh
c:\Users\Ilya\Documents\github\eslint\lib\rules\no-unused-vars.js:248
        var column = namePattern.exec(content).index;
                                              ^
TypeError: Cannot read property 'index' of null
    at getLocation (c:\Users\Ilya\Documents\github\eslint\lib\rules\no-unused-vars.js:248:47)
    at EventEmitter.Program:exit (c:\Users\Ilya\Documents\github\eslint\lib\rules\no-unused-vars.js:281:49)
    at EventEmitter.emit (events.js:117:20)
    at Controller.controller.traverse.leave (c:\Users\Ilya\Documents\github\eslint\lib\eslint.js:835:25)
    at Controller.__execute (c:\Users\Ilya\Documents\github\eslint\node_modules\estraverse\estraverse.js:397:31)
    at Controller.traverse (c:\Users\Ilya\Documents\github\eslint\node_modules\estraverse\estraverse.js:485:28)
    at EventEmitter.module.exports.api.verify (c:\Users\Ilya\Documents\github\eslint\lib\eslint.js:820:24)
    at processText (c:\Users\Ilya\Documents\github\eslint\lib\cli-engine.js:206:27)
    at processFile (c:\Users\Ilya\Documents\github\eslint\lib\cli-engine.js:231:12)
    at executeOnFile (c:\Users\Ilya\Documents\github\eslint\lib\cli-engine.js:499:23)
```

CC @mysticatea

**Comment by mysticatea** [comment]
Thank you for the report, I will invest and fix this.
