### ISSUE TITLE
eslint-config-eslint broken

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#4145]
Getting an error when I try to use it:

```
Error reading YAML file: ./default.yml
Error: Cannot read config file: ./default.yml
Error: ENOENT, no such file or directory 'c:\Users\Nicholas\projects\personal\es
pree\default.yml'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at c:\Users\Nicholas\projects\personal\espree\node_modules\eslint-config-esl
int\index.js:25:33
    at Object.<anonymous> (c:\Users\Nicholas\projects\personal\espree\node_modul
es\eslint-config-eslint\index.js:32:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by nzakas** [comment]
Working on this.
