### ISSUE TITLE
`array-bracket-spacing` sometimes fails on empty arrays

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint#4231]
`array-bracket-spacing` will fail if set to  `[ 2, "never", {"arraysInArrays": true } ]` or ` [ 2, "never", {"objectsInArrays": true } ]` for empty arrays:

```js
/*eslint array-bracket-spacing: [ 2, "never", {"arraysInArrays": true } ]*/

var foo = [];
```

Fails with:

```
/home/ian/Local_code/eslint/eslint/lib/rules/array-bracket-spacing.js:128
        return node.type === "ArrayExpression" || node.type === "ArrayPattern";
                   ^

TypeError: Cannot read property 'type' of undefined
    at isArrayType (/home/ian/Local_code/eslint/eslint/lib/rules/array-bracket-spacing.js:128:20)
    at EventEmitter.validateArraySpacing (/home/ian/Local_code/eslint/eslint/lib/rules/array-bracket-spacing.js:150:48)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/home/ian/Local_code/eslint/eslint/lib/util/node-event-generator.js:42:22)
    at CommentEventGenerator.enterNode (/home/ian/Local_code/eslint/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.controller.traverse.enter (/home/ian/Local_code/eslint/eslint/lib/eslint.js:782:36)
    at Controller.__execute (/home/ian/Local_code/eslint/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/home/ian/Local_code/eslint/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/home/ian/Local_code/eslint/eslint/lib/eslint.js:779:24)
```

I have a fix ready if this is accepted.

**Comment by alberto** [comment]
Confirmed

**Comment by nzakas** [comment]
@IanVS You can accept bugs your yourself
