### ISSUE TITLE
New config file plugin/extends resolution not working with node.js API and `configFile` option

### ISSUE THREAD

**Issue by feross** [eslint/eslint#5175]
The file resolution for the `plugin` and `extends` options works differently in eslint 2.0.0.

`standard` 6.0.0 is using `eslint` 2.0.0-rc.0 and the `configFile` option to the node.js API. [The code](https://github.com/feross/standard/blob/39a54d33f95ca564d976ea2cb97f4c3a45ed0c09/options.js) looks roughly like this:

```js
var CLIEngine = require("eslint").CLIEngine
var cli = new CLIEngine({ configFile: path.join(__dirname, 'rc', '.eslintrc') })
```

This `.eslintrc` file contains:

```json
{
  "extends": ["standard", "standard-jsx"]
}
```

The `eslint-config-standard` and `eslint-config-standard-jsx` packages are dependencies of the `standard` package, of course. 

The problem is that when users install `standard` as a dependency of their own project and run it, they get the following error:

```
Error: Cannot find module 'eslint-config-standard-jsx' from '/home/travis/build/matjaz/stdin2'
Referenced from: /home/travis/build/matjaz/stdin2/node_modules/standard/rc/.eslintrc
    at Function.module.exports [as sync] (/home/travis/build/matjaz/stdin2/node_modules/standard/node_modules/eslint/node_modules/resolve/lib/sync.js:33:11)
    at resolve (/home/travis/build/matjaz/stdin2/node_modules/standard/node_modules/eslint/lib/config/config-file.js:393:38)
    at load (/home/travis/build/matjaz/stdin2/node_modules/standard/node_modules/eslint/lib/config/config-file.js:412:24)
    at /home/travis/build/matjaz/stdin2/node_modules/standard/node_modules/eslint/lib/config/config-file.js:331:36
    at Array.reduceRight (native)
    at applyExtends (/home/travis/build/matjaz/stdin2/node_modules/standard/node_modules/eslint/lib/config/config-file.js:314:28)
    at Object.load (/home/travis/build/matjaz/stdin2/node_modules/standard/node_modules/eslint/lib/config/config-file.js:436:22)
    at loadConfig (/home/travis/build/matjaz/stdin2/node_modules/standard/node_modules/eslint/lib/config.js:67:33)
    at new Config (/home/travis/build/matjaz/stdin2/node_modules/standard/node_modules/eslint/lib/config.js:192:38)
    at CLIEngine.executeOnFiles (/home/travis/build/matjaz/stdin2/node_modules/standard/node_modules/eslint/lib/cli-engine.js:492:28)
```

It seems that the `process.cwd()` is being used as starting point for the search, instead of the config file's folder.

Perhaps the `relativeTo` argument is not being passed to the `resolve` function [in this code](https://github.com/eslint/eslint/blob/11435afd76278a1291566c92af985bf8fad0731f/lib/config/config-file.js#L389-L394)?

In any case, this affected `standard` [recently](https://github.com/feross/standard/issues/406) and required [this hack](https://github.com/feross/standard/compare/v6.0.1...v6.0.3) to workaround. Hoping we can figure out a real fix to this.

**Comment by gyandeeps** [comment]
Might be related to https://github.com/eslint/eslint/issues/5164

**Comment by feross** [comment]
Yeah, the bug probably crept in with that change, but I think this may be a separate issue.

**Comment by feross** [comment]
I noticed that `applyExtends()` is called [here](https://github.com/eslint/eslint/blob/1803f87bf4784e5103932e9bcd1e73e595d4e8ef/lib/config.js#L63) with a `filePath` that's an empty string.

But even if that's fixed, in `applyExtends()`, it still takes a code path where the `filePath` argument isn't taken into account during `resolve()`.

**Comment by nzakas** [comment]
Pretty sure this is just a symptom of #5164. I'll leave this open until I can confirm.

**Comment by alberto** [comment]
@feross can you check again now that #5164 is fixed?

**Comment by feross** [comment]
eslint 2.1.0 works better, and the example in the original issue works now. But it's not working correctly when `eslint` is hoisted to a higher level `node_modules` than the configs are at.

Here's an example. Passing this config into the `CLIEngine` constructor:

```json
{
  configFile: '/Users/feross/code/webtorrent/node_modules/standard/eslintrc.json'
}
```

Does not work when npm decides to install `eslint` at the top level.

```
├─┬ standard@6.0.6
│ ├── eslint-config-standard@5.1.0
│ ├── eslint-config-standard-jsx@1.1.1
│ ├── eslint-plugin-promise@1.0.8
│ ├── eslint-plugin-react@3.16.1
│ ├── eslint-plugin-standard@1.3.2
├─┬ eslint@2.1.0
│ ├─┬ chalk@1.1.1
      ...
```

Instead of using the config path (which is inside `node_modules/standard`) as the root, it's using `/Users/feross/code/webtorrent/node_modules` for some reason. Here's the error:

```
Error: Cannot find module 'eslint-config-standard-jsx' from '/Users/feross/code/webtorrent/node_modules'
Referenced from: /Users/feross/code/webtorrent/node_modules/standard/eslintrc.json
    at Function.module.exports [as sync] (/Users/feross/code/webtorrent/node_modules/eslint/node_modules/resolve/lib/sync.js:33:11)
    at resolve (/Users/feross/code/webtorrent/node_modules/eslint/lib/config/config-file.js:415:38)
    at load (/Users/feross/code/webtorrent/node_modules/eslint/lib/config/config-file.js:434:24)
    at /Users/feross/code/webtorrent/node_modules/eslint/lib/config/config-file.js:353:36
    at Array.reduceRight (native)
    at applyExtends (/Users/feross/code/webtorrent/node_modules/eslint/lib/config/config-file.js:336:28)
    at Object.load (/Users/feross/code/webtorrent/node_modules/eslint/lib/config/config-file.js:457:22)
    at loadConfig (/Users/feross/code/webtorrent/node_modules/eslint/lib/config.js:67:33)
    at new Config (/Users/feross/code/webtorrent/node_modules/eslint/lib/config.js:192:38)
    at CLIEngine.executeOnFiles (/Users/feross/code/webtorrent/node_modules/eslint/lib/cli-engine.js:492:28)
```

**Comment by nzakas** [comment]
I'll take a look

**Comment by nzakas** [comment]
Did this second case work in ESLint 1.x?

It looks like `eslint-config-standard-jsx` isn't in the lookup path from `eslint`. The call to `require()` is happening inside of `eslint`, so it starts looking up from `eslint/node_modules` and would miss `standard/node_modules` regardless of what I'm doing.

(Side note: It's amazing how much trouble npm 3 introduced with this feature. Just doesn't seem worth it.)

**Comment by nzakas** [comment]
@feross can you try this branch and see if your issue is resolved? https://github.com/eslint/eslint/pull/5712

**Comment by nzakas** [comment]
Ping @feross I'd really like your feedback on this before we merge. Can you please give the branch mentioned above a try?

**Comment by feross** [comment]
@nzakas Sorry for the delay. Yes, this works as expected now.

**Comment by sheerun** [comment]
This seems to happen again..
