### ISSUE TITLE
no-empty-function rule raises TypeError

### ISSUE THREAD

**Issue by randycoulman** [eslint/eslint#5227]
When I run ESLint 2.0 on this file:

```javascript
/*eslint no-empty-function: 2*/
/*eslint-env es6*/

import React from 'react'
import ReactDOM from 'react-dom'

document.addEventListener('DOMContentLoaded', () =>
  ReactDOM.render(
    <div />,
    document.getElementById('root')
  )
)
```

with this configuration file:

```json
{
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
        "jsx": true
    }
  }
}
```

I get the following error:

```sh
/usr/local/lib/node_modules/eslint/lib/rules/no-empty-function.js:118
            node.body.body.length === 0 &&
                          ^

TypeError: Cannot read property 'length' of undefined
    at EventEmitter.reportIfEmpty (/usr/local/lib/node_modules/eslint/lib/rules/no-empty-function.js:118:27)
    at emitOne (events.js:90:13)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (/usr/local/lib/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (/usr/local/lib/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:591:23)
    at CommentEventGenerator.enterNode (/usr/local/lib/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.controller.traverse.enter (/usr/local/lib/node_modules/eslint/lib/eslint.js:836:36)
    at Controller.__execute (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/eslint/lib/eslint.js:833:24)
```

I'm not sure where in the file it's failing.

**Comment by ilyavolodin** [comment]
Verified. @mysticatea could you take a look?

**Comment by mysticatea** [comment]
Oops, I'm really sorry! :astonished: :confounded:

**Comment by randycoulman** [comment]
Wow, thanks for the quick fix @mysticatea !  Thanks everyone for your work on this project.  I've been finding it very useful and valuable lately!
