### ISSUE TITLE
no-useless-constructor rule causing crash

### ISSUE THREAD

**Issue by jakepusateri** [eslint/eslint#5290]
The version of ESLint you are using.
```
$ node_modules/.bin/eslint -v
v2.0.0
```

Env and parserOptions 
```
    "env": {
        "browser": true,
        "node": true,
        "jasmine": true,
        "es6": true
    },
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true,
            "experimentalObjectRestSpread": true
        }
    },
```

What you did.
`"no-useless-constructor": 2`

What you expected to happen.
eslint not to crash.

What actually happened.
eslint crashed.

## Repro 1

```
import React from 'react';
var foo = 2;
class TestComponent extends React.Component {
    constructor() {
        super(foo);
    }
    render() {
        return <div/>;
    }
}
```
```
/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/rules/no-useless-constructor.js:30
            return (arg.type === "Identifier" && arg.name === ctorParams[index].name) ||
                                                                               ^

TypeError: Cannot read property 'name' of undefined
    at /Users/jacobp/z/static-mortgage/node_modules/eslint/lib/rules/no-useless-constructor.js:30:80
    at Array.every (native)
    at isRedundantSuperCall (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/rules/no-useless-constructor.js:30:45)
    at EventEmitter.checkForConstructor (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/rules/no-useless-constructor.js:53:46)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:591:23)
    at CommentEventGenerator.enterNode (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.controller.traverse.enter (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/eslint.js:836:36)

```

## Repro 2

```
import React from 'react';
class TestComponent extends React.Component {
    constructor() {
        super(...arguments);
    }
    render() {
        return <div/>;
    }
}
```
```
/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/rules/no-useless-constructor.js:33
                ctorParams[index].type === "RestElement" &&
                                 ^

TypeError: Cannot read property 'type' of undefined
    at /Users/jacobp/z/static-mortgage/node_modules/eslint/lib/rules/no-useless-constructor.js:33:34
    at Array.every (native)
    at isRedundantSuperCall (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/rules/no-useless-constructor.js:29:45)
    at EventEmitter.checkForConstructor (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/rules/no-useless-constructor.js:52:46)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:591:23)
    at CommentEventGenerator.enterNode (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.controller.traverse.enter (/Users/jacobp/z/static-mortgage/node_modules/eslint/lib/eslint.js:836:36)
```

**Comment by ilyavolodin** [comment]
That looks like a bug. We should crash on the rules. @mysticatea could you take a look please?

**Comment by BYK** [comment]
Able to repro, working on it.

**Comment by mysticatea** [comment]
Thanks @BYK , I could not take it for now.
