### ISSUE TITLE
Crash in `constructor-super`

### ISSUE THREAD

**Issue by yukidarake** [eslint/eslint#5319]
**The version of ESLint you are using (run eslint -v)**

```
$ ./node_modules/.bin/eslint -v
v2.1.0
```

**The source code that caused the problem**
```js
class Foo extends Object {
  constructor(method) {
    super();
    this.method = method || function() {};
  }
}
```

**The configuration you're using (for the rule or your entire config file)**
```yaml
env:
  es6: true
rules:
  constructor-super: 2
```

**The actual ESLint output complete with line numbers**
```
$ ./node_modules/.bin/eslint foo.js
/private/tmp/test/node_modules/eslint/lib/rules/constructor-super.js:69
        return segInfoMap[segment.id].calledInEveryPaths;
                                     ^

TypeError: Cannot read property 'calledInEveryPaths' of undefined
    at isCalledInEveryPath (/private/tmp/test/node_modules/eslint/lib/rules/constructor-super.js:69:38)
    at Array.every (native)
    at EventEmitter.onCodePathSegmentStart (/private/tmp/test/node_modules/eslint/lib/rules/constructor-super.js:156:56)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at forwardCurrentToHead (/private/tmp/test/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:176:34)
    at processCodePathToExit (/private/tmp/test/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:506:9)
    at CodePathAnalyzer.leaveNode (/private/tmp/test/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:9)
    at CommentEventGenerator.leaveNode (/private/tmp/test/node_modules/eslint/lib/util/comment-event-generator.js:111:23)
    at Controller.controller.traverse.leave (/private/tmp/test/node_modules/eslint/lib/eslint.js:839:36)
```

**Comment by BYK** [comment]
I was able to reproduce on latest master. Thanks for the great issue report @yukidarake!

**Comment by mysticatea** [comment]
Thank you for this report!
