### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by timseverien** [eslint/eslint#5324]
When running `--init` and choosing a popular style guide, any option seems to throw the following error:

```shell
Unexpected token }
SyntaxError: Unexpected token }
    at Object.parse (native)
    at check (/usr/local/lib/node_modules/eslint/lib/util/npm-util.js:75:25)
    at Object.checkDevDeps (/usr/local/lib/node_modules/eslint/lib/util/npm-util.js:114:12)
    at installModules (/usr/local/lib/node_modules/eslint/lib/config/config-initializer.js:77:29)
    at getConfigForStyleGuide (/usr/local/lib/node_modules/eslint/lib/config/config-initializer.js:263:5)
    at null.completed (/usr/local/lib/node_modules/eslint/lib/config/config-initializer.js:326:26)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/eslint/node_modules/inquirer/lib/ui/prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/eslint/node_modules/rx-lite/rx.lite.js:1550:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/eslint/node_modules/rx-lite/rx.lite.js:1489:14)
    at Subject.Rx.Subject.addProperties.onCompleted (/usr/local/lib/node_modules/eslint/node_modules/rx-lite/rx.lite.js:5871:19)
```

Node.js: 5.6.0
npm: 3.7.2
eslint: 2.1.0

**Comment by timseverien** [comment]
Following these exact steps on eslint 2.0.0 works fine.

**Comment by timseverien** [comment]
Turns the error is caused by a corrupted package.json. Sorry!
