### ISSUE TITLE
eslint can't find plugins in the node search path but outside eslint's parent directory

### ISSUE THREAD

**Issue by dsilva** [eslint/eslint#5468]
**What version of ESLint are you using?**
2.2.0

**What configuration and parser (Espree, Babel-ESLint, etc.) are you using?**
babel-eslint

**What did you do? Please include the actual source code causing the issue.**
.eslintrc:

```
{
  "parser": "babel-eslint",

  "env": {
    "node": true,
    "es6": true
  }
}
```

Take the built eslint npm artifacts and put them in one directory -- let's call that $eslint_parent.

Take the built babel-eslint npm artifacts and put them in another directory -- let's call that $babel_eslint_parent.

Create a symlink farm of node modules, call that $symlink_farm:

```
$symlink_farm
 |- eslint -> $eslint_parent/eslint
 |- babel-eslint -> $babel_eslint_parent/babel-eslint
 |- resolve -> ... # some other root
 |- ...  # other modules
```

Run this command:
```
export NODE_PATH=$symlink_farm
node $symlink_farm/eslint/bin/eslint.js  --no-ignore src/ 
```

**What did you expect to happen?**
No errors.

**What actually happened? Please include the actual, raw output from ESLint.**

```
Error: Cannot find module 'babel-eslint' from '$eslint_parent'
    at Function.module.exports [as sync] ($resolve_parent/resolve/lib/sync.js:33:11)
    at Object.load ($eslint_parent/eslint/lib/config/config-file.js:459:43)
    ...
```

Relevant part of eslint's config-file.js at https://github.com/eslint/eslint/blob/v2.2.0/lib/config/config-file.js#L451 

```
            config.parser = resolveModule.sync(config.parser, {
                basedir: getLookupPath(path.dirname(path.resolve(filePath)))
            });
```
and getLookupPath:

```
function getLookupPath(configFilePath) {

    // calculates the path of the project including ESLint as dependency
    var projectPath = path.resolve(__dirname, "../../../");
    if (configFilePath && pathIsInside(configFilePath, projectPath)) {
        // be careful of https://github.com/substack/node-resolve/issues/78
        return path.resolve(configFilePath);
    }

    // default to ESLint project path since it's unlikely that plugins will be
    // in this directory
    return projectPath;
}
```

The problem is that __dirname is the fully-resolved $eslint_parent/eslint/lib/config/config-file.js instead of $symlink_farm/eslint/lib/config/config-file.js.  So path.resolve(__dirname, "../../../") means $eslint_parent instead of $symlink_farm, and $eslint_parent/babel-eslint does not exist.

Rather than reimplementing node's module path lookup mechanism, using it directly would avoid the issue.  This change for example works for me:

```
config.parser = resolveParser(config.parser, filePath);
...
function resolveParser(parser, filePath) {
  try {
    return require.resolve(parser);
  } catch (e) {
    try {
      return require.resolve('eslint-plugin-', parser);
    } catch (e) {
      return resolveModule.sync(parser, {
          basedir: getLookupPath(path.dirname(path.resolve(filePath)))
      });
    }
  }
}
```

**Comment by nzakas** [comment]
Thanks, we can take a look. The goal of the current code was to avoid so many try-catch statements, so we will need to look at possible solutions.

**Comment by BYK** [comment]
Can this be related to https://github.com/nodejs/node/issues/3402? If so should we still try to find a workaround?

**Comment by nzakas** [comment]
Ooh, nice find. We should probably wait to see what the resolution of that is.

**Comment by dsilva** [comment]
It's related but I doubt that the meaning of __dirname will change anytime soon (if ever). Even if it does, it doesn't fix the case where you have multiple directories in the NODE_PATH environment variable.

**Comment by nzakas** [comment]
@dsilva your bug report was about symlinks. Can you confirm that there's also a problem without using them?

**Comment by dsilva** [comment]
Sorry, I should have mentioned originally that this also happens without symlinks.  Here's a minimal repro:

```
# set up initial project

mkdir repro && cd repro
npm init -y
npm install eslint@2.4.0 babel-eslint@5.0.0 babel-preset-es2015-node5@1.1.2 estraverse-fb@1.3.1
echo '{ "parser": "babel-eslint", "env": {"node": true, "es6": true}, "ecmaFeatures": {"modules": true, "blockBindings": true, "destructuring": true}, "rules":{"prefer-const": 2} }' > .eslintrc
echo '{ "presets": ["es2015-node5"], ignore: ["node_modules", "commonjs"] }' > .babelrc
echo -e "export let foo = (array) => {\n  let [a, b] = array\n  console.log(a, "a", b, "b")\n}" > test.js

# eslint runs normally and catches prefer-const violations:
node node_modules/eslint/bin/eslint.js test.js

mkdir commonjs
mv node_modules/babel-eslint/ commonjs/

# this should run normally, but fails with
#   Cannot find module 'babel-eslint' from '/private/tmp/repro/node_modules'
NODE_PATH=node_modules:commonjs node node_modules/eslint/bin/eslint.js test.js


# create a patch file

cat > config.patch <<'EOF'
--- node_modules/eslint/lib/config/config-file.js 2016-03-07 21:15:46.000000000 +0000
+++ config-file-patched.js 2016-03-14 10:18:18.000000000 +0000
@@ -450,7 +450,7 @@

         // include full path of parser if present
         if (config.parser) {
-            config.parser = resolveModule.sync(config.parser, {basedir: basedir});
+            config.parser = resolveParser(config.parser, filePath);
         }

         // validate the configuration before continuing
@@ -472,6 +472,20 @@
     return config;
 }

+function resolveParser(parser, filePath) {
+  try {
+    return require.resolve(parser);
+  } catch (e) {
+    try {
+      return require.resolve('eslint-plugin-', parser);
+    } catch (e) {
+      return resolveModule.sync(parser, {
+          basedir: getLookupPath(path.dirname(path.resolve(filePath)))
+      });
+    }
+  }
+}
+
 //------------------------------------------------------------------------------
 // Public Interface
 //------------------------------------------------------------------------------
EOF


# apply the patch
patch -p0 < config.patch

# now eslint should run and catch prefer-const violations again
NODE_PATH=node_modules:commonjs node node_modules/eslint/bin/eslint.js test.js
```

**Comment by nzakas** [comment]
@dsilva can you try this branch and see if it fixes your issue? https://github.com/eslint/eslint/pull/5712

**Comment by dsilva** [comment]
@nzakas I tried that branch but still run into the same issue:

```
> eslint --no-ignore src/ test-es6/

Could not find 'babel-eslint' relative to '/private/tmp/el/eslint/x/node_modules'.
Error: Could not find 'babel-eslint' relative to '/private/tmp/el/eslint/x/node_modules'.
    at Object.ModuleResolver.resolve (/private/tmp/el/eslint/x/package/lib/util/module-resolver.js:51:19)
    at Object.load (/private/tmp/el/eslint/x/package/lib/config/config-file.js:479:38)
    at loadConfig (/private/tmp/el/eslint/x/package/lib/config.js:67:33)
    at getLocalConfig (/private/tmp/el/eslint/x/package/lib/config.js:129:23)
    at Config.getConfig (/private/tmp/el/eslint/x/package/lib/config.js:230:22)
    at processText (/private/tmp/el/eslint/x/package/lib/cli-engine.js:149:27)
    at processFile (/private/tmp/el/eslint/x/package/lib/cli-engine.js:221:18)
    at executeOnFile (/private/tmp/el/eslint/x/package/lib/cli-engine.js:583:23)
    at /private/tmp/el/eslint/x/package/lib/cli-engine.js:620:13
    at Array.forEach (native)
```

**Comment by dsilva** [comment]
this is how I used your branch:

```
$ cd /tmp
$ mkdir el
$ cd el
$ git clone https://github.com/eslint/eslint.git
$ cd eslint/
$ git checkout issue5175
$ npm build && npm pack
$ mkdir x
$ cd x
$ tar zxf ../eslint-2.5.3.tgz
```

Then symlinked the resulting directory (/private/tmp/el/eslint/x/package/) as my eslint package directory in $NODE_PATH.

**Comment by nzakas** [comment]
Hmm OK, I'll keep digging

**Comment by dsilva** [comment]
Hi @nzakas, sorry for the delay -- your updated branch worked over here too.

**Comment by nzakas** [comment]
:+1: sweet, thanks for verifying! This will go out on Friday.
