### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by jrouleau** [eslint/eslint#5573]
This is not the same as #5426

**What version are you using?**
2.4.0

**What configuration are you using?**
Extends `eslint-config-rlabs` based on `eslint-config-airbnb`
```json
{
  "extends": "rlabs/es6",
}
```

**What did you do?**
***Error 1***
When there is an unused parameter in the contructor
```javascript
class Child extends Parent {
  constructor(test) {
    super()
  }
}
```
***Error 2***
When there is an undefined symbol in the constructor. Mostly noticeable with live linting while typing.
```javascript
class Child extends Parent {
  constructor() {
    gibberish
  }
}
```
**What happened?**
***Error 1***
```
TypeError: Cannot read property 'type' of undefined
    at isRedundantSuperCall (/REDACTED/node_modules/eslint/lib/rules/no-useless-constructor.js:59:25)
    at EventEmitter.checkForConstructor (/REDACTED/node_modules/eslint/lib/rules/no-useless-constructor.js:79:46)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/REDACTED/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (/REDACTED/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:591:23)
    at CommentEventGenerator.enterNode (/REDACTED/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.traverser.traverse.enter (/REDACTED/node_modules/eslint/lib/eslint.js:843:36)
    at Controller.__execute (/REDACTED/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/REDACTED/node_modules/estraverse/estraverse.js:501:28)
```

***Error 2***
```
TypeError: Cannot read property 'type' of undefined
    at isRedundantSuperCall (/REDACTED/node_modules/eslint/lib/rules/no-useless-constructor.js:24:38)
    at EventEmitter.checkForConstructor (/REDACTED/node_modules/eslint/lib/rules/no-useless-constructor.js:79:46)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/REDACTED/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (/REDACTED/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:591:23)
    at CommentEventGenerator.enterNode (/REDACTED/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.traverser.traverse.enter (/REDACTED/node_modules/eslint/lib/eslint.js:843:36)
    at Controller.__execute (/REDACTED/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/REDACTED/node_modules/estraverse/estraverse.js:501:28)
```

**What did you expect to happen?**
***Error 1***
Not crash.  Receive `no-unused-vars` on the unused paramater

***Error 2***
Not crash. Receive `no-undef` on the 'gibberish'

**Comment by ilyavolodin** [comment]
Thanks for the report. @mysticatea Could you take a quick look?

**Comment by mysticatea** [comment]
Thank you for this issue.
I can reproduce this.
