### ISSUE TITLE
Error: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by scott-stephen** [eslint/eslint#5605]
**What version of ESLint are you using?**
2.4.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
I've attached the source code to reproduce.
[eslintTest.zip](https://github.com/eslint/eslint/files/179001/eslintTest.zip)

**What did you do? Please include the actual source code causing the issue.**
Edited the constructor in the Tab.js file. Exception is thrown whenever the 'super()' function is missing.
 
**What did you expect to happen?**
Not have an exception thrown.

**What actually happened? Please include the actual, raw output from ESLint.**
```
$ ./node_modules/eslint/bin/eslint.js Tab.js

Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at isRedundantSuperCall (/Users/stephenpersonal/Downloads/eslintTest/node_modules/eslint/lib/rules/no-useless-constructor.js:24:38)
    at EventEmitter.checkForConstructor (/Users/stephenpersonal/Downloads/eslintTest/node_modules/eslint/lib/rules/no-useless-constructor.js:79:46)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (/Users/stephenpersonal/Downloads/eslintTest/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (/Users/stephenpersonal/Downloads/eslintTest/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:591:23)
    at CommentEventGenerator.enterNode (/Users/stephenpersonal/Downloads/eslintTest/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.traverser.traverse.enter (/Users/stephenpersonal/Downloads/eslintTest/node_modules/eslint/lib/eslint.js:843:36)
    at Controller.__execute (/Users/stephenpersonal/Downloads/eslintTest/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/stephenpersonal/Downloads/eslintTest/node_modules/estraverse/estraverse.js:501:28)

```

**Comment by mysticatea** [comment]
Thank you for this issue.

I guess this is duplicate of #5573.

**Comment by scott-stephen** [comment]
Yes, I guess I must of missed it in my search.
