### ISSUE TITLE
Error: Cannot find module 'estraverse-fb'

### ISSUE THREAD

**Issue by olalonde** [eslint/eslint#5615]
**What version of ESLint are you using?**

eslint 2.4.0

**What parser (default, Babel-ESLint, etc.) are you using?**

babel-eslint

I'm still getting the `Error: Cannot find module 'estraverse-fb'` error after installing 2.4.0.

```

> eslint src/

Error: Cannot find module 'estraverse-fb'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at monkeypatch (/node_modules/babel-eslint/index.js:59:32)
    at Object.exports.parse (/node_modules/babel-eslint/index.js:385:5)
    at parse (/node_modules/eslint/lib/eslint.js:577:27)
    at EventEmitter.module.exports.api.verify (/node_modules/eslint/lib/eslint.js:715:19)
    at processText (/node_modules/eslint/lib/cli-engine.js:187:27)
    at processFile (/node_modules/eslint/lib/cli-engine.js:227:18)
    at executeOnFile (/node_modules/eslint/lib/cli-engine.js:603:23)

$ ./node_modules/.bin/eslint --version
v2.4.0
```

**Comment by platinumazure** [comment]
As has been discussed in other issues before, this is resolved in ESLint but babel-eslint still needs to push an update.

What you can do:

1. If you're using `babel-eslint@5.x`, try `babel-eslint@6.x` (but be advised that this is still in beta).
1. If you're already using `babel-eslint@6.x`, please open an issue on the [babel-eslint issue list](https://github.com/babel/babel-eslint/issues/new).
