### ISSUE TITLE
ignore-path

### ISSUE THREAD

**Issue by MullinsN** [eslint/eslint#5636]
**What version are you using?**

**What did you do?**

**What happened?**

**What did you expect to happen?**

**Comment by MullinsN** [comment]
Version: v2.4.0

What did I do: Run **eslint server.js** from the CMD on Windows 10.

What happened: Had this error returned

**D:\Dropbox\Projects\myLibraryNodeV2>eslint server.js
undefined is not a function
TypeError: undefined is not a function
    at new IgnoredPaths (C:\Users\Dev\AppData\Roaming\npm\node_modules\eslint\lib\ignored-paths.js:152:17)
    at CLIEngine.executeOnFiles (C:\Users\Dev\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine.js:494:28)
    at Object.cli.execute (C:\Users\Dev\AppData\Roaming\npm\node_modules\eslint\lib\cli.js:179:95)
    at Object.<anonymous> (C:\Users\Dev\AppData\Roaming\npm\node_modules\eslint\bin\eslint.js:79:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
**
What did I expect to happen? An example of eslint to run.

Additional information. 

Running on Windows 10, using CMD.

When I ran eslint -v that worked, and returned v2.4.0. Ran eslint --init and that appears to hang.

**Comment by ilyavolodin** [comment]
I can't reproduce this using Windows 10 on my local machine. Everything is working fine for me in bash console and in CMD. Could you try uninstalling and reinstalling eslint? It looks like something might've not install correctly for you.

**Comment by MullinsN** [comment]
Ok. I will uninstall and try again. Thank you.

**Comment by MullinsN** [comment]
It appears that this machine had an old old version of NPM (1.3.2), so it appears once reinstalled Node, problem went away. Sorry for wasting your time.
