### ISSUE TITLE
eslint 2.4.0 complaining about missing dependency of estraverse-fb

### ISSUE THREAD

**Issue by alexmngn** [eslint/eslint#5638]
**What version of ESLint are you using?**
2.4.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**
```
{
  "parser": "babel-eslint",
  "ecmaFeatures": {
    "classes": true,
    "jsx": true
  },
  "plugins": [
    "react"
  ],

  "extends": "eslint-config-airbnb"
}
```

**What did you do? Please include the actual source code causing the issue.**
`$ eslint src/index.jsx`

**What actually happened? Please include the actual, raw output from ESLint.**
```
Error: Cannot find module 'estraverse-fb'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at monkeypatch (/usr/local/lib/node_modules/babel-eslint/index.js:59:32)
    at Object.exports.parse (/usr/local/lib/node_modules/babel-eslint/index.js:385:5)
    at parse (/usr/local/lib/node_modules/eslint/lib/eslint.js:577:27)
    at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/eslint/lib/eslint.js:715:19)
    at processText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:187:27)
    at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:227:18)
    at executeOnFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:603:23)
```

This is similar to #5476 but I'm using 2.4.0 which was supposed to fix the issue.
I also tried 2.2.0 and I got the same issue, maybe something else is wrong?

**Comment by kellyrmilligan** [comment]
++ same issue after reading the previous issue. 2.4.0 and babel-eslint 5.0.0

**Comment by ilyavolodin** [comment]
This issue has been fixed on our side. You need eslint v2.4.0 and babel-eslint 6.0.0-beta for a working setup. Please upgrade your babel-eslint.
Closing as fixed.
