### ISSUE TITLE
.eslintrc.js: Unexpected token on colon in config

### ISSUE THREAD

**Issue by brettdorrans** [eslint/eslint#5645]
**What version of ESLint are you using?**
v2.4.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
https://gist.github.com/brettdorrans/78781da5bb3a180b4293

**What did you do? Please include the actual source code causing the issue.**
When running eslint using this config (I've tried different config files too, same issue), it immediately errors, choking on the formatting of the config file.

**What did you expect to happen?**
eslint to run successfully.

**What actually happened? Please include the actual, raw output from ESLint.**
```
SyntaxError: /project/.eslintrc.js: Unexpected token (2:7)
  1 | {
> 2 |   "env": {
    |        ^
  3 |     "browser": true,
  4 |     "node": true,
  5 |     "es6": true,
    at Parser.pp.raise (project/node_modules/babylon/index.js:1378:13)
    at Parser.pp.unexpected (project/node_modules/babylon/index.js:2817:8)
    at Parser.pp.semicolon (project/node_modules/babylon/index.js:2804:38)
    at Parser.pp.parseExpressionStatement (project/node_modules/babylon/index.js:2178:8)
    at Parser.parseExpressionStatement (project/node_modules/babylon/index.js:3529:20)
    at Parser.pp.parseStatement (project/node_modules/babylon/index.js:1879:17)
    at Parser.parseStatement (project/node_modules/babylon/index.js:3507:22)
    at Parser.pp.parseBlockBody (project/node_modules/babylon/index.js:2208:21)
    at Parser.pp.parseBlock (project/node_modules/babylon/index.js:2189:8)
    at Parser.pp.parseStatement (project/node_modules/babylon/index.js:1838:19)
    at Parser.parseStatement (project/node_modules/babylon/index.js:3507:22)
    at Parser.pp.parseBlockBody (project/node_modules/babylon/index.js:2208:21)
    at Parser.pp.parseTopLevel (project/node_modules/babylon/index.js:1747:8)
    at Parser.parse (project/node_modules/babylon/index.js:1349:17)
    at Object.parse (project/node_modules/babylon/index.js:45:50)
    at File.parse (project/node_modules/babel-core/lib/transformation/file/index.js:479:24)
```

**Comment by ksmithut** [comment]
if you're using json, you should use `.eslintrc.json`

**Comment by brettdorrans** [comment]
Something weird is going on with my setup, closing this as I don't think it's related to eslint directly. Thanks for your help, ksmithut, that pointed me in the correct direction.
