### ISSUE TITLE
eslint fails with Error: Cannot find module 'object-assign' (missing dependency)

### ISSUE THREAD

**Issue by doug-wade** [eslint/eslint#5680]
**What version of ESLint are you using?**
2.5.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

```json
{
  "env": {
    "node": true,
    "es6": true
  },
  "ecmaFeatures": {
    "blockBindings": true,
    "arrowFunctions": true
  },
  "rules": {
    "array-bracket-spacing": [
      2,
      "never"
    ],
    "brace-style": [
      2,
      "1tbs"
    ],
    "consistent-return": 0,
    "indent": [
      2,
      2
    ],
    "no-multiple-empty-lines": [
      2,
      {
        "max": 2
      }
    ],
    "no-use-before-define": [
      2,
      "nofunc"
    ],
    "no-var": 0,
    "quote-props": [
      2,
      "as-needed"
    ],
    "quotes": [
      2,
      "single"
    ],
    "keyword-spacing": 2,
    "space-before-function-paren": [
      2,
      {
        "anonymous": "always",
        "named": "never"
      }
    ],
    "space-in-parens": [
      2,
      "never"
    ],
    "strict": [
      0,
      "global"
    ],
    "curly": [
      2,
      "all"
    ],
    "eol-last": 2,
    "key-spacing": [
      2,
      {
        "align": "colon"
      }
    ],
    "no-eval": 2,
    "no-with": 2,
    "space-infix-ops": 2,
    "dot-notation": [
      2,
      {
        "allowKeywords": true
      }
    ],
    "eqeqeq": 2,
    "no-alert": 2,
    "no-caller": 2,
    "no-extend-native": 2,
    "no-extra-bind": 2,
    "no-implied-eval": 2,
    "no-iterator": 2,
    "no-label-var": 2,
    "no-labels": 2,
    "no-lone-blocks": 2,
    "no-loop-func": 2,
    "no-multi-str": 2,
    "no-native-reassign": 2,
    "no-new": 2,
    "no-new-func": 2,
    "no-new-wrappers": 2,
    "no-octal-escape": 2,
    "no-proto": 2,
    "no-return-assign": 2,
    "no-script-url": 2,
    "no-sequences": 2,
    "no-unused-expressions": 2,
    "yoda": 2,
    "no-shadow": 2,
    "no-shadow-restricted-names": 2,
    "no-undef-init": 2,
    "camelcase": 2,
    "comma-spacing": 2,
    "new-cap": 2,
    "new-parens": 2,
    "no-array-constructor": 2,
    "no-extra-parens": 2,
    "no-new-object": 2,
    "no-spaced-func": 2,
    "no-trailing-spaces": 2,
    "semi": 2,
    "semi-spacing": [
      2,
      {
        "before": false,
        "after": true
      }
    ]
  }
}
```

**What did you do? Please include the actual source code causing the issue.**
npm install

**What did you expect to happen?**
a successful installation

**What actually happened? Please include the actual, raw output from ESLint.**

```
dougwade redfin.npm/rfnpm ‹dbw-bad-eslint-version› » rm -r node_modules
dougwade redfin.npm/rfnpm ‹dbw-bad-eslint-version› » npm install
|
> rfnpm@0.4.3 prepublish /Users/doug.wade/code/main/redfin.npm/rfnpm
> npm run lint


> rfnpm@0.4.3 lint /Users/doug.wade/code/main/redfin.npm/rfnpm
> eslint --no-eslintrc --config .eslintrc .

module.js:327
    throw err;
    ^

Error: Cannot find module 'object-assign'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/doug.wade/code/main/redfin.npm/rfnpm/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:32:14
    at Object.<anonymous> (/Users/doug.wade/code/main/redfin.npm/rfnpm/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:134:2)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "run" "lint"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! rfnpm@0.4.3 lint: `eslint --no-eslintrc --config .eslintrc .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rfnpm@0.4.3 lint script 'eslint --no-eslintrc --config .eslintrc .'.
npm ERR! This is most likely a problem with the rfnpm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint --no-eslintrc --config .eslintrc .
npm ERR! You can get their info via:
npm ERR!     npm owner ls rfnpm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/doug.wade/code/main/redfin.npm/rfnpm/npm-debug.log

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! rfnpm@0.4.3 prepublish: `npm run lint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rfnpm@0.4.3 prepublish script 'npm run lint'.
npm ERR! This is most likely a problem with the rfnpm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint
npm ERR! You can get their info via:
npm ERR!     npm owner ls rfnpm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/doug.wade/code/main/redfin.npm/rfnpm/npm-debug.log
```

**Comment by alberto** [comment]
@nzakas i saw you just commited bundling deps and it looks like it could be related. Can you have a look at it?

**Comment by tuckbick** [comment]
When running `npm ls`, in addition to `object-assign`, I am also seeing `UNMET DEPENDENCY through@^2.3.6` and `UNMET DEPENDENCY esprima@^2.6.0`

**Comment by ben-eb** [comment]
Yeah, I am also getting this -

https://github.com/postcss/postcss-selector-parser/pull/56 (https://travis-ci.org/postcss/postcss-selector-parser/builds/118560266)
https://github.com/ben-eb/postcss-discard-duplicates/pull/14 (https://travis-ci.org/ben-eb/postcss-discard-duplicates/builds/118559165)

**Comment by btmills** [comment]
Disclaimer: I've never used `bundledDependencies` before, so I'm debugging from zero knowledge.

![eslint](https://cloud.githubusercontent.com/assets/1709537/14053753/ee8c7e1e-f2a9-11e5-8b81-e3b190d9b34d.png)

That's on a machine with npm 3, and those are the three dependencies that we're getting errors about.

**Comment by btmills** [comment]
```sh
$ npm --version
3.3.12
$ ls node_modules
eslint esprima object-assign through
$ node_modules/.bin/eslint --init
// Works just fine
```

```sh
$ npm --version
2.7.4
$ ls node_modules
eslint
$ node_modules/.bin/eslint --init
// Throws the error above
```

Does this mean npm 3 deduping was masking the issue?

**Comment by ilyavolodin** [comment]
@btmills That would be my guess

**Comment by mourner** [comment]
From http://status.npmjs.org/:

> Identified - We have identified 74 packages (with 83 total publications) affected by the misconfiguration. We are diligently working to fix the metadata for the failed versions so that they can be republished by their authors. 

I expect `object-assign` to be among these packages. So it looks like an NPM issue that will be resolved soon.

**Comment by serkanyersen** [comment]
@mourner I was able to fix the issue by running `npm install object-assign`. Installing the package was fine.
It seems more like it was not included in the dependencies?

**Comment by mourner** [comment]
@serkanyersen ESLint doesn't use this package, it's a sub-dependency, which should be installed, but doesn't because of an NPM bug, I assume.

**Comment by nzakas** [comment]
We've confirmed that this is an issue only when using npm < 3 do to the deduping. It's likely that npm 3 deduping is masking a missed dependency in one of our dependencies.

**Comment by thefotios** [comment]
@mourner not sure if that's applicable. `eslint` and `object-assign` technically "install" fine. The npmjs.org bug was related to being able to fetch packages (I was hitting it before and getting a 404 for a supposedly published package).

This seems to be a packaging issue here in `eslint`

**Comment by ilyavolodin** [comment]
We identified the issue causing this bug and we are in the process of fixing it now. Point release incoming.

**Comment by nzakas** [comment]
We've identified the culprit as a bug in the release process. Basically, the release was done from an unclean environment. We're updating the release tool to ensure a clean environment before release.

**Comment by aivus** [comment]
@mourner 
>I expect object-assign to be among these packages.

No, `object-assign` not in this packages: https://gist.github.com/soldair/151e14e506c27c416ceb#file-versions-json

**Comment by nzakas** [comment]
We just pushed v2.5.1 which should allow people to start installing ESLint again. I had to do this manually due to lack of time/energy.

We're leaving this open so we can update our tools and integrate the fix permanently.

**Comment by nzakas** [comment]
There's a related problem in v2.5.1:

```
$ node_modules/.bin/eslint --init
Cannot find module 'through'
Error: Cannot find module 'through'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Nicholas\projects\personal\tmp\node_modules\eslint\node_modules\inquirer\lib\ui\bottom-bar.js:6:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by nzakas** [comment]
It looks like whatever weird hiccups npm was having yesterday have now been resolved. I did a quick test locally and things look better. Prepping a PR for the build step.
