### ISSUE TITLE
Cannot find module 'eslint-plugin-react' error in a no react project

### ISSUE THREAD

**Issue by Jokcy** [eslint/eslint#5721]
**What version of ESLint are you using?**
v2.5.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint(default runs into the same error)

**Please show your full configuration:**
```
{
  "parser": "babel-eslint",
  "plugins": [
      "html"
  ],
  "globals": {
    "AlipayJSBridge": true
  },
  "env": {
    "es6": true,
    "browser": true,
    "jasmine": true,
    "node": true
  },
  "rules": {
    "array-bracket-spacing": 0,
    "computed-property-spacing": [
      2,
      "never"
    ],
    "consistent-return": 2,
    "dot-notation": 0,
    "eol-last": 2,
    "eqeqeq": 2,
    "max-len": [
      2,
      120,
      4
    ],
    "new-cap": [
      2,
      {
        "capIsNew": false
      }
    ],
    "no-eq-null": 2,
    "no-mixed-spaces-and-tabs": 2,
    "no-multiple-empty-lines": [
      2,
      {
        "max": 2
      }
    ],
    "no-trailing-spaces": 2,
    "no-use-before-define": [
      2,
      "nofunc"
    ],
    "no-undef": 2,
    "no-underscore-dangle": 0,
    "no-unused-vars": 2,
    "no-var": 2,
    "object-curly-spacing": [
      2,
      "always"
    ],
    "quotes": [
      2,
      "single"
    ],
    "semi": [
      2,
      "never"
    ],
    // new version
     "keyword-spacing": [
       2,
       {"after": true, "before": true}
     ],
    "space-before-blocks": [
      2,
      "always"
    ],
    "no-warning-comments": [
      1,
      {
        "terms": [
          "todo",
          "fixme"
        ],
        "location": "anywhere"
      }
    ],
    "strict": 0,
    "vars-on-top": 2,
    "indent": [
      2,
      2,
      {
        "SwitchCase": 1
      }
    ]
  }
}

```

**What did you do? Please include the actual source code causing the issue.**
```
gulp.task('lint', function () {

  return gulp.src(['src/**/*'])
    .pipe(eslint())
    .pipe(eslint.format())
    .pipe(eslint.failAfterError())

})
```
or in webpack
```
preLoaders: [
      { test: /\.(js|vue)$/, loader: 'eslint-loader', exclude: /node_modules/ }
    ],
```

**What did you expect to happen?**
lint the src files

**What actually happened? Please include the actual, raw output from ESLint.**
Actually my project is not a react project. Maybe it has some relationship to react native?
```
Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.module.exports.load (/Users/Jokcy/workspace/personal/test/vue/node_modules/gulp-eslint/node_modules/eslint/lib/config/plugins.js:116:26)
    at Array.forEach (native)
    at Object.module.exports.loadAll (/Users/Jokcy/workspace/personal/test/vue/node_modules/gulp-eslint/node_modules/eslint/lib/config/plugins.js:138:21)
    at Object.load (/Users/Jokcy/workspace/personal/test/vue/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:470:21)
    at loadConfig (/Users/Jokcy/workspace/personal/test/vue/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:67:33)
    at getLocalConfig (/Users/Jokcy/workspace/personal/test/vue/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:129:23)
    at Config.getConfig (/Users/Jokcy/workspace/personal/test/vue/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:230:22)
    at processText (/Users/Jokcy/workspace/personal/test/vue/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine.js:149:27)
    at CLIEngine.executeOnText (/Users/Jokcy/workspace/personal/test/vue/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine.js:662:26)
    at verify (/Users/Jokcy/workspace/personal/test/vue/node_modules/gulp-eslint/index.js:20:23)
    at Transform._transform (/Users/Jokcy/workspace/personal/test/vue/node_modules/gulp-eslint/index.js:68:18)
    at Transform._read (_stream_transform.js:167:10)
```

**Comment by ilyavolodin** [comment]
v2.5.0 had an issue with npm bundle. Could you try upgrading to v2.5.3?

**Comment by Jokcy** [comment]
@ilyavolodin I updated and nothing changed. Also I tried to move the project to another folder the it runs OK. I don't understand

**Comment by platinumazure** [comment]
Maybe you have a config file in an ancestor directory (above project root) that is pulling in react? Try setting `root: true` in your project config.

**Comment by nzakas** [comment]
@Jokcy any update?

**Comment by Jokcy** [comment]
@nzakas Sorry for replying so late, root: true is OK for me now.

**Comment by nzakas** [comment]
OK, thanks!
