### ISSUE TITLE
no-this-before-super: Cannot read property "superCalled" of undefined

### ISSUE THREAD

**Issue by nashe** [eslint/eslint#5894]
Aloha,

**What version of ESLint are you using?**

Tried with v2.5.3, v.2.8.0 (in Atom using the global `eslint`).

**What parser (default, Babel-ESLint, etc.) are you using?**

Default?

**Please show your full configuration:**

```json
{
    "extends": "eslint:recommended",
    "env": {
      "es6": true
    },
    "parserOptions": {
      "sourceType": "module"
    },
    "rules": {
       "indent": ["error", 2, {"SwitchCase": 1}]
    }
}

```

**What did you do? Please include the actual source code causing the issue.**

```js
export class A extends Array {

  constructor() {
    return;
    this.x = 'x';
  }

}
```

**What did you expect to happen?**

No error message. The `no-unreachable` rule matched correctly. 

**What actually happened? Please include the actual, raw output from ESLint.**

```
TypeError: Cannot read property 'superCalled' of undefined
    at isCalled (xxx/node_modules/eslint/lib/rules/no-this-before-super.js:65:38)
    at Array.every (native)
    at isBeforeCallOfSuper (xxx/node_modules/eslint/lib/rules/no-this-before-super.js:83:48)
    at EventEmitter.ThisExpression (xxx/node_modules/eslint/lib/rules/no-this-before-super.js:245:17)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (xxx/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (xxx/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:609:23)
    at CommentEventGenerator.enterNode (xxx//node_modules/eslint/lib/util/comment-event-generator.js:99:23)
    at Controller.traverser.traverse.enter (xxx/node_modules/eslint/lib/eslint.js:887:36)
```

**Comment by mysticatea** [comment]
Thank you for this issue.

I will fix it.

**Comment by nashe** [comment]
Awesome, thanks!
