### ISSUE TITLE
Cannot finish file scan in `eslint --init` when file contains invalid ESLint config comment

### ISSUE THREAD

**Issue by victor-homyakov** [eslint/eslint#5985]
**What version of ESLint are you using?**
2.8.0
**What parser (default, Babel-ESLint, etc.) are you using?**
default I hope
**Please show your full configuration:**
There is no configuration yet
**What did you do? Please include the actual source code causing the issue.**
`eslint --init`
and I choose to scan my files to determine the best configuration
one of files contains invalid comment `/*eslint max-statements[2,60], max-depth:[2,4] */`
**What did you expect to happen?**
successful finish
**What actually happened? Please include the actual, raw output from ESLint.**
```
(mention.js:31:13) Failed to parse JSON from ' max-statements[2,60], "max-depth":[2,4]': Unexpected token m
Error: (mention.js:31:13) Failed to parse JSON from ' max-statements[2,60], "max-depth":[2,4]': Unexpected token m
    at getSourceCodeOfFile (C:\Users\khomyackov\AppData\Roaming\npm\node_modules\eslint\lib\util\source-code-util.js:43:15)    at C:\Users\khomyackov\AppData\Roaming\npm\node_modules\eslint\lib\util\source-code-util.js:99:26
    at Array.forEach (native)
    at getSourceCodeOfFiles (C:\Users\khomyackov\AppData\Roaming\npm\node_modules\eslint\lib\util\source-code-util.js:98:15)    at configureRules (C:\Users\khomyackov\AppData\Roaming\npm\node_modules\eslint\lib\config\config-initializer.js:128:23)
    at processAnswers (C:\Users\khomyackov\AppData\Roaming\npm\node_modules\eslint\lib\config\config-initializer.js:250:18)
    at null.completed (C:\Users\khomyackov\AppData\Roaming\npm\node_modules\eslint\lib\config\config-initializer.js:404:30)
    at PromptUI.onCompletion (C:\Users\khomyackov\AppData\Roaming\npm\node_modules\eslint\node_modules\inquirer\lib\ui\prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (C:\Users\khomyackov\AppData\Roaming\npm\node_modules\eslint\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:1550:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\khomyackov\AppData\Roaming\npm\node_modules\eslint\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:1489:14)
```

**Comment by nzakas** [comment]
Hmm, I'm not sure we can do anything about this. I was thinking we could skip a file with parse errors, but if all of your files have the same problem, that wouldnt help.

It seems like erroring out in this way is the best option here, but let's see what @IanVS thinks.

**Comment by IanVS** [comment]
Hm, yeah I made the decision when creating autoconfig that parse errors should bubble up and not be skipped over.  Otherwise, the results of autoconfig could be different than what's expected, and once the user starts to lint their files they're going to have to deal with the parse errors anyway.  I think this is a case of "fail fast", and personally I don't consider it a bug.

**Comment by nzakas** [comment]
Can we run ESLint with configuration comments disabled (and not parsed)?

**Comment by IanVS** [comment]
Hm, I'm not aware of a way, but I assume that would need to be handled within espree, right?  Could be an interesting enhancement, for those wanting to find out how much they're relying on inline config. 😃

**Comment by IanVS** [comment]
The next question would be whether to use such an option within autoconfig.  I tend to think "no", because if files already have eslint config comments, they should be respected just like they will be during regular linting.  Otherwise, the generated config will not be accurate.

**Comment by victor-homyakov** [comment]
Could "Invalid eslint configuration comment" be just another error/warning?

**Comment by victor-homyakov** [comment]
It also may help writing configuration comments in IDEs with ESLint support like WebStorm.

**Comment by nzakas** [comment]
@IanVS we added `allowInlineConfig` as an option on `verify()`: https://github.com/eslint/eslint/blob/master/lib/eslint.js#L715

Wouldn't that do the trick?

**Comment by IanVS** [comment]
Cool, didn't know about that one.  So yes, it looks like we _could_, but I would still argue that we _shouldn't_, for the reasons I mentioned above.

**Comment by nzakas** [comment]
Fair enough. Then perhaps we can make config comment parsing failure a reported error instead of a thrown error as @victor-homyakov suggested? That would be a change to the core rather than an autoconfig change.

**Comment by kaicataldo** [comment]
Closing this because we haven't made any progress in months. Thanks for contributing!
