### ISSUE TITLE
Cannot finish file scan in `eslint --init`

### ISSUE THREAD

**Issue by victor-homyakov** [eslint/eslint#5992]
**What version of ESLint are you using?**
2.8.0
**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**
none yet
**What did you do? Please include the actual source code causing the issue.**
1. `eslint --init scripts` on existing project
2. I choose to scan my files to determine the best configuration
**What did you expect to happen?**
successful finish
**What actually happened? Please include the actual, raw output from ESLint.**
```
Determining Config: 31% [=========---------------------] 57.2s elapsed, eta 130.1s Cannot read property 'errorCount' of undefined
TypeError: Cannot read property 'errorCount' of undefined
    at C:\Users\khomyackov\AppData\Roaming\npm\node_modules\eslint\lib\config\autoconfig.js:315:68
    at Array.forEach (native)
    at C:\Users\khomyackov\AppData\Roaming\npm\node_modules\eslint\lib\config\autoconfig.js:314:29
    at Array.forEach (native)
    at C:\Users\khomyackov\AppData\Roaming\npm\node_modules\eslint\lib\config\autoconfig.js:310:22
    at Array.forEach (native)
    at Registry.lintSourceCode (C:\Users\khomyackov\AppData\Roaming\npm\node_modules\eslint\lib\config\autoconfig.js:305:19)
    at configureRules (C:\Users\khomyackov\AppData\Roaming\npm\node_modules\eslint\lib\config\config-initializer.js:146:25)
    at processAnswers (C:\Users\khomyackov\AppData\Roaming\npm\node_modules\eslint\lib\config\config-initializer.js:250:18)
    at null.completed (C:\Users\khomyackov\AppData\Roaming\npm\node_modules\eslint\lib\config\config-initializer.js:404:30)
```

**Comment by victor-homyakov** [comment]
Additional info for `autoconfig.js:315`:
```
result.ruleId: max-len
ruleSetIdx: 9
lintedRegistry.rules[result.ruleId]: [
  { config: 2, specificity: 1, errorCount: 2186 },
  { config: [ 2, [Object] ], specificity: 2, errorCount: 2045 },
  { config: [ 2, [Object] ], specificity: 2, errorCount: 2045 },
  { config: [ 2, [Object] ], specificity: 2, errorCount: 2047 },
  { config: [ 2, [Object] ], specificity: 2, errorCount: 2047 },
  { config: [ 2, [Object] ], specificity: 2, errorCount: 2092 },
  { config: [ 2, [Object] ], specificity: 2, errorCount: 2184 },
  { config: [ 2, [Object] ], specificity: 2, errorCount: 2094 },
  { config: [ 2, [Object] ], specificity: 2, errorCount: 2186 }
]
```

**Comment by ilyavolodin** [comment]
@IanVS Could you take a look please?

**Comment by IanVS** [comment]
@victor-homyakov thanks for the good information.  Is it possible that you have an eslint configuration comment in one of your files which is enabling `max-len`?

**Comment by IanVS** [comment]
I believe I have a fix in https://github.com/eslint/eslint/pull/5999.

**Comment by victor-homyakov** [comment]
@IanVS yes, the file contains `/*eslint max-len:[1,140,4]*/`

**Comment by victor-homyakov** [comment]
@IanVS I confirm that your fix solves this issue

**Comment by IanVS** [comment]
Getting good, detailed bug reports makes me so happy.  😃   Thanks for taking the time to do a little extra troubleshooting.

Hopefully we can squeeze this fix into today's release.
