### ISSUE TITLE
Redundant plugin redeclaration to use plugin's environment

### ISSUE THREAD

**Issue by segrey** [eslint/eslint#6030]
Plugins defined in parent eslint configuration files are not taken into account when validating environment. As a result, eslint fails with error. However, there are no errors when referencing rules from plugins declared in parent eslint config only.

Let's consider an example:
`package.json`:
```JSON
{
  "name": "eslint-problem-demo",
  "version": "0.0.1",
  "devDependencies": {
    "eslint": "^2.9.0",
    "eslint-plugin-angular": "^1.0.1"
  }
}
```

`.eslintrc` in the project root directory:
```
{
  "plugins": ["angular"]
}
```

`src/.eslintrc`:
```
{
  "env": {
    "angular/angular": true
  },
  "rules": {
    "angular/no-run-logic": "error"
  }
}
```

`src/app.js`:
```javascript
(function () {
  'use strict';

  angular
    .module('demo')
    .run(function () {
      // angular/no-run-logic should err in the next line saying
      // "The run function may only contain call expressions"
      var getValue = function () {
          return 10;
      };
      getValue();
    });
})();
```

Linting `src/app.js` fails with the error:
```
~/eslint-problem-demo $ ./node_modules/.bin/eslint src/app.js 
/home/segrey/eslint-problem-demo/src/.eslintrc:
	Environment key "angular/angular" is unknown

Error: /home/segrey/eslint-problem-demo/src/.eslintrc:
	Environment key "angular/angular" is unknown

    at /home/segrey/eslint-problem-demo/node_modules/eslint/lib/config/config-validator.js:145:23
    at Array.forEach (native)
    at validateEnvironment (/home/segrey/eslint-problem-demo/node_modules/eslint/lib/config/config-validator.js:138:34)
    at Object.validate (/home/segrey/eslint-problem-demo/node_modules/eslint/lib/config/config-validator.js:167:5)
    at Object.load (/home/segrey/eslint-problem-demo/node_modules/eslint/lib/config/config-file.js:518:19)
    at loadConfig (/home/segrey/eslint-problem-demo/node_modules/eslint/lib/config.js:64:33)
    at getLocalConfig (/home/segrey/eslint-problem-demo/node_modules/eslint/lib/config.js:126:23)
    at Config.getConfig (/home/segrey/eslint-problem-demo/node_modules/eslint/lib/config.js:227:22)
    at processText (/home/segrey/eslint-problem-demo/node_modules/eslint/lib/cli-engine.js:220:27)
    at processFile (/home/segrey/eslint-problem-demo/node_modules/eslint/lib/cli-engine.js:295:18)
```

However, commenting out `"env": { "angular/angular": true }` section in `src/.eslintrc` makes eslint show found eslint-plugin-angular specific error (thus, it meas `"angular/no-run-logic": "error"` rules works).

Also, re-declaring `"plugins": ["angular"]` in `src/.eslintrc` fixes the problem (but it seems to be redundant).

Custom rules and environments should require uniform plugin declaration.

eslint 2.9.0 with default parser, node 6.0.0

**Comment by ilyavolodin** [comment]
Hmm.. Interesting. I'm guessing this is because we are loading environments before we merge configs. Feels like something that we should fix and have it behave the same way as rules. I wonder if shareable configs inside plugins will act the same way?

**Comment by nzakas** [comment]
This is intentional. We don't want people doing what you are attempting to do because it creates unclear config dependencies. Any config referencing `amgular/sonething` should also have `angular` listed as a plugin. That way, the config can be copied anywhere else and still work the same.

**Comment by ilyavolodin** [comment]
@nzakas That's a valid point, but in that case, shouldn't the rule configuration from plugin behave the same way?

**Comment by nzakas** [comment]
@ilyavolodin I'm not sure what you're asking, can you give an example?

**Comment by ilyavolodin** [comment]
@nzakas Based on the original description, if you declare plugin in the top .eslintrc file, you can then enable/disable rules in .eslintrc files in subfolders without having to declare plugin again. I haven't verified that, but if that's actually possible, and configs are supposed to be portable, we should disable that functionality.

**Comment by nzakas** [comment]
@ilyavolodin I think you misread that. I believe what @segrey reports is that that doesn't work.

**Comment by segrey** [comment]
@nzakas yes, in my original report I was assuming that plugin declarations are inherited similarly to other properties. The reason of this assumption is that rules can be disabled/enabled without declaring plugins explicitly. If this assumption is wrong, then rules should also require explicit plugin declaration (as @ilyavolodin said).

**Comment by segrey** [comment]
@nzakas as for unclear config dependencies, good point. How about supporting explicit config dependency declaration via `extends` property? It doesn't work now.

**Comment by ilyavolodin** [comment]
@nzakas I was confused by this sentence in the original message:

> However, commenting out "env": { "angular/angular": true } section in src/.eslintrc makes eslint show found eslint-plugin-angular specific error (thus, it meas "angular/no-run-logic": "error" rules works).

However, I just tried it, and you get "Definition for rule "angular/no-private-call" was not found", so it's not working with rule configuration either without specifying plugin. In that case, I think this is behaving correctly. The only thing we might want to fix is that when you specify rule configuration without specifying plugin, you get a nice error message, however, when you specify environment from plugin without plugin declaration, you get an error message + stack trace.

@segrey Just to make sure, are you saying that rule configuration works would declaring plugin (if plugin declared in the upper config)? I tested it just now, and it's not working for me.

**Comment by segrey** [comment]
@ilyavolodin odd, I've just tested and got found eslint angular errors, see my configuration below.
`.eslintrc`:
```JSON
{
  "plugins": ["angular"]
}
``` 

`src/.eslintrc`:
```JSON
{
  "rules": {
    "angular/no-run-logic": "error"
  }
}
```

```
~/eslint-problem-demo $ ./node_modules/eslint/bin/eslint.js src/app.js 

/home/segrey/eslint-problem-demo/src/app.js
  9:7  error  The run function may only contain call expressions  angular/no-run-logic

✖ 1 problem (1 error, 0 warnings)
```

**Comment by segrey** [comment]
Could you please let me know whether you get `Definition for rule 'angular/no-run-logic' was not found` or `The run function may only contain call expressions` for the configuration from [my previous comment](https://github.com/eslint/eslint/issues/6030#issuecomment-216355517)? (with the same package.json)
If you get `Definition for rule 'angular/no-run-logic' was not found`, feel free to request more information about my environment.

**Comment by nzakas** [comment]
Okay, I think we all misunderstood what was going on here.

The error isn't about a **rule** not being found, it's about an **environment** not being found. In the original description, the error is about `angular/angular`. In the [preceding comment](https://github.com/eslint/eslint/issues/6030#issuecomment-216355517), only a rule is enabled.

In that case, @sergey it's likely that the environment just doesn't exist in the plugin.

**Comment by ilyavolodin** [comment]
@nzakas Environment does exist. Here's my summery of what I understand is happening. Given two configs, one in the top level and one in the subfolder:
* If top level config declares a plugin, when you declare an environment from that plugin in subconfig without re-declaration of the plugin you get a stacktrace error, saying that environment doesn't exist.
* If top level config declares a plugin, when you configure a rule from that plugin in subconfig without re-declaration of the plugin everything is working, and you get report containing linting errors from the plugin rule that you configured.

Now I tried checking both of the scenarios described above, and while first one behaves as I described, second one for me returns `Definition for rule "angular/no-private-call" was not found`, which is what I expected to happen. I'm not sure what's the differences in setup is between what I've tried and what @segrey is reporting.

@segrey Could you run the second scenario that I described with `--debug` flag and post the output here?

**Comment by segrey** [comment]
@ilyavolodin yep, that's a correct summary. Here is my output:
```
~/eslint-problem-demo $ ./node_modules/eslint/bin/eslint.js --version
v2.9.0
~/eslint-problem-demo $ ./node_modules/eslint/bin/eslint.js --debug src/app.js 
  eslint:cli Running on files +0ms
  eslint:ignored-paths Looking for ignore file in /home/segrey/eslint-problem-demo +30ms
  eslint:ignored-paths Could not find ignore file in cwd +2ms
  eslint:glob-util Creating list of files to process. +0ms
  eslint:cli-engine Processing /home/segrey/eslint-problem-demo/src/app.js +1ms
  eslint:cli-engine Linting /home/segrey/eslint-problem-demo/src/app.js +1ms
  eslint:config Constructing config for /home/segrey/eslint-problem-demo/src/app.js +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /home/segrey/eslint-problem-demo/src/.eslintrc +1ms
  eslint:config-file Loading config file: /home/segrey/eslint-problem-demo/src/.eslintrc +1ms
  eslint:config Using /home/segrey/eslint-problem-demo/src/.eslintrc +37ms
  eslint:config Loading /home/segrey/eslint-problem-demo/.eslintrc +1ms
  eslint:config-file Loading config file: /home/segrey/eslint-problem-demo/.eslintrc +0ms
  eslint:config Using /home/segrey/eslint-problem-demo/.eslintrc +18ms
  eslint:config Merging command line environment settings +1ms
  eslint:config-ops Apply environment settings to config +0ms
  eslint:cli-engine Linting complete in: 123ms +57ms

/home/segrey/eslint-problem-demo/src/app.js
  9:7  error  The run function may only contain call expressions  angular/no-run-logic

✖ 1 problem (1 error, 0 warnings)
```
