### ISSUE TITLE
[][0] TypeError: Expected a string

### ISSUE THREAD

**Issue by steambap** [eslint/eslint#6050]
**What version of ESLint are you using?**
2.9.0 (xo)
**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint (xo)
**Please show your full configuration:**
xo default config
**What did you do? Please include the actual source code causing the issue.**

> test('do not explode when object is undefined', t => {
	t.is(toProp([][0]), undefined);
	t.deepEqual(toProp([1, 'DICTIONARY_ID']), [1, 'DICTIONARY_ID']);
});

**What did you expect to happen?**
parse '[][0]' grammar or rise a lint error
**What actually happened? Please include the actual, raw output from ESLint.**

> TypeError: Expected a string
    at module.exports (D:\xampp\htdocs\LemonCloud\node_modules\is-get-set-prop\lib\index.js:25:11)
    at EventEmitter.MemberExpression (D:\xampp\htdocs\LemonCloud\node_modules\eslint-plugin-no-use-extend-native\rules\no-use-extend-native.js:71:39)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (D:\xampp\htdocs\LemonCloud\node_modules\eslint\lib\util\node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (D:\xampp\htdocs\LemonCloud\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (D:\xampp\htdocs\LemonCloud\node_modules\eslint\lib\util\comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (D:\xampp\htdocs\LemonCloud\node_modules\eslint\lib\eslint.js:886:36)
    at Controller.__execute (D:\xampp\htdocs\LemonCloud\node_modules\estraverse\estraverse.js:397:31)
    at Controller.traverse (D:\xampp\htdocs\LemonCloud\node_modules\estraverse\estraverse.js:501:28)

**Comment by mysticatea** [comment]
Thank you for this issue.

It seems to be happened in [eslint-plugin-no-use-extend-native].
Could you report an issue on their repo?

Closing as there is nothing to fix here. Feel free to reopen if I'm wrong.

[eslint-plugin-no-use-extend-native]: https://www.npmjs.com/package/eslint-plugin-no-use-extend-native
