### ISSUE TITLE
Allow capital letters in jsdoc tags

### ISSUE THREAD

**Issue by knowledgecode** [eslint/eslint#6121]
**What version of ESLint are you using?**
2.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
```YAML
---
  rules:
    valid-jsdoc: 1
```

**What did you do? Please include the actual source code causing the issue.**
```JavaScript
/**
 * test function
 * @Returns {void}
 */
var f = function () {
};
```

**What did you expect to happen?**
Maybe:
```
  1:1  warning  Missing JSDoc @returns for function  valid-jsdoc
```

**What actually happened? Please include the actual, raw output from ESLint.**
```
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at isValidReturnType (/Users/knowledgecode/.nodebrew/node/v4.4.4/lib/node_modules/eslint/lib/rules/valid-jsdoc.js:127:49)
    at /Users/knowledgecode/.nodebrew/node/v4.4.4/lib/node_modules/eslint/lib/rules/valid-jsdoc.js:289:38
    at Array.forEach (native)
    at EventEmitter.checkJSDoc (/Users/knowledgecode/.nodebrew/node/v4.4.4/lib/node_modules/eslint/lib/rules/valid-jsdoc.js:256:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.leaveNode (/Users/knowledgecode/.nodebrew/node/v4.4.4/lib/node_modules/eslint/lib/util/node-event-generator.js:49:22)
    at CodePathAnalyzer.leaveNode (/Users/knowledgecode/.nodebrew/node/v4.4.4/lib/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:627:23)
    at CommentEventGenerator.leaveNode (/Users/knowledgecode/.nodebrew/node/v4.4.4/lib/node_modules/eslint/lib/util/comment-event-generator.js:110:23)
    at Controller.traverser.traverse.leave (/Users/knowledgecode/.nodebrew/node/v4.4.4/lib/node_modules/eslint/lib/eslint.js:889:36)
```

I guess the case insensitive string comparison causes this error (valid-jsdoc.js:258):
```JavaScript
                jsdoc.tags.forEach(function(tag) {

                    switch (tag.title.toLowerCase()) {

                        case "param":
```
Or `doctrine` parse error?

**Comment by kaicataldo** [comment]
This seems to be related to https://github.com/eslint/eslint/issues/6145. In both cases, changing the first character of the tag from lowercase to uppercase results in missing properties that the valid-jsdoc rule is expecting. Changing the characters back to lowercase fixes the issue.

<img width="1003" alt="screen shot 2016-05-12 at 12 14 58 am" src="https://cloud.githubusercontent.com/assets/7041728/15203991/bfd583a2-17d6-11e6-9b40-6928dd62dce0.png">

**Comment by alberto** [comment]
@kaicataldo yes, JSDoc is case insensitive.

**Comment by nzakas** [comment]
Doing a new release of Doctrine that supports uppercase JSDoc tags now. Should be ready in a few minutes.

**Comment by alberto** [comment]
Cool, thanks
