### ISSUE TITLE
TypeError: Cannot read property 'range' of null in v2.9.0

### ISSUE THREAD

**Issue by garrett-gottlieb** [eslint/eslint#6130]
**What version of ESLint are you using?**
v2.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint

**Please show your full configuration:**

**What did you do? Please include the actual source code causing the issue.**

Because of the error, it is unclear as to where this error exists. See below.

*.eslintrc*

```json
{
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 6,
    "jsx": true,
    "experimentalObjectRestSpread": true
  },
  "extends": "eslint:recommended",
  "rules": {
    "comma-dangle": [0, "always-multiline"],
    "complexity": [1, 6],
    "curly": [2, "all"],
    "default-case": [2],
    "dot-notation": [1],
    "dot-location": [1, "property"],
    "eqeqeq": [2, "allow-null"],
    "guard-for-in": [2],
    "indent": [2, 2],
    "quotes": [2, "single"],
    "linebreak-style": [2, "unix"],
    "max-depth": [1, 3],
    "max-len": [1, 120],
    "max-params": [1, 4],
    "max-statements": [1, 20],
    "no-alert": [2],
    "no-caller": [2],
    "no-console": [0],
    "no-else-return": [1],
    "no-extend-native": [2],
    "no-eval": [2],
    "no-floating-decimal": [2],
    "no-implied-eval": [2],
    "no-invalid-this": [2],
    "no-loop-func": [1],
    "no-multi-str": [2],
    "no-native-reassign": [2],
    "no-new-func": [2],
    "no-new-wrappers": [2],
    "no-proto": [2],
    "no-return-assign": [2, "except-parens"],
    "no-script-url": [2],
    "no-self-compare": [2],
    "no-sequences": [2],
    "no-unexpected-multiline": [2],
    "no-unused-expressions": [2],
    "no-unused-vars": [2, {"args": "none"}],
    "no-useless-call": [2],
    "no-var": [2],
    "no-with": [2],
    "radix": [2],
    "semi": [2, "never"],
    "valid-jsdoc": [1, {
      "prefer": {
        "returns": "return"
      },
      "requireParamDescription": false,
      "requireReturn": false,
      "requireReturnDescription": false
    }]
  },
  "env": {
    "es6": true,
    "browser": true,
    "mocha": true,
    "node": true
  },
  "ecmaFeatures": {
    "jsx": true,
    "experimentalObjectRestSpread": true
  },
  "plugins": [
    "react"
  ]
}
```

*.eslintignore*
```
**/*.html
app
libs
mixpanel.jsx
node_modules
```

**What did you expect to happen?**
Output a useful error

**What actually happened? Please include the actual, raw output from ESLint.**

```
gsquare567@Macintosh-2 ~/S/mobile> eslint -c .eslintrc **/*.jsx
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
    at isSafe (/usr/local/lib/node_modules/eslint/lib/rules/no-loop-func.js:123:6)
    at Array.every (native)
    at EventEmitter.checkForLoops (/usr/local/lib/node_modules/eslint/lib/rules/no-loop-func.js:186:29)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/usr/local/lib/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/usr/local/lib/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/usr/local/lib/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (/usr/local/lib/node_modules/eslint/lib/eslint.js:886:36)
    at Controller.__execute (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
gsquare567@Macintosh-2 ~/S/mobile> eslint -v
v2.9.0
```

**Comment by ilyavolodin** [comment]
Could you try the same file without `babel-eslint`? `babel-eslint` is not 100% compatible with ESTree, as such some of the errors might be due to the parser.

**Comment by garrett-gottlieb** [comment]
After experimentation, using the default parser and
```
"experimentalObjectRestSpread": true
```
along with
```
"no-loop-func": [1],
```
causes the error. When I remove either of those, it works.

**Comment by mysticatea** [comment]
Thank you for this issue.

Could you provide the source code to reproduce this?

**Comment by mysticatea** [comment]
> it is unclear as to where this error exists.

Ah, I'm sorry.
I'll investigate this.

**Comment by alberto** [comment]
Can you run it with `--debug`? It should tell you the file it was linting when it failed

**Comment by mysticatea** [comment]
I got it.

If a reference in a function in a loop uses a `let` variable before the declaration, this crash happens.

```js
/* eslint-env es6 */
/* eslint no-loop-func:2 */

while (true) {
    (function() { a; });
}
let a;
```
