### ISSUE TITLE
object-property-newline has problems with the experimental object rest spread feature

### ISSUE THREAD

**Issue by fatfisz** [eslint/eslint#6207]
**What version of ESLint are you using?**
2.10.2
**What parser (default, Babel-ESLint, etc.) are you using?**
default, Babel-ESLint - both don't work
**Please show your full configuration:**
```js
parserOptions: {
  ecmaVersion: 6,
  ecmaFeatures: {
    experimentalObjectRestSpread: true
  }
}
```
**What did you do? Please include the actual source code causing the issue.**
```js
var obj = { k1: 'val1', k2: 'val2', ...{} };
```
**What did you expect to happen?**
No errors.
**What actually happened? Please include the actual, raw output from ESLint.**
```
TypeError: Cannot read property 'range' of undefined
      at SourceCode.api.getFirstToken (D:\Projects\eslint\lib\token-store.js:9:3834)
      at EventEmitter.ObjectExpression (D:\Projects\eslint\lib\rules\object-property-newline.js:9:2164)
      at NodeEventGenerator.enterNode (D:\Projects\eslint\lib\util\node-event-generator.js:9:359)
      at CodePathAnalyzer.enterNode (D:\Projects\eslint\lib\code-path-analysis\code-path-analyzer.js:9:23334)
      at CommentEventGenerator.enterNode (D:\Projects\eslint\lib\util\comment-event-generator.js:9:2024)
      at Controller.traverser.traverse.enter (D:\Projects\eslint\lib\eslint.js:9:32865)
      at Controller.__execute (D:\Projects\eslint\node_modules\estraverse\estraverse.js:397:31)
      at Controller.traverse (D:\Projects\eslint\node_modules\estraverse\estraverse.js:501:28)
      at Controller.Traverser.controller.traverse (D:\Projects\eslint\lib\util\traverser.js:9:626)
      at EventEmitter.module.exports.api.verify (D:\Projects\eslint\lib\eslint.js:9:32670)
      at runRuleForItem (D:\Projects\eslint\lib\testers\rule-tester.js:9:9027)
      at testValidTemplate (D:\Projects\eslint\lib\testers\rule-tester.js:9:9669)
      at Context.<anonymous> (D:\Projects\eslint\lib\testers\rule-tester.js:9:14513)
      at callFn (D:\Projects\eslint\node_modules\mocha\lib\runnable.js:315:21)
      at Test.Runnable.run (D:\Projects\eslint\node_modules\mocha\lib\runnable.js:308:7)
      at Runner.runTest (D:\Projects\eslint\node_modules\mocha\lib\runner.js:422:10)
      at D:\Projects\eslint\node_modules\mocha\lib\runner.js:533:12
      at next (D:\Projects\eslint\node_modules\mocha\lib\runner.js:342:14)
      at D:\Projects\eslint\node_modules\mocha\lib\runner.js:352:7
      at next (D:\Projects\eslint\node_modules\mocha\lib\runner.js:284:14)
      at Immediate._onImmediate (D:\Projects\eslint\node_modules\mocha\lib\runner.js:320:5)
```

I'd like to try and fix this, if that's ok. I've already started setting up some tests and reading the code.

**Comment by fatfisz** [comment]
I think I have a fix for this, but it's late and I'll have to continue after having a good sleep :smile: I want to add a few more tricky test cases, but my brain is fried rn.

By the way, just to make sure: should this be ok with `object-property-newline` turned on?
```js
var obj = { k1: 'val1', [
  k2]: 'val2' };
```
Currently there's no error thrown for that and I think that's wrong, because the second property starts at the first line.

Also this case, with `allowMultiplePropertiesPerLine: true`:
```js
var obj = { [
  k1]: 'val1', k2: 'val2' };
```
No error here too, while the first property starts at the first line.

My fix would take such cases into consideration too.

**Comment by nzakas** [comment]
Thanks for the bug report. @vitorbal what do you think about https://github.com/eslint/eslint/issues/6207#issuecomment-219897227? Also, @markelog can you confirm if the JSCS version of this rule catches the examples in https://github.com/eslint/eslint/issues/6207#issuecomment-219897227?

**Comment by markelog** [comment]
[disallowObjectKeysOnNewLine](http://jscs.info/rule/disallowObjectKeysOnNewLine) works with computed properties, but doesn't catch this -

```js
var obj = { k1: 'val1', [
  k2]: 'val2' };
```

there is no analogue to `allowMultiplePropertiesPerLine` option as i recall

**Comment by vitorbal** [comment]
Thanks for the bug report, @fatfisz!
@nzakas I think both examples should trigger an error since the beginning of the object property starts at the `[`.
I'm just wondering if the second example not being caught by JSCS could cause any compatibility issues with people migrating over to ESLint from JSCS?
@markelog the analogous option in JSCS for `allowMultiplePropertiesPerLine` would be `"allExcept": ["sameLine"]`. Does it also not catch it with this option turned on?

**Comment by markelog** [comment]
@vitorbal oh sorry confused disallow and require rules, yeah it doesn't

**Comment by nzakas** [comment]
@markelog do you consider the JSCS rule not catching the multi-line computed property as a bug?

**Comment by markelog** [comment]
I definitely do
