### ISSUE TITLE
Export { x } from ... doesn't generate variable declaration

### ISSUE THREAD

**Issue by SohKai** [eslint/eslint#6210]
Using v2.10.2, re-export statements in the fashion of `export { x } from ...` or `export { x as y } from ...` results in nodes that have `declaration: null`. I'm not well-versed enough with how the parsing is done to know if these statements would make sense having a declaration (since they don't declare variables the same way a `export var x = y` would do), but this lack of a declaration breaks rules that assume it'll be there (ie. [vars-on-top](https://github.com/eslint/eslint/blob/master/lib/rules/vars-on-top.js#L69)).

Running ESLint with `vars-on-top` will throw an exception on this file:

```js
export { default } from 'your-package';

var test = 'bad';
```

Exception:

```js
Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at isVarOnTop (.../node_modules/eslint/lib/rules/vars-on-top.js:69:50)
    at globalVarCheck (.../node_modules/eslint/lib/rules/vars-on-top.js:87:18)
    at EventEmitter.VariableDeclaration (.../node_modules/eslint/lib/rules/vars-on-top.js:125:25)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (.../node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (.../node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (.../node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (.../node_modules/eslint/lib/eslint.js:886:36)
    at Controller.__execute (.../node_modules/estraverse/estraverse.js:397:31)
```

**Comment by ilyavolodin** [comment]
Is that a valid syntax? Shouldn't it be `export default from 'your-package';` instead? Sorry I'm not really up to date on `export` syntax. But in any case, we should fix the rule crash, I think.

**Comment by michaelficarra** [comment]
@ilyavolodin Yes, it is. No, your suggestion is not valid.

**Comment by mysticatea** [comment]
Thank you for this issue.

I confirmed it.
I will fix it.
