### ISSUE TITLE
Syntax Error on eslint --init (ask questions about style) when package.json is malformed

### ISSUE THREAD

**Issue by petertrotman** [eslint/eslint#6257]
On running `eslint --init` I get the following error. I've tried a few different choices and all result in the same problem. The init phase never succeeds.
```
$ ./node_modules/eslint/bin/eslint.js --init
? How would you like to configure ESLint? Answer questions about your style
? Are you using ECMAScript 6 features? Yes
? Are you using ES6 modules? Yes
? Where will your code run? Browser
? Do you use CommonJS? Yes
? Do you use JSX? Yes
? Do you use React Yes
? What style of indentation do you use? Spaces
? What quotes do you use for strings? Single
? What line endings do you use? Unix
? Do you require semicolons? Yes
? What format do you want your config file to be in? JavaScript
Unexpected token }
SyntaxError: Unexpected token }
    at Object.parse (native)
    at check (/home/peter/Projects/rikesh-accounting-web/node_modules/eslint/lib/util/npm-util.js:76:25)
    at Object.checkDevDeps (/home/peter/Projects/rikesh-accounting-web/node_modules/eslint/lib/util/npm-util.js:116:12)
    at installModules (/home/peter/Projects/rikesh-accounting-web/node_modules/eslint/lib/config/config-initializer.js:86:29)
    at processAnswers (/home/peter/Projects/rikesh-accounting-web/node_modules/eslint/lib/config/config-initializer.js:262:5)
    at null.completed (/home/peter/Projects/rikesh-accounting-web/node_modules/eslint/lib/config/config-initializer.js:469:30)
    at PromptUI.onCompletion (/home/peter/Projects/rikesh-accounting-web/node_modules/eslint/node_modules/inquirer/lib/ui/prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/home/peter/Projects/rikesh-accounting-web/node_modules/eslint/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1550:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/peter/Projects/rikesh-accounting-web/node_modules/eslint/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1489:14)
    at Subject.Rx.Subject.addProperties.onCompleted (/home/peter/Projects/rikesh-accounting-web/node_modules/eslint/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5871:19)
```

**What version of ESLint are you using?**
```
$ ./node_modules/eslint/bin/eslint.js -v
v2.10.2
```
```
$ node -v
v4.4.5
```

**What parser (default, Babel-ESLint, etc.) are you using?**

n/a

**Please show your full configuration:**

n/a

**What did you do? Please include the actual source code causing the issue.**

See above.

**What did you expect to happen?**

To successfully create the .eslintrc

**What actually happened? Please include the actual, raw output from ESLint.**

Syntax Error

**Comment by platinumazure** [comment]
Totally guessing here, but I'm wondering if we're trying to parse your `package.json` here and maybe there's a syntax error in that file? Could you post that here and/or try running the contents of `package.json` through jsonlint.com?

**Comment by petertrotman** [comment]
You are correct! I've continued working on this project and now the package.json is correctly formatted and eslint --init works fine... I'll close the issue but it might be worth catching this error and showing a more useful error message :-)

**Comment by platinumazure** [comment]
I agree we should handle this better. Hope it's okay if i reopen and retitle the issue. :smile:

**Comment by platinumazure** [comment]
Reproduced with package.json file consisting solely of an open curly brace. We should catch this and display a friendly message to the user (IMO).

**Comment by kaicataldo** [comment]
Working on this!
