### ISSUE TITLE
`no-useless-rename` fails on spread operators in destructured statements

### ISSUE THREAD

**Issue by EvNaverniouk** [eslint/eslint#6284]
The new `no-useless-rename` rule will fail with:

```
TypeError: Cannot read property 'type' of undefined
    at EventEmitter.checkDestructured (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/lib/rules/no-useless-rename.js:96:26)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/lib/eslint.js:886:36)
    at Controller.__execute (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/lib/util/traverser.js:36:33)
```

When a spread operator is encountered, such as in this code:

```
const {...stuff} = myObject;
```

The issue is in the `checkDestructured` function which is expecting a `properties[i].key` to exist. But the ExperimentalSpread AST object does not have a `key` defined.

**Comment by platinumazure** [comment]
Could you please provide your configuration (at least for the rule), for ease of reproduction? Thanks!

**Comment by EvNaverniouk** [comment]
My apologies for not following the template. The rule configuration used in my case was the default:

```
"no-useless-rename": [2, {
        "ignoreDestructuring": false,
        "ignoreImport": false,
        "ignoreExport": false
}]
```

**Comment by platinumazure** [comment]
Thank you! I agree this seems like a bug- hopefully we can get on it pretty quickly.

Ping @mysticatea?

**Comment by michaelficarra** [comment]
eslint doesn't support object spread. That is part of a stage 2 proposal.

**Comment by EvNaverniouk** [comment]
I should clarify that I am also using `"parser": "babel-eslint"` with `babel-eslint` version `6.0.4`

**Comment by platinumazure** [comment]
This is where the issue template comes in handy :-)

**Comment by ilyavolodin** [comment]
@EvNaverniouk Can you try this with default parser? We do not maintain `babel-eslint`, and if the issue is coming from parser, there's nothing we can do about it.

P.S. @michaelficarra Object Rest/Spread is the only experimental feature that we support, it's controlled by `experimentalObjectRestSpread` switch in `ecmaFeatures`.

**Comment by michaelficarra** [comment]
@ilyavolodin That's strange. Why do we make such an exception?

**Comment by EvNaverniouk** [comment]
This issue is reproducible without `babel-eslint`.

Command used to test: `node_modules/.bin/eslint test.js`

Contents of `test.js`:

```
var {...stuff} = myObject;
```

ESLint configuration:

```
{
    "parserOptions": {
        "ecmaFeatures": {
            "experimentalObjectRestSpread": true
        },
        "ecmaVersion": 6
    },
    "rules": {
        "no-useless-rename": [2, {
            "ignoreDestructuring": false,
            "ignoreImport": false,
            "ignoreExport": false
        }]
    }
}
```

Output:

```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at EventEmitter.checkDestructured (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/lib/rules/no-useless-rename.js:94:38)
    at emitOne (events.js:90:13)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/lib/eslint.js:886:36)
    at Controller.__execute (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (/Users/evgueni.naverniouk/Git/ux/node_modules/eslint/lib/util/traverser.js:36:33)
```

**Comment by platinumazure** [comment]
@ilyavolodin @michaelficarra Now that we have a reproduction without babel-eslint, I think we need to accept this issue, unless I'm missing something. For what it's worth, I'm :+1: to avoiding rule crashes where possible.

**Comment by ilyavolodin** [comment]
@platinumazure Agree. Seems like a valid bug, rules shouldn't just crash.
@michaelficarra Mostly due to two reasons. This was number one requested new feature, and we were getting a lot of requests for it. And we were also getting a lot of false-positives from `babel-eslint` users, because they couldn't switch to Espree due to the lack of objectRestSpread, which is suggested by a lot of React examples/tutorials out there. We felt like in this case user experience mattered more then purity.

**Comment by platinumazure** [comment]
Working on this.
