### ISSUE TITLE
getConfigForFile does not find .eslintrc's extended config

### ISSUE THREAD

**Issue by reergymerej** [eslint/eslint#6315]
**What version of ESLint are you using?**
2.11.1

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
{
  "extends": "airbnb"
}

**What did you do? Please include the actual source code causing the issue.**
Trying to use Node API to read config for a file using eslintrc extending another config.
[link to reproduction example][github]

[getConfigForFile][docs] works when .eslintrc extends a locally installed config, but not when it's globally installed.  This caused an issue in [another package][react-codemod].

**What did you expect to happen?**
Expected `getConfigForFile` to find globally installed eslint-config-airbnb.

**What actually happened? Please include the actual, raw output from ESLint.**
ESLint throws when trying to find extended config (eslint-config-airbnb).

/Users/jeremy.greer/code/personal/get-config-for-file/node_modules/eslint/lib/config/config-file.js:396
            throw e;
            ^

Error: Cannot find module 'eslint-config-airbnb'
Referenced from: /Users/jeremy.greer/code/personal/get-config-for-file/.eslintrc
    at Object.ModuleResolver.resolve (/Users/jeremy.greer/code/personal/get-config-for-file/node_modules/eslint/lib/util/module-resolver.js:75:19)
    at resolve (/Users/jeremy.greer/code/personal/get-config-for-file/node_modules/eslint/lib/config/config-file.js:473:33)
    at load (/Users/jeremy.greer/code/personal/get-config-for-file/node_modules/eslint/lib/config/config-file.js:490:24)
    at /Users/jeremy.greer/code/personal/get-config-for-file/node_modules/eslint/lib/config/config-file.js:386:36
    at Array.reduceRight (native)
    at applyExtends (/Users/jeremy.greer/code/personal/get-config-for-file/node_modules/eslint/lib/config/config-file.js:363:28)
    at Object.load (/Users/jeremy.greer/code/personal/get-config-for-file/node_modules/eslint/lib/config/config-file.js:525:22)
    at loadConfig (/Users/jeremy.greer/code/personal/get-config-for-file/node_modules/eslint/lib/config.js:64:33)
    at getLocalConfig (/Users/jeremy.greer/code/personal/get-config-for-file/node_modules/eslint/lib/config.js:126:23)
    at Config.getConfig (/Users/jeremy.greer/code/personal/get-config-for-file/node_modules/eslint/lib/config.js:227:22)

[github]: https://github.com/reergymerej/get-config-for-file
[docs]: http://eslint.org/docs/developer-guide/nodejs-api#getconfigforfile
[react-codemod]: https://github.com/reactjs/react-codemod/issues/51

**Comment by reergymerej** [comment]
@ilyavolodin Thanks for the insight.
