### ISSUE TITLE
no-useless-rename breaks destructuring with object spread

### ISSUE THREAD

**Issue by MikaAK** [eslint/eslint#6442]
**What version of ESLint are you using?**
v2.11.1
**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
```json
{
  "root": true,
  "parserOptions": {
    "ecmaVersion": "7",
    "sourceType": "module",
    "ecmaFeatures": {
      "impliedStrict": true,
      "experimentalObjectRestSpread": true
    },
  },

  "env": {
    "es6": true,
    "browser": true,
    "jquery": true,
    "jasmine": true,
    "mocha": true,
    "commonjs": true,
    "phantomjs": true
  },
  "rules": {
    "no-useless-rename": 1
  },
  "globals": {
    "assert": false,
    "sinon": false,
    "_": false,
    "angular": false,
    "window": false,
    "__DEV__": false,
    "StripeCheckout": false,
    "__PROD__": false,
    "__TEST__": false,
    "__STAGING__": false,
    "__SENTRY_EDVISOR_WEB_CLIENT_PUBLIC_DSN__": false,
    "__INTERCOM_API_ID___": false,
    "__API_URL__": false,
    "__STRIPE_PUBLISHABLE_API_KEY__": false,
    "__STRIPE_CONNECT_KEY__": false,

    "document": false,
    "delete": false,
    "FormData": false,
    "getComputedStyle": false,
    "Pikaday": false,
    "requestAnimationFrame": false,
    "inject": false,
    "expect": false,
    "it": false,
    "describe": false,
    "protractor": false,
    "by": false,
    "exports": false,
    "element": false,
    "elements": false,
    "browser": false,
    "__dirname": false,
    "require": false
  }
}
```
**What did you do? Please include the actual source code causing the issue.**
destructure using the same name 
```javascript
const gatherPromotions = ({quoteOption: {course, promotions, ...quoteOption}, ...rest}) => ({
})
```

**What did you expect to happen?**
No errors to occures
**What actually happened? Please include the actual, raw output from ESLint.**
Eslint explodes with
```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at EventEmitter.checkDestructured (/Users/mika/n/lib/node_modules/eslint/lib/rules/no-useless-rename.js:94:38)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (/Users/mika/n/lib/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/mika/n/lib/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/Users/mika/n/lib/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (/Users/mika/n/lib/node_modules/eslint/lib/eslint.js:905:36)
    at Controller.__execute (/Users/mika/n/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/mika/n/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (/Users/mika/n/lib/node_modules/eslint/lib/util/traverser.js:36:33)```
```

### Note
This works perfectly fine in the [babel REPL](https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Cstage-2%2Cstage-3&code=const%20gatherPromotions%20%3D%20(%7BquoteOption%3A%20%7Bcourse%2C%20promotions%2C%20...quoteOption%7D%2C%20...rest%7D)%20%3D%3E%20(%7B%0A%7D))  and removing the `no-useless-rename` rule stops the error

**Comment by mysticatea** [comment]
Thank you for this issue.

This has been fixed in v2.12.0 (bb69380dd1fc31d98ccc7f41483117375ce22a84).
