### ISSUE TITLE
2.13 regression: no-multiple-empty-lines breaks on files without line breaks

### ISSUE THREAD

**Issue by strawbrary** [eslint/eslint#6449]
**What version of ESLint are you using?**
2.13.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
```js
{
  "rules": {
    "no-multiple-empty-lines": [2, { max: 2, maxEOF: 1 }]
  }
}
```

**What did you do? Please include the actual source code causing the issue.**
Run eslint against a file with no line breaks.
```js
var a = 5;
```

**What did you expect to happen?**
Run without error

**What actually happened? Please include the actual, raw output from ESLint.**
```
Cannot read property 'length' of null
TypeError: Cannot read property 'length' of null
    at /Users/strawbrary/projects/chell/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:101:47
    at Array.forEach (native)
    at EventEmitter.checkBlankLines (/Users/strawbrary/projects/chell/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:100:23)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.leaveNode (/Users/strawbrary/projects/chell/node_modules/eslint/lib/util/node-event-generator.js:49:22)
    at CodePathAnalyzer.leaveNode (/Users/strawbrary/projects/chell/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:627:23)
    at CommentEventGenerator.leaveNode (/Users/strawbrary/projects/chell/node_modules/eslint/lib/util/comment-event-generator.js:110:23)
    at Controller.traverser.traverse.leave (/Users/strawbrary/projects/chell/node_modules/eslint/lib/eslint.js:908:36)
    at Controller.__execute (/Users/strawbrary/projects/chell/node_modules/estraverse/estraverse.js:397:31)
```

Submitted #6451 as a fix.

**Comment by nzakas** [comment]
Yikes, sorry about that.
