### ISSUE TITLE
eslint --init Error

### ISSUE THREAD

**Issue by damarnez** [eslint/eslint#6476]
**What version of ESLint are you using?**
v2.13.0
**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**

**What did you do? Please include the actual source code causing the issue.**
eslint --init
**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

? How would you like to configure ESLint? Use a popular style guide
? Which style guide do you want to follow? AirBnB
? What format do you want your config file to be in? JSON
Could not find a package.json file. Run 'npm init' to create one.
Error: Could not find a package.json file. Run 'npm init' to create one.
    at check (/usr/local/lib/node_modules/eslint/lib/util/npm-util.js:76:15)
    at Object.checkDevDeps (/usr/local/lib/node_modules/eslint/lib/util/npm-util.js:124:12)
    at installModules (/usr/local/lib/node_modules/eslint/lib/config/config-initializer.js:86:29)
    at getConfigForStyleGuide (/usr/local/lib/node_modules/eslint/lib/config/config-initializer.js:289:5)
    at .completed (/usr/local/lib/node_modules/eslint/lib/config/config-initializer.js:353:26)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/eslint/node_modules/inquirer/lib/ui/prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/eslint/node_modules/rx-lite/rx.lite.js:1550:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/eslint/node_modules/rx-lite/rx.lite.js:1489:14)
    at Subject.Rx.Subject.addProperties.onCompleted (/usr/local/lib/node_modules/eslint/node_modules/rx-lite/rx.lite.js:5871:19)
    at Subject.tryCatcher (/usr/local/lib/node_modules/eslint/node_modules/rx-lite/rx.lite.js:63:31)

**Comment by kaicataldo** [comment]
Might be a silly question, but are you sure you're in a project directory that has a package.json?

**Comment by platinumazure** [comment]
When you create a config based on a popular style guide, ESLint attempts to npm install the configuration you're extending. In order to do that, we need to check and see what has already been installed. We could probably handle this better (or at least have a clearer error message), but the workaround is to run `npm init` first, before running `eslint --init`

**Comment by ilyavolodin** [comment]
I think we should add a clearer error message in this case. We can't do much without package.json, but we can guide users to create one.

**Comment by kaicataldo** [comment]
I wonder if we can throw this warning earlier in the flow so that users don't get a few questions in before it blows up on them

**Comment by ilyavolodin** [comment]
We could add a check for package.json as soon as you answered first question (popular style guide).

**Comment by kaicataldo** [comment]
I know it's not accepted yet, but took a crack at what a solution could look like

**Comment by nzakas** [comment]
Seems pretty straightforward 👍
