### ISSUE TITLE
error in the generator-star-spacing rule

### ISSUE THREAD

**Issue by romeovs** [eslint/eslint#6528]
**What version of ESLint are you using?**
```
$ node_modules/.bin/eslint -v                                                                                                                                     
v2.13.1
```
**What parser (default, Babel-ESLint, etc.) are you using?**
`babel-eslint`
**Please show your full configuration:**

```
parser: babel-eslint
extends: standard
plugins:
  - flowtype

env:
  node: true
  mocha: true

rules:
  # allow dangling comma
  no-comma-dangle: off
  comma-dangle:
    - error
    - always-multiline

  flowtype/space-after-type-colon:
    - error
    - always

  flowtype/space-before-type-colon:
    - error
    - always

  no-var:
    - error

  no-console:
    - error
```

**What did you do? Please include the actual source code causing the issue.**
`$ eslint src/`
**What did you expect to happen?**
No error to happen, just lint.

**What actually happened? Please include the actual, raw output from ESLint.**

Got the error 
```
/Users/romeo/code/go/foo/node_modules/eslint/lib/rules/generator-star-spacing.js:69
            while (token.value !== "*") {
                        ^

TypeError: Cannot read property 'value' of undefined
    at getStarToken (/Users/romeo/code/go/foo/node_modules/eslint/lib/rules/generator-star-spacing.js:69:25)
    at EventEmitter.checkFunction (/Users/romeo/code/go/foo/node_modules/eslint/lib/rules/generator-star-spacing.js:125:29)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/Users/romeo/code/go/foo/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/romeo/code/go/foo/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/Users/romeo/code/go/foo/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (/Users/romeo/code/go/foo/node_modules/eslint/lib/eslint.js:905:36)
    at Controller.__execute (/Users/romeo/code/go/foo/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/romeo/code/go/foo/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
```

**Comment by vitorbal** [comment]
Thanks, @romeovs! The generator-star-spacing rule doesn't support generators, so you should use the generator-star-spacing that is provided by the [eslint-plugin-babel](https://github.com/babel/eslint-plugin-babel).
If you have any other questions feel free to drop by our [Gitter chatroom](https://gitter.im/eslint/eslint) and we will be happy to help with anything!

**Comment by romeovs** [comment]
that fixes it!

**Comment by vitorbal** [comment]
Glad to hear! :)

**Comment by michaelficarra** [comment]
@vitorbal What made you think @romeovs was using an async function?

@romeovs Please post the actual source code, as requested in the template that you partially filled out.

**Comment by romeovs** [comment]
I was using async functions to be clear.
The actual codebase I'm running this on so it's hard to tell where the problem originates from.

I can reproduce the bug on this snippet:
```
async function derp () {
  console.log('never gonna give you up')
}
```

but it does not occur on this one:
```
function derp () {
  console.log('never gonna let you down')
}
```

**Comment by vitorbal** [comment]
@michaelficarra you're totally right, I just assumed it was since we've had a couple of similar issues these past weeks. Thanks for double-checking!

**Comment by ljharb** [comment]
Since async/await is now stage 4, should this be reopened?

**Comment by ilyavolodin** [comment]
@ljharb It's still not implemented in Acorn/Espree, so I think we should hold off till we can actually implant this change.

**Comment by ljharb** [comment]
Sounds good! Linking to https://github.com/ternjs/acorn/issues/441 and https://github.com/eslint/espree/issues/287
