### ISSUE TITLE
eslint throws if package.json is in UTF-8 with BOM

### ISSUE THREAD

**Issue by vsemozhetbyt** [eslint/eslint#6556]
**What version of ESLint are you using?**
2.13.1
**What parser (default, Babel-ESLint, etc.) are you using?**
default

**What did you do?...**
I've checked a `.js` file in the NW.js project directory with `package.json` in UTF-8 with BOM (there are no eslint settings in this `package.json`).

**What did you expect to happen?**
Output from eslint according to `.eslintrc.json` in some ancestor directory.

**What actually happened? Please include the actual, raw output from ESLint.**
```
Cannot read config file: ...\package.json
Error: Cannot read config file: ...\package.json
Error: Unexpected token ﻿ in JSON at position 0
SyntaxError: Cannot read config file: ...\package.json
Error: Cannot read config file: ...\package.json
Error: Unexpected token ﻿ in JSON at position 0
    at Object.parse (native)
    at loadJSONConfigFile (...\node_modules\eslint\lib\config\config-file.js:121:21)
    at loadPackageJSONConfigFile (...\node_modules\eslint\lib\config\config-file.js:179:16)
    at loadConfigFile (...\node_modules\eslint\lib\config\config-file.js:208:26)
    at Object.load (...\node_modules\eslint\lib\config\config-file.js:499:18)
    at loadConfig (...\node_modules\eslint\lib\config.js:64:33)
    at getLocalConfig (...\node_modules\eslint\lib\config.js:126:23)
    at Config.getConfig (...\node_modules\eslint\lib\config.js:227:22)
    at processText (...\node_modules\eslint\lib\cli-engine.js:223:27)
    at processFile (...\node_modules\eslint\lib\cli-engine.js:298:18)
```

If I resave the `package.json` in UTF-8 without BOM, all is OK.

**Comment by platinumazure** [comment]
This seems like it shouldn't throw. Unless JSON is very explicitly not allowed to be encoded in UTF8 with BOM, I think we should see if we can work around this.

**Comment by gyandeeps** [comment]
@vsemozhetbyt Can you read the file using nodejs `readFile` function outside of Eslint?
Can you plz try it. Thanks

**Comment by vsemozhetbyt** [comment]
@platinumazure NW.js has no problem with this JSON. I think this is not concerned JSON format by itself, but IO file preprocessing.

@gyandeeps Should not Eslint strip BOM before calling `JSON.parse` on string from a Unicode file?

**Comment by mysticatea** [comment]
Yeah.
We are stripping BOM from source code.
We should strip BOM from config files as same as that.
