### ISSUE TITLE
./node_modules/.bin/eslint doesn't work

### ISSUE THREAD

**Issue by TheKnarf** [eslint/eslint#6664]
**What version of ESLint are you using?**
v3.0.1

**Node version**
```
$ node --version
v5.3.0
```

**OS**
`System Version: OS X 10.11.5 (15F34)`

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
```
{
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaFeatures": {
            "experimentalObjectRestSpread": true,
            "jsx": true
        },
        "sourceType": "module"
    },
    "plugins": [
        "react"
    ],
    "rules": {
        "linebreak-style": ["error","unix"],
        "quotes": ["error","single"],
        "semi": ["error", "always"],
        "strict": ["error", "never"],
        "react/jsx-uses-react": 2,
        "react/jsx-uses-vars": 2,
        "react/react-in-jsx-scope": 2
    }
}
```

**What did you do?**
```
$ ./node_modules/.bin/eslint

module.js:328
    throw err;
    ^

Error: Cannot find module '../lib/cli'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/fl-macbook-retina/Dropbox (Personal)/Projects/intrahs/node_modules/.bin/eslint:30:11)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
```

**Description of problem**
Running `./node_modules/.bin/eslint` does not work and gives me the error over.
However running `./node_modules/eslint/bin/eslint.js` works perfectly.

**Comment by TheKnarf** [comment]
Nuking the `node_modules` folder, updating npm (`npm i -g npm`) and reinstalling (`npm install`) fixed the issue.
