### ISSUE TITLE
Cannot find module config

### ISSUE THREAD

**Issue by azat-io** [eslint/eslint#6717]
Hi there!

I'm using ESLint `3.1.1 v.` and `eslint-cofig-standard#5.3.5`.

Here is my `.eslintrc` file:

```
{
  "extends": "standard"
}
```

When I'm trying to use it via console I get an error:

```bash
azat@pc:~/git/shri-msk-2016-multimedia$ eslint gulpfile.babel.js

Cannot find module 'eslint-config-standard'
Referenced from: /home/azat/git/shri-msk-2016-multimedia/.eslintrc
Error: Cannot find module 'eslint-config-standard'
Referenced from: /home/azat/git/shri-msk-2016-multimedia/.eslintrc
    at Object.ModuleResolver.resolve (/usr/local/lib/node_modules/eslint/lib/util/module-resolver.js:77:19)
    at resolve (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:475:33)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:492:24)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:388:36
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:365:28)
    at Object.load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:527:22)
    at loadConfig (/usr/local/lib/node_modules/eslint/lib/config.js:67:33)
    at getLocalConfig (/usr/local/lib/node_modules/eslint/lib/config.js:129:23)
    at Config.getConfig (/usr/local/lib/node_modules/eslint/lib/config.js:230:22)
```

What's wrong?

**Comment by platinumazure** [comment]
Hi @azat-io, can you please confirm that you have installed `eslint-config-standard` globally?

If you want to run ESLint with local project dependencies (i.e., you ran `npm install --save-dev eslint-config-standard` without a `-g` flag), then you need to run ESLint locally as well.

From a shell:

```shell
azat@pc:~/git/shri-msk-2016-multimedia$ ./node_modules/.bin/eslint gulpfile.babel.js
```

Or you can simplify that by creating an npm script:

(package.json)
```json
{
    "scripts": {
        "lint": "eslint gulpfile.babel.js"
    }
}
```

(on the shell)
```shell
azat@pc:~/git/shri-msk-2016-multimedia$ npm run lint
```

When specified in npm scripts, npm will look for a local ESLint if one is installed.

------

In general, globally installed ESLint must be paired with globally installed configurations and/or plugins, and locally installed ESLint must be used to get at locally installed configurations and/or plugins.

Hope this helps!

**Comment by platinumazure** [comment]
Also, you may wish to review our [Installation and Usage](https://github.com/eslint/eslint/blob/master/README.md#installation-and-usage) guide in our project README. Thanks!

**Comment by azat-io** [comment]
It works locally and not works globally:

```bash
azat@pc:~/git/shri-msk-2016-multimedia$ eslint -v

v3.1.1

azat@pc:~/git/shri-msk-2016-multimedia$ ./node_modules/.bin/eslint gulpfile.babel.js

/home/azat/git/shri-msk-2016-multimedia/gulpfile.babel.js
  27:8  error  'test' is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)

azat@pc:~/git/shri-msk-2016-multimedia$ eslint gulpfile.babel.js

Cannot find module 'eslint-config-standard'
Referenced from: /home/azat/git/shri-msk-2016-multimedia/.eslintrc
Error: Cannot find module 'eslint-config-standard'
Referenced from: /home/azat/git/shri-msk-2016-multimedia/.eslintrc
    at Object.ModuleResolver.resolve (/usr/local/lib/node_modules/eslint/lib/util/module-resolver.js:75:19)
    at resolve (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:479:33)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:496:24)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:392:36
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:363:28)
    at Object.load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:530:22)
    at loadConfig (/usr/local/lib/node_modules/eslint/lib/config.js:64:33)
    at getLocalConfig (/usr/local/lib/node_modules/eslint/lib/config.js:136:23)
    at Config.getConfig (/usr/local/lib/node_modules/eslint/lib/config.js:263:22)
```

**Comment by platinumazure** [comment]
Awesome-- that means you should run ESLint locally in order for it to find your locally-installed `eslint-config-standard`. As I noted earlier, you can make this a little easier by making an npm script (but that's not required).

Closing as I believe the question has been answered. Please reopen if I have missed anything. Thanks!
