### ISSUE TITLE
[Bug] Async function declaration

### ISSUE THREAD

**Issue by kobezzza** [eslint/eslint#6773]
eslint 3.1.1
"parser": "babel-eslint"

```js
export async function main() {

}
```

Output:

```
Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
    at getStarToken (C:\Users\kobez\Documents\dev\TravelChat\node_modules\eslint\lib\rules\generator-star-spacing.js:68:25)
    at EventEmitter.checkFunction (C:\Users\kobez\Documents\dev\TravelChat\node_modules\eslint\lib\rules\generator-star-spacing.js:123:29)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (C:\Users\kobez\Documents\dev\TravelChat\node_modules\eslint\lib\util\node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (C:\Users\kobez\Documents\dev\TravelChat\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (C:\Users\kobez\Documents\dev\TravelChat\node_modules\eslint\lib\util\comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (C:\Users\kobez\Documents\dev\TravelChat\node_modules\eslint\lib\eslint.js:902:36)
    at Controller.__execute (C:\Users\kobez\Documents\dev\TravelChat\node_modules\eslint\node_modules\estraverse\estraverse.js:397:31)
    at Controller.traverse (C:\Users\kobez\Documents\dev\TravelChat\node_modules\eslint\node_modules\estraverse\estraverse.js:501:28)

Process finished with exit code 1
```

With

```js
export const main = async () => {

};
```

All fine.

**Comment by mysticatea** [comment]
Thank you for this issue.

Async functions are not a part of JavaScript yet (it's a proposal).
You can use [babel-eslint] and [eslint-plugin-babel] in order to use such features.

Especially, you can use `babel/generator-star-spacing` rule for that error.

[babel-eslint]: https://github.com/babel/babel-eslint#readme
[eslint-plugin-babel]: https://github.com/babel/eslint-plugin-babel#readme

**Comment by kobezzza** [comment]
@babel-eslint i always use babel-eslint, and ESlint crashes. Toggle off generator-star-spacing fixed it, thanks.

**Comment by adiachenko** [comment]
@mysticatea Async functions proposal has been [moved to stage 4](https://github.com/tc39/proposals/commit/e8c03544751b071b973064ef7d437a34ac6752cd). I don't know if I'm correct but I seem to have read somewhere that you may support stage 4 proposals.

**Comment by mysticatea** [comment]
@adiachenko It happened after this issue. :smile:

Now we are working for supports of the new stage 4 features.
We need several steps.

1. Acorn, the base of our parser,  supports those: https://github.com/ternjs/acorn/issues/441
2. Our parser supports those: https://github.com/eslint/espree/issues/287
3. Then, ESLint rules support those.  
   Actually, wrong AST nodes of `babel-eslint` cause the error, I think. So we cannot fix rules before our parser supports those.

**Comment by hzoo** [comment]
@mysticatea https://github.com/babel/babel-eslint/issues/350
