### ISSUE TITLE
Issue with command line interface after installing

### ISSUE THREAD

**Issue by ankitr** [eslint/eslint#6809]
**What version are you using?**
I'm using version 3.2.0.

**What did you do?**
I installed eslint with `npm install -g eslint`. After the installation, I ran `eslint --init` as suggested in the Getting Started guide.

**What happened?**
I got an error with this output:
```
/usr/local/lib/node_modules/eslint/lib/cli.js:18
let fs = require("fs"),
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/eslint/bin/eslint.js:29:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```
It turns out that the same thing happened whenever I ran any command with `eslint`.

**What did you expect to happen?**
Normal `eslint --init` behavior.

**Comment by gyandeeps** [comment]
Make sure you use NodeJS version >= 4 since we require that for Eslint 3.0
I hope this helps.

**Comment by ankitr** [comment]
That fixed it! Thanks!
