### ISSUE TITLE
ESLint crashed: Failed to load plugin react

### ISSUE THREAD

**Issue by stoplion** [eslint/eslint#6859]
Eslint crashes in Sublime Text 

Eslint `v3.2.2`
`"eslint-plugin-react": "^6.0.0",`

```
SublimeLinter: eslint output:
Failed to load plugin react: undefined is not a function
TypeError: Failed to load plugin react: undefined is not a function
    at Object.<anonymous> (/Users/me/Code/myproject/node_modules/eslint-plugin-react/index.js:66:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.module.exports.load (/Users/me/Code/myproject/node_modules/eslint/lib/config/plugins.js:114:26)
    at Array.forEach (native)
    at Object.module.exports.loadAll (/Usersme/Code/myproject/node_modules/eslint/lib/config/plugins.js:136:21) ```

**Comment by platinumazure** [comment]
Does this happen on the command line?

If so, the problem is with eslint-plugin-react. If not, the problem is with sublime linter. Either way, not sure it's an ESLint issue yet.

**Comment by stoplion** [comment]
Yes you are correct. It does not happen for the command line.
