### ISSUE TITLE
TypeError after upgrading from 3.0.0 to 3.3.1: "Cannot read property 'value' of undefined"

### ISSUE THREAD

**Issue by callumlocke** [eslint/eslint#6929]
**What version of ESLint are you using?**

3.3.1

**What parser (default, Babel-ESLint, etc.) are you using?**

babel-eslint

**Please show your full configuration:**

```yml
root: true
parser: babel-eslint
extends: airbnb/base
rules:
  brace-style: [2, stroustrup, { allowSingleLine: false }]
  no-console: 0
  prefer-template: 0
  global-require: 0
  no-underscore-dangle: 0
```

**What did you do? Please include the actual source code causing the issue.**

Upgraded eslint from 3.0.0 to 3.3.1, along with upgrading some other deps, then ran `npm install`. Then I ran `eslint .` in the project.

[This commit](https://github.com/callumlocke/esbox/pull/104/commits/b4b3b310d1d6f8e5c19fad1acfa053b47458d68f) shows all the dep updates. Before this commit, `eslint .` worked. Now it fails.

**What did you expect to happen?**

I expected running `eslint .` in the project would work as normal (or possibly fail with a new linting error).

**What actually happened? Please include the actual, raw output from ESLint.**

I got an uncaught TypeError coming from inside eslint:

```
Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
    at getStarToken (/home/travis/build/callumlocke/esbox/node_modules/eslint/lib/rules/generator-star-spacing.js:68:25)
    at EventEmitter.checkFunction (/home/travis/build/callumlocke/esbox/node_modules/eslint/lib/rules/generator-star-spacing.js:123:29)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/home/travis/build/callumlocke/esbox/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/home/travis/build/callumlocke/esbox/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/home/travis/build/callumlocke/esbox/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (/home/travis/build/callumlocke/esbox/node_modules/eslint/lib/eslint.js:895:36)
    at Controller.__execute (/home/travis/build/callumlocke/esbox/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/home/travis/build/callumlocke/esbox/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
```

(This output is from [travis](https://travis-ci.org/callumlocke/esbox/jobs/153230324), but I get the same error locally too.)

**Comment by ilyavolodin** [comment]
@callumlocke Could you try the same code that fails with default parser (instead of `babel-eslint`)?

**Comment by alberto** [comment]
@callumlocke are you running on node >= 4?

**Comment by mysticatea** [comment]
I guess this is same as #6274.

**Comment by HenriBeck** [comment]
It works with the default parser, but not with babel-eslint. Though then it reports a bunch of other errors when you are using experimental features like async/await.

**Comment by HenriBeck** [comment]
Turning off the rule 'generator-star-spacing' fixes this issue, so you can use the babel-eslint parser again

**Comment by ilyavolodin** [comment]
In that case, it's a problem with `babel-eslint` parser. You should open an issue there.
Closing, as there's nothing we can do about third-party parser errors.
