### ISSUE TITLE
valid-jsdoc crashes with a TypeError when given an invalid parameter type

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#7184]
**Tell us about your environment**

* **ESLint Version:** master
* **Node Version:** 6.6.0
* **npm Version:** 3.10.3

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

```json
{
  "rules": {
    "valid-jsdoc": [2, {"preferType": {"foo": "bar"}}]
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
/**
* @param {{gibberish}} bar - the parameter
*/
function foo(bar) { }
```

**What did you expect to happen?**

I expected ESLint to either report a JSDoc issue or exit without reporting an error.

**What actually happened? Please include the actual, raw output from ESLint.**

ESLint threw a TypeError:

```
TypeError: Cannot read property 'name' of null
    at getCurrentExpectedTypes (path/to/eslint/lib/rules/valid-jsdoc.js:153:21)
    at validateType (path/to/eslint/lib/rules/valid-jsdoc.js:195:39)
    at Array.forEach (native)
    at validateType (path/to/eslint/lib/rules/valid-jsdoc.js:201:22)
    at path/to/eslint/lib/rules/valid-jsdoc.js:330:25
    at Array.forEach (native)
    at EventEmitter.checkJSDoc (path/to/eslint/lib/rules/valid-jsdoc.js:255:28)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.leaveNode (path/to/eslint/lib/util/node-event-generator.js:49:22)
```

**Comment by kaicataldo** [comment]
Rules should definitely never throw an error. I'll look into this.
