### ISSUE TITLE
Unexpected token ( in lib/cli.js:123

### ISSUE THREAD

**Issue by MathRobin** [eslint/eslint#7257]
* **ESLint Version:** 3.6.1
* **Node Version:** 6.4.0
* **npm Version:** 3.10.3

**What parser (default, Babel-ESLint, etc.) are you using?** default

**What did you do? Please include the actual source code causing the issue.**

```shell
node --harmony ./node_modules/eslint/bin/eslint.js --stdin --quiet -c ./.eslintrc
```

**What actually happened? Please include the actual, raw output from ESLint.**

```shell
Error:/bin/bash: Validating JavaScript:
/var/www/api/node_modules/eslint/lib/cli.js:123
    execute(args, text) {
           ^
SyntaxError: Unexpected token (
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/api/node_modules/eslint/bin/eslint.js:29:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
	ESLint Failed: app/utils/api.keywords.js
```

**Comment by mysticatea** [comment]
Thank you for this issue.

Could you ensure your node version?
That error message is the message which is shown if node 0.12 executes ESLint.

**Comment by MathRobin** [comment]
I have done node - v in my terminal and got this version number :s

**Comment by MathRobin** [comment]
Tried nodejs -v and got 0.10. I guess my client uses nodejs and not node... hell. After update of both to node 6.6.0, verything works great. Thanks !
