### ISSUE TITLE
Bug: The prop value with an expression type of UpdateExpression could not be resolved.

### ISSUE THREAD

**Issue by joscha** [eslint/eslint#7341]
**Tell us about your environment**

If you check out [this branch](https://bitbucket.org/atlassian/atlaskit/pull-requests/689/chore-update-eslint-to-v3/diff), and run
```
npm install
npm run lint
```

you can see the error.

* **ESLint Version:**
3.7.1
* **Node Version:**
6.5.0
* **npm Version:**
3.10.3

**What parser (default, Babel-ESLint, etc.) are you using?**

eslint w/ plugins

**Please show your full configuration:**

```js
const path = require('path');

module.exports = {
  root: true,
  extends: 'ak-base',
  settings: {
    'import/resolver': {
      webpack: {
        config: path.join(__dirname, 'build', 'webpack', 'development.js'),
      },
    },
  },
};
```

**What did you do? Please include the actual source code causing the issue.**

 I am not sure which file causes the issue - the command that produces the error is:

```console
eslint --color --format 'node_modules/eslint-friendly-formatter' . --ext .js,.jsx
```

which worked fine in eslint 2.x

**What did you expect to happen?**

My code to be linted

**What actually happened? Please include the actual, raw output from ESLint.**

```
The prop value with an expression type of UpdateExpression could not be resolved.
  Please file issue to get this fixed immediately.
Error: The prop value with an expression type of UpdateExpression could not be resolved.
  Please file issue to get this fixed immediately.
    at Object.extractLiteral [as JSXExpressionContainer] (/Users/jfeth/dev/atlaskit/node_modules/jsx-ast-utils/lib/values/expressions/index.js:173:11)
    at getLiteralValue (/Users/jfeth/dev/atlaskit/node_modules/jsx-ast-utils/lib/values/index.js:65:35)
    at extractValue (/Users/jfeth/dev/atlaskit/node_modules/jsx-ast-utils/lib/getPropValue.js:24:12)
    at getLiteralPropValue (/Users/jfeth/dev/atlaskit/node_modules/jsx-ast-utils/lib/getPropValue.js:56:10)
    at EventEmitter.JSXAttribute (/Users/jfeth/dev/atlaskit/node_modules/eslint-plugin-jsx-a11y/lib/rules/aria-proptypes.js:78:58)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/Users/jfeth/dev/atlaskit/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/jfeth/dev/atlaskit/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/Users/jfeth/dev/atlaskit/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (/Users/jfeth/dev/atlaskit/node_modules/eslint/lib/eslint.js:898:36)
```

**Comment by joscha** [comment]
It seems as if https://github.com/evcohen/jsx-ast-utils/ doesn't know the JSX `UpdateExpression` type. Adding `UpdateExpression: noop` here: https://github.com/evcohen/jsx-ast-utils/blob/master/src/values/expressions/index.js#L67 seems to make eslint run, but I can't tell if that's the right way to fix it /cc @evcohen

**Comment by joscha** [comment]
`jsx-ast-utils` version `1.3.2` fixes this.
