### ISSUE TITLE
Unable to initilize 

### ISSUE THREAD

**Issue by thorerik** [eslint/eslint#7801]
**Tell us about your environment**

* **ESLint Version:**
eslint@3.12.2
* **Node Version:**
v7.1.0
* **npm Version:**
3.10.9
* **OS:**
Windows 10 x64

**What parser (default, Babel-ESLint, etc.) are you using?**
default probably
**Please show your full configuration:**

N/A

**What did you do? Please include the actual source code causing the issue.**

```
 .\node_modules\.bin\eslint.cmd --init
```

**What did you expect to happen?**
Initilize a base configuration ref http://eslint.org/docs/user-guide/getting-started

**What actually happened? Please include the actual, raw output from ESLint.**
```
> .\node_modules\.bin\eslint.cmd --init
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:683:19)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at Console.log (console.js:43:16)
    at process.once.err (C:\Users\thor\src\bf\bfx-dashboard\node_modules\eslint\bin\eslint.js:50:17)
    at process.g (events.js:292:16)
    at emitOne (events.js:96:13)
```

**Comment by not-an-aardvark** [comment]
I think this is caused by https://github.com/nodejs/node/issues/9542, which is a socket bug in Node 7.1.0 that occurs on Windows. If you upgrade to Node 7.2.0 or later, the issue should be fixed.

**Comment by thorerik** [comment]
That was it, thanks!
