### ISSUE TITLE
eslint --init throws: TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by gfx** [eslint/eslint#7860]
`eslint --init` fails when my enviroment:

* ESLint v3.12.2
* NodeJS v6.9.2
* npm 3.10.8

with the answers:

```
$ eslint --init
? How would you like to configure ESLint? Inspect your JavaScript file(s)
? Which file(s), path(s), or glob(s) should be examined? client/
? What format do you want your config file to be in? JSON
? Are you using ECMAScript 6 features? Yes
? Are you using ES6 modules? Yes
? Where will your code run? Browser
? Do you use CommonJS? No
? Do you use JSX? Yes
? Do you use React? Yes
Determining Config: 23% [=======-----------------------] 1.0s elapsed, eta 3.3s Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at lintResults.forEach.result (~/.ghq/github.com/proj/node_modules/eslint/lib/config/autoconfig.js:301:60)
    at Array.forEach (native)
    at ruleSets.forEach.ruleSet (~/.ghq/github.com/proj/node_modules/eslint/lib/config/autoconfig.js:296:29)
    at Array.forEach (native)
    at filenames.forEach.filename (~/.ghq/github.com/proj/node_modules/eslint/lib/config/autoconfig.js:292:22)
    at Array.forEach (native)
    at Registry.lintSourceCode (~/.ghq/github.com/proj/node_modules/eslint/lib/config/autoconfig.js:287:19)
    at configureRules (~/.ghq/github.com/proj/node_modules/eslint/lib/config/config-initializer.js:148:25)
    at processAnswers (~/.ghq/github.com/proj/node_modules/eslint/lib/config/config-initializer.js:248:18)
    at inquirer.prompt.err [as completed] (~/.ghq/github.com/proj/node_modules/eslint/lib/config/config-initializer.js:418:30)
```

with a patch to `autoconfig.js`:

```diff
# line 301
+                    console.log(lintedRegistry.rules[result.ruleId]);
+                    console.log(result.ruleId, ruleSetIdx);
                     if (lintedRegistry.rules[result.ruleId][ruleSetIdx]) {
                         lintedRegistry.rules[result.ruleId][ruleSetIdx].errorCount += 1;
                     }
```

it shows:

```
undefined
import/extensions 0
```

Seams `lintedRegistry.rules["import/extensions"]` is missing.

**Comment by alberto** [comment]
@gfx any idea how `eslint-plugin-import` got installed and enabled there? I can't reproduce this

**Comment by gfx** [comment]
@alberto I just add `eslint-plugin-import` to `devDependencies` in package.json and enable it in .elsintrc.

**Comment by nzakas** [comment]
@ianvs any idea why a plugin rule would show up in auto config?

**Comment by IanVS** [comment]
I think that one of his files has an inline config that is enabling `import/extensions`, and the code is not properly guarded.  It guards against core rules, as a result of the fix to https://github.com/eslint/eslint/issues/5992, but we also need to check for plugin rules.  I can fix this quickly.
