### ISSUE TITLE
no-extra-boolean-cast autofixer handles some Boolean() calls incorrectly

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#7977]
**Tell us about your environment**

* **ESLint Version:** master
* **Node Version:** 7.4.0
* **npm Version:** 4.0.5

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

```yml
rules:
  no-extra-boolean-cast: error
parserOptions:
  ecmaVersion: 2015
```

**What did you do? Please include the actual source code causing the issue.**

I ran `eslint theFile.js --fix` on three different files:

```js
// Case 1
!Boolean(...foo);
```

```js
// Case 2
!Boolean(foo, bar());
```

```js
// Case 3
!Boolean();
```

**What did you expect to happen?**

I expected the syntax of the files to be valid after autofixing

**What actually happened? Please include the actual, raw output from ESLint.**

In the first two files, the code was autofixed to

```js
// Case 1
!...foo;
```

```js
// Case 2
!foo;
```

An error was thrown when running the command on the third file:

```
TypeError: Cannot read property 'type' of undefined
    at Object.getPrecedence (/path/to/eslint/lib/ast-utils.js:620:21)
    at Object.fix (/path/to/eslint/lib/rules/no-extra-boolean-cast.js:103:42)
    at RuleContext.report (/path/to/eslint/lib/rule-context.js:127:34)
    at EventEmitter.CallExpression (/path/to/eslint/lib/rules/no-extra-boolean-cast.js:97:29)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/path/to/eslint/lib/util/node-event-generator.js:39:22)
    at CodePathAnalyzer.enterNode (/path/to/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/path/to/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.enter (/path/to/eslint/lib/eslint.js:928:36)

```

The first autofixed line is a syntax error, and the second autofixed line changes the behavior of the code (it no longer calls `bar()`).

To fix this, I think we need to avoid doing an autofix for `no-extra-boolean-cast` in the following cases:

* `Boolean` is called with more than one argument
* `Boolean` is called with a spread element as the first argument
* `Boolean` is called with no arguments. (Alternatively, we could just fix `!Boolean()` to `true`.)

**Comment by ljharb** [comment]
Why would anyone call `Boolean` with more than one argument?

`Boolean()` should be equivalent to `Boolean(undefined)`, in other words, `false`.

**Comment by not-an-aardvark** [comment]
> Why would anyone call Boolean with more than one argument?

¯\\\_(ツ)_/¯

> `Boolean()` should be equivalent to `Boolean(undefined)`, in other words, `false`.

Yes, but the rule only activates when the expression is negated to `!Boolean()` (since the `Boolean` call is then a useless cast), which would be `true`.
