### ISSUE TITLE
Build broken with Node 7.7.1

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#8177]
**Tell us about your environment**

* **ESLint Version:** master
* **Node Version:** 7.7.1
* **npm Version:** 4.1.2

**What did you do? Please include the actual source code causing the issue.**

1. Clone the eslint repo and run `npm install` as usual
1. Run `npm test`

**What did you expect to happen?**

I expected the tests to pass.

**What actually happened? Please include the actual, raw output from ESLint.**

Two tests failed:

```
  1) Config "after each" hook:
     Uncaught TypeError: callback is not a function
      at node_modules/mock-fs/lib/binding.js:39:9
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at Immediate._tickCallback (internal/process/next_tick.js:104:9)

  2) Config "before each" hook:
     TypeError: Cannot read property 'call' of undefined
```

Additionally, the coverage is lower than expected:

```
ERROR: Coverage for statements (93.92%) does not meet global threshold (99%)
ERROR: Coverage for branches (93.2%) does not meet global threshold (98%)
ERROR: Coverage for lines (93.97%) does not meet global threshold (99%)
ERROR: Coverage for functions (95.23%) does not meet global threshold (99%)
```

I haven't investigated this yet, but it seems like it has something to do with `mock-fs`.

[Example build](https://travis-ci.org/eslint/eslint/jobs/206892215)

**Comment by not-an-aardvark** [comment]
This is caused by https://github.com/tschaub/mock-fs/issues/197. I'm going to see if I can figure out a workaround.

**Comment by not-an-aardvark** [comment]
It looks like this issue will be fairly difficult to work around (short of skipping the failing tests altogether). I submitted a [patch](https://github.com/tschaub/mock-fs/pull/198) to mock-fs that fixes this issue, so hopefully everything will be fine and it will be merged soon. If it ends up taking too long, we could also skip the failing tests or temporarily depend on the commit with the fix instead of the package from npm.
