### ISSUE TITLE
constructor-super throws when it encounters nested loops

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#8248]
**Tell us about your environment**

* **ESLint Version:** master
* **Node Version:** 7.7.2
* **npm Version:** 4.1.2

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

```yml
rules:
    constructor-super: error
parserOptions:
    ecmaVersion: 2015
```

**What did you do? Please include the actual source code causing the issue.**

```js
class Foo extends Bar {
    constructor() {
        for (a in b) for (c in d);
    }
}
```

**What did you expect to happen?**

I expected ESLint to not crash.

**What actually happened? Please include the actual, raw output from ESLint.**

ESLint crashed.

```
TypeError: Cannot read property 'calledInSomePaths' of undefined
    at isCalledInSomePath (/path/to/eslint/lib/rules/constructor-super.js:132:63)
    at Array.some (native)
    at CodePath.funcInfo.codePath.traverseSegments.segment (/path/to/eslint/lib/rules/constructor-super.js:270:63)
    at CodePath.traverseSegments (/path/to/eslint/lib/code-path-analysis/code-path.js:208:30)
    at EventEmitter.onCodePathSegmentLoop (/path/to/eslint/lib/rules/constructor-super.js:263:35)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
    at CodePathAnalyzer.onLooped (/path/to/eslint/lib/code-path-analysis/code-path-analyzer.js:646:26)
    at makeLooped (/path/to/eslint/lib/code-path-analysis/code-path-state.js:191:15)
    at CodePathState.popLoopContext (/path/to/eslint/lib/code-path-analysis/code-path-state.js:1024:17)
```

It looks like when `CodePath#traverseSegments` is called, there is a segment where one of `segment.prevSegments` never triggered `onCodePathSegmentStart`. I'm not familiar with code path analysis, so I don't know whether this is a rule bug or a code path analysis bug in core.

@mysticatea, do you know where the issue might be coming from?

**Comment by mysticatea** [comment]
Oh, thank you for the report.
I'll investigate it.

**Comment by mysticatea** [comment]
I found the code path is broken if the body of a loop is the same kind loop.
I will fix this later.
