### ISSUE TITLE
generator-star-spacing rule raise "Cannot read property 'range' of null"  with babel-eslint parser

### ISSUE THREAD

**Issue by Crazymax11** [eslint/eslint#8301]
**Tell us about your environment**

* **ESLint Version:** 3.18.0
* **Node Version:** 6.6.0
* **npm Version:**  3.10.3

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint

**Please show your full configuration:** 

```
{
    "env": {
        "browser": true,
        "es6": true,
        "node": false,
        "mocha": false,
        "commonjs": true
    },
    "plugins": [
      "sort-class-members",
      "import"
    ],
    "extends": "eslint:recommended",
    "parser": "babel-eslint",
    "parserOptions": {
        "sourceType": "module"
    },
    "rules": {
        "curly": [
          "warn",
          "all"
        ],
        "operator-linebreak": [
          "warn",
          "after"
        ],
        "camelcase": [
          "off",
          {
            "properties": "always"
          }
        ],
        "max-len": [
          "warn",
          120
        ],
        "indent": [
          "warn",
          4,
          {
            "SwitchCase": 1
          }
        ],
        "quotes": [
          "warn",
          "single"
        ],
        "require-jsdoc": [
            "warn", {
                "require": {
                    "FunctionDeclaration": true,
                    "MethodDefinition": true,
                    "ClassDeclaration": true
                }
            }
        ],
        "no-multi-str": "warn",
        "no-mixed-spaces-and-tabs": "error",
        "no-trailing-spaces": "warn",
        "no-multiple-empty-lines": [
            "warn",
            {
                "max": 2,
                "maxEOF": 1
            }
        ],
        "space-unary-ops": [
          "warn",
          {
            "words": false,
            "nonwords": false
          }
        ],
        "no-with": "error",
        "brace-style": [
          "warn",
          "1tbs",
          {
            "allowSingleLine": true
          }
        ],
        "keyword-spacing": [
          "warn",
          {}
        ],
        "space-infix-ops": "warn",
        "space-before-blocks": [
          "warn",
          "always"
        ],
        "eol-last": "warn",
        "space-before-function-paren": [
          "warn",
          {
            "anonymous": "ignore",
            "named": "never"
          }
        ],
        "array-bracket-spacing": [
          "warn",
          "never"
        ],
        "space-in-parens": [
          "warn",
          "never"
        ],
        "key-spacing": [
          "warn",
          {
            "beforeColon": false,
            "afterColon": true
          }
        ],
        "linebreak-style": [
          "error",
          "unix"
        ],
        "comma-style": [
          "warn",
          "last"
        ],
        "no-empty": [
          "warn",
          {
            "allowEmptyCatch": true
          }
        ],
        "padded-blocks": [
            "warn",
            "never"
        ],
        "no-implicit-coercion": [
          "warn",
          {
            "boolean": true,
            "string": true,
            "number": true
          }
      ],
        "no-fallthrough": "warn",
        "no-console":[
            "warn"
        ],
        "no-unused-vars": "error",
        "no-unreachable": "error",
        "no-cond-assign": "warn",
        "no-extra-semi": "warn",
        "arrow-parens": "warn",
        "sort-class-members/sort-class-members": [
          "warn",
          {
            "order": [
              "[static-properties]",
              "[static-methods]",
              "[properties]",
              "[conventional-private-properties]",
              "constructor",
              "[methods]",
              "[conventional-private-methods]"
            ],
            "accessorPairPositioning": "getThenSet"
          }
        ],
        "prefer-const": "warn",
        "no-new-object": "error",
        "object-shorthand": "warn",
        "quote-props": ["error", "as-needed"],
        "no-array-constructor": "error",
        "array-callback-return": "error",
        "prefer-template": "warn",
        "template-curly-spacing": "warn",
        "no-useless-escape": "warn",
        "prefer-rest-params": "warn",
        "no-new-func": "error",
        "no-param-reassign": "error",
        "prefer-spread": "warn",
        "no-useless-constructor": "error",
        "no-dupe-class-members": "error",
        "no-duplicate-imports": "error",
        "import/first": "error",
        "import/no-webpack-loader-syntax": "error",
        "generator-star-spacing": "error",
        "dot-notation": "error",
        "no-undef": "error",
        "eqeqeq": "error",
        "no-nested-ternary": "error",
        "no-unneeded-ternary": "error",
        "spaced-comment": "error",
        "comma-dangle": ["warn", "never"],
        "semi": "error",
        "radix": "error",
        "no-var": "error"
    }
}
```

**.babelrc**
```
{
    "presets": ['es2015', 'es2016', 'es2017'],
    "plugins": ['transform-object-rest-spread', 'transform-async-to-generator', 'transform-class-properties']
}
```

**babel packages**
```
    "babel-core": "^6.18.2",
    "babel-eslint": "^6.1.2",
    "babel-loader": "^6.2.8",
    "babel-plugin-transform-async-to-generator": "^6.16.0",
    "babel-plugin-transform-class-properties": "^6.22.0",
    "babel-plugin-transform-object-rest-spread": "^6.19.0",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-polyfill": "^6.16.0",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-es2016": "^6.16.0",
    "babel-preset-es2017": "^6.16.0",
    "babel-runtime": "^6.18.0"
```

**What did you do? Please include the actual source code causing the issue.**

```
async function test() {
    console.log('hello world');
}
```

**What did you expect to happen?**

At least it should not crash with weird error. 
Error goes away after "generator-star-spacing" is offed.

**What actually happened? Please include the actual, raw output from ESLint.**
```
./node_modules/.bin/eslint test.js                                         
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
    at TokenStore.getTokenBefore (/home/msosnov/projects/workspace0/node_modules/.registry.npmjs.org/eslint/3.18.0/node_modules/eslint/lib/token-store/index.js:318:17)
    at EventEmitter.checkFunction (/home/msosnov/projects/workspace0/node_modules/.registry.npmjs.org/eslint/3.18.0/node_modules/eslint/lib/rules/generator-star-spacing.js:131:42)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.applySelector (/home/msosnov/projects/workspace0/node_modules/.registry.npmjs.org/eslint/3.18.0/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/home/msosnov/projects/workspace0/node_modules/.registry.npmjs.org/eslint/3.18.0/node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (/home/msosnov/projects/workspace0/node_modules/.registry.npmjs.org/eslint/3.18.0/node_modules/eslint/lib/util/node-event-generator.js:308:14)
    at CodePathAnalyzer.enterNode (/home/msosnov/projects/workspace0/node_modules/.registry.npmjs.org/eslint/3.18.0/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:602:23)
    at CommentEventGenerator.enterNode (/home/msosnov/projects/workspace0/node_modules/.registry.npmjs.org/eslint/3.18.0/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Traverser.enter (/home/msosnov/projects/workspace0/node_modules/.registry.npmjs.org/eslint/3.18.0/node_modules/eslint/lib/eslint.js:928:36)
```

**Comment by mysticatea** [comment]
Thank you for this issue.

This is caused by old `babel-eslint`'s bug (https://github.com/babel/babel-eslint/issues/406).
Please use the latest `babel-eslint`.

**Comment by Crazymax11** [comment]
thanks!
