### ISSUE TITLE
Error Thrown: Line number out of range

### ISSUE THREAD

**Issue by HoraceShmorace** [eslint/eslint#8401]
**Tell us about your environment**

* **ESLint Version:** 3.19.0
* **Node Version:** 7.7.3
* **npm Version:** 4.4.4

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

```
module.exports = {
    "extends": "standard",
    "plugins": [
        "standard",
        "promise"
    ]
};
```

**What did you do? Please include the actual source code causing the issue.**

```
eslint --fix */**
```

**What did you expect to happen?**
Successful execution.

**What actually happened? Please include the actual, raw output from ESLint.**
```
Line number out of range (line 318 requested, but only 317 lines present).
RangeError: Line number out of range (line 318 requested, but only 317 lines present).
    at SourceCode.getIndexFromLoc (/usr/local/lib/node_modules/eslint/lib/util/source-code.js:389:19)
    at Object.fix (/usr/local/lib/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:116:52)
    at RuleContext.report (/usr/local/lib/node_modules/eslint/lib/rule-context.js:127:34)
    at Program:exit.allLines.reduce.concat.reduce (/usr/local/lib/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:108:37)
    at Array.reduce (native)
    at EventEmitter.Program:exit (/usr/local/lib/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:93:22)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:191:7)
    at NodeEventGenerator.applySelector (/usr/local/lib/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/usr/local/lib/node_modules/eslint/lib/util/node-event-generator.js:294:22)
```

**Comment by not-an-aardvark** [comment]
Thanks for the report. It would be useful to have an example of code that causes this error -- can you try to figure out which file is causing it? (If you run eslint with the `--debug` flag and look for messages marked with `eslint:cli-engine`, you should see messages like "Processing /path/to/file". I think the last file that gets printed before the error would be the file causing the problem.

**Comment by HoraceShmorace** [comment]
Thanks for that insight, @not-an-aardvark.

It appears that this error is consistently thrown if the file ends in a new line with a space character. When I delete the space, the error goes away.

Unfortunately, this pre-existing codebase in which I'm working oddly seems to have a lot of files that end in a new line + space.

**Comment by not-an-aardvark** [comment]
Thanks, I was able to reproduce this issue.

**Comment by Dids** [comment]
This is still happening, so should this be reopened?

**Comment by honomoa** [comment]
I can reproduce by add only two space at last line in any file.

**Comment by not-an-aardvark** [comment]
If you're encountering a bug, please create a new issue and fill out the [bug report template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md).
