### ISSUE TITLE
Cannot read property 'range' of null

### ISSUE THREAD

**Issue by BridgeAR** [eslint/eslint#8550]
**Tell us about your environment**

* **ESLint Version: 4.0.0-alpha.2**
* **Node Version: 7.10.0**
* **npm Version: 4.2.0**

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

```js
module.exports = {
    "extends": "eslint:recommended"
};
```

**What did you do? Please include the actual source code causing the issue.**

```js
const number = 5;
number / (5 / 5);
```

**What did you expect to happen?**
No error

**What actually happened? Please include the actual, raw output from ESLint.**
```
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenAfter (/node_modules/eslint/lib/token-store/index.js:319:17)
    at EventEmitter.BinaryExpression[operator='/'] > BinaryExpression[operator='/'] (/node_modules/eslint/lib/rules/no-unexpected-multiline.js:85:55)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at NodeEventGenerator.applySelector (/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (/node_modules/eslint/lib/util/node-event-generator.js:308:14)
    at CodePathAnalyzer.enterNode (/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:602:23)
    at Traverser.enter (/node_modules/eslint/lib/eslint.js:909:36)
    at Traverser.__execute (/node_modules/estraverse/estraverse.js:397:31)
```

**Comment by not-an-aardvark** [comment]
Thanks for reporting, I can reproduce this issue.
