### ISSUE TITLE
Cannot lint the same code twice/trice via CLIEngine#executeOnText (TypeError: Cannot read property 'text' of undefined)

### ISSUE THREAD

**Issue by finom** [eslint/eslint#8750]
Hello,
I'm trying to use CLIEngine but I get the error (`TypeError: Cannot read property 'text' of undefined`) at this line: https://github.com/eslint/eslint/blob/eb5d12c15a32084907f1c58bcbec721b5008495d/lib/linter.js#L784

It happens when I try to lint the same code twice or trice but when I pass new code argument to `CLIEngine#executeOnText` function, everything works just fine two or three times and then throws the error again.

I tried to use many configurations, (parser, cache, plugins, useEslintrc) and got the same error even using basic config.

**Tell us about your environment**

* **ESLint Version: 4.0.0**
* **Node Version: 6.4.0**
* **npm Version: 5.0.3**

**What parser (default, Babel-ESLint, etc.) are you using?**
Tried both.

**Please show your full configuration:**
As I said above I tried many configurations. The error isn't dependent on config.

```
rules: {}
```

**What did you do? Please include the actual source code causing the issue.**

```js
new CLIEngine({
        rules: {},
    })
    .executeOnText(code)
```

**What did you expect to happen?**
To not get the error.

**What actually happened? Please include the actual, raw output from ESLint.**

```
[0] TypeError: Cannot read property 'text' of undefined
[0]     at Linter.verify (/home/finom/Dropbox/sync/todd/eslint.io/packages/backend/node_modules/eslint/lib/linter.js:782:65)
[0]     at multipassFix (/home/finom/Dropbox/sync/todd/eslint.io/packages/backend/node_modules/eslint/lib/cli-engine.js:169:27)
[0]     at processText (/home/finom/Dropbox/sync/todd/eslint.io/packages/backend/node_modules/eslint/lib/cli-engine.js:272:27)
[0]     at CLIEngine.executeOnText (/home/finom/Dropbox/sync/todd/eslint.io/packages/backend/node_modules/eslint/lib/cli-engine.js:738:26)
[0]     at lint (/home/finom/Dropbox/sync/todd/eslint.io/packages/backend/api/lint.js:15:6)
[0]     at module.exports (/home/finom/Dropbox/sync/todd/eslint.io/packages/backend/api/lint.js:22:17)
[0]     at Layer.handle [as handle_request] (/home/finom/Dropbox/sync/todd/eslint.io/packages/backend/node_modules/express/lib/router/layer.js:95:5)
[0]     at next (/home/finom/Dropbox/sync/todd/eslint.io/packages/backend/node_modules/express/lib/router/route.js:137:13)
[0]     at Route.dispatch (/home/finom/Dropbox/sync/todd/eslint.io/packages/backend/node_modules/express/lib/router/route.js:112:3)
[0]     at Layer.handle [as handle_request] (/home/finom/Dropbox/sync/todd/eslint.io/packages/backend/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by finom** [comment]
The problem isn't on ESLint side. Sorry for opening.
