### ISSUE TITLE
Plugins not loading

### ISSUE THREAD

**Issue by borela** [eslint/eslint#8753]
**Tell us about your environment**

* **ESLint Version:** 4.0.0
* **Node Version:** 8.1.2
* **npm Version:** 5.0.3

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint

**Please show your full configuration:**

```json
{
  "extends": "ctrine-js-web",
  "parser": "Babel-ESLint"
}
```
This is not an easy error do reproduce, the error message is as follows:

```sh
λ node_modules\.bin\eslint .
Cannot read property 'react/display-name' of undefined
Referenced from: ctrine-js-shared
Referenced from: ctrine-js-web
Referenced from: ~presentable\.eslintrc.json
TypeError: Cannot read property 'react/display-name' of undefined
Referenced from: ctrine-js-shared
Referenced from: ctrine-js-web
Referenced from: ~presentable\.eslintrc.json
    at Object.keys.forEach.key (~presentable\node_modules\eslint\lib\config\config-ops.js:177:68)
    at Array.forEach (native)
    at deepmerge (~presentable\node_modules\eslint\lib\config\config-ops.js:176:30)
    at Object.keys.forEach (~presentable\node_modules\eslint\lib\config\config-ops.js:158:34)
    at Array.forEach (native)
    at deepmerge (~presentable\node_modules\eslint\lib\config\config-ops.js:150:30)
    at Object.keys.forEach.key (~presentable\node_modules\eslint\lib\config\config-ops.js:178:32)
    at Array.forEach (native)
    at Object.deepmerge [as merge] (~presentable\node_modules\eslint\lib\config\config-ops.js:176:30)
    at loadConfigFile (~presentable\node_modules\eslint\lib\config\config-file.js:240:22)
```

The settings are loading, the issue is that **sometimes**(other projects with the same settings are working as intended) **the plugins are not loading before the rules** and shows that error. I cannot reproduce this error reliably but I believe this is related to yaml files and the loops looking at the keys without considering the order like loading the plugin before extending the file.

**Comment by borela** [comment]
Found the error, invisible character.
