### ISSUE TITLE
indent rule throws TypeError: Cannot read property 'range' of undefined

### ISSUE THREAD

**Issue by peet** [eslint/eslint#8893]
**Tell us about your environment**

* **ESLint Version:** 4.1.1
* **Node Version:** 8.1.1 (or 6.9.4)
* **npm Version:** 5.0.4 (or 3.10.10)

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

module.exports = {
  root: true,
  'parser': 'babel-eslint',
  'parserOptions': {
    ecmaVersion: 2016,
  },
  rules: {
    indent: 2,
  },
};

```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js

`${_ => { return _ ? `${''}` : ''}}`;

`a(${_})`;

```

**What did you expect to happen?**
No errors

**What actually happened? Please include the actual, raw output from ESLint.**
```
Cannot read property 'range' of undefined
TypeError: Cannot read property 'range' of undefined
    at SourceCode.getTokensBetween (C:\Users\peet\git\eslint-import-range\node_modules\eslint\lib\token-store\index.js:557:17)
    at parenPairs.forEach.pair (C:\Users\peet\git\eslint-import-range\node_modules\eslint\lib\rules\indent.js:932:68)
    at Array.forEach (native)
    at addParensIndent (C:\Users\peet\git\eslint-import-range\node_modules\eslint\lib\rules\indent.js:926:24)
    at Linter.Program:exit (C:\Users\peet\git\eslint-import-range\node_modules\eslint\lib\rules\indent.js:1379:17)
    at emitOne (events.js:115:13)
    at Linter.emit (events.js:210:7)
    at NodeEventGenerator.applySelector (C:\Users\peet\git\eslint-import-range\node_modules\eslint\lib\util\node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (C:\Users\peet\git\eslint-import-range\node_modules\eslint\lib\util\node-event-generator.js:294:22)
    at NodeEventGenerator.leaveNode (C:\Users\peet\git\eslint-import-range\node_modules\eslint\lib\util\node-event-generator.js:317:14)
```
A repo with a runnable example is [here](https://github.com/peet/eslint-import-range)

The example is obviously heavily reduced, but all parts are necessary to reproduce. The contents of the inner template sections doesn't matter, but without them it doesn't error. The ternary, and the arrow function with the explicit return are both needed. Aditionally the order of the two template strings is significant - in the other order it doesn't error.

**Comment by not-an-aardvark** [comment]
Thanks for reporting. Does this issue also occur when you remove `babel-eslint`? I can't seem to reproduce it with the default parser.

**Comment by peet** [comment]
Removing `babel-eslint` does indeed cause the example, and the original file, to lint fine.

**Comment by not-an-aardvark** [comment]
Thanks, in this case this seems like a bug in `babel-eslint`. I would recommend reporting the issue there instead.
