### ISSUE TITLE
Error: Cannot find module 'ajv'

### ISSUE THREAD

**Issue by steveklabnik** [eslint/eslint#8934]
**Tell us about your environment**

Windows 10 + nodist, dunno what else is relevant, happy to expand

* **ESLint Version:** 3.19.0
* **Node Version:** v7.2.1
* **npm Version:** 5.2.0

**What parser (default, Babel-ESLint, etc.) are you using?**

I think the default, as I didn't change anything.

<details>
<summary>Configuration</summary>

```js

module.exports = {
  root: true,
  parserOptions: {
    ecmaVersion: 2017,
    sourceType: 'module'
  },
  extends: 'eslint:recommended',
  env: {
    browser: true
  },
  rules: {
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```bash
> npm install eslint --save-dev
> vim package.json // add `"eslint": "eslint app"` to scripts
> npm run eslint
```

**What did you expect to happen?**

eslint should run

**What actually happened? Please include the actual, raw output from ESLint.**

```text
> npm run eslint
npm WARN lifecycle The node binary used for scripts is C:\Program Files (x86)\Nodist\bin\node.exe but npm is using C:\
ogram Files (x86)\Nodist\v-x64\7.2.1\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path
or the node binary npm was executed with.

> frontend@0.0.0 eslint C:\Users\steve\src\rustdoc\frontend
> eslint app

module.js:472
    throw err;
    ^

Error: Cannot find module 'ajv'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\steve\src\rustdoc\frontend\node_modules\eslint\lib\util\ajv.js:11:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.0.0 eslint: `eslint app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frontend@0.0.0 eslint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\steve\AppData\Roaming\npm-cache\_logs\2017-07-12T16_05_49_005Z-debug.log
```

That warning happens, but doesn't affect other things; `npm run test` calls out to `ember test` just fine, for example.

that debug log:

<details>
```text
> cat C:\Users\steve\AppData\Roaming\npm-cache\_logs\2017-07-
T16_05_49_005Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\Nodist\\v-x64\\7.2.1\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\Nodist\\npmv\\5.2.0\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'eslint' ]
2 info using npm@5.2.0
3 info using node@v7.2.1
4 verbose run-script [ 'preeslint', 'eslint', 'posteslint' ]
5 info lifecycle frontend@0.0.0~preeslint: frontend@0.0.0
6 info lifecycle frontend@0.0.0~eslint: frontend@0.0.0
7 warn lifecycle The node binary used for scripts is C:\Program Files (x86)\Nodist\bin\node.exe but npm is using C:\Pr
ram Files (x86)\Nodist\v-x64\7.2.1\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path f
 the node binary npm was executed with.
8 verbose lifecycle frontend@0.0.0~eslint: unsafe-perm in lifecycle true
9 verbose lifecycle frontend@0.0.0~eslint: PATH: C:\Program Files (x86)\Nodist\npmv\5.2.0\bin\node-gyp-bin;C:\Users\st
e\src\rustdoc\frontend\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\NVIDIA Co
oration\PhysX\Common;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32
:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) M
agement Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\
tel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Prog
m Files\Lenovo\Touch Fingerprint Software\;C:\Program Files (x86)\Common Files\Lenovo;C:\ProgramData\Lenovo\ReadyApps;
\Program Files (x86)\Skype\Phone\;C:\ProgramData\chocolatey\bin;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Pr
ram Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\CMake\bin;C:\Program Files (x86)\Nodist
in;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Ruby23\bin;C:\Users\steve\A
Data\Local\Programs\Python\Python35\Scripts\;C:\Users\steve\AppData\Local\Programs\Python\Python35\;C:\Users\steve\App
ta\Local\Programs\Python\Python36-32\Scripts\;C:\Users\steve\AppData\Local\Programs\Python\Python36-32\;C:\Users\steve
cargo\bin;C:\Users\steve\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\ste
\AppData\Local\NASM\;C:\Program Files\PostgreSQL\9.6\bin\;C:\Program Files\Heroku\bin;C:\Program Files (x86)\tidy\bin;
\Users\steve\curl\src;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;
10 verbose lifecycle frontend@0.0.0~eslint: CWD: C:\Users\steve\src\rustdoc\frontend
11 silly lifecycle frontend@0.0.0~eslint: Args: [ '/d /s /c', 'eslint app' ]
12 silly lifecycle frontend@0.0.0~eslint: Returned: code: 1  signal: null
13 info lifecycle frontend@0.0.0~eslint: Failed to exec eslint script
14 verbose stack Error: frontend@0.0.0 eslint: `eslint app`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\Nodist\npmv\5.2.0\lib\utils\lifecycle.js:289:
)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\Nodist\npmv\5.2.0\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid frontend@0.0.0
16 verbose cwd C:\Users\steve\src\rustdoc\frontend
17 verbose Windows_NT 10.0.15063
18 verbose argv "C:\\Program Files (x86)\\Nodist\\v-x64\\7.2.1\\node.exe" "C:\\Program Files (x86)\\Nodist\\npmv\\5.2.
\bin\\npm-cli.js" "run" "eslint"
19 verbose node v7.2.1
20 verbose npm  v5.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error frontend@0.0.0 eslint: `eslint app`
23 error Exit status 1
24 error Failed at the frontend@0.0.0 eslint script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```
</details>

`ajv` is in my `package-lock.json`, so it's certainly being installed. Dunno what's up. Happy to elaborate if something is missing here!

**Comment by gyandeeps** [comment]
i have seen such issues with npm 5.x. AS lot of time you have to reinstall all modules or just eslint to fix these kinds of issues. I haven't seen this issue with eslint specific but in general i have seen these things happen.

**Comment by steveklabnik** [comment]
that... totally fixed it. Thanks @gyandeeps .
