### ISSUE TITLE
charAt of undefined error when using "ignoreConstructors": true option on "object-shorthand" rule

### ISSUE THREAD

**Issue by reicruz** [eslint/eslint#9052]
**Tell us about your environment**

* **ESLint Version:**  v3.19.0
* **Node Version:** v8.2.1
* **npm Version:** v5.3.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```
"rules": {
  "object-shorthand": ["error", "always", { "ignoreConstructors": true }]
}
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
const Example = proxyquire(PATH, {
  './example': function () {
    return;
  }
};
```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

```
Cannot read property 'charAt' of undefined
TypeError: Cannot read property 'charAt' of undefined
    at isConstructor (/Users/cruzr0/lifion/meta/ohcm-metadata-dna-client/node_modules/eslint/lib/rules/object-shorthand.js:120:35)
    at EventEmitter.Property:exit (/Users/cruzr0/lifion/meta/ohcm-metadata-dna-client/node_modules/eslint/lib/rules/object-shorthand.js:395:48)
    at emitOne (events.js:115:13)
    at EventEmitter.emit (events.js:210:7)
    at NodeEventGenerator.applySelector (/Users/cruzr0/lifion/meta/ohcm-metadata-dna-client/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/Users/cruzr0/lifion/meta/ohcm-metadata-dna-client/node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.leaveNode (/Users/cruzr0/lifion/meta/ohcm-metadata-dna-client/node_modules/eslint/lib/util/node-event-generator.js:317:14)
    at CodePathAnalyzer.leaveNode (/Users/cruzr0/lifion/meta/ohcm-metadata-dna-client/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:622:23)
    at CommentEventGenerator.leaveNode (/Users/cruzr0/lifion/meta/ohcm-metadata-dna-client/node_modules/eslint/lib/util/comment-event-generator.js:111:23)
    at Traverser.leave (/Users/cruzr0/lifion/meta/ohcm-metadata-dna-client/node_modules/eslint/lib/eslint.js:932:36)
```

**Comment by platinumazure** [comment]
I believe this was resolved by #8577, which was included in 4.0.0-beta.0. If you upgrade to ESLint 4.x, this should resolve itself for you.

**Comment by reicruz** [comment]
Upgraded to 4.x and no longer seeing the error, thanks @platinumazure for pointing that out!

**Comment by platinumazure** [comment]
Awesome! I'm going to go ahead and close this, but please comment or create another issue if you need anything else.
