### ISSUE TITLE
eslint --init fails with "TypeError: Cannot read property 'trim' of null" when npm is not installed

### ISSUE THREAD

**Issue by athei** [eslint/eslint#9102]
**Tell us about your environment**

* **ESLint Version:** 4.4.1
* **Node Version:** 8.3.0
* **npm Version:** Using yarn 0.27.5

**What parser (default, Babel-ESLint, etc.) are you using?**
Right now I am just initializing the config.

**What did you do? Please include the actual source code causing the issue.**
I am trying to use eslint for a project.  I just installed it locally using package.json and yarn and run ```./node_modules/.bin/eslint --init```.

**What did you expect to happen?**
I expect a .eslintrc to be written.

**What actually happened? Please include the actual, raw output from ESLint.**
```js
? How would you like to configure ESLint? Use a popular style guide
? Which style guide do you want to follow? Airbnb
? Do you use React? Yes
? What format do you want your config file to be in? JSON
Checking peerDependencies of eslint-config-airbnb@latest
Cannot read property 'trim' of null
TypeError: Cannot read property 'trim' of null
    at Object.fetchPeerDependencies (/Users/alexander/Developer/seduceme/web-react/node_modules/eslint/lib/util/npm-util.js:69:13)
    at getPeerDependencies (/Users/alexander/Developer/seduceme/web-react/node_modules/eslint/lib/config/config-initializer.js:75:26)
    at hasESLintVersionConflict (/Users/alexander/Developer/seduceme/web-react/node_modules/eslint/lib/config/config-initializer.js:359:40)
    at Object.when (/Users/alexander/Developer/seduceme/web-react/node_modules/eslint/lib/config/config-initializer.js:452:83)
    at /Users/alexander/Developer/seduceme/web-react/node_modules/run-async/index.js:25:25
    at Promise (<anonymous>)
    at /Users/alexander/Developer/seduceme/web-react/node_modules/run-async/index.js:24:19
    at /Users/alexander/Developer/seduceme/web-react/node_modules/inquirer/lib/ui/prompt.js:106:30
    at tryCatcher (/Users/alexander/Developer/seduceme/web-react/node_modules/rx-lite/rx.lite.js:67:31)
    at Defer.subscribeCore (/Users/alexander/Developer/seduceme/web-react/node_modules/rx-lite/rx.lite.js:2159:37)
```

**Comment by not-an-aardvark** [comment]
Thanks for the report. What operating system and terminal are you using?

**Comment by not-an-aardvark** [comment]
Thanks, in that case I agree that we should handle the error more gracefully.

For more discussion about using yarn, see https://github.com/eslint/eslint/issues/8787 and https://github.com/eslint/eslint/pull/9023.

**Comment by not-an-aardvark** [comment]
Fixed in https://github.com/eslint/eslint/pull/9169
