### ISSUE TITLE
"Cannot read property 'type' of undefined" when updating to version 4.14.0

### ISSUE THREAD

**Issue by bary12** [eslint/eslint#9773]
**Tell us about your environment**

* **ESLint Version:** 4.14.0, The error did not occur in 4.13.1
* **Node Version:** 6.10.4
* **npm Version:** 5.5.1

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

See [eslint-config-canonical](https://github.com/gajus/eslint-config-canonical/blob/master/configurations/eslintrc.json)
<details>
<summary>Configuration</summary>

```js

{
  "extends": "canonical",
  "root": true,
  "rules": {
    "filenames/match-regex": 0
  }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

This was caused by a certain file, I don't know which part of the file, but the problem seems to be there. See [the source code of the file](https://github.com/gajus/eslint-plugin-jsdoc/blob/master/src/rules/checkParamNames.js).

```bash
./node_modules/.bin/eslint ./src ./test
```

This seems to have happened in particular on the file mentioned above,

```bash
./node_modules/.bin/eslint ./src/rules/checkParamNames.js
```

**What actually happened? Please include the actual, raw output from ESLint.**
ESlint crashed with the following error:

```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at isForInRef (/home/travis/build/gajus/eslint-plugin-jsdoc/node_modules/eslint/lib/rules/no-unused-vars.js:410:24)
    at variable.references.some.ref (/home/travis/build/gajus/eslint-plugin-jsdoc/node_modules/eslint/lib/rules/no-unused-vars.js:447:21)
    at Array.some (<anonymous>)
    at isUsedVariable (/home/travis/build/gajus/eslint-plugin-jsdoc/node_modules/eslint/lib/rules/no-unused-vars.js:446:40)
    at collectUnusedVariables (/home/travis/build/gajus/eslint-plugin-jsdoc/node_modules/eslint/lib/rules/no-unused-vars.js:569:26)
    at Program:exit (/home/travis/build/gajus/eslint-plugin-jsdoc/node_modules/eslint/lib/rules/no-unused-vars.js:621:36)
    at listeners.(anonymous function).forEach.listener (/home/travis/build/gajus/eslint-plugin-jsdoc/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/home/travis/build/gajus/eslint-plugin-jsdoc/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/home/travis/build/gajus/eslint-plugin-jsdoc/node_modules/eslint/lib/util/node-event-generator.js:251:26)
```
Note that here eslint-plugin-jsdoc is the repository being linted.

This did not occur with eslint@4.7.2

EDIT: Now also checked with version 4.13.1 and the error does not occur. Seems to be a problem specifically with 4.14.0

**Comment by bary12** [comment]
Duplicate of #9767, #9762
