### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sybrendotinga** [eslint/eslint#9803]
It seems that with eslint-config-standard enabled in my Vue project I can not run the eslint command anymore. While running webpack I don't get this error, but when I run `yarn lint` I get the error down below. Maybe it has something to do with babel-eslint, that has no support for ESlint 4?

I hope this is the right place to start looking.
  
**Tell us about your environment**

* **ESLint Version:** 4.14.0
* **Node Version:** 8.5.0 (Also tried 9.3.0)
* **yarn Version:** 1.3.2

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint  // Maybe this is the problem? ESlint 4.* is not supported?

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

**package.json**
```js

{
  "scripts": {
    "lint": "eslint . --format 'node_modules/eslint-friendly-formatter' --ext .js,.vue",
    "lint:fix": "yarn lint --fix"
  },
  "dependencies": {},
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-eslint": "^7.2.3",
    "babel-loader": "^7.1.2",
    "babel-plugin-lodash": "^3.3.2",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-stage-2": "^6.22.0",
    "babel-runtime": "^6.26.0",
    "eslint": "^4.14.0",
    "eslint-config-standard": "^11.0.0-beta.0",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-node": "^5.2.1",
    "eslint-plugin-promise": "^3.6.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "^4.0.0-beta.4",
    "vue": "^2.5.13",
  }
}
```
**.eslintrc.js**

```js
module.exports = {
  root: true,
  parserOptions: {
    parser: 'babel-eslint',
    ecmaVersion: 2017,
    sourceType: 'module'
  },
  env: {
    browser: true,
    node: true
  },
  extends: [
    'standard',
    'plugin:vue/recommended',
    './.eslint-plugin-jdi.js' // This file contains our own rules
  ]
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
// I do not know where it goes wrong
```

```bash
eslint . --ext .js,.vue
```

**What did you expect to happen?**
I expected output of the ESLint command

```bash
✨  Done in Xs.
```

**What actually happened? Please include the actual, raw output from ESLint.**

```bash
$ eslint . --ext .js,.vue
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.match] (<anonymous>)
    at String.match (native)
    at Literal (/Users/sybrendotinga/Documents/Webprojects/frontend/vue-boilerplate/node_modules/eslint/lib/rules/no-octal-escape.js:32:40)
    at listeners.(anonymous function).forEach.listener (/Users/sybrendotinga/Documents/Webprojects/frontend/vue-boilerplate/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/sybrendotinga/Documents/Webprojects/frontend/vue-boilerplate/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/sybrendotinga/Documents/Webprojects/frontend/vue-boilerplate/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/sybrendotinga/Documents/Webprojects/frontend/vue-boilerplate/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/sybrendotinga/Documents/Webprojects/frontend/vue-boilerplate/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/sybrendotinga/Documents/Webprojects/frontend/vue-boilerplate/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ilyavolodin** [comment]
It looks like the error is happening in no-octal-escape rule, but without code sample, we wouldn't be able to reproduce it. Could you provide minimal working example of the code that results in this exception?

**Comment by platinumazure** [comment]
@sybrendotinga If you could run ESLint with the `--debug` flag, you could look in the debug output to determine what file is being linted at the time of the crash. That will help you find the code that is causing the issue. Thanks!

**Comment by sybrendotinga** [comment]
@platinumazure Thanks! That helped me to the right file. It seemed that the file was 'corrupt'. When I emptied the file and run the eslint command it worked. Maybe that has to do with the no-octal-escape that @ilyavolodin mentioned. I rewrote the contents of the file, and now it seems to work again. I don't exactly know what happend, but thanks to your help. Thanks guys!
