### ISSUE TITLE
Attempting to init as YAML fails

### ISSUE THREAD

**Issue by ryzokuken** [eslint/eslint#9915]
**Tell us about your environment**

* **ESLint Version:** ^4.16.0
* **Node Version:** v8.4.0
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**

None

**Please show your full configuration:**

N/A

```bash
./node_modules/bin/eslint --init
```

**What did you expect to happen?**

ESLint to initialize properly.

**What actually happened? Please include the actual, raw output from ESLint.**
```
harbor-vue on  master [⇡] is 📦 v1.0.0-alpha.1 via ⬢ v8.4.0
➜ ./node_modules/.bin/eslint --init
? How would you like to configure ESLint? Use a popular style guide
? Which style guide do you want to follow? Airbnb
? Do you use React? No
? What format do you want your config file to be in? YAML
Checking peerDependencies of eslint-config-airbnb-base@latest
Installing eslint-config-airbnb-base@latest, eslint-plugin-import@^2.7.0
npm WARN rm not removing /Users/ryzokuken/Code/harbor-vue/node_modules/.bin/electron-download as it wasn't installed by /Users/ryzokuken/Code/harbor-vue/node_modules/electron-download
npm WARN rm not removing /Users/ryzokuken/Code/harbor-vue/node_modules/.bin/mkdirp as it wasn't installed by /Users/ryzokuken/Code/harbor-vue/node_modules/mkdirp
npm WARN rm not removing /Users/ryzokuken/Code/harbor-vue/node_modules/.bin/mime as it wasn't installed by /Users/ryzokuken/Code/harbor-vue/node_modules/mime
npm WARN rm not removing /Users/ryzokuken/Code/harbor-vue/node_modules/fsevents/node_modules/.bin/node-pre-gyp as it wasn't installed by /Users/ryzokuken/Code/harbor-vue/node_modules/fsevents/node_modules/node-pre-gyp
npm WARN rm not removing /Users/ryzokuken/Code/harbor-vue/node_modules/.bin/browserslist as it wasn't installed by /Users/ryzokuken/Code/harbor-vue/node_modules/browserslist
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN eslint-config-airbnb-base@12.1.0 requires a peer of eslint@^4.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-import@2.8.0 requires a peer of eslint@2.x - 4.x but none is installed. You must install peer dependencies yourself.
npm WARN harbor-vue@1.0.0-alpha.1 No repository field.

+ eslint-config-airbnb-base@12.1.0
+ eslint-plugin-import@2.8.0
added 8 packages, removed 1133 packages and updated 42 packages in 12.496s
Cannot find module 'js-yaml'
Error: Cannot find module 'js-yaml'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at writeYAMLConfigFile (/Users/ryzokuken/Code/harbor-vue/node_modules/eslint/lib/config/config-file.js:267:18)
    at Object.write (/Users/ryzokuken/Code/harbor-vue/node_modules/eslint/lib/config/config-file.js:309:13)
    at writeFile (/Users/ryzokuken/Code/harbor-vue/node_modules/eslint/lib/config/config-initializer.js:53:16)
    at inquirer.prompt.then.earlyAnswers (/Users/ryzokuken/Code/harbor-vue/node_modules/eslint/lib/config/config-initializer.js:477:13)
    at <anonymous>
```

**Comment by not-an-aardvark** [comment]
What happens if you remove your `node_modules/` folder and run `npm install` again? It seems like `eslint` wasn't installed with the proper dependencies, which is unexpected -- if anything it might be an issue with npm.

**Comment by zeorin** [comment]
I just had this issue, and I took the steps that @not-an-aardvark suggested. This time the initialization was successful. In my case I had initially installed ESLint with:
```
yarn add --dev eslint
```
So perhaps it's a Yarn problem.

**Comment by amazingrando** [comment]
I can also confirm @not-an-aardvark's solution. This appears to be an issue with Yarn.

**Comment by nzakas** [comment]
Closing per last comment.
